### ISSUE TITLE
Error in specifying COSP in tag zz_cam6_3_018_mosaic_branch

### ISSUE THREAD

**Issue by lkemmons** [ESCOMP/CAM#1008]
### What happened?

When running ./manage_externals/checkout_externals cannot find correct COSPv2.0 code:
Processing externals description file : Externals_CAM.cfg
Checking out externals: chem_proc, carma, cosp2, ERROR:root:Command '['svn', 'checkout', '--quiet', 'https://github.com/CFMIP/COSPv2.0/tags/v2.1.4cesm/src', '/glade/u/home/emmons/derecho/cases_mosaic/cesm_src_cam6_3_018_mosaic/src/physics/cosp2/src']' returned non-zero exit status 1.
ERROR:root:Failed with output:
    svn: E170013: Unable to connect to a repository at URL 'https://github.com/CFMIP/COSPv2.0/tags/v2.1.4cesm/src'
    svn: E160013: '/CFMIP/COSPv2.0/tags/v2.1.4cesm/src' path not found

ERROR: In directory
    /glade/u/home/emmons/derecho/cases_mosaic/cesm_src_cam6_3_018_mosaic
Process did not run successfully; returned status 1:
    svn checkout --quiet https://github.com/CFMIP/COSPv2.0/tags/v2.1.4cesm/src /glade/u/home/emmons/derecho/cases_mosaic/cesm_src_cam6_3_018_mosaic/src/physics/cosp2/src
See above for output from failed command.

### What are the steps to reproduce the bug?

Downloading this tag worked a few months ago.
Today I ran the following:
> cd /glade/u/home/emmons/derecho/cases_mosaic/
> git clone https://github.com/ESCOMP/CAM -b zz_cam6_3_018_mosaic_branch cesm_src_cam6_3_018_mosaic
> cd cesm_src_cam6_3_018_mosaic
> ./manage_externals/checkout_externals

### What CAM tag were you using?

zz_cam6_3_018_mosaic_branch

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Other (please specify below)

### Path to a case directory, if applicable

N/A

### Will you be addressing this bug yourself?

No

### Extra info

I set up this code in
/glade/u/home/emmons/derecho/cesm_src/cam6_3_018_mosaic01_20230622/
last June without problem.

**Comment by cacraigucar** [comment]
This is probably due to the phaseout of svn checkouts by the github folks.  Please refer to:  https://bb.cgd.ucar.edu/cesm/threads/how-to-fix-problems-using-checkout_externals-by-implementing-github-svn-deprecation-changes.9073/

Following those directions should solve your problem.  If it does, please comment here and close the issue.  If not, let us know.

**Comment by lkemmons** [comment]
Thanks, Cheryl.  
I made the changes to Externals_CAM.cfg, but got stuck on COSP, so just changed that to not required:
----
3,4c3,4
< protocol = svn
< repo_url = https://svn-ccsm-models.cgd.ucar.edu/tools/proc_atm/chem_proc/release_tags
---
> protocol = git
> repo_url = https://github.com/ESCOMP/CHEM_PREPROCESSOR.git
10,12c10,12
< protocol = svn
< repo_url = https://svn-ccsm-models.cgd.ucar.edu/carma/release_tags
< tag = carma3_49_rel
---
> protocol = git
> repo_url = https://github.com/ESCOMP/CARMA_base.git
> tag = carma4_01
17,20c17,21
< protocol = svn
< repo_url = https://github.com/CFMIP/COSPv2.0/tags/
< tag = v2.1.4cesm/src
< required = True
---
> protocol = git
> repo_url = https://github.com/CFMIP/COSPv2.0
> sparse = ../.cosp_sparse_checkout
> tag = v2.1.4cesm
> required = False
---

This tag is the only publicly available version of the 'mosaic' gas-aerosol code (which allows for the simulation of nitrate aerosols), so it would be great if someone could help update this so new users can download and use it directly.
Thanks!

**Comment by cacraigucar** [comment]
@fvitt - I've assigned this issue to you

**Comment by lkemmons** [comment]
My functioning (1-day run) case is:
/glade/u/home/emmons/derecho/cases_mosaic/f.cam6_3_018mosaic.FCnudged.TS1mosaic.f09.01/

**Comment by fvitt** [comment]
@lkemmons 
This is the new mosaic branch tag:
zz_cam6_3_018_mosaic0.3

**Comment by lkemmons** [comment]
Seems to build and run fine:
/glade/u/home/emmons/derecho/cases_mosaic/f.cam6_3_018mosaic03.FCnudged.TS1mosaic.f09.01/
