### ISSUE TITLE
Tag cam6_3_157 missing updated .gitignore

### ISSUE THREAD

**Issue by jtruesdal** [ESCOMP/CAM#1012]
### Issue Type

Code Clean-up

### Issue Description

cam6_3_157 is missing an updated .gitignore file. That tag included changes to move the FV3 cam interface to an external that  requires an update to .gitignore.  Without the update the new FV3 interface directory is reported as an untracked file after the interface code is pulled in via checkout_externals.  This error doesn't affect the running of CAM or its answers but makes development work with that checked out code a little more cumbersome as the developer will need to clear these untracked files before checking out a different tag with the local repository.  Below is the git diff of the one line mod

diff --git a/.gitignore b/.gitignore
index cafb205f..e24b6fa5 100644
--- a/.gitignore
+++ b/.gitignore
@@ -14,7 +14,7 @@ src/physics/pumas
 src/physics/pumas-frozen
 src/physics/rrtmgp/data
 src/physics/rrtmgp/ext
-src/dynamics/fv3/atmos_cubed_sphere
+src/dynamics/fv3
 libraries/FMS
 libraries/mct
 libraries/parallelio

### Will this change answers?

No

### Will you be implementing this yourself?

Any CAM SE can do this

**Comment by cacraigucar** [comment]
Brought in in #992
