### ISSUE TITLE
SILHS subcolumns output as all zeros

### ISSUE THREAD

**Issue by bstephens82** [ESCOMP/CAM#1015]
### What happened?

When running SILHS with either -phys cam6 or -phys cam_dev (although for cam_dev see the necessary code changes associated with issue #844), SILHS subcolumn fields are being output to netcdf as all zeros, despite being nonzero right before the outfld call and even within the outfld call.  I have also tried setting the entire SILHS subcolumn field `WM_lh_out = 1.0_r8` immediately before the [outfld call in subcol_SILHS.F90](https://github.com/ESCOMP/CAM/blob/776400d2a56d1c95551c9782810e4120ecb4f111/src/physics/cam/subcol_SILHS.F90#L1631), just to make sure the outfld call is not receiving anything crazy, and it still outputs all zeros in the netcdf history file.

### What are the steps to reproduce the bug?

- Using a recent tag (I've tested up to cam6_3_155), set up a CAM test case with "-silhs -psubcols 4" included in CAM_CONFIG_OPTS.  You can use either -phys cam6 or -phys cam_dev (although cam_dev will require some code changes to cam_dev/micro_pumas_cam.F90 associated with separate issue #844 to work).  Ask @bstephens82 for the tentative code changes (or see PR #1016).
- Then add SILHS output fields to fincl1 in user_nl_cam, for example fincl1 = 'SILHS_WM_SCOL' or 'SILHS_THLM_SCOL'.  
- You will also need to add `use_gw_convect_dp=.false.` to your namelist since turning on SILHS will automatically set `deep_scheme='off'` and for some reason that won't run with the `gw` flag set to T.  This seems like a separate bug to me, but in any case this is necessary when `deep_scheme='off'`.
- I believe you also need to SourceMod in cam/subcol_SILHS.F90 where you change `l_outfld_subcol=.true.` (this is [hard-coded to false by default in that module](https://github.com/ESCOMP/CAM/blob/776400d2a56d1c95551c9782810e4120ecb4f111/src/physics/cam/subcol_SILHS.F90#L842)...I am not sure why). 

### What CAM tag were you using?

cam6_3_155

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

/glade/derecho/scratch/stepheba/cam155_0/

### Will you be addressing this bug yourself?

Any CAM SE can do this

### Extra info

I spoke to @brian-eaton about this and he suggested this might be related to something similar we are seeing in COSP.

Worth knowing:  There is an automated test that runs SILHS when a new tag is created, thanks @Katetc for telling me about this test.  It can be run with 
~~~
./create_test SMS_Ln9.f19_f19.F2000climo.derecho_intel.cam-silhs
~~~
However, this test runs with -phys cam6, so it will not catch the cam_dev-SILHS bug (#844) and, while the namelist that it automatically generates *does* include some SILHS output fields (namely SILHS_CLUBB_PRECIP_FRAC and SILHS_CLUBB_ICE_SS_FRAC), these are included in `fincl1` and the first integer in nhtfrq is 0 by default, meaning monthly output.  Since this test only runs for a few time steps, it does not appear that it will actually output any SILHS fields, so it would have no way of catching this error where the output is all zeros.  I checked all the output files after running the test, to verify there was no SILHS output.  Then I set nhtfrq=1 for the h0 output files, and the SILHS output was all zeros.

I have also tested this problem with finite volume dycore in addition to the SE dycore.  That has no effect on the zeros (I was wondering whether it might've had something to do with interpolation).

**Comment by brian-eaton** [comment]
I did a couple of low res tests on my desktop with the gnu compiler.

Using the F2000climo compset with FV (10x15), `-silhs -psubcols 4`, and the source mod in `subcol_SILHS.F90` setting `l_subcol_output=.true.`, the run produced non-zero output for `SILHS_WM_SCOL` and `SILHS_THLM_SCOL`.  This is consistent with what I observed for COSP fields with 2 `mdims`.

I tried the same run switching to SE (ne3pg3) and got an index out of bounds error in check_energy.F90:
```
At line 494 of file /work/test-src/cam6_3_155_scol/src/physics/cam/check_energy.F90
Fortran runtime error: Index '64' of dimension 1 of array 'cpairv' outside of expected range (16:1)
```
This is a bug in check_energy in treating the subcolumn case.  I can't pursue this now.  I'm still suspicious that the zero field output is the same issue as we have with COSP using interpolated output (#944).

**Comment by bstephens82** [comment]
Hi @brian-eaton, can you tell me what the ./create_newcase command was that you used for the FV (10x15) test?  I thought I had tried a FV test and still gotten all zeros, I'd like to see if I can just reproduce your result.  A working test would be great to have if I explore this further.  Thanks.

**Comment by brian-eaton** [comment]
@bstephens82, I ran a test on derecho that you can look at.  It's in `/glade/derecho/scratch/eaton/cesm-tests/c63155scol_f2k-scol-f09-9s-dbg_128x1/`.  The subcolumn fields are in the h0i.nc file.  There's a cprnc output that shows the non-zero field values in cpr.h0i.out.  Note that the source mod setting `l_subcol_output=.true.` is in the source directory rather than a separate file in the SourceMods directory.

**Comment by bstephens82** [comment]
Thanks @brian-eaton that's interesting.  It seems the WM subcolumn output looks reasonable.  The --res in your README file appears to still be f09_f09_mg17, and I guess you were running on a desktop with a gnu compiler so I am not sure I can reproduce this exactly.  I will try a short FV test again just to confirm I got all zeros when I compile it the normal way on Derecho.  Can I ask how your run is low-res despite using the --res f09_f09_mg17 resolution (apologies for my ignorance on this).  Thanks again.

**Comment by brian-eaton** [comment]
I ran 10x15 on my desktop and 0.9x1.25 on derecho.  I don't think the bad behavior with zero subcolumn output depends on grid resolution.  I'm happy to look at your case if you can reproduce the zero subcolumn output with the FV dycore.

**Comment by bstephens82** [comment]
Okay @brian-eaton, yeah I tried another short FV dycore test with the cam6_3_155 tag, the case directory is here: /glade/derecho/scratch/stepheba/cam155_silhstest_fv and the SILHS_WM_SCOL output seems to be all zeros (that's the only SILHS variable I output).  Maybe if you take a look you might notice some significant difference between our case setups that would provide clues?  I don't think I know what tag you're using.

**Comment by brian-eaton** [comment]
I see that your run produced zeros for `SILHS_WM_SCOL`.  I used `cam6_3_155` with just the mod in `subcol_SILHS.F90` to set `l_outfld_subcol=.true.`  (`/glade/work/eaton/src/cam6_3_155_scol/`).  I didn't find that mod in your case directory.  Where did you make that change?

**Comment by bstephens82** [comment]
Okay @brian-eaton, thanks for taking a look at that.  I had missed that step, and so I included it and now I am getting output as you did in the FV case.  So I must've missed that step before.  So it looks like the SILHS output works with the FV dycore but not with the SE.  Thanks again for helping to figure that out.

**Comment by brian-eaton** [comment]
I still suspect that the problem with zero subcolumn output is the same problem we've observed with COSP.  I've only observed the problem when using interpolated output with SE.  Using native grid output with SE works fine with COSP.  I'm not sure whether the subcolumn fields can be interpolated, so you probably need to output them to a separate file on the native grid anyway.  But I think there is still an issue with subcolumns for the SE dycore in check_energy.  Since you were able to complete a run with SE and subcolumns I'm wondering whether that same run would work with debug flags on.  I caught the problem using gnu with debugging in my desktop testing.

**Comment by bstephens82** [comment]
> Since you were able to complete a run with SE and subcolumns I'm wondering whether that same run would work with debug flags on.

Shouldn't be hard to find out!  I can check.

**Comment by bstephens82** [comment]
@brian-eaton Yes, when I set DEBUG=TRUE using cam_dev physics (with the micro_pumas_cam.F90 fixes I wrote) and the SE dycore, I get an error in cam/check_energy.F90:
~~~
forrtl: severe (408): fort: (2): Subscript #1 of the array CP_OR_CV_DYCORE has value 17 which is greater than the upper bound of 16
~~~
It doesn't seem to be exactly the same as your error but this is on Derecho etc so maybe not a surprise.  Seems to be essentially the same.

**Comment by bstephens82** [comment]
Hi @brian-eaton, just FYI, I tried that last run again, with DEBUG=TRUE, cam_dev, etc., but with [line 494 in check_energy.F90](https://github.com/ESCOMP/CAM/blob/eaa6435335f7919f33e24b1ca5a1259ef886c967/src/physics/cam/check_energy.F90#L494) replaced with a statement just setting `scaling(:,:) = 1.0_r8` for simplicity, to get past that particular dimensionality problem, and the SILHS_WM_SCOL output is nonzero as it should be.  When I turn interpolate back on, the output is zeros, but there are no other complaints at runtime.

**Comment by brian-eaton** [comment]
I think this confirms my suspicion that the problem with zero subcolumn output is the same as the problem we've seen with COSP output (#944).  It's only occuring with interpolated SE output, and it's not specific to subcolumns; any field with 2 mdims will experience the problem.  I will check with Peter about the best fix in check_energy.
