### ISSUE TITLE
ne3_ne3_mg37 does not work in some instances of CAM

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#1037]
### What happened?

@cacraigucar was unable to run F2000climo and FHIST compsets using ne3_ne3_mg37 on izumi.  @brian-eaton indicated that he was able to run successfully, so he will compare the two runs and see if anything needs modification.  I should also note that I got the same error when I ran with ne5_ne5_mg37.

### What are the steps to reproduce the bug?

On izumi:

 ./create_newcase --case test_cam6_3_160_02 --compset FHIST --res ne3pg3_ne3pg3_mg37 --run-unsupported
cd test_cam6_3_160_02 
 ./xmlchange --force ROF_NCPL=\$ATM_NCPL;  ./xmlchange DOUT_S=FALSE,STOP_OPTION=nsteps,STOP_N=9,DEBUG=TRUE
./case.setup
./case.build
./case.submit

### What CAM tag were you using?

cam6_3_160

### What machine were you running CAM on?

CGD machine (e.g. izumi)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

 /scratch/cluster/cacraig/cam6_3_160/cime/scripts/test_cam6_3_160_02

### Will you be addressing this bug yourself?

No

### Extra info

The partial error traceback from the run:

forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
cesm.exe           000000000B98111A  Unknown               Unknown  Unknown
libpthread-2.17.s  00007F2BF6EB0630  Unknown               Unknown  Unknown
cesm.exe           0000000002246A06  rrtmg_sw_rad_mp_r         396  rrtmg_sw_rad.f90
cesm.exe           000000000165CC5D  radsw_mp_rad_rrtm         515  radsw.F90
cesm.exe           00000000015E0766  radiation_mp_radi        1212  radiation.F90
cesm.exe           00000000013C72A6  physpkg_mp_tphysb        2878  physpkg.F90
cesm.exe           000000000138A59D  physpkg_mp_phys_r        1188  physpkg.F90
cesm.exe           00000000009CAFF9  cam_comp_mp_cam_r         260  cam_comp.F90
cesm.exe           0000000000976D65  atm_comp_nuopc_mp         909  atm_comp_nuopc.F90
libesmf.so         00007F2BFA69DA7E  _ZNK5ESMCI13Metho         377  ESMCI_MethodTable.C
libesmf.so         00007F2BFA69EEE2  _ZN5ESMCI11Method         563  ESMCI_MethodTable.C

**Comment by nusbaume** [comment]
@cacraigucar Have you tried to run this simulation with GNU, or on Derecho?  I remember in the past the version of the Intel compiler that was on Izumi had problems that would cause spurious behavior, which I thought was part of the reason that none of our Izumi tests are Intel.  Of course maybe the compiler has been updated since last I tried it (which was at least over a year ago)?

Anyways, just a possible thought.

**Comment by brian-eaton** [comment]
I can confirm that the problem is with the intel compiler on izumi.  I can successfully run this test with both gnu and nag.

**Comment by cacraigucar** [comment]
That is good to know.  Whenever I run my tests on izumi using create_newcase (which I do a lot), I never specify the compiler.  So this is the first time that intel on izumi broke for me.  I suppose we should probably verify that it works on derecho with intel before we close this issue.  @brian-eaton - could you do that?

**Comment by cacraigucar** [comment]
This issue appears to be just with an old version of intel on izumi.  Closing issue
