### ISSUE TITLE
Replace ne16np4 grid for WACCM HIST test with ne16np4.pg3

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CAM#1038]
### What happened?

The test SMS_D_Ln9.ne16_ne16_mg17.FX2000.derecho_intel.cam-outfrq9 fails because of a missing transient dataset for ne16np4, while there is one for ne16np5.pg3.

### What are the steps to reproduce the bug?

Run SMS_D_Ln9.ne16_ne16_mg17.FX2000.derecho_intel.cam-outfrq9

### What CAM tag were you using?

cam6_3_161

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Will you be addressing this bug yourself?

No

### Extra info

See the CTSM issue on this:

https://github.com/ESCOMP/CTSM/issues/2547

There it was decided that CAM should address this and change the test to ne30np4.pg3 rather than adding a new dataset in CTSM.

**Comment by fvitt** [comment]
Yes, FX2000 can be run on a CSLAM grid.  `cam_physics_mesh` needs to point to a valid EMSF mesh file for the CSLAM grid.  This should work for the `ne16pg3` grid:
```
cam_physics_mesh = '/glade/campaign/cesm/cesmdata/inputdata/share/meshes/ne16pg3_ESMFmesh_cdf5_c20211018.nc'
```
