### ISSUE TITLE
cam6 should have additional clubb diffusion activated but it doesn't

### ISSUE THREAD

**Issue by adamrher** [ESCOMP/CAM#1041]
### What happened?

In cam6_3_059 we brought in new defaults for the additional clubb mixing and renamed it ```clubb_l_do_expldiff_rtm_thlm```. It now defaults to false for all cases except cam_dev. However prior to cam6_3_059, this was set to false **except if you're running clubb.** Specifically, this is what it looks like in older code bases:

```
<clubb_expldiff                                   > .false. </clubb_expldiff>
<clubb_expldiff       clubb_sgs="1"               > .true.  </clubb_expldiff>
<clubb_expldiff       clubb_sgs="1" silhs="1"     > .false. </clubb_expldiff>
```

We need to implement this in our new code base as the lack of this logic means -phys cam6 won't give you cam6 physics as was originally defined.

### What are the steps to reproduce the bug?

run with CAM60 in the compset longname, or set -phys cam6 in config opts.

### What CAM tag were you using?

cam6_3_059 or later

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Will you be addressing this bug yourself?

Yes, but I will need some help

**Comment by brian-eaton** [comment]
@adamrher, I think it is sufficient to change the current settings in `namelist_defaults_cam.xml` from
```
<clubb_l_do_expldiff_rtm_thlm                     > .false. </clubb_l_do_expldiff_rtm_thlm>
<clubb_l_do_expldiff_rtm_thlm phys="cam7"         > .true.  </clubb_l_do_expldiff_rtm_thlm>
```
to
```
<clubb_l_do_expldiff_rtm_thlm                        > .false. </clubb_l_do_expldiff_rtm_thlm>
<clubb_l_do_expldiff_rtm_thlm clubb_sgs="1"          > .true.  </clubb_l_do_expldiff_rtm_thlm>
<clubb_l_do_expldiff_rtm_thlm clubb_sgs="1" silhs="1"> .false. </clubb_l_do_expldiff_rtm_thlm>
```
Do you agree?  I could add this to a future miscellaneous tag.

**Comment by adamrher** [comment]
Yes I agree. Thanks Brian.

**Comment by brian-eaton** [comment]
Removed `misc` tag.  This change will cause answer changes in all cam6 configurations, so should go in by itself.
