### ISSUE TITLE
Removing mct

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CAM#1061]
### What happened?

In file cam_map_utils.F90 I found a call to m_MergeSorts which is
in the mct library we are removing.   

### What are the steps to reproduce the bug?

Build a cam case with the cime branch detailed below.

### What CAM tag were you using?

cam_develelopment as of  cam6_3_162

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

GNU

### Path to a case directory, if applicable

SMS_Ld2.ne30pg3_t232.BLT1850_v0c.derecho_gnu.allactive-defaultio

### Will you be addressing this bug yourself?

Any CAM SE can do this

### Extra info

I am running from a source sandbox with the mct library removed - this requires a  branch in cime 
```
https://github.com/jedwards4b/cime
 * [new branch]          remove_mct_for_cesm -> remove_mct_for_cesm
```

Extra information from @jedwards4b via email:

I am working on fully removing the mct library as we have discussed.    I just ran into several instances of calls to m_mergesorts from cam.   I would like to suggest that we add
[https://github.com/fortran-lang/stdlib ](https://github.com/fortran-lang/stdlib)as a prerequisite for cesm and use [the sort functions provided ](https://stdlib.fortran-lang.org/module/stdlib_sorting.html)therein as replacements for m_mergesorts.   This library has all sorts of useful
utilities and they have an agreement with the fortran standards committee that promises if new functions are adopted in the future they will be compatible with the functions defined in this library.

**Comment by jedwards4b** [comment]
Also found 
```
/glade/work/jedwards/sandboxes/cesm3_0_x/components/cam/src/chemistry/mozart/mo_srf_emissions.F90:58:9:

   58 |     use m_MergeSorts,     only : IndexSort
      |         1
```

**Comment by jedwards4b** [comment]
and:
```
/glade/work/jedwards/sandboxes/cesm3_0_x/components/cam/src/chemistry/mozart/mo_extfrc.F90:62:9:                                                                                                                    
                                                                                                                                                                                                                    
   62 |     use m_MergeSorts,  only : IndexSort                                                                                                                                                                     
      |         1                                                                           
```

**Comment by jedwards4b** [comment]
I have built /glade/work/jedwards/fstdlib/intel/2023.2.1/ and added capability to link it to cesm in my sandbox - if there is a cam developer will take on replacing these sort functions I can provide you with the work I've done.   

https://github.com/jedwards4b/ccs_config_cesm.git
  [new branch]      fortran_stdlib_support -> fortran_stdlib_support

https://github.com/jedwards4b/cime
   691b0c7a8..beeea0d0a  remove_mct_for_cesm -> remove_mct_for_cesm

**Comment by gold2718** [comment]
> if there is a cam developer will take on replacing these sort functions I can provide you with the work I've done.

What do you mean by "replace"? Could that module be added to the share library?

**Comment by jedwards4b** [comment]
I mean replacing the calls to mct's IndexSort with the [sort_index](https://stdlib.fortran-lang.org/interface/sort_index.html) provided by fortran_stdlib.

**Comment by jedwards4b** [comment]
The issue is with calls directly from cam to mct - the share library was not involved.

**Comment by gold2718** [comment]
> I mean replacing the calls to mct's IndexSort with the [sort_index](https://stdlib.fortran-lang.org/interface/sort_index.html) provided by fortran_stdlib.

Does that routine do the exact same thing as the MCT version? Is that library being used in CESM now?

**Comment by gold2718** [comment]
> The issue is with calls directly from cam to mct - the share library was not involved.

Exactly, but it could be which was my suggestion. Merely add the m_MergeSorts module (with a possible rename) to share. This code is from the old MPEU library which was added to MCT.

**Comment by jedwards4b** [comment]
In the interest of expediency I'll give your suggestion a try.  But I'm worried that once I put it there we will never remove it.

**Comment by gold2718** [comment]
> In the interest of expediency I'll give your suggestion a try. But I'm worried that once I put it there we will never remove it.

You could just port the routines used in CAM to a new share module. FWIW, I added the [8-byte IndexSort to MCT](https://github.com/MCSclimate/MCT/pull/17) back in 2015. It only went into MCT because that is where the MPEU stuff ended up.

**Comment by jedwards4b** [comment]
This issue is solved by adding m_MergeSort.F90 to the cesm_share library.  Thank you @gold2718 for the suggestion.
