### ISSUE TITLE
Prevent users from turning on OpenMP when using the SE dycore

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#1087]
### Issue Type

Code Clean-up

### Issue Description

It is looking like the fix for using OpenMP within the SE dycore may not make the release.  To prevent users from doing this, I propose adding an error in configure.

### Will this change answers?

No

### Will you be implementing this yourself?

No

**Comment by gold2718** [comment]
Is configure the right place for this? I thought SE threading was controlled by namelist variables, `se_horz_num_threads`, `se_vert_num_threads`, and `se_tracer_num_threads`.

**Comment by brian-eaton** [comment]
Hi @gold2718.  The `se_*_num_threads` variables are set by default to 0 in the namelist, so unless the user explicitly sets them (the expert user edge case) `build-namelist` won't be able to trap this.  Those variables are set to reasonable defaults at runtime by `subroutine dyn_readnl`.

`buildcpp` sets the `-smp` flag to `configure` if the case variable `NTHRDS_ATM` is greater than 1.  So `configure` knows whether threading has been enabled in the build.  I think it's the best place for this check.  Anything I'm missing?

**Comment by gold2718** [comment]
Don't we want to allow threading in the physics? If we turn off `-smp` in configure, I think that will prevent threading across chunks. Have I forgotten how this works (not at all unlikely these days :)?
To get build-namelist to trap `se_*_num_threads`, I think all you have to do is add a (temporary?) check after the variable values are loaded (I think on line 4148) and die if any of them are greater than zero.

**Comment by brian-eaton** [comment]
Running with threads in the physics, but not in the SE dycore, is not a configuration that has been explored as far as I know.  My gut feeling is that performance will be better from maximizing the task count for a given compute resource, rather than reducing task count to enable threads.  Running the SE dycore with threads was never a win, even though it used to work.

Your suggestion about trapping user set namelist values works for the user who sets those values.  But most users do not set those values and instead get the defaults that are set at runtime.  A build-namelist trap doesn't prevent that.

My read on this PR is not that we want to explore any new configurations but rather that we want to let users know that smp is currently not working with SE.  Comments welcome.

**Comment by gold2718** [comment]
> My read on this PR is not that we want to explore any new configurations but rather that we want to let users know that smp is currently not working with SE. Comments welcome.

I agree with this. I also agree that this only affects a user who goes through the trouble of adding any of the `se_*_num_threads` variables in their user_nl_cam. To me, that means that the build-namelist trap will be able to alert those users without bothering anyone else.

**Comment by gold2718** [comment]
> My gut feeling is that performance will be better from maximizing the task count for a given compute resource, rather than reducing task count to enable threads

I think there are numbers that back up that gut feeling (at least on most of today's machines), however, we usually have not been prescriptive in preventing users from trying configurations that we do not recommend.

**Comment by cacraigucar** [comment]
Right now, a user can turn on smp while using the SE dycore simply by setting ATM_NTHRDS.  They will get a runtime error that (if I remember correctly) does not give them any meaningful information, but rather points them into a wrong direction.  This issue is to prevent this from happening until the SE dycore can handle threading.  I stand by my initial request of giving an error during configure.

I do not think we need to trap the namelist settings as most users won't be trying them out (that is a more advanced feature).

As code freeze loams ever nearer, I believe that putting in the error stop in configure is the appropriate way to handle this as we don't need to do additional testing/research on other fixes.
