### ISSUE TITLE
Allow for SE tracer transport of water vapor when running CSLAM

### ISSUE THREAD

**Issue by adamrher** [ESCOMP/CAM#1088]
### What is the feature/what would you like to discuss?

Prior to PR https://github.com/ESCOMP/CAM/pull/968/, tracers were advected by both CSLAM and the SE tracer transport scheme when running CSLAM configurations -- the CSLAM tracer values would then overwrite the SE tracer values at the end of the time-step. In the PR linked above we turned off the advection by SE tracer transport, which sped up the model considerably. However, I noticed in an FKESSLER run that this creates a significant amount of noise in the solution:

![fkessler_T850_day10](https://github.com/user-attachments/assets/1135eeb4-5c37-4168-82b4-4604e5a526af)

Where CAM = cam6_4_007, and CAM-SIMA uses an older version of SE that predates the PR.

Peter and I were thinking that we could revert the PR https://github.com/ESCOMP/CAM/pull/968 for water vapor only -- that PR turned off SE transport of all tracers -- as that should alleviate the noise seen in the baroclinic wave.

### Is there anyone in particular you want to be part of this conversation?

@PeterHjortLauritzen has agreed to implement these code mods.

### Will this change (regression test) answers?

Yes

### Will you be implementing this enhancement yourself?

No

**Comment by adamrher** [comment]
FYI, Peter asked me add the CoupledEval3 label. This work will not be completed by the July 31 capability freeze.

**Comment by adamrher** [comment]
Unfortunately, I don't think we've identified the right PR that led to the increased noise in the solution. I ran tag cam6_3_132 and it gives similar noisy features (left panel):

![616](https://github.com/user-attachments/assets/276d3706-1267-49ed-9514-a1f531905ae8)

**Comment by PeterHjortLauritzen** [comment]
Turns out CAM-SIMA FKESSLER had Q=0 leading to the discrepancy (this has been fixed).
