### ISSUE TITLE
Bug with physprops files for mam4_mode3 for RRTMGP

### ISSUE THREAD

**Issue by cecilehannay** [ESCOMP/CAM#1103]
### What happened?

I am looking at the physprops files for `mam4_mode3` in ``/glade/campaign/cesm/cesmdata/inputdata/atm/cam/physprops/``
for 
- RRTMG:  `mam4_mode3_rrtmg_aeronetdust_c141106.nc`
- RRTMGP: `mam4_mode3_rrtmg_aeronetdust_sig1.2_dgnl.40_c150219.nc`

There is a bug in the `namelist_defaults_cam.xml`

- **For RRMTG**
we select the `mam4_mode3_rrtmg_aeronetdust_sig1.2_dgnl.40_c150219.nc` for `cam6`:
```
<mam4_mode1_file rad="rrtmg">atm/cam/physprops/mam4_mode1_rrtmg_aeronetdust_c141106.nc</mam4_mode1_file>
<mam4_mode2_file rad="rrtmg">atm/cam/physprops/mam4_mode2_rrtmg_aitkendust_c141106.nc</mam4_mode2_file>
<mam4_mode3_file rad="rrtmg">atm/cam/physprops/mam4_mode3_rrtmg_aeronetdust_c141106.nc</mam4_mode3_file>
<mam4_mode4_file rad="rrtmg">atm/cam/physprops/mam4_mode4_rrtmg_c130628.nc</mam4_mode4_file>

<mam4_mode1_file rad="rrtmg" ver="strat">atm/cam/physprops/mam4_mode1_rrtmg_aeronetdust_sig1.6_dgnh.48_c140304.nc</mam4_mode1_file>
<mam4_mode3_file rad="rrtmg" ver="strat" phys="cam6">atm/cam/physprops/mam4_mode3_rrtmg_aeronetdust_sig1.2_dgnl.40_c150219.nc</mam4_mode3_file>
```
- **For RRMTGP**:
the `cam6` has been removed so we select `mam4_mode3_rrtmg_aeronetdust_sig1.2_dgnl.40_c150219.nc` for cam_dev or cam7:
```
<mam4_mode1_file rad="rrtmgp">atm/cam/physprops/mam4_mode1_rrtmg_aeronetdust_c141106.nc</mam4_mode1_file>
<mam4_mode2_file rad="rrtmgp">atm/cam/physprops/mam4_mode2_rrtmg_aitkendust_c141106.nc</mam4_mode2_file>
<mam4_mode3_file rad="rrtmgp">atm/cam/physprops/mam4_mode3_rrtmg_aeronetdust_c141106.nc</mam4_mode3_file>
<mam4_mode4_file rad="rrtmgp">atm/cam/physprops/mam4_mode4_rrtmg_c130628.nc</mam4_mode4_file

<mam4_mode1_file rad="rrtmgp" ver="strat">atm/cam/physprops/mam4_mode1_rrtmg_aeronetdust_sig1.6_dgnh.48_c140304.nc</mam4_mode1_file>
<mam4_mode3_file rad="rrtmgp" ver="strat">atm/cam/physprops/mam4_mode3_rrtmg_aeronetdust_sig1.2_dgnl.40_c150219.nc</mam4_mode3_file>

```

@fvitt and @tilmes confirmed we want `mam4_mode3_rrtmg_aeronetdust_c141106.nc` for coarse mode 
see the discussion: https://github.com/NCAR/amwg_dev/discussions/561#discussioncomment-10131298

The line should be modified or removed 
```
<mam4_mode3_file rad="rrtmgp" ver="strat">atm/cam/physprops/mam4_mode3_rrtmg_aeronetdust_sig1.2_dgnl.40_c150219.nc</mam4_mode3_file>
```
as it is overwritting:
```
<mam4_mode3_file rad="rrtmgp">atm/cam/physprops/mam4_mode3_rrtmg_aeronetdust_c141106.nc</mam4_mode3_file>
```

### What are the steps to reproduce the bug?

Turn on RRTMGP

### What CAM tag were you using?

cesm2_3_alpha17f

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Other (please specify below)

### Path to a case directory, if applicable

/glade/campaign/cesm/cesmdata/cseg/runs/cesm2_0/b.e23_alpha17f.BLT1850.ne30_t232.098

### Will you be addressing this bug yourself?

No

**Comment by brian-eaton** [comment]
Hi @cecilehannay.  When I added RRTMGP at cam6_3_148 the intention was that the same optics files would be used for rrtmgp as are used for rrtmg.  I see that the rrtmgp version of `mam4_mode3_file` with the `ver="strat"` attribute is missing the `phys="cam6"` attribute.  This is a mistake from the initial merge.  I will add the `phys="cam6"` attribute so the rrtmg and rrtmgp versions are the same.

**Comment by cecilehannay** [comment]
Yes, adding the `phys="cam6"` attribute will work. Thanks a lot.
