### ISSUE TITLE
PLB,SCT,SUB, and TMC test need to be updated for cime6.1.12

### ISSUE THREAD

**Issue by fischer-ncar** [ESCOMP/CAM#1134]
### Issue Type

Infrastructure Update

### Issue Description

In cime6.1.12 the location of append_testlog was moved in cime.  So the PLB, SCT, SUB, and TMC test scripts need to be updated.

`from CIME.utils import append_testlog`

Needs to be changed to

`from CIME.status import append_testlog`

### Will this change answers?

No

### Will you be implementing this yourself?

No

**Comment by cacraigucar** [comment]
@brian-eaton - would this be a candidate for your PR #1131?
