### ISSUE TITLE
turning RRTMG-P on by default in CAM7   + some namelist defaults 

### ISSUE THREAD

**Issue by cecilehannay** [ESCOMP/CAM#1143]
### Issue Type

Other (please describe below)

### Issue Description

We would like to turn RRTMG-P on by default in CAM7.

We are also using some namelist changes:

We want to keep the correct radiative property for mam4_mode3 when running with RRTMGP. It was a bug and it was reported already. But if RRTMGP becomes the default, we want to make sure this is fixed:
```
M:mam4_mode3:/glade/campaign/cesm/cesmdata/inputdata/atm/cam/physprops/mam4_mode3_rrtmg_aeronetdust_c141106.nc
```

Other changes:
- We need to have a `ubc_file_path allowing` to full 20th century period.  I saw emails about this from Bill and Francis. 

```
ubc_file_path=  /glade/campaign/cesm/cesmdata/inputdata/atm/cam/chem/ubc/b.e21.BWHIST.f09_g17.CMIP6-historical-WACCM.ensAvg123.cam.h0zm.H2O.1849-2014_c240604.nc
```

- I think we want to change the  seasalt_emis_scale  to:    
```
 seasalt_emis_scale             = 0.75D0 
```

### Will this change answers?

Yes

### Will you be implementing this yourself?

No

---- 

@PeterHjortLauritzen, @cacraigucar, @tilmes

**Comment by brian-eaton** [comment]
@cecilehannay, I'm putting together changes for this issue.  Do you have any other updates for the cam7 default configuration?

**Comment by tilmes** [comment]
@cecilehannay Can we add the AOD output variable I sent you earlier as a default?
I am also wondering if we could save some output in original resolution, which would help with aerosol budgets.. I can send a list for that..
Simone
