### ISSUE TITLE
Visualization of nudging windows

### ISSUE THREAD

**Issue by GilbertCloud** [ESCOMP/CAM#1152]
### What is the feature/what would you like to discuss?

In the CAM tools, there's a nudging window visualization script in NCL. I converted the NCL to a Jupyter notebook and I'd like that to be added to the CAM nudging tools. The notebook can be found here: [https://github.com/GilbertCloud/CESMwindnudgingvisualization](https://github.com/GilbertCloud/CESMwindnudgingvisualization). 

### Will this change (regression test) answers?

No

### Will you be implementing this enhancement yourself?

Any CAM SE can do this

**Comment by cacraigucar** [comment]
@nusbaume - Should we open a PR to CAM for this?  If so, could you add this to your to do list?

**Comment by cacraigucar** [comment]
@GilbertCloud - After internal discussions, we agreed that the appropriate repo for this tool is:  https://github.com/NCAR/AMP_toolbox

Please open a Pull Request in that github repository for this.  When you have done that, please close this issue.
