### ISSUE TITLE
Time shown in history file names is incorrect for instantaneous data

### ISSUE THREAD

**Issue by phillips-ad** [ESCOMP/CAM#1167]
### What happened?

The translated time present in instantaneous history files does not match that shown in the actual file name. If the time variable translates to February 1st year 10 at 00Z, the history file name should end in "0010-02.nc". Right now, the file name ends in "0010-01.nc". 

### What are the steps to reproduce the bug?

Doing a ncdump on a file shows the issue:
ncdump -t -v time /glade/derecho/scratch/hannay/archive/b.e30_beta02.BMT1850.ne30_t232.104/atm/hist/b.e30_beta02.BMT1850.ne30_t232.104.cam.h0i.0010-01.nc
output: time = "0010-02-01"

### What CAM tag were you using?

cam6_4_014

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Other (please specify below)

### Path to a case directory, if applicable

/glade/campaign/cesm/cesmdata/cseg/runs/cesm2_0/b.e30_beta02.BMT1850.ne30_t232.104

### Will you be addressing this bug yourself?

No

**Comment by brian-eaton** [comment]
This is related to the comment in #1166 which explains why there is an instantaneous file associated with a monthly average file.  Those two files have the same date in the filename.  The fix here is that the instantaneous file should get a filename that uses the same template as the other non-monthly instantaneous output files.
