### ISSUE TITLE
MPAS not initializing reference pressures in the same way as other dycores

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [ESCOMP/CAM#1168]
### What happened?

Problem identified by @cjablono!

MPAS is not setting reference pressures in ```physics/cam/ref_pres.F90```

```
real(r8), protected :: pref_edge(pverp)     ! Layer edges
real(r8), protected :: pref_mid(pver)       ! Layer midpoints
real(r8), protected :: pref_mid_norm(pver)  ! Layer midpoints normalized by
                                                                         ! surface pressure ('eta' coordinate)

real(r8), protected :: psurf_ref            ! reference pressure
```

in the same way as other dycores. Other dycores use 1000hPa for the reference surface pressure whereas MPAS is using 1013.25hPa (coming from calling std_atm_profile from ```dynamics/mpas/dyn_grid.F90```) .

These reference pressures are used throughout physics.

### What are the steps to reproduce the bug?

N/A

### What CAM tag were you using?

N/A

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Will you be addressing this bug yourself?

Yes

**Comment by nusbaume** [comment]
This issues was supposed to be closed by PR #1169.  Closing now.
