### ISSUE TITLE
Suggested improvement for openfile

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CAM#1183]
### What is the feature/what would you like to discuss?

In [cam_pio_openfile ](https://github.com/ESCOMP/CAM/blob/cam_development/src/utils/cam_pio_utils.F90#L1141) the file is opened and then a message is written that it was successfully opened.  As a consequence if a file is not opened correctly the message is not printed.  This make it difficult to determine what file was causing the issue.   I would like to request that this message be moved to prior to opening the file:

 ```
if(pio_iotask_rank(pio_subsystem) == 0) then                                                                                                                
       write(iulog,*) 'Opening existing file ', trim(fname), file%fh                                                                                                  
 end if     
```
I think that this will be a great help in debugging issues with inputdata.

### Is there anyone in particular you want to be part of this conversation?

@brian-eaton 

### Will this change (regression test) answers?

No

### Will you be implementing this enhancement yourself?

Any CAM SE can do this

**Comment by briandobbins** [comment]
And I'll just second this.

**Comment by peverwhee** [comment]
@jedwards4b 

This could be a naive question, but the code currently looks like:

```
  subroutine cam_pio_openfile(file, fname, mode)
    use pio,            only: pio_openfile, file_desc_t, pio_noerr, pio_iotask_rank
    use cam_abortutils, only: endrun

    type(file_desc_t), intent(inout), target :: file
    character(len=*), intent(in) :: fname
    integer, intent(in) :: mode

    integer :: ierr

    ierr = pio_openfile(pio_subsystem, file, pio_iotype, fname, mode)

    if(ierr/= PIO_NOERR) then
       call endrun('Failed to open '//trim(fname)//' to read')
    else if(pio_iotask_rank(pio_subsystem) == 0) then
       write(iulog,*) 'Opened existing file ', trim(fname), file%fh
    end if
  end subroutine cam_pio_openfile
```

Would we achieve the same effect if we instead left the code mostly as-is but handled the errors on the CAM side within _cam_pio_openfile_ via a `pio_seterrorhandling` call? I'm just wondering if the `Failed to open <filename> to read` message might be clearer to the average user than what PIO outputs.

**Comment by jedwards4b** [comment]
I think that there is an issue with that in that the failure is happening at a layer below PIO and control is not sent back to the PIO layer to be in turn passed back to cam.

**Comment by peverwhee** [comment]
@jedwards4b ah, ok. thanks! i'll plop this change into my current open PR
