### ISSUE TITLE
O3 is not an invariant

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CAM#1189]
### Issue Type

Infrastructure Update

### Issue Description

I am trying to create a fully active compset using CAM70%MT%CT4S and I am getting an error from cam 
```
trcdata_init: file%has_ps =  T
 O3                               is not an invariant
 ERROR: tracer_cnst_init
```

### Will this change answers?

Yes

### Will you be implementing this yourself?

Yes, but I will need some help

**Comment by jedwards4b** [comment]
From @fvitt : It looks like you have prescribed oxidants specified in the namelist. When using T4S chemistry, the oxidants are prognosed and should not be prescribed.

**Comment by jedwards4b** [comment]
Again from @fvitt: The issue is with the namelist use case file
 CAM_NML_USE_CASE: 1850_cam_mt

This is appropriate for the ghg_mam for chemistry which needs prescribed oxidants.  You need an 1850 use case file for the T4S chemistry , which we don't currently have.

**Comment by fvitt** [comment]
@lkemmons @tilmes 
I may need some help with namelist settings for the T4S chemistry for 1850 compsets.   A build namelist use case file is needed for T4S perpetual 1850 conditions.  I can take an initial attempt creating the use case file.

**Comment by jedwards4b** [comment]
@fvitt Is there a use case for the HIST case?  I could continue work on that compset while waiting for the 1850 use case.

**Comment by fvitt** [comment]
> I think that there is: CAM_NML_USE_CASE: hist_trop_strat_ts4_cam7 I'll work on the HIST case while waiting for an 1850 use case.

Yes. Give that a try.

**Comment by lkemmons** [comment]
Yes - there were no aircraft in 1850 so the emissions in the file are zero!

**Comment by fvitt** [comment]
@lkemmons Please review namelist settings in this test case:
```
/glade/derecho/scratch/fvitt/1850C_T4S_ne30pg3_test01/CaseDocs
```

**Comment by lkemmons** [comment]
I think the chemistry settings (emissions, megan, etc.) look ok.
A side note - In all chemistry compsets we can remove 'ISOPNO3' from the
wet and dry dep lists -- it is a short-lived radical, so there is no need
to have it be deposited.

**Comment by fvitt** [comment]
> @fvitt do you have a final version of the use case(s) that I can grab?

Not yet.  I am working through some details.

**Comment by fvitt** [comment]
@peverwhee and @cacraigucar 
My mods are in branch:
```
https://github.com/fvitt/CAM/tree/climchem_preind
```

Should I submit a separate PR for this?

**Comment by peverwhee** [comment]
Thanks @fvitt ! No need, I'll incorporate them into Jim's existing PR (though I will tag you to review it once I do to make sure I don't miss something).

**Comment by peverwhee** [comment]
@fvitt 

(hopefully) quick question - with the new use_case updates, I'm getting this namelist diff for SMS_D_Ln9_P1280x1.ne30pg3_ne30pg3_mg17.FHISTC_MTt1s.derecho_intel.cam-outfrq9s_Leung_dust:

>   BASE: stream_ndep_year_align = 1
>   COMP: stream_ndep_year_align = 1850
>   BASE: stream_ndep_year_first = 2000
>   COMP: stream_ndep_year_first = 1850
>   BASE: stream_ndep_year_last = 2000
>   COMP: stream_ndep_year_last = 2015

Is this expected? Is it due to this code update - https://github.com/ESCOMP/CAM/pull/1078/files#diff-210ebba5e69199eb3fffc65054ad51cc7a996fd749fa5eb89c10bec849c62c7f ?

**Comment by peverwhee** [comment]
@fvitt 

Sorry, me again!
I'm also getting quite a few answer differences. Do you mind confirming for me that these are ok/expected `/glade/derecho/scratch/courtneyp/aux_cam_intel_20241118183306` ?

>   ERC_D_Ln9.f19_f19_mg17.QPMOZ.derecho_intel.cam-outfrq3s (Overall: DIFF) details:
>   ERP_Ld3.ne30pg3_ne30pg3_mg17.FHISTC_MTt4s.derecho_intel.cam-outfrq1d_aoa (Overall: DIFF) details:
>   ERP_Ln9.ne30pg3_ne30pg3_mg17.FCnudged.derecho_intel.cam-outfrq9s (Overall: DIFF) details:
>   SMS_D_Ln9.f09_f09_mg17.FCvbsxHIST.derecho_intel.cam-outfrq9s (Overall: DIFF) details:
>   SMS_D_Ln9.f19_f19_mg17.QPC2000climo.derecho_intel.cam-outfrq3s_usecase (Overall: DIFF) details:
>   SMS_D_Ln9_P1280x1.ne30pg3_ne30pg3_mg17.FHISTC_MTt1s.derecho_intel.cam-outfrq9s_Leung_dust (Overall: DIFF) details:
>   SMS_Ld1.ne30pg3_ne30pg3_mg17.FC2010climo.derecho_intel.cam-outfrq1d (Overall: DIFF) details:
>   SMS_Lh12.f09_f09_mg17.FCSD_HCO.derecho_intel.cam-outfrq3h (Overall: DIFF) details:

**Comment by fvitt** [comment]
@peverwhee Are you seeing differences in `gas_wetdep_list` namelist settings in the the above baseline failures?

**Comment by peverwhee** [comment]
@peverwhee yes. in addition to the answer changes, the wetdep and drydep lists have changed due to the removal of ISOPNO3.
