### ISSUE TITLE
CAM-SE updates: new high resolution initial conditions and topo files, new clubb_gamma and bug fix

### ISSUE THREAD

**Issue by adamrher** [ESCOMP/CAM#122]
These three todo's are scheduled to be completed prior to the cesm2.2 code freeze. 

1.) New ncdata files for ne120np4, ne120pg3 and variable-resolution ARCTIC & ARCTICGRIS grids.

2.) New (lower) clubb_gamma value for all CAM-SE runs. @jtruesdal, wondering if you can chime in here. After reviewing your F2000climo tuning runs, lowering clubb_gamma from the default value 0.308 -> 0.263 reduces RESTOM from 4.0 -> 2.758 W/m2. Lowering clubb_gamma to 0.248 further reduces RESTOM to 1.669 W/m2. My understanding is that @cecilehannay considered this small 0.248 value as lower than anything she had experimented with before, and so recommended the mid range clubb_gamma = 0.263 for CAM-SE.

3.) Bug fix. Set hyper-viscosity coefficient for temperature equal to hyper-viscosity for pressure. This is required to stabilize CAM-SE for longer integrations (+10 years).

I will have all three of these changes in a forked-off-branch sometime next week. (*correction: I would ask that Brian complete 2): dycore dependence to clubb_gamma)

cc @PeterHjortLauritzen

**Comment by adamrher** [comment]
I found a bug in the variable resolution topography generator that will change answers. I regenerated the ARCTIC, ARCTCGRIS and CONUS grid topography files, and am adding a fourth (4) item to this issue, to update the bnd_topo entries in namelist_defaults.xml to point to these new files. I have modified the name of this issue to reflect this additional task.

**Comment by adamrher** [comment]
I have completed all four tasks in my forked off branch. I branched off of cam6_2_022:

https://github.com/adamrher/CAM/tree/cam6_2_022.se

For task 1, I tried to adhere closely to the naming convention used in the ncdata and bnd_topo files I am replacing.

I was able to complete task 2 by myself after all. After a lengthy email discussion with Cecile and John T this weekend, we decided to set clubb_gamma = 0.270 & clubb_c14 = 1.6 for CAM-SE. This does not represent a final tuning product, but does a great deal to lower ne30pg3's RESTOM in a B compset ... In the words of John T, it's "a good starting point."

I added and completed an additional task to add namelist entries for the clubb_timestep used in the ARCTIC, ARCTICGRIS & CONUS grids. Let me know how I can help to move this issue forward.

**Comment by brian-eaton** [comment]
I'll turn this into a PR sometime this week.

**Comment by adamrher** [comment]
@brian-eaton Peter and I noticed that nu = 0.25 in the same block of code that addresses the bug fix in this issue. nu is supposed to be 0.5. Can I commit this change to my branch, or is it too late?

**Comment by brian-eaton** [comment]
Go ahead.  I haven't grabbed your branch yet.

**Comment by adamrher** [comment]
OK, we're all set. I've updated the branch.

**Comment by adamrher** [comment]
Peter wanted me to increase the default se_nu_top to 5.e5. So I've also added that to my branch. In doing so, I think I found a problem. I don't *think* that the se_refined_mesh=1 flags in namelist defaults is working. Here it is used in defining se_nu_top:

<img width="859" alt="Screen Shot 2020-05-09 at 5 40 31 PM" src="https://user-images.githubusercontent.com/29961476/81487686-de079580-921c-11ea-83b0-07e1d8303822.png">

And here is the atm_in file for one of my ARCTICGRIS grid:

<img width="717" alt="Screen Shot 2020-05-09 at 5 42 05 PM" src="https://user-images.githubusercontent.com/29961476/81487690-ec55b180-921c-11ea-8d1e-04b3e296a7c0.png">

So for my refined grid it is using the default nu_top. And this larger nu_top is leading to a cfl violation in the sponge layer hyper-viscosity.

The nu_top is the only place in namelist deafults that exclusively uses only the se_refined_mesh=1 flag. It is used in conjunction with hypervis_type="tensor" or "scalar", and so I think that's why it hasn't been a problematic in that the regional refinement hypervisc is turned on for regional refinement grids.

**Comment by gold2718** [comment]
I wonder if there is a typo on line 3577 of build_namelist. The logic in namelist_defaults_cam is (correctly I think) `se_refined_mesh`, however, on line 3577, it is defining `refined_mesh`. Try adding an initial `se_`.

**Comment by adamrher** [comment]
yep, that did it:

<img width="701" alt="Screen Shot 2020-05-09 at 7 24 01 PM" src="https://user-images.githubusercontent.com/29961476/81488771-b0c1e400-922a-11ea-990b-d97a095d6d8f.png">

thanks steve. I've updated the branch with this mod and documented it in ChangeLog
