### ISSUE TITLE
Memory leak in CAM diagnostics

### ISSUE THREAD

**Issue by gold2718** [ESCOMP/CAM#126]
Normally, `dtcond` and `dqcond` are deallocated at the end of `phys_run2`. However, if `single_column.and.scm_crm_mode` is `.true.`, `phys_run2` exits before the call to `diag_deallocate`.  In any case, a check should be inserted around the `allocate` calls for `dtcond` and `dqcond` in cam_diagnostics.

**Comment by cacraigucar** [comment]
@gold2718 Do you want?
 if (.not. (single_column.and.scm_crm_mode)) call diag_allocate()
 inside phys_run1.

I could see having instead at the top of phys_run2:
if (single_column.and.scm_crm_mode) then
  call diag_deallocate()
  return
endif

**Comment by gold2718** [comment]
I think your solution is fine and a bit safer.

**Comment by gold2718** [comment]
Fixed in CESM2.1 and CESM3, not going to fix in CESM2.2
