### ISSUE TITLE
SCAM6 namelist definitions inconsistent

### ISSUE THREAD

**Issue by mikaelwitte** [ESCOMP/CAM#130]
### Summary of Issue:
The namelist variable scm_iop_lhflxshflxTg is specified as a logical, but string variables are given as valid values in namelist_definitions.xml. This is also the case for several other SCAM-specific namelist variables (scm_use_obs_qv,scm_force_latlon).
### Expected behavior and actual behavior:
An error is thrown at runtime that a logical (either .true. or .false.) is not a valid value for the variable.
### Steps to reproduce the problem. Include externals description file(s) and link to public repository):
Set scm_iop_lhflxshflxtg=.true. in user_nl_cam for any build using FSCAM compset.
### Screen output or log file showing the error message and context:
![Screen Shot 2020-04-30 at 2 58 44 PM](https://user-images.githubusercontent.com/11082590/80763364-350dbc00-8af3-11ea-8987-9c7eb56940c1.png)

**Comment by gold2718** [comment]
@cacraigucar, these items have your name on them (probably erroneously)
@jtruesdal, do you know anything about how these variables got this way?
@mikaelwitte is using an older release branch tag but these entries seem to still be on the release branch and on cam_development.

**Comment by jtruesdal** [comment]
Looks like a bug that's been in the code for a while.  These variables just must not be used much.  I can coordinate with cheryl and get a fix in.
