### ISSUE TITLE
modal_aero_rename opens too many files 

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CAM#131]
In file [cam/src/chemistry/modal_aero/modal_aero_rename.F90](https://github.com/ESCOMP/CAM/blob/cam_development/src/chemistry/modal_aero/modal_aero_rename.F90) there is code that I believe to be incorrectly opening excessive numbers of files.   In my testing of compset f19_f19.QPC6 I am getting an error "Too many open files" that I have traced to the open statement at [line 367](https://github.com/ESCOMP/CAM/blob/cam_development/src/chemistry/modal_aero/modal_aero_rename.F90#L367) of this file.   This code is repeated at line 996 of the file.

In each case the file is being opened on all tasks but primarily is only used on master.
In my sandbox i have commented the calls at line 367 and 996 and it solves the problem.

**Comment by jedwards4b** [comment]
Commenting these open statements causes the total number of open files reported to go from several thousand to around 12.

**Comment by cacraigucar** [comment]
@fvitt I believe this is your code.  If it is a bug, could you add which projects (cam_development and/or release code) need the fix.  If you agree that Jim's fix is correct, you can also add the "next tag" label and we can add it to the next tags in the respective branches as this change can go in with others.

**Comment by fvitt** [comment]
Yikes!  It looks like something leftover from someone's development (not mine) -- trying to dump stuff out to file... I can do a quick cleanup if you like.

**Comment by cacraigucar** [comment]
@fvitt  Sorry - I didn't mean to imply you wrote it  - you are the recipient of many people's development efforts.  Yes, if you can propose a fix, we can put it into the next CAM tag(s) - unless this needs to go in ASAP.

**Comment by jedwards4b** [comment]
Now that I've found a work around, I don't see this issue as urgent - the next tag is fine.
