### ISSUE TITLE
SE updates for release.

### ISSUE THREAD

**Issue by brian-eaton** [ESCOMP/CAM#139]
. Address instabilities in WACCM simulations:
  - new sponge layer formulation (WACCM only)
  - code for horizontal and vertical molecular diffusion and thermal
    conductivity in the SE dynamical core 

. Functionality for species dependent thermodynamic properties of air in
  the SE dycore (for WACCM-x)

. Refactoring in physconst.F90 for general compositions of air
  and more accurate moist thermodynamics.

. Add FV3 remapping functionality to improve total energy conservation
  properties and QBO simulations with lower vertical resolution.

. Add spun-up initial condition for various CAM and WACCM configurations.

. Bug fix in the computation of OMEGA in SE dycore.

. Set EPS_AAREA=1.e-4 for all SE variable resolution grids.

**Comment by gold2718** [comment]
> Add FV3 remapping functionality to improve total energy conservation
properties and QBO simulations with lower vertical resolution.

Why is this an SE update?

**Comment by brian-eaton** [comment]
The addition is to SE.  The remapping functionality added is from FV3.  I agree the wording isn't perfect:)

**Comment by brian-eaton** [comment]
The 'bug fix for the gravity wave code' was addressed separately by PR #148.  That issue is therefore removed from this one.
