### ISSUE TITLE
Fix for floating point issue in GW drag.

### ISSUE THREAD

**Issue by brian-eaton** [ESCOMP/CAM#147]
. Fix for a floating point issue that was responsible for instability in
  WACCM configurations with the SE dycore.

Note that this fix was originally included in issue #139, but has been
removed for testing purposes since it changes answers for configurations
other than WACCM with SE.  This fix should be added first.

**Comment by gold2718** [comment]
Note that this fix is a workaround for the instability issue documented in #150.
