### ISSUE TITLE
Two new proposed labels

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#15]
As Francis and I were talking about his pull requests this morning, and I went to review what was pending, I realized that it makes sense (at least to me) for us to have two labels (cam_release and cam_development) which could be applied to each issue/pull request that pertains to one or both CAM branches.  We can visually open each pull request and see which branch it is addressing, but it might be nice to be able to sort on the label.  As for issues, we don't see if it applies to a single or both branches (unless someone puts it in their text).

I propose two labels:
cam_release
cam_development

When a user opens an issue/pull request they will select one or both if they are appropriate.

Thoughts?
@fvitt @fischer-ncar @brian-eaton @gold2718 @nusbaume

**Comment by gold2718** [comment]
I would go one step further and add the release number so that we can search on that label.
cam_development
cam_cesm2_1_rel
One or both labels should be added to any issue or PR that affects that branch.

**Comment by billsacks** [comment]
I just wanted to add this helpful and little-known feature when searching GitHub PRs: You can add in the search query something like `base:cam_development` to only see PRs that are to be merged into that branch. (I'm not at all arguing against your suggestion of labels, I just wanted to add this as an FYI.)

**Comment by nusbaume** [comment]
I think having labels describing which branch the issue/PR is targeting is a great idea!  However, I do agree that if/when we end up having more than one release branch in this repo it would be good to have labels that distinguish between them.

Also, thanks for the tip @billsacks!  I imagine the more ways we can search for issues/PR, the better.
