### ISSUE TITLE
Verify no externals are using branches prior to CESM2.2

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#157]
Currently CTSM is using a branch awaiting a PR from that group

**Comment by gold2718** [comment]
Shouldn't this be done for every CESM tag?

**Comment by gold2718** [comment]
Are these branches on forks? If so, a tag on the fork is as valid (and more stable) than a branch.

**Comment by cacraigucar** [comment]
I was loosely using the term "branch".  The CTSM external is indeed a tag on a user's fork.  My sole intention was to flag a task that needed to be done prior to code freeze (and was a reminder to me)
