### ISSUE TITLE
cam6_2_002: misc waccm(x) updates

### ISSUE THREAD

**Issue by fvitt** [ESCOMP/CAM#16]
- [x] issue #14  misc waccm(x) updates

 - adjust Nitric Oxide deactivation rate (in NO cooling)
 - zero the EPP forcings above the input data
 - 2-degree capability for FC6XSD compset
 - some support for half-degree WACCMX
 - bug fix in WACCMX ring filter for half-degree resolution
 - adjustments to FWmaSD 2-degree namelist settings

**Comment by fvitt** [comment]
addressed in cam6_2_002

**Comment by cacraigucar** [comment]
Resolved #14
