### ISSUE TITLE
Extend emission files for SSP runs past 2100 

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#164]
From email exchange:

From @drmikemills

Cheryl, Cecile, and Francis,

My 1-year test run for the proposed BSSP585ext compset crashed on November 29, 2101 due to the co2flux_fuel_file ending. I don't know why it didn't crash on December 16, but regardless, I need to make a change to run this case. I am not sure what this file does in CAM, so I am not sure whether this should be held at 2100 levels as many other emissions are.

The extension scenario is described in www.geosci-model-dev.net/9/3461/2016/ as:

"For the extension of SSP5-8.5, this involves CO2 emissions that are reduced linearly starting in 2100 to less than 10 GtC yr−1 in 2250, while all other emissions are held constant at 2100 levels."

For WACCM, this just meant using the provided time-varying LBC file, and keeping the surface emissions and external forcings cyclic for 2100. But CAM also adds the co2flux_fuel_file. What does this file do?

Case: /glade/work/mmills/case/b.e21.BSSP585extcmip6.f09_g17.CMIP6-SSP5-8.5ext-CAM.001

atm.log:
 nstep, te    15985   0.27058761467966328E+10   0.27058767939764795E+10   0.35827518215457112E-04   0.98634503701396650E+05
 input_data_utils::set_wghts_indices cannot not find time indices for input file
 : /glade/p/cesmdata/cseg/inputdata/atm/cam/ggas/emissions-cmip6_CO2_anthro_surf
 ace_ScenarioMIP_IAMC-REMIND-MAGPIE-ssp585_201401-210112_fv_0.9x1.25_c20190207.n
 c
 ERROR: 
 input_data_utils::set_wghts_indices cannot not find time indices for input file
 : /glade/p/cesmdata/cseg/inputdata/atm/cam/ggas/emissions-cmip6_CO2_anthro_surf
 ace_ScenarioMIP_IAMC-REMIND-MAGPIE-ssp585_201401-210112_fv_0.9x1.25_c20190207.n
 c
atm.log.2915660.chadmin1.ib0.cheyenne.ucar.edu.200628-230048 lines 43639-43704/43704 (END)

atm_in:
&co2_cycle_nl
 co2_flag		= .true.
 co2_readflux_aircraft		= .true.
 co2_readflux_fuel		= .true.
 co2flux_fuel_file		= '/glade/p/cesmdata/cseg/inputdata/atm/cam/ggas/emissions-cmip6_CO2_anthro_surface_ScenarioMIP_IAMC-REMIND-MAGPIE-ssp585_201401-210112_fv_0.9x1.25_c20190207.nc'
/

> ncdump -v date /glade/p/cesmdata/cseg/inputdata/atm/cam/ggas/emissions-cmip6_CO2_anthro_surface_ScenarioMIP_IAMC-REMIND-MAGPIE-ssp585_201401-210112_fv_0.9x1.25_c20190207.nc|tail
    20961116, 20961216, 20970116, 20970215, 20970316, 20970416, 20970516, 
    20970616, 20970716, 20970816, 20970916, 20971016, 20971116, 20971216, 
    20980116, 20980215, 20980316, 20980416, 20980516, 20980616, 20980716, 
    20980816, 20980916, 20981016, 20981116, 20981216, 20990116, 20990215, 
    20990316, 20990416, 20990516, 20990616, 20990716, 20990816, 20990916, 
    20991016, 20991116, 20991216, 21000116, 21000215, 21000316, 21000416, 
    21000516, 21000616, 21000716, 21000816, 21000916, 21001016, 21001116, 
    21001216, 21010116, 21010215, 21010316, 21010416, 21010516, 21010616, 
    21010716, 21010816, 21010916, 21011016, 21011116, 21011216 ;

Mike
___________________________________________________
Mike Mills

--------------------------------------------------------------------------------------------------------------

From In non-WACCM runs, there are CO2 constituents (tracers), enabled with co2_flag=.true. in co2_cycle_nl.
In CAM runs forced with CO2 concentrations, which are more typical, these CO2 constituents are purely diagnostic.
That is, their values do not feed back into any other computations.
In CAM runs forced with CO2 emissions, (esm-hist, esm-ssp585), the net CO2 constituent is used in radiation computations,
and is passed to surface components for surface BGC computations, which also provide a boundary flux condition for the CO2 constituents.

The co2flux_fuel_file dataset (and the CO2 emissions in aircraft_emit_nl) provide forcings for these tracers.
I've previously created these datasets from input4MIPs datasets.
I'll create versions of these for the extension runs, based on the GMD paper that Mike helpfully provided a reference for.

These generated datasets will need to be included in the use case file(s) in the CAM tag supporting these extension compsets.

Keith

**Comment by fvitt** [comment]
@drmikemills, 
Do you have a fix for this issue for the next cesm2.1 release?

**Comment by cacraigucar** [comment]
@drmikemills responded as follows to a question on whether this should go into the upcoming CESM2.1 release or not.

------

I was helping Katherine Thayer-Calder to set up this coupled CAM compset for LIWG runs with active glaciers. The last I heard from Katherine, on October 7, she had had some success getting it to run after Keith Lindsay gave her an updated co2flux_fuel_file file.

As for whether this should be released, I think that would be a question for AMWG, LIWG, or co-chairs.

Mike

-----

@katec - I have assigned this issue to you and removed @fvitt from it.
