### ISSUE TITLE
Core dump when using f19_f19 instead of f19_f19_mg17

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#167]
Using the f19_f19 grid instead of f19_f19_mg17 yields a core dump.  If the correct grid is used, the same code runs fine.

The command used (using cam6_2_033) was:

./create_newcase --case test_kessler_cam6_2_033_try06 --res f19_f19 --compset FKESSLER --compiler intel --run-unsupported

The backtrace was:
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
cesm.exe           0000000003BF8D0A  Unknown               Unknown  Unknown
libpthread-2.17.s  00007FF89BBB75F0  Unknown               Unknown  Unknown
cesm.exe           0000000000B4DA80  dyn_comp_mp_dyn_r        1230  dyn_comp.F90
cesm.exe           00000000011BCA67  stepon_mp_stepon_         315  stepon.F90
cesm.exe           0000000000877532  cam_comp_mp_cam_r         241  cam_comp.F90
cesm.exe           000000000083589A  atm_comp_mct_mp_a         353  atm_comp_mct.F90
cesm.exe           00000000004691F3  component_mod_mp_         257  component_mod.F90
cesm.exe           0000000000439FDD  cime_comp_mod_mp_        2202  cime_comp_mod.F90
cesm.exe           000000000045FDED  MAIN__                    122  cime_driver.F90
cesm.exe           00000000004183A2  Unknown               Unknown  Unknown
libc-2.17.so       00007FF89B7FC505  __libc_start_main     Unknown  Unknown
cesm.exe           00000000004182A9  Unknown               Unknown  Unknown

**Comment by fischer-ncar** [comment]
FYI: The f19_f19 resolution is using the gx1v6 mask, f19_f19_mg17 is using the gx1v7 mask.

**Comment by brian-eaton** [comment]
Why shouldn't f19_f19 be a sufficient grid specifier when the mask is irrelevant?

**Comment by adamrher** [comment]
Are these two the same? What's the difference?

```
  <model_grid alias="f19_f19_mg16" not_compset="_POP">
    <grid name="atm">1.9x2.5</grid>
    <grid name="lnd">1.9x2.5</grid>
    <grid name="ocnice">1.9x2.5</grid>
    <mask>gx1v6</mask>
  </model_grid>

  <model_grid alias="f19_f19" not_compset="_POP">
    <grid name="atm">1.9x2.5</grid>
    <grid name="lnd">1.9x2.5</grid>
    <grid name="ocnice">1.9x2.5</grid>
    <mask>gx1v6</mask>
  </model_grid>
```

My understanding is that the mask should be in the grid alias, and here it is not.

@fischer-ncar @jedwards4b @nusbaume

**Comment by brian-eaton** [comment]
@adamrher, f19_f19 and f19_f19_mg16 are the same.  They are both aliases for the 1.9x2.5 grid using the gx1v6 mask.  The f19_f19 alias is the older alias, and is just maintained for backwards compatibility.

I just tested this configuration with cam6_3_106 on my desktop with gnu and on izumi with nag.  Both ran fine.  I think it's safe to close this comment.

**Comment by cacraigucar** [comment]
Works now - closing
