### ISSUE TITLE
Bugs in SE/WACCM-X

### ISSUE THREAD

**Issue by brian-eaton** [ESCOMP/CAM#170]
WACCM-X using the SE dycore is under development and not supported in the CESM-2.2 release.  @PeterHjortLauritzen  has provided some bug fixes for the current code so that it now runs using a custom compset.

src/dynamics/se/dycore/prim_advance_mod.F90
. fix extents in some array args
. fix calc for grad_exner

src/dynamics/se/dycore/prim_advection_mod.F90
. fix extents in some array args

src/dynamics/se/dycore/prim_state_mod.F90
. fix some do loop extents

src/dynamics/se/dyn_comp.F90
. fix some do loop extents

src/utils/physconst.F90
. fix thermal_energy calc for variable dry air props
. fix some do loop extents

**Comment by gold2718** [comment]
Please say something about what the bugs are so that we can trace when an issue is fixed. @PeterHjortLauritzen, can you help with that?

**Comment by brian-eaton** [comment]
This issue is resolved by PR#168.  There are notes in the file changes about the specific fixes.  What is the traceability issue?

**Comment by gold2718** [comment]
Issues are where the bugs are described. I do not see any place where the bugs are listed out. We cannot trace bugs if they are not documented. In summary, the Issue documents the bug and the PR documents the bug fix.

**Comment by brian-eaton** [comment]
Updated description with specific fixes listed in PR #168.

**Comment by gold2718** [comment]
I will try one more time:
In summary, the Issue documents the bug and the PR documents the bug fix.
I still do not see any description of what the problem is. If there is a fix, there must be a problem. What were the problems?

**Comment by brian-eaton** [comment]
I think "wrong extent in a do loop" is documenting a bug.  Are you saying that "wrong extent in a do loop" is not a problem?  This is the kind of problem that is often discovered through careful code review.

**Comment by gold2718** [comment]
> I think "wrong extent in a do loop" is documenting a bug. Are you saying that "wrong extent in a do loop" is not a problem? This is the kind of problem that is often discovered through careful code review.

That is indeed a (bare bones) description, however, it did not appear anywhere in this issue until just now. All I am asking for is some (hopefully slightly more detailed) descriptions like that for each problem.
