### ISSUE TITLE
Correct error checking input_data_utils module

### ISSUE THREAD

**Issue by fvitt** [ESCOMP/CAM#175]
The following correction is needed in input_data_utils module (subroutine set_wghts_indices) to allow for the last time record of an input file when time bounds are used.

--- a/src/chemistry/utils/input_data_utils.F90
+++ b/src/chemistry/utils/input_data_utils.F90
@@ -398,7 +398,7 @@ contains
        endif
     endif
 
-    if (.not.(index>0.and.index<obj%ntimes)) then
+    if (.not.(index>0.and.index<=obj%ntimes)) then
        errmsg = 'input_data_utils::set_wghts_indices cannot not find time indices for input file: '&
             // trim(obj%filename)
        write(iulog,*) trim(errmsg)

**Comment by gold2718** [comment]
@fvitt, does this need to go into the CESM2.2 release? If so, please add the "next_release" label and the CESM2.2 milestone.

**Comment by fvitt** [comment]
This is not required for cesm2.2.  If we can get it in, that would be nice.
