### ISSUE TITLE
Update to CSTM dev107 to fix FXHIST failing test

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#182]

**Comment by gold2718** [comment]
@fvitt, can you make a PR for this when you and @ekluzek work out the remaining issues?

**Comment by fvitt** [comment]
Yes I can prepare a PR for this.
Is it okay to include a fix for #175 in the same PR?  Or should that be a separate PR?

**Comment by gold2718** [comment]
Yes, that sounds great, thanks.
