### ISSUE TITLE
Update default PE layouts for some of the new SE/FV3 grids

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CAM#183]
C96, C192, and C384, ne0np4.ARCTICGRIS.ne30x8, and ne0np4.ARCTIC.ne30x4 don't have default PE layouts setup for them, and as such likely will have problems using the default. ne0np4.CONUS is only using 8 nodes which I wonder if it's adequate. C24 and C48 are then using the default layout which might be fine since they are low resolution (although it looks like the default is only a single node).

Note related CTSM issue: https://github.com/ESCOMP/CTSM/issues/1105

Brian Dobbins has volunteered to work on this.

@adamrher @PeterHjortLauritzen @jtruesdal 

@PeterHjortLauritzen  the rough metric that @mvertens thought we should have is to be able to run 5 years a day on cheyenne -- does that sound like the right standard to have?

**Comment by PeterHjortLauritzen** [comment]
Sounds good with 5 years per day.
