### ISSUE TITLE
config_pes.xml is out of date

### ISSUE THREAD

**Issue by gold2718** [ESCOMP/CAM#185]
cime_config/config_pes.xml has entries for Yellowstone and Pronghorn where there should be entries for Cheyenne and possibly Casper.
Also, there are a couple of Hobart entries which should at least have Izumi added.
Do we also need to review resolution coverage for this file?

**Comment by gold2718** [comment]
@briandobbins, can you tackle this as part of your work on #183?

**Comment by briandobbins** [comment]
@gold2718 

Can we also remove Edison / Eos entries?  Those systems have both been decommissioned.  (There are 'eos'-specific things in some other parts of the code, too, but I'll just remove these from the config_pes.xml for now.  I wanted to check with this being my first commit.)

If so, I'll create a PR for an updated config_pes.xml that has the Yellowstone/Pronghorn entries removed (5 entries, some covered by Cheyenne cases others not), Izumi added to 2 cases that had Hobart entries, and the Edison/Eos entries removed.  I'll do a later commit for the #183 later today or tomorrow if my runs work.

**Comment by gold2718** [comment]
I would check with Jim to see what he did with B case edison entries (e.g., update them to cori? delete?) and copy that.
By default, I would lean towards removing entries from decommissioned systems.
