### ISSUE TITLE
Mismatch of start date and 1 degree and 2 degree initial files for FXHIST compset

### ISSUE THREAD

**Issue by joemci** [ESCOMP/CAM#191]
It was noticed that the start date in the FXHIST compset is 1979-01-01 but the initial files for 1 and 2 degree out of the box configurations are for 2000-01-01.  Would like to be consistent with FHIST and FWHIST and start on 1979-01-01, so initial files need to be changed.

**Comment by gold2718** [comment]
@joemci, it sounds like you consider this a bug which should be fixed for the CESM2.2 release, it that correct?

**Comment by joemci** [comment]
Yes, otherwise the start date and ic files will not match out of the box

**Comment by brian-eaton** [comment]
Does the model run with this initial file?  If so, and you want an IC file that's more in balance with the 1979 forcings the thing to do is to run for whatever period of time is necessary for the simulation to come into balance with those forcings and make sure a new initial file is created via an appropriate setting of the inithist namelist variable.  This comment assumes that the date in the current file is an accurate indication that the initial fields are indeed representative of year 2000 climate.  That's often not the case so it would be good to verify that first.

**Comment by joemci** [comment]
Yes, the model will run with the current initial file which appears to be from a year 2000 run.  We now have 1 and 2 degree ic files in balance for 1979-01-01.

**Comment by cacraigucar** [comment]
Implemented in cam6_2_044
