### ISSUE TITLE
CAM not honoring setting of PIO_NETCDF_FORMAT for hist/rest output.

### ISSUE THREAD

**Issue by jtruesdal** [ESCOMP/CAM#202]
Setting the PIO_NETCDF_FORMAT is not currently working for CAM and is needed for writing large files.  This issue is associated with pull request #201

**Comment by cacraigucar** [comment]
I believe this should be closed.  @jtruesdal and/or @gold2718 could you please confirm this?

**Comment by jtruesdal** [comment]
Yes, I'll close it. Its an issue that I ran into and Jim fixed with #201.  The PR has the wording 
fixes #201
instead of the closes #201 which is why it probably didn't close automatically.
