### ISSUE TITLE
Github Action workflow only works on cam_development

### ISSUE THREAD

**Issue by nusbaume** [ESCOMP/CAM#209]
Currently the Github Action workflow done after pull requests is set to only run on the `cam_development` branch.  However, we ideally want it to run on all branches.  This should be doable by simply removing the check for `cam_development` in the workflow YAML file.  

However, this will require that all branch project columns have the same column titles that are used in `cam_development`, which I will make sure of ahead of the pull request.

**Comment by cacraigucar** [comment]
My intention was that they have identical headers.  If not, feel free to modify them
