### ISSUE TITLE
Use Heelis E-Potential model in WACCM

### ISSUE THREAD

**Issue by fvitt** [ESCOMP/CAM#21]
Use Heelis high-latitude electric potential model in WACCM rather than Weimer96 which is used for joule heating and ion drag.  This will make the WACCM electric potential more consistent with WACCMX which uses Heelis as the default and has the option to use Weimer05. WACCMX does not use Weimer96.

**Comment by nusbaume** [comment]
Looks like this issue was supposed to be closed automatically, but never was (so closing it now).
