### ISSUE TITLE
FSCAM is failing prealpha test

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#213]
This test is failing.

SMS_D_Ln9.T42_T42.FSCAM.cheyenne_intel.cam-scam_mpace_outfrq9s

Looks like it started failing at cam6_2_046.

Error message is

err=Smartmatch is experimental at /glade/u/home/fischer/code/cesm2_2_alpha06f/components/cam/bld/perl5lib/Build/ChemNamelist.pm line 274.
CAM build-namelist - ERROR: Invalid namelist variable in '-infile' /glade/scratch/fischer/t/cesm2_2_alpha06f_alpha_intel/SMS_D_Ln9.T42_T42.FSCAM.cheyenne_intel.cam-scam_mpace_outfrq9s.GC.c2_2_a6f_int/Buildconf/camconf/namelist.
 ERROR: in _validate_pair (package Build::NamelistDefinition): Variable name scmlat not found in /glade/u/home/fischer/code/cesm2_2_alpha06f/components/cam/bld/namelist_files/namelist_definition.xml'
  File "/glade/u/home/fischer/code/cesm2_2_alpha06f/cime/scripts/Tools/../../scripts/lib/CIME/test_scheduler.py", line 797, in _run_catch_exceptions
    return run(test)
  File "/glade/u/home/fischer/code/cesm2_2_alpha06f/cime/scripts/Tools/../../scripts/lib/CIME/test_scheduler.py", line 724, in _setup_phase
    expect(cmdstat in [0, TESTS_FAILED_ERR_CODE], "Fatal error in case.cmpgen_namelists: {}".format(output))
  File "/glade/u/home/fischer/code/cesm2_2_alpha06f/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 137, in expect
    raise exc_type(msg)

My guess is Steve removed a little bit too much.

**Comment by gold2718** [comment]
Actually, I did not remove enough. CAM has not been setting scmlat and scmlon but there was a hack that shoved this stuff into the CAM namelist that needed to go away. I will remove the remaining uses (missed the ones in the usermods_dirs).
