### ISSUE TITLE
Add Horizontal Momentum Tendency Budget Variables

### ISSUE THREAD

**Issue by siouxyalie** [ESCOMP/CAM#226]
I'd like to add modifications I've already made that output U and V tendencies for all parameterizations and the dynamical core. While a temperature and moisture budget can be output by setting history_budget = .true., existing horizontal momentum tendency variables available for output have inconsistent names and by no means make a complete, closed budget. Pull request to come soon.

Mods will allow outputing UTEND_TOT, UTEND_CORE, UTEND_PHYSTOT, UTEND_MACROP, UTEND_VDIFF, UTEND_DCONV, UTEND_SHCONV, UTEND_GWDTOT, UTEND_NDG, UTEND_RAYLEIGH, UTEND_QBORLX, UTEND_LUNART, and UTEND_IONDRG. Same for V as well.

Features:

- Some of the tendency variables above may be zero, depending on the CAM configuration. However, setting history_budget = .true. will output all of them so that the sum of all the UTEND_* variables (except for UTEND_PHYSTOT and UTEND_TOT) is equal UTEND_TOT regardless of configuration. That said, I have only tested this in SCAM and with in nudged runs with the FV dycore.

- As mentioned, by default, these variables will not be output. However, with history_budget = .true., a closed U and V tendency budget will be output in addition to the existing, untouched T and Q budgets.

Caveats:

- Some of these tendencies can already be output (e.g. UTGW_TOTAL = UTEND_GWDTOT, UTEND_CLUBB = UTEND_MACROP for default CAM6, ZMMTU = UTEND_DCONV). I have not altered existing variables, but rather added variables with a consistent naming convention. Some of the added variables will be redundant.

- Some parameterizations currently do not influence horizontal momentum, but may in the future (e.g. microphysics, dry adjustment). Additional variables would need to added should such development ever occur.

- Important: time integrating UTEND_TOT **will not** give the instantaneous U. However, time integrating UTEND_TOT **will** give instantaneous UAP (U after physics). This is because U is output in the middle of physics (after deep convection but before radiation). UAP is essentially U at the end of the time step loop (at least for the FV core...).

**Comment by siouxyalie** [comment]
Quick comment: Default averaging flag for UAP, VAP (U,V after physics) is "A". I think it makes more sense for these variables to be output instantaneously. This way, time integrating the time averaged UTEND_TOT will give UAP.  However, it looks like the the averaging flag set by avgflat_pertape overrides the default set by addfld, making the potential change from "A" to "I" in UAP, VAP addfld calls irrelevant. So, solely setting history_budget = .true. will output a closed budget, but time integrating this budget will not give U,V or UAP,VAP. This is potentially very confusing. I did not want to alter any existing code, nor did I know how to somehow make it so UAP, VAP are only ever output instantaneously, so I'll leave it up to the real developers to decide.

**Comment by siouxyalie** [comment]
Code ready for review.

**Comment by adamrher** [comment]
Is ur concern that if you amend the addfld call to be 'I' for these terms, you are worried users might add 'A' to their avgflag_pertape, and so budgets would no longer be correct? Or is the issue that addfld flags are not
 being honored even in the default cause where there are no user_nl_cam mods? My apologies if I'm missing something here.

**Comment by siouxyalie** [comment]
Regardless of time averaging, the budget closes. However, if you want to test that the time integral of the sum of all time-averaged tendencies gives your time-varying UAP (i.e. tint_{0}^{t}(tavg(UTEND_TOT)) == UAP(t)), the u-tendencies need to be time averaged (unless outputting every time step) and UAP needs to be instantaneous.

Currently, the addfld call for UAP is something like addfld('UAP','m/s',something,'A','U after physics',something). Say I change 'A' to 'I'.

If I'm looking at h0 or h1 output, and avgflag_pertape = 'A','A', then then UAP is output time averaged and not instantaneous. Testing if the sum of your total tendencies gives time-vary UAP will not work, as UAP is not instantaneous. I think avgflag_pertape overrides the default averaging flag in the addfld call.

I will check if setting the addfld avgflag to 'I', setting history_budget = .true., and no change to avgflag_pertape gives time averaged tendencies and instantaneous UAP. If so, simply changing the addfld averaging flag to 'I' would be appropriate, I think.

**Comment by adamrher** [comment]
I think we're on the same page, that we both expect that the addfld avgflags are only honored if you don't explicitly set avgflag_pertape. Be curious to know if this isn't happening for some reason.

**Comment by brian-eaton** [comment]
The addfld call provides the default setting.  It is overridden by either avgflag_pertape or an explicit fincl specification.

**Comment by siouxyalie** [comment]
Makes sense. I would advocate to change the default averaging for UAP and VAP to 'I', then. I have no idea if this would mess others up, though, I'd guess most people do not use these variables.
