### ISSUE TITLE
Replace Wave Watch 3 (ww3) subversion external with github version

### ISSUE THREAD

**Issue by nusbaume** [ESCOMP/CAM#23]
The current Wave Watch 3 (ww3) externals are being pulled from the subversion repo.  However, ideally these externals should be pulled from github instead.

**Comment by nusbaume** [comment]
After discussing with Cheryl, we decided that instead of creating a new PR, we would just list the code that needs modified here, and whoever ends up creating the next tag (or the tag after that) can implement these changes into their own PR for testing, assuming there are no direct conflicts with any other code modifications.  

We have also created a new "next tag" label to help SEs search for these sort of few line, ideally b4b issues in the future (and thus incorporate them into their own PRs when applicable).  If anyone has a problem or concern with this plan going forward then feel free to reply in this issue thread.  If it does end up being ok with everyone then we will go ahead and add this to the SE workflow wiki.

Finally, for this particular issue the ww3 entry in the Externals.cfg file needs to be replaced with:

```
[ww3]
tag = ww3_190402
protocol = git
repo_url = https://github.com/ESCOMP/WW3-CESM.git
local_path = components/ww3
required = True
``` 

in the "cam_development" branch, and with:

```
[ww3]
tag = ww3_cesm2_0_rel_01
protocol = git
repo_url = https://github.com/ESCOMP/WW3-CESM.git
required = True
local_path = components/ww3
```

in the "cam_cesm2_1_rel" branch.  

I have already made sure that checkout_externals works with these changes, and that there are no code differences between the github and subversion checkouts (excluding one line in the ChangeLog).  However, I have done no formal regression testing, which will hopefully be done in a future PR anyways.

**Comment by gold2718** [comment]
I still do not understand the logic of mashing together unrelated commits. The GitHub workflow is smoother and issues are easier to track (and debug) when made separately.
Using this issue and #20 as an example, say for the sake of argument that issue #20 introduced a change (AQP11 to AQPCONST) which is incompatible with my current work. Because there is no separate commit with issue #22 alone, I cannot easily use that while avoiding the #20 change as well.
Merging #20 as a separate PR with a couple of simple tests (already made by @nusbaume) would make no difference in the testing required to merge #20 and make a tag. On the other hand, it makes needed changes available more quickly.
If anyone still disagrees, please add some compelling arguments here.

**Comment by brian-eaton** [comment]
We mash together logically distinct change sets into single commits all the
time.  Our testing requires enough resources (compute and human) that
separating logically distinct changes into separate commits would be
burdensome.  The commit I just made to the release branch contained two
distinct parts; a bug fix and an enhancement.  I see no reason to turn that
into 2 commits.

We don't have any guidelines as to what "a couple of simple tests" should
be comprised of.  I don't feel we should be burdening the developer who's
making a tested commit deal with finding the problems from a previous
commit that was not adequately tested.  I think the lightweight commit
approach that Steve is suggesting works fine in the context of automated
nightly testing and/or a dedicated test engineer.  But we currently lack
both of those resources.

I'm not really swayed by the importance of being able to back out a
previous commit that's incompatible with my current branch.  It seems to me
that what goes on the trunk is being decided and coordinated taking into
account the goals for the trunk code, and independently of whether a given
trunk commit may conflict with some developer's branch.  If the current
trunk is somehow incompatible with my branch, then I have the option to
stay on my branch without updating until I want to get my changes to the
trunk, at which time I need to resolve those conflicts.  The resolution
needs to happen sooner or later.

I'm OK with the suggestion Jesse and Cheryl have made in this issue.  Using
the issue mechanism does leave a trail for tracking a change, and makes it
easy for the person in line for commit to decide whether or not to pull the
additional presumably small change into their own testing and PR.

**Comment by cacraigucar** [comment]
Discussion moved to issue #25

**Comment by gold2718** [comment]
> We don't have any guidelines as to what "a couple of simple tests" should
> be comprised of. I don't feel we should be burdening the developer who's
> making a tested commit deal with finding the problems from a previous
> commit that was not adequately tested.

But this is precisely what the current approach does. In this case, it burdens the tag-making developer (@cacraigucar) with a change made by a different developer (@nusbaume). While this particular case might not be problematic, there have been cases where the contributed code ('can you put this stuff in with your upcoming tag?') causes a problem which the tag-making developer has had to track down. With the 2 commit / 1 tag approach, the tag developer has the option of easily trying out a failing test by leaving out the first commit or trying out that test with the first commit but not the pending tag commit. git provides 21st century tools to make this sort of debugging easier, why not use them?

**Comment by nusbaume** [comment]
I have created a new branch on my CAM fork labeled "wave_watch_fix_rel" That contains the edits above for the "cam_cesm2_1_rel" branch.  This was done to test the workflow proposed in issue #25 .

**Comment by cacraigucar** [comment]
Put in PR #26 (cam development branch) and PR #32 (cam_release branch)
