### ISSUE TITLE
Too much stdout from clubb

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CAM#238]
This is being written from every task in the cam model.  Please limit it to the mastertask.  
https://github.com/ESCOMP/CLUBB_CESM/blob/master/clubb_api_module.F90#L2883

**Comment by cacraigucar** [comment]
Move the call in clubb_intr.F90 into the masterproc section.

**Comment by cacraigucar** [comment]
Duplicated in #454.  Will be addressed in upcoming misc PR.
