### ISSUE TITLE
Remove pack/unpack from PUMAS interface code #254

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#254]
Remove the pack/unpack from MG.

**Comment by cacraigucar** [comment]
@andrewgettelman @Katetc 

What does the utility, micro_mg_get_cols do in an version of MG which does not do packing?  I am still getting mgncol being 7 when I call that routine.  

I have done my first attempt at removing all of the MGPacker object and packed arrays in micro_mg_cam, but the job is core dumping in micro_mg3_0_tend.  I need some advice on how MG operates in unpacked scenarios.   I thought I might pass the entire pcols,pver arrays and MG will find the correct cloud locations, but looking inside micro_mg3_0_tend, the arrays are all dimensioned mgncol.

**Comment by andrewgettelman** [comment]
I believe mgncol is the number of columns being passed. So if you pass pcols, pver then mgncol = pcols?
