### ISSUE TITLE
Provide RRTMGP as a radiation parameterization

### ISSUE THREAD

**Issue by brianpm** [ESCOMP/CAM#255]
I am working on a project that is supposed to use the updated radiation scheme [rte-rrtmgp](https://github.com/earth-system-radiation/rte-rrtmgp/tree/overview-manuscript-submission). To get ready for it, I am working on incorporating rte-rrtmgp into CAM. This is just getting started, but @brian-eaton shared code with me that he developed to use an earlier version of RRTMGP in CAM, so I am starting from there. 

Down the road, I expect rte-rrtmgp to become the default radiation scheme. 

My plan is to connect to the rte-rrtmgp repository, so I have already included that into `Externals_CAM.cfg` with these lines: 

```
[rrtmgp]
local_path = src/physics/rrtmgp/ext
protocol = git
repo_url = https://github.com/earth-system-radiation/rte-rrtmgp.git
tag = 1.2.1
required = True
```

**Comment by dan800** [comment]
Hi Brian,
We think we have discovered an issue with RRTMG heating rates that is impacting the S2S predictions using WACCM (10K-15K jumps in temperature in ensembles initialized with MERRA-2) This is described here - [https://drive.google.com/file/d/1yAxvxlSToSgRDSCVqj-XBOOuathaKWBH/view?usp=sharing](url)
It seems that we can solve it by moving to RRTMG SW v4.10. Is there overlap with what you are doing?
Dan

**Comment by brianpm** [comment]
Hi Dan,
I don't *think* this overlaps with this issue. I'm not sure what is left of RRTMG inside of RRTMGP, as they've done an extensive refactoring. If you think the problem still exists in RTE-RRTMGP, we can file an issue with them.

**Comment by peverwhee** [comment]
We're currently encountering a potential memory leak in the RRTMGP code (or our interface) that is causing runs to die without helpful errors. See below for status:

You can find a branch with the up-to-date RRTMPG code that Brian and I are working with here: https://github.com/peverwhee/CAM/tree/rrtmgp

The following case fails in the "expected" way (dies on the 60th timestep with NTASKS=144 on cheyenne; 183rd timestep if I increase NTASKS to 360):

./create_newcase --case "${CASEDIR}" --compset F2000climo --res ne30pg3_ne30pg3_mg17 --walltime 03:00:00 --user-mods-dir=../../cime_config/usermods_dirs/rrtmgp --run-unsupported

I've also spent a fair amount of time working with SCAM with RRTMGP on izumi. It runs without issue for as long as I've tried it thus far, but there still does seem to be a (very) small amount of memory being lost. If you want to replicate that case, you can do:

./create_newcase --case "${CASEDIR}" --compset FSCAM --res T42_T42 --user-mods-dir ../../cime_config/usermods_dirs/scam_rrtmgp

Here are a couple of modules/subroutines that I have been suspicious of for a while but can't nail down a specific problem:
1. $CAM/src/physics/rrtmgp/ext/rte/kernels/mo_rte_solver_kernels.F90 - if I place shr_mem_getUsage calls around the call to sw_dif_and_source(), memory is SOMETIMES lost but I can't figure out how/why.
2. $CAM/src/physics/rrtmgp/ext/rrtmgp/kernels/mo_gas_optics_kernels.F90 - the NAG compiler on izumi is unhappy with the inputs to the interpolation() subroutine so long as the 'bind(C, name="interpolation")' is there. I have gone through the inputs several times and nothing jumps out at me as "wrong."

**Comment by brianpm** [comment]
Update from December 2022.

RRTMGP appears to be running in a relatively recent CAM tag. The code is here: https://github.com/brianpm/CAM/tree/include_rrtmgp

@jiang-zhu was able to run some test cases and identified one additional bug that has been fixed. He has also noted that there appears to be anomalous longwave heating in the lowest model level and systematically lower insolation (about 2 W/m2) compared to the baseline RRTMG case. He also noted that there is a slight inconsistency between the wavenumber bands that are hard-coded in `radconstants.F90` and those in the RRTMGP netCDF files. 

I'm investigating the longwave heating and insolation issues.

For the wavenumber bins, I'd like to simply use those defined in the netCDF file (which can be changed via the namelist). I am not sure whether other parts of the model rely on the hard-coded values. Help would be appreciated on this.

**Comment by jiang-zhu** [comment]
Hi @brianpm 

I think we may need to update all the aerosol files, such as sulfate_rrtmg_c080918.nc, because "The optical properties of other constituents such as clouds and aerosols are computed at the same spectral points and added to the values
of the gaseous atmosphere" (Pincus, Mlawer, & Delamere, 2019). I may be wrong ...
