### ISSUE TITLE
User-mod directory needed for SMYLE simulations

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CAM#256]
I need to work with someone to add a user-mod directory for the SMYLE simulations.

Information on the settings is here.

https://docs.google.com/document/d/1rV3fWCIt-D1fAbzQ6uaQeZyLagzzKnopofr88eXegzY/edit?ts=5f7e43e4

I think the only change needed for CAM is to point to a CO2 future scenario file that has the historical period included in it, so that one simulation from 1850-2025 can be done without changing datasets mid-stream.

Who is the person I need to work with for this?

**Comment by cacraigucar** [comment]
@ekluzek Are you looking for someone to advise you on the CAM side of the project or to simply pull in the changes after you have made them?  Also, is this issue going into the cam_development branch or is it another of the CESM2.1 side projects?

**Comment by ekluzek** [comment]
@cacraigucar I need to work with someone on this. I'll likely at least need someone to help me figure out what the changes to CAM namelist needs to be. I took a quick look at the use-cases directory and I have an idea of what needs to happen, but I'm not completely sure. Since, this is CAM though -- I'd rather have a CAM person create this branch.

This would NOT go into cam development, It'll just be a CESM2.1 side project. Right now we aren't sure if it'll go into official CESM2.1.x, but it needs to be a branch for SMYLE that based off the version of CAM that's in CESM2.1.x.

**Comment by gold2718** [comment]
Who is the scientist who is working on this? They should have some idea of the necessary namelist changes.
Or is there a user_nl_cam file from a case we can reference?
The main use of a user_mod file would be to add this to CAM, is that the goal?

**Comment by ekluzek** [comment]
The scientists that I know about are: Stephen Yeager, Gokhan, Dave L., Will Weider. All Ocean or Land people. I don't know if they have someone who's responsible for the CAM part of this. I'll check with the land people tomorrow on if there's a scientist responsible for CAM.

The need for a user-mod directory is so that the CESM branch for this can point to the user-mod directory for each of the subcomponents.

**Comment by gold2718** [comment]
If this is an active experiment, there must be a user_nl_cam file we can start with. That, and a name (e.g., `CAM60%SMYLE` that would be used in the compset longname) would allow us to set up the branch.

**Comment by ekluzek** [comment]
@gold2718 these are experiments that are being planned, rather than already carried out. For the answer to your question the answer I got from the group is @cecilehannay and @nanr as the scientists that will be working on this to represent CAM.

**Comment by gold2718** [comment]
@ekluzek, great, then they can update this issue with answers to my questions when they have the necessary information.
Thanks for opening the issue.

**Comment by ekluzek** [comment]
@nanr notes that another part of this is to add the historical part of the LBC files to the SSP part....

I think we should merge these two files, with the output file going in the same directory.
/glade/p/cesmdata/cseg/inputdata/atm/waccm/lb/LBC_1750-2015_CMIP6_GlobAnnAvg_c180926.nc
/glade/p/cesmdata/cseg/inputdata/atm/waccm/lb/LBC_2014-2500_CMIP6_SSP370_0p5degLat_GlobAnnAvg_c190301.nc

**Comment by nanr** [comment]
@gold2718 I am putting together the use_case that will accompany the CAM60%SMYLE compset.  I have created all the forcing files I need.

**Comment by gold2718** [comment]
@nanr, @ekluzek, any updates on this? It would be good to know when to expect a PR so we can get it into our development cycle.

**Comment by gold2718** [comment]
@nanr, I have added this issue to the to-do list for our main development branch, cam_development.
I did not add it to CESM2.2 -- is there a use case why this should be added to that release (assuming there are any CESM 2.2 updates?).

**Comment by nanr** [comment]
@gold2718 I might be wrong about adding smyle to CESM2.2.  I do not understand all the implications for carrying it forward (or not), but for now, let's leave it with CESM2.1.4.  Sorry for the confusion.

**Comment by nanr** [comment]
> @nanr, @ekluzek, any updates on this? It would be good to know when to expect a PR so we can get it into our development cycle.

@gold2718 @ekluzek We are not using the user-mods dir for cam.

**Comment by cacraigucar** [comment]
@nanr and @ekluzek  I will go ahead and close this issue when I close the SMYLE CESM2.1 branch PR.  If at a later date you need this brought into cam_development, please go ahead and open a new issue.
