### ISSUE TITLE
attempt to initialize variable prior to calling intent(out) subroutine

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CAM#263]
In the se dycore here:
https://github.com/ESCOMP/CAM/blob/cam_development/src/dynamics/se/dyn_comp.F90#L2168
and again here:
https://github.com/ESCOMP/CAM/blob/cam_development/src/dynamics/se/dyn_comp.F90#L2196
the variable buffer is initialized to 0 prior to calling infld,  but infld defines buffer as intent(out)
most compilers seem to ignore the intent but the nag compiler does not and as a result the
field is uninitialized where it is not read in from the file.  In pio2 this is causing an error reading the initial file
(test ERC_D_Ln9.ne16_ne16_mg17.QPC4.izumi_nag.cam-outfrq3s_usecase).

**Comment by brian-eaton** [comment]
I'll fix this.

**Comment by jedwards4b** [comment]
@brian-eaton I am in the process and it's more complicated than it at first appears, pio uses the fillvalue to fill in points in the buffer which are not read from the file - so in cam you need to find out what the fill value is then search the array and change fillvalue to 0.

**Comment by brian-eaton** [comment]
Thanks for the heads up!  Carry on:)

**Comment by gold2718** [comment]
I'll just set the entire array to `-900.0` after the file read.


:) It's being a long week (note lack of past tense)
