### ISSUE TITLE
contrail parameterization

### ISSUE THREAD

**Issue by chihchen24** [ESCOMP/CAM#274]
A contrail parameterization was implemented and we will like it to get into the CAM development tag.
The parameterization is triggered only if user_nl_cam includes aviation emission files needed for the parameterization.
Otherwise, the parameterization will not be activated and thus will not change the answer of the simulation.

In addition to the parameterization, we will need to request disk space in inputdata directory to store the aviation emission files for the parameterization.

@andrewgettelman @cacraigucar

**Comment by nusbaume** [comment]
Closed manually as we forgot to add this to the CAM development project.
