### ISSUE TITLE
Remove test_release category from CAM's testing

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#283]
The test_release category was created for a one-time use, but remains (unmaintained) in the testing file.  It should be removed as no one actively uses it for testing.

Check and see if any tests exist only as test_release, and if so, possibly move it to prebeta.

**Comment by peverwhee** [comment]
@cacraigucar the only test I found that only exists as test_release was of compset FTJ16 - should I move it to prebeta? and if so, under which section?

to clarify, I'm removing all tests (that exist elsewhere) from testlist_cam with the category "test_release", correct? Should the category also be removed from the cime/scripts/lib/CIME/case/case.py script?

**Comment by cacraigucar** [comment]
I would like to get feedback from @gold2718 and @nusbaume on this particular test.  

Here is the history of it being in test_release.
Prior to releasing CESM2.0, Mariana requested that all compsets be tested and as a result, I created the test_release category. 
At that point a compset named FDSBAROMOIST along with all other compsets was added to the test_release category.  It did not have any other level of test.
When Brian Eaton made cam6_0_028 "add moist Held-Suarez simple physics", he change this test to be FTJ16 in the test_release category.

This leads me to believe that he intended the test to be minimally tested and should at least reside at the prebeta level.

As for removing the test from the cime case.py script, a change there would require opening an issue in ESCMCI/cime.  I will ask @fischer-ncar on whether an issue should be opened there or not.

**Comment by fischer-ncar** [comment]
You can open a cime issue to remove test_release from case.py.  But it'll be a very low priority, it doesn't hurt anything to leave it in.  test_release is just being used to print a warning message about a compset being unsupported, but tested.  CAM is the only one using a test_release category.

**Comment by gold2718** [comment]
Do we know if E3SM uses test categories? If so, we can't remove any.
If not, I agree with @fischer-ncar that it is not a priority.
Opening an issue will at least get a response from E3SM (if they care).

**Comment by fischer-ncar** [comment]
The function in case.py that test_release is used in, has a comment "CESM only:".

**Comment by nusbaume** [comment]
My vote would also be to add an issue to CIME about removing it, even if it takes a long time for anyone to get to it (as at least then there will be a record).

**Comment by peverwhee** [comment]
I will add an issue to CIME about removing the category.

Thoughts on FTJ16?

**Comment by cacraigucar** [comment]
> I will add an issue to CIME about removing the category.
> 
> Thoughts on FTJ16?

@gold2718 and @nusbaume  - What are your thoughts?  

I believe this needs to be tested and since moist Held-Suarez should be pretty stable, I think prebeta may be appropriate.  On the other hand, I really hate to have anything tested solely in prebeta that is not tested in either aux_cam or prealpha unless it is something very simple, like a different grid.  Brian Eaton determined that this should be tested just at release, which is why I'm willing to go to prebeta with it.

**Comment by gold2718** [comment]
It does need to be tested as it is part of the official [CESM Simpler Models hierarchy](https://www.cesm.ucar.edu/models/simpler-models/) (see [Moist Held Suarez](https://www.cesm.ucar.edu/models/simpler-models/moist_hs/index.html)).
My vote is prealpha which is earlier in the cycle. I think we will have other tests for the physics in this compset with the new infrastructure.

**Comment by cacraigucar** [comment]
@peverwhee Knowing that it will soon be more actively used, I concur with @gold2718 and agree that it should be tested at the prealpha level

**Comment by nusbaume** [comment]
It looks like this issue wasn't closed automatically because it was re-opened, but the project card wasn't moved.  Will go ahead and close it now.
