### ISSUE TITLE
drydep files - need sensible solution

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#284]
When adding the second listed file to the namelist_defaults_cam.xml file, answer changes were seen.  A discussion needs to occur and a decision on how best to handle this type of file for unstructured grids.  @fvitt and @brian-eaton  - any thoughts?

@gold2718 you may want to elaborate as you have more insights into this issue

<drydep_srf_file hgrid="ne5np4"          >atm/cam/chem/trop_mam/atmsrf_ne5np4_110920.nc</drydep_srf_file>
<drydep_srf_file hgrid="ne5np4"   npg="3">atm/cam/chem/trop_mam/atmsrf_ne5pg3_201105.nc</drydep_srf_file>

**Comment by fvitt** [comment]
Why is this closed?  Did someone implement a solution for this problem?

**Comment by cacraigucar** [comment]
@adamher concluded that answers should change if using npg3.  @fvitt- Did we misinterpret the issue?

**Comment by adamrher** [comment]
while i think the drydep surface files need to go, the specific issue above isn't really an issue, as stated. the drydep surface files need to be defined on the physics grid, and so a separate file for np4 and pg3 is req'd.
