### ISSUE TITLE
cam_snapshot is not working with clubb_tend_cam

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#286]
There is an error with cam_snapshot when clubb_tend_cam is set.  The error occurs in build-namelist.

**Comment by cacraigucar** [comment]
@gold2718 It appears that clubb_tend_cam is not being added to the @validList_bc when it should be in build-namelist.  Since this logic was brought  in by your PR https://github.com/cacraigucar/CAM/pull/1, could you please provide a fix for it?  

To get Cecile running, I had her comment out the if/else logic around the "push (@validList_bc, ("'clubbZ_tend_cam'"));" line so that it gets added to the list.  My attempts at fixing it properly are not giving me the results I expect, so to be safe, I'm requesting your assistance.

**Comment by gold2718** [comment]
I have no idea when it is supposed to be added and you provided no reproducer. What is the situation when it should be set but isn't?
Currently, it seems to be added if `clubb_sgs` is on. Is that no longer true? If there has been a logic change, just update the logic in `check_snapshot_settings`. If there has _not_ been a logic change but the current routine is broken, add reproduction instructions to this issue.

**Comment by cacraigucar** [comment]
To reproduce the problem:

./create_newcase  --compset F2000climo --res f10_f10_mg37 --case test_try01 --run-unsupported  (note any CAM6 compset demonstrates this problem)

user_nl_cam:
cam_take_snapshot_before ='clubb_tend_cam'
cam_take_snapshot_after = 'clubb_tend_cam'
cam_take_snapshot_before_num = 6
cam_take_snap_after_num = 7

./case.setup
./preview_namelist (this script demonstrates the problem)

**Comment by gold2718** [comment]
I do not have time to deal with this (add it to the Tuesday priority list), however, the problem is probably simply that the call to `check_snapshot_settings` is coming before all the relevant variables (e.g., `$clubb_sgs`) are set. Try moving that call further down.

**Comment by cacraigucar** [comment]
For the upcoming PR - there were two bugs when used with a WACCMX run that Cecile was making.  The bugs identified as needing to be fixed are:

1. The call to check_snapshot_settings section in bld/build-namelist does need to be moved down to right before "Write output files" as @gold2718 suggested.
2. There was a bug during run that said N2O_snapshot has already been added. To fix this in src/control/cam_snapshot.F90 in the routine cam_cnst_snapshot_init, add "_cnst_snapshot" to the output constituent name instead of "_snapshot".  This avoids the duplicate name.

**Comment by cecilehannay** [comment]
I am still having an issue. 
The model crashes with the error:

1: pionfwrite_mod::write_nfdarray_double         107   IAM:            0  start:
1:                     1                     1  count:                  48600
1:                     1  size :                     1  error:          -60
1:       19667           0
1: pio_support::pio_die:: myrank=          -1 : ERROR:
1: pionfwrite_mod::write_nfdarray_double:         250 :
1: NetCDF: Numeric conversion not representable

My case directory is in:
/glade/p/cesmdata/cseg/runs/cesm2_0/f.e21.FWscHIST.ne30_L48_BL10_v1_tag20201111.001_snapshot

**Comment by cacraigucar** [comment]
Also, to better identify variables in the file, the structure name should be added to the output name.  For instance state%t should be state_t_snapshot instead of t_snapshot.

**Comment by cacraigucar** [comment]
> I am still having an issue.
> The model crashes with the error:
> 
> 1: pionfwrite_mod::write_nfdarray_double 107 IAM: 0 start:
> 1: 1 1 count: 48600
> 1: 1 size : 1 error: -60
> 1: 19667 0
> 1: pio_support::pio_die:: myrank= -1 : ERROR:
> 1: pionfwrite_mod::write_nfdarray_double: 250 :
> 1: NetCDF: Numeric conversion not representable
> 
> My case directory is in:
> /glade/p/cesmdata/cseg/runs/cesm2_0/f.e21.FWscHIST.ne30_L48_BL10_v1_tag20201111.001_snapshot

@cecilehannay - Do you suspect that this error still will occur?  Should I research it?

**Comment by cecilehannay** [comment]
With the workaround, it works.

 if (nstep == 7279) then
                 call
cam_snapshot_all_outfld_tphysbc(cam_snapshot_before_num, state, tend,
cam_in, cam_out, pbuf, &
                      flx_heat, cmfmc, cmfcme, pflx, zdu, rliq, rice, dlf,
dlf2, rliq2, det_s, det_ice, net_flx)
                 write(0,*) 'wrote out snapshot'
                 return
             end if
             if (nstep > 7279) call endrun ('Stopping after timestep')

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Cecile Hannay
National Center for Atmospheric Research
email: hannay@ucar.edu
webpage: http://www.cgd.ucar.edu/staff/hannay/

"Live as if you were to die tomorrow. Dream as if you were to live
forever."
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by cacraigucar** [comment]
@adamrher Pointed out a potential issue.  The cam_snapshot code is within the macmic timestep.  It is being written out in each timestep and appears that it might be overwriting the same location in the output files.

@gold2718 How does outfld handle outputting fields within CLUBB?  I'm not seeing any special logic taking into account macmic timesteps in the outfld calls in clubb_intr.

**Comment by gold2718** [comment]
> How does outfld handle outputting fields within CLUBB? I'm not seeing any special logic taking into account macmic timesteps in the outfld calls in clubb_intr.

This is where CAM's history processing kicks in. CAM Snapshot uses the 'I' (instantaneous) field processing. This name is not very accurate, the better way to read it is as 'last sampled value'. Therefore, the snapshot file will contain the value from the last `macmic` cycle.

To change this behavior, CLUBB would have to change how it creates output fields (e.g., by creating a different field for each cycle using `addfld`) and/or using logic to control when `outfld` is called.

**Comment by adamrher** [comment]
Could I populate an array of size (macmic_num_steps, pver, pcols) within the subcycle and then outfld that array just outside the loop? I just want to be able to track the instantaneous state throughout the subcycles.

**Comment by cacraigucar** [comment]
@adamher  Your proposal should work just fine.  I will not attempt to modify cam_snapshot to handle the macmic subsetps.

**Comment by gold2718** [comment]
I was thinking of that -- easy to do for a field or two. You will need `add_hist_coord` to add the new (cycle index) dimension.

A lot more work but probably useful would be to add this to cam_snapshot.

For an example of using `add_hist_coord`, see src/physics/cam/subcol.F90
