### ISSUE TITLE
CAM wiki documentation

### ISSUE THREAD

**Issue by cecilehannay** [ESCOMP/CAM#292]
On the CAM wiki: https://github.com/ESCOMP/CAM/wiki
the menu needs to be fix to match the main page.

On the main page (left column), under the tile CAM documentation, we have: 
- CAM Documentation
- Atmosphere Model Working Group (AMWG)

On the menu  (right column), under the title CAM documentation, we have:
- CAM6 user's guide
- CAM6 science development
- CESM2 development simulations
These are outdated links and they need to be changed to match the main page

Thank you. 

PS: Sorry, I don't have permissions to edit CAM wiki.

**Comment by gold2718** [comment]
Fixed, thanks for noticing the issue.
