### ISSUE TITLE
Update needed for cesm2-le ssp245BB

### ISSUE THREAD

**Issue by fischer-ncar** [ESCOMP/CAM#293]
This issue is similar to #266 #249.  Need to add a new use_case for ssp245BB_cam6.

**Comment by cacraigucar** [comment]
@fischer-ncar Who is supplying the changes required?

**Comment by fischer-ncar** [comment]
@nanr has passed the changes to me.

**Comment by cacraigucar** [comment]
@fischer-ncar  When you open the PR, you most likely will get the next CESM2.1 commit slot
