### ISSUE TITLE
Incorrect repo url for COSP?

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#295]
Opening an issue for the PR #294 opened by @KapilS25 to enable discussion of the issue.

@KapilS25 indicates that /tags does not exist on the repo and that it should be /tree instead

**Comment by cacraigucar** [comment]
@gold2718 or @brian-eaton Since the current setup seems to work, do one of you know if the reason is that we are using the svn protocol for manage_externals?  Do we need to change this?

**Comment by brian-eaton** [comment]
We're using svn protocol to extract part of the repo, just like we were doing for MPAS before Michael and Steve got together to do something different.  The "something different" would need to happen in the COSP repo, so Justin Swales and/or Robert Pincus would need to be involved.
