### ISSUE TITLE
Code fix in  aero_model.F90

### ISSUE THREAD

**Issue by tilmes** [ESCOMP/CAM#298]
We found a bug in  aero_model.F90 for the calculation  of  tropospheric surface area density:
The following code needs to  include also p-organics in the calculation of the index_chm_mass (used for surface area density calculations). This old code:
 do n = 1,nmodes
       call rad_cnst_get_info(0, n, mode_type=mode_type, nspec=nspec)
       if ( trim(mode_type) /= 'primary_carbon') then ! ignore the primary_carbon mode
          do l = 1, nspec
             call rad_cnst_get_info(0, n, l, spec_type=spec_type, spec_name=spec_name)
             index_tot_mass(n,l) = get_spc_ndx(spec_name)
             if ( trim(spec_type) == 'sulfate'   .or. &
                  trim(spec_type) == 's-organic' .or. &
                  trim(spec_type) == 'black-c'   .or. &
                  trim(spec_type) == 'ammonium') then
                index_chm_mass(n,l) = get_spc_ndx(spec_name)
             endif
          enddo
       endif
    enddo

Has to  be  changed to:
 do n = 1,nmodes
       call rad_cnst_get_info(0, n, mode_type=mode_type, nspec=nspec)
       if ( trim(mode_type) /= 'primary_carbon') then ! ignore the primary_carbon mode
          do l = 1, nspec
             call rad_cnst_get_info(0, n, l, spec_type=spec_type, spec_name=spec_name)
             index_tot_mass(n,l) = get_spc_ndx(spec_name)
             if ( trim(spec_type) == 'sulfate'   .or. &
                  trim(spec_type) == 's-organic' .or. &
                  **trim(spec_type) == 'p-organic' .or. &**
                  trim(spec_type) == 'black-c'   .or. &
                  trim(spec_type) == 'ammonium') then
                index_chm_mass(n,l) = get_spc_ndx(spec_name)
             endif
          enddo
       endif
    enddo
This fix will impact chemistry configurations of CESM in particular effects on tropospheric chemistry.

**Comment by cacraigucar** [comment]
@tilmes It sounds like this bug fix might need to in addition to going into cam_development , it might also need to go into the CESM2.2 branch and maybe even CESM2.1.  Please advise on which branches this should go into.

**Comment by tilmes** [comment]
I would suggest just adding it in a CESM2.2 branch and the cam_development version

**Comment by fvitt** [comment]
@tilmes 
Please point me to modified source code that fixes this issue, if you have it.

**Comment by tilmes** [comment]
@fvitt This is the surface area bug, which may be tested alon gwht the MAM #315 bug fix.

**Comment by cacraigucar** [comment]
@fvitt - Was it deemed that this issue should not be fixed on CESM2.2 after all?  Is that why you closed this PR?

**Comment by fvitt** [comment]
@tilmes can confirm.  This does not need to be fixed in 2.2.

**Comment by tilmes** [comment]
Yes, that  is fine!  Thanks!
