### ISSUE TITLE
Bug report and suggested change modal_aero_data.F90 and in modal_aero_gasaerexch.F90

### ISSUE THREAD

**Issue by tilmes** [ESCOMP/CAM#299]
We worked on removing hard coded mw numbers in the code and therefore suggesting a change to this code:
modal_aero_data.F90  and 
if ( soa_multi_species ) then modal_aero_gasaerexch.F90. During that process, we also found a bug in modal_aero_gasaerexch.F90, as outlined below:

modal_aero_data.F90:
For CAM (without chemistry) (else statement below), the model is using hard coded molecular weitht  number. This does not seem to be necessary, because, molecular weights are expected to be properly defined in the chemistry (cnst_mw). 
This change is currently tested in a F2000 CAM configuration.

            if ( soa_multi_species ) then 
                ! Molecular weight for the species
                specmw_amode(l,m) = cnst_mw(qArrIndex)
             else ! the follow preserves the molecular weights historically used in MAM
                call rad_cnst_get_info(0, m, l, spec_type=spec_type )
                select case( spec_type )
                case('sulfate')
                   if (ntot_amode==7) then
                      specmw_amode(l,m) = 96._r8
                   else
                      specmw_amode(l,m) = 115._r8
                   endif
                case('ammonium')
                   specmw_amode(l,m) = 18._r8
                case('p-organic','s-organic','black-c')
                   specmw_amode(l,m) = 12._r8
                case('seasalt')
                   specmw_amode(l,m) = 58.5_r8
                case('dust')
                   specmw_amode(l,m) = 135._r8
                case default
                   call endrun('modal_aero_data_init: species type not recognized: '//trim(spec_type))
                end select
             endif

Further clean up in modal_aero_gasaerexch.F90 is suggested in lines 591 and 592: instead of setting:
 mw_poa_host = 12.0_r8
mw_soa_host = 250.0_r8
Changing this to:
! get molecular weight from the host model
            do n = 1, ntot_amode
              do l = 1, nspec_amode(n)
                  call rad_cnst_get_info(0, n, l, spec_type=spec_type )
                  select case( spec_type )
                   case('s-organic')
                     mw_soa_host(:) = specmw_amode(l,n)
                   case('p-organic')
                     mw_poa_host(:) = specmw_amode(l,n)
                   end select
               end do
            end do

Finally, a bug was found while looking through the routine in Line 1280, where the part shown below should be removed:
Because 1. mw for soa is assumed to 150, which is wrong, second, g0_soa should not be scaled to the mw, following personal communication by Manish
! IF mw of soa EQ 12 (as in the MAM3 default case), this has to be in
      ! should actully talk the mw from the chemistry mechanism and substitute with 12.0
      if (.not.soa_multi_species) then
         g0_soa = g0_soa*(150.0_r8/12.0_r8)
      else
      end if

I have tested the changes listed above in combination CAM and this is changing aerosols in CAM configuration. I am currently  running a test where I only add the changes to modal_aero_data.F90 to identify the specifics.  Happy to show results etc.

Thanks, Simone

**Comment by cacraigucar** [comment]
@tilmes For this issue as well, we need to know which CAM branches the changes go into.

**Comment by tilmes** [comment]
Suggested changes would need to go into the development branch.

**Comment by fvitt** [comment]
@tilmes
Do you have modified source files you can point me to?

**Comment by tilmes** [comment]
Here is a run that used those changes:
/glade/p/cesm/chwg_dev/tilmes/cases/cesm2_ch/f.e22.F2000.f09_f09_mg17.cam_cesm2_2_rel_02.soafix/SourceMods/src.cam
