### ISSUE TITLE
A cam prealpha test is exceeding it's 20 minute wallclock

### ISSUE THREAD

**Issue by fischer-ncar** [ESCOMP/CAM#302]
The prealpha test

`SMS_D_Ln9.ne0CONUSne30x8_ne0CONUSne30x8_mt12.FCnudged.cheyenne_intel.cam-outfrq9s_refined_camchem`

Has a 20 minute wallclock limit set for it.  In the latest round of testing it's been taking 21 minutes to complete all 
of the test.  I would recommend the wallclock be set to 30 minutes.

**Comment by cacraigucar** [comment]
Alternatively, could this be shortened to less than 9 timesteps?  @fvitt what are your thoughts?

**Comment by fischer-ncar** [comment]
I think this is more of an issue of cprnc processing the ne0CONUSne30x8_ne0CONUSne30x8_mt12.  The run itself takes 13 minutes, cprnc takes another 8 minutes.

**Comment by fvitt** [comment]
Just bump up the wall clock time to 30 or 40 minutes.

**Comment by cacraigucar** [comment]
@fischer-ncar indicated this is no longer an issue
