### ISSUE TITLE
Add the ALI-ARMS non-lte code as an option for high-top versions of CAM

### ISSUE THREAD

**Issue by dan800** [ESCOMP/CAM#306]
Non-LTE cooling rates in the mesosphere are calculated using a parameterization based on the ALI-ARMS (Accelerated Lambda Iterations for Atmospheric Radiation and Molecular Spectra) non-LTE model. The current calculation (Fomichev) is not designed for CO2 concentration over 720 ppmv, so not intended for 4xCO2 experiments. The new parameterization is accurate over a larger range of CO2 values.

Ref: Kutepov, A. A., O. A. Gusev, and V. P. Ogibalov (1998), Solution of the non-LTE problem for molecular gas in planetary atmospheres: Superiority of accelerated lambda iteration, J. Quant. Spectrosc. Radiat. Transfer, 60, 199 – 220.

**Comment by cacraigucar** [comment]
From 4/29/2021 meeting with Dan, Cheryl and Steve:

Turn on output for qrlf, co2cool, o3cool, c2scool and qrlaliarms.  Make a 5 day run using FW2000 and f09_f09_mg17, turning on timing for tphysbc and adjusting detail as needed.  Make a separate run with ALI-ARMS turned off to see what timing impacts it may have.

In src/physics/ali_arms/nlte_aliarms.F90, remove the zkm calculation and replace with state%zm from calling routine.  Units in routine need to be km and are probably in meters in state.

Repeat 5 day run with this modification

Next step:
  Make separate routines for o3cool and c2scool that can be called from src/physics/waccm/nlte_lw.F90 like nocool and o3pcool are currently called.

@gold2718 and @dan800: Please update this if needed.
