### ISSUE TITLE
Adding namelist variables to CAM for Perturbed Parameter Ensemble

### ISSUE THREAD

**Issue by andrewgettelman** [ESCOMP/CAM#313]
We have a series of additional variables in the physics to be pulled to namelist in order to facilitate a large multi-member Perturbed Parameter Ensemble (PPE) with CAM6. This changes about 6 routines (I think), but does NOT change answers: the values will be set to the CAM default. Should be ready in a few weeks. Kate is working on this. Just making a placeholder for it.

**Comment by andrewgettelman** [comment]
Adding @gold2718 , @cacraigucar @Katetc and @trudeeidhammer to this comment....

We are nearly ready to run the PPE. This is 1250 years of simulation, so we have to be a bit careful. We want to make sure we have the final code staged for the CAM trunk at least before we do the simulations, so they are traceable in the future.

So here is where I think we stand (feel free to discuss, even in my absence, if I get anything wrong, which I am sure I did)

1. Trude has one or two more namelist variables (In clubb_intr.F90)
2. Kate was going to:
- Assemble the PPE code, merge it up to the head of the cam trunk and make a PR.
- Check if we can run with the same CLM tag as they used for their PPE. 
3. Once Kate has the PR and starts regression testing, then Trude can do final tests and run (or wait for Kate's regression testing
4. I am hoping that this PR can be the next CAM tag. There is no immediate rush to get approved if we have the PR and it is going through review. Trude can run from the tag anyway. The answer changes are (should be) roundoff as we are not changing defaults. 

I will probably push back against changes to names of the namelist variables, since we will be running already. 

If desired, the SEs can take a quick look and see if the names are okay. I think the current names are on the CAM PPE Namelist variables sheet. 
https://docs.google.com/spreadsheets/d/1ILulvyTRyflzI_kEQ9aU0bpjm6WO_DSKABjG4jnm048/edit?usp=sharing

**Comment by cacraigucar** [comment]
Please make sure any new namelist variables have the module name prepended to the name.  We've been trying to have the namelist variable identify the module it goes with.
