### ISSUE TITLE
Need to transport CL and BR

### ISSUE THREAD

**Issue by fvitt** [ESCOMP/CAM#314]
Chemical species CL and BR need to be transported in all configurations.

We have not been transporting CL and BR in the WACCM middle atmosphere configurations, including D-region chemistry configuration, (waccm_ma and waccm_mad). The assumption that these species do not need to be transported breaks down in the upper atmosphere (above 80 km or so) where species are not well mixed.  This has lead to unrealistic concentrations of chlorine and bromine simulations that use WACCM middle atmosphere chemistry.

The chemistry mechanisms that need to change are:
-  waccm_ma
-  waccm_ma_mam4
-  waccm_mad
-  waccm_mad_mam4

**Comment by lkemmons** [comment]
@fvitt 
The new mechanism files, with CL and BR removed from the 'non-transported' list are:
/glade/u/home/emmons/mechanisms/MZ279_MA_MAM4_20200925.in
/glade/u/home/emmons/mechanisms/MZ280_MAD_MAM4_20210122.in
/glade/u/home/emmons/mechanisms/MZ281_MAD_20210122.in
/glade/u/home/emmons/mechanisms/MZ282_MA_20210122.in

Doug Kinnison reported that these worked great.
