### ISSUE TITLE
error in mo_srf_emissions using ESMF library with leap year

### ISSUE THREAD

**Issue by mvertens** [ESCOMP/CAM#317]
When running the aux_cam testlist on cheyenne - the following test:
SMS_D_Ln9_Vnuopc.f09_f09_mg17.FCts2nudged.cheyenne_intel.cam-outfrq9s_leapday
Resulted in the following traceback in the cesm.log file
```
40:cesm.exe           000000000B757464  shr_abort_mod_mp_         114  shr_abort_mod.F90
40:cesm.exe           000000000B7572C2  shr_abort_mod_mp_          61  shr_abort_mod.F90
40:cesm.exe           0000000002A9EB37  time_manager_mp_c        1242  time_manager.F90
40:cesm.exe           0000000002A93AAD  time_manager_mp_s         271  time_manager.F90
40:cesm.exe           0000000002AEBCB9  tracer_data_mp_re        1200  tracer_data.F90
40:cesm.exe           0000000002AE121E  tracer_data_mp_ad         704  tracer_data.F90
40:cesm.exe           0000000006099E17  mo_srf_emissions_         309  mo_srf_emissions.F90
40:cesm.exe           000000000320C071  chemistry_mp_chem        1102  chemistry.F90
40:cesm.exe           000000000116DFD1  physpkg_mp_phys_t        2715  physpkg.F90
40:cesm.exe           0000000001139B93  physpkg_mp_phys_r        1036  physpkg.F90
40:cesm.exe           00000000007D8D8A  cam_comp_mp_cam_r         258  cam_comp.F90
40:cesm.exe           0000000000786E10  atm_comp_nuopc_mp         845  atm_comp_nuopc.F90
```

The atm log file contained the following output before the crash:
 ```
emiss_shipping
 READ_NEXT_TRCDATA emiss_bb
 READ_NEXT_TRCDATA emiss_res_tran
 set_time_float_from_date: error return from ESMF_TimeSet for set_time_float_from_date
 ERROR: CHKRC
```
And finally, the PET log file contained the following error message - which points to the source of the problem.
 PET0222 ESMCI_Calendar.C:1059 ESMCI::Calendar::convertToTime() Input argument out of range  - ; Gregorian: for Febru\ary 2010, dd=29 > 28 days in the month

It seems that the mct esmf_wrf_timemgr is not picking up these type of failures (the same issue arose in a CTSM test) and using the ESMF library for time management triggers the expected error.

**Comment by gold2718** [comment]
There is logic to set this correctly when `calendar==shr_cal_noleap`. What is `calendar` being set to in CAM when this problem occurs?
