### ISSUE TITLE
cannot build CAM/MPAS compset with ESMF/NUOPC

### ISSUE THREAD

**Issue by mvertens** [ESCOMP/CAM#318]
When I try to build the following test:

When I try to build the following test:
   ERC_D_Ln9_Vnuopc.mpasa120z32_mpasa120.FKESSLER.cheyenne_intel.cam-outfrq3s_usecase
I am getting the following build error from cam:

```
/glade/work/mvertens/cesm.nuopc_dev.jan20.camdev/components/cam/src/dynamics/mpas/dycore/src/framework/mpas_derived_types.F(35): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [ESMF_STUBS]
   use ESMF_Stubs
-------^
compilation aborted for /glade/work/mvertens/cesm.nuopc_dev.jan20.camdev/components/cam/src/dynamics/mpas/dycore/src/framework/mpas_derived_types.F (code 1)
ifort: remark #10397: optimization reports are generated in *.optrpt files in the output location
```

In looking further at the MPAS code in CAM, mpas_derive_types.F90 is using the following:
```
   use ESMF
   use ESMF_BaseMod
   use ESMF_Stubs
   use ESMF_CalendarMod
   use ESMF_ClockMod
   use ESMF_TimeMod
   use ESMF_TimeIntervalMod

```
Also - I am not sure you can directly use any of those other use statements for ESMF other than 'use ESMF'.

**Comment by MiCurry** [comment]
I believe this issue can be closed with the merge of #391.

**Comment by jtruesdal** [comment]
Miles is correct.  I upgraded a recent CESM tag to use cam6_0_23 and reran the test which passed.

PASS ERC_D_Ln9_Vnuopc.mpasa120z32_mpasa120.FKESSLER.cheyenne_intel.cam-outfrq3s_usecase CREATE_NEWCASE
PASS ERC_D_Ln9_Vnuopc.mpasa120z32_mpasa120.FKESSLER.cheyenne_intel.cam-outfrq3s_usecase XML
PASS ERC_D_Ln9_Vnuopc.mpasa120z32_mpasa120.FKESSLER.cheyenne_intel.cam-outfrq3s_usecase SETUP
PASS ERC_D_Ln9_Vnuopc.mpasa120z32_mpasa120.FKESSLER.cheyenne_intel.cam-outfrq3s_usecase SHAREDLIB_BUILD time=151
PASS ERC_D_Ln9_Vnuopc.mpasa120z32_mpasa120.FKESSLER.cheyenne_intel.cam-outfrq3s_usecase MODEL_BUILD time=153
PASS ERC_D_Ln9_Vnuopc.mpasa120z32_mpasa120.FKESSLER.cheyenne_intel.cam-outfrq3s_usecase SUBMIT
PASS ERC_D_Ln9_Vnuopc.mpasa120z32_mpasa120.FKESSLER.cheyenne_intel.cam-outfrq3s_usecase RUN time=219
PASS ERC_D_Ln9_Vnuopc.mpasa120z32_mpasa120.FKESSLER.cheyenne_intel.cam-outfrq3s_usecase COMPARE_base_rest
PASS ERC_D_Ln9_Vnuopc.mpasa120z32_mpasa120.FKESSLER.cheyenne_intel.cam-outfrq3s_usecase MEMLEAK insuffiencient data for memleak test
PASS ERC_D_Ln9_Vnuopc.mpasa120z32_mpasa120.FKESSLER.cheyenne_intel.cam-outfrq3s_usecase SHORT_TERM_ARCHIVER

**Comment by jtruesdal** [comment]
Thanks Miles.  Retested it, updated the PR to note that it closes that
issue and manually closed it with a comment.

jt
