### ISSUE TITLE
Remove duplicate compset definitons

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#319]
There appear to be a handful of duplicate compsets in the cime_config/config_compsets.xml file.  FKESSLER is an example.

**Comment by peverwhee** [comment]
The following duplicate compsets have 1 in the untested category and 1 in the tested category (the tested one was added more recently). Is it the right call to remove the untested compsets?
 - F1850_BDRD
 - FFSPCAMS
 - FHIST_BDRD

Also, the QPHISTC6 and QPC6HIST aliases correspond to the same compset and I'm not sure which one (if either) should be removed. QPC6HIST was added more recently and there is a similarly-formatted QPC5HIST alias.

**Comment by cacraigucar** [comment]
@peverwhee You can verify whether compsets are tested or not by looking in the cime_config/testefs/testlist_cam.xml file and seeing if they have an "aux_cam", "prealpha" or "prebeta" test for it.

As for the names QPHISTC6 vs QPC6HIST, I did a "git blame" and these were added by @fischer-ncar.  He should be able to tell us definitively which it should be.  I believe that the duplicate compsets and these two names came from a "git merge" that went haywire when he brought in the testing tag.

**Comment by gold2718** [comment]
Since there is a `QPC5HIST` compset, I vote to keep `QPC6HIST` and dump `QPHISTC6`.
Also not following that ordering is `FHIST_DARTC6` which maybe should be `FHISTC6_DART` or even drop the `C6` entirely because there is only one and this compset will likely want to always be run with the latest version of CAM.

**Comment by cacraigucar** [comment]
@peverwhee and @gold2718 Whatever changes are adopted for the names in config_compsets.xml, they will also need to match what is used in testlist_cam.xml.  Interestingly, QPHISTC6 and QPC6HIST both have aux_cam tests, so maybe it wasn't a bad merge.  I agree that QPC6HIST most likely should be the name, but I'd like to hear confirmation from @fischer-ncar that he wasn't intending to have these tests be different for some reason (even though they are not)

**Comment by fischer-ncar** [comment]
QPHISTC6 and QPC6HIST should be identical, and are.  You can replace the QPHISTC6 with QPC6HIST in testlist_cam.xml.

**Comment by peverwhee** [comment]
ok - i will remove QPHISTC6 from config_compsets and replace accordingly in testlist_cam.
