### ISSUE TITLE
convective wet scavening namelist changes

### ISSUE THREAD

**Issue by tilmes** [ESCOMP/CAM#322]
Namelist changes are requested to add the namelist changes currently in CAMchem also to WACCM and CAM.

# Aerosol convective processes
if ($chem =~ /trop_strat/) {
    add_default($nl, 'convproc_do_aer', 'val'=>'.true.');
    add_default($nl, 'convproc_do_evaprain_atonce', 'val'=>'.true.');
    add_default($nl, 'convproc_pom_spechygro', 'val'=>'0.2D0');
    add_default($nl, 'convproc_wup_max', 'val'=>'4.0D0');

These changes are physical improvements of the convective wet removal process (implemented by Dick Easter) and result in much improved representation of aerosols compared to observations especially in seasalt and black carbon. 
They remove aerosols from the free troposphere and therefore have significant impacts on SW and LW cloud forcing.

https://webext.cgd.ucar.edu/F2000climo/f.e21.F2000climo.f09_f09_mg17.cam6_2_022_convproc.001/atm/f.e21.F2000climo.f09_f09_mg17.cam6_2_022_convproc.001_yrs1-5-f.e21.F2000climo.f09_f09_mg17.cam6_2_022.001_yrs1-5/

[CESM_convective_wet_removal.pdf](https://github.com/ESCOMP/CAM/files/5895199/CESM_convective_wet_removal.pdf)

**Comment by fvitt** [comment]
The plan is to update PR #315 to include these changes to the default convproc namelist setting for all cam6 phys configurations.
