### ISSUE TITLE
Change master branch name

### ISSUE THREAD

**Issue by gold2718** [ESCOMP/CAM#326]
In keeping with the announcement from Anke Kamrath, we should rename the CAM `master` branch.
While both Anke and GitHub have suggested `main` as an alternative, that name also does not reflect the role of the default branch in CAM.

I suggest that we rename the default branch as either `default` or `announce` since it is used for some general announcements about the CAM git repository.

Although this change will not affect most users, we should include instructions for removing the `master` branch in users clones as part of the resolution of this issue (maybe just `git branch -d master` once a different branch or tag is checked out).

**Comment by nusbaume** [comment]
My vote is for `announce`, as it makes it clear that the branch doesn't actually have any model code, but that it does contain info (e.g. the README file) that users should pay attention to.

**Comment by swrneale** [comment]
Just in my amateur read up it seems a lot of git-ers are using main or primary. Or maybe something like 'front'?

**Comment by cacraigucar** [comment]
@swrneale Our repository is different than most other ones.  The default branch that you get when you checkout the repository (current master  and what we are renaming) contains only a README and the CODE_OF_CONDUCT.  Most other git repositories will get their actual code with this branch.  In their cases, the name main or primary makes sense.  We purposefully opted to not have any code in this branch as we want the user to make a selection on whether they want a release branch or the development branch.  We could still use one of those names, but Steve is proposing a more descriptive name of the purpose of our default branch.

I'm still pondering the name so am not registering a vote yet.

**Comment by nusbaume** [comment]
`master` branch has been renamed to `main`.  This name was chosen because it matches the standard Github default branch name, and is being used in other CAM-related repos.
