### ISSUE TITLE
PUMAS (Microphysics) Bug Fixes

### ISSUE THREAD

**Issue by andrewgettelman** [ESCOMP/CAM#329]
We have a series of bug fixes coming in for PUMAS. I think Kate will be bringing these in.

These include two existing issues: #257 and #309 

As well as a bug identified in the PUMAS repository: ESCOMP/PUMAS#20

These are in addition to the two PR's already submitted for GPU optmization work.

**Comment by Katetc** [comment]
The top two bug fixes have been rolled into the optimization PR (pr #324 ), the PUMAS bug referenced above (nimax changes) will be addressed in a later science update PR. We will add a new issue for that one when we get closer.
