### ISSUE TITLE
Remove reprosum namelist settings from FSD test

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#334]
During regression testing for cesm2_3_alpha02b, it was discovered that the FSD test was not handling the reprosum namelist settings correctly.  These settings will be removed for the FSD tests.

**Comment by fvitt** [comment]
Is this only in the prealpha test?  Are we leaving the aux_cam test as it is?

**Comment by cacraigucar** [comment]
This will only be for the prealpha test.  The aux_cam test is using outfrq9s which does not have the reprosum namelist variables.
