### ISSUE TITLE
SE dycore not reading default ncdata for ne30np4 F2000

### ISSUE THREAD

**Issue by adamrher** [ESCOMP/CAM#339]
Running the ne30_ne30_mg17 grid with a F2000climo compset errors out:

` ERROR: check_file_layout: ERROR: either ncol or ncol_d dimension not found in ncdata file`

This same default ncdata is used for ne30pg2, ne30pg3 & ne30np4. This file has a dimension size ncol_d = 48602:
/glade/p/cesmdata/cseg/inputdata/atm/cam/inic/se/F2000climo_ne30pg3_mg17_01-01-00000_c200424.nc

This file works fine for ne30pg2 and ne30pg3, as ncol_d = 48602 is consistent with their definition of ncol_d. ne30np4 seems to not want ncol_d, but rather ncol = 48602, which is not present in this file.

ne30np4 runs fine if I instead point to this CAM-Chem inic, which has dimensions ncol = 48602:
/glade/p/cesmdata/cseg/inputdata/atm/cam/inic/se/f.e22.FC2010climo.ne30_ne30_mg17.cam6_2_022.001.cam.i.0016-01-01-00000_c200610.nc

@PeterHjortLauritzen

**Comment by adamrher** [comment]
Peter says

> rename ncol_d to ncol and it works (agreed it needs to be fixed)

So I copied the problematic ncdata file into my local directory and ncrename -d ncol_d,ncol. Then ran a test that now gives:

`INFLD_REAL_1D_2D: read field PHIS`
`CAM_PIO_CHECK_VAR INFO: variable lat is not on file`
 `ERROR: READ_DYN_FIELD_2D: Could not find lat field on input datafile`

I don't know why feeding in a dimensioned ncol ncdata file is now triggering an error looking for a lat dimension.

**Comment by adamrher** [comment]
> I see two ways to resolve this:

>Create the ne30np4 dataset
Move the test to be ne30np4.pg3

I'd advocate for the first since it the second would sort of ``hide" that this is a problem still. The preferable solution is to fix the np4 code so it can read in pgXnp4 ncdata files. 

If you go with a new ne30np4 dataset, the one I linked at the top of this thread should work (unless the test is for a different ne base resolution np4 grid).

**Comment by gold2718** [comment]
> ... since the preferable solution is to fix the np4 code so it can read in pgXnp4 ncdata files.

Can you explain what it means to "fix the np4 code" to be able to read an _incompatible_ grid? The pg3 grid (and thus data on it) is not compatible. Are you suggesting adding a new feature to read in the pg3 (or pgx) data and use the internal SE mechanisms to transform the data to the GLL grid? That would be a new feature, not a bug fix.

**Comment by adamrher** [comment]
The pgX code reads in the ncdata on the GLL grid. My understanding is that this was a design choice to reduce the number of ncdata files needed in the repo (sounds good in theory!).

**Comment by gold2718** [comment]
> The pgX code reads in the ncdata on the GLL grid. My understanding is that this was a design choice to reduce the number of ncdata files needed in the repo (sounds good in theory!).

It sounds like whoever set up the ncdata files did not get that message since there is a pg3 file but no GLL file.

More importantly, what is the best SE grid for testing F2000climo?

**Comment by adamrher** [comment]
> More importantly, what is the best SE grid for testing F2000climo?

ne30pg3

At issue in this thread is that it seems ne30np4 doesn't recognize the dimension ```ncol_d``` (= GLL grid = 48602 for all ne30xx variants), and instead is looking for ```ncol=48602```. But ```ncol``` now refers to the pgX grid ever since this physgrid work commenced. So ne30np4 should be modified to look for ```ncol_d```, and we should verify that all ncdata files have an ```ncol_d```.

**Comment by gold2718** [comment]
> At issue in this thread is that it seems ne30np4 doesn't recognize the dimension `ncol_d` (= GLL grid = 48602 for all ne30xx variants)

Ahh, I get it now (and see this in the original posting). This used to work so it got broken somewhere in the reworking of the SE dycore over the last year or two.

**Comment by PeterHjortLauritzen** [comment]
A little more info if it is useful:

By design we wanted SE and SE-CSLAM (ne30np4 and ne30pg3, respectively, for 1 degree) to be able to use the same initial condition file. When we write an initial condition file from an SE-CSLAM run then latitude is "lat_d", longitude "lon_d", area is "area_d" and the dimension is "ncol_d". For an SE run the variables are without "_d".

So taking an initial condition file from an SE-CSLAM run and wanting to use it for an SE run (which is what some users want to do) we get the error

 INFLD_REAL_1D_2D: read field PHIS
 ERROR: 
 check_file_layout: ERROR: either ncol or ncol_d dimension not found in ncdata f
 ile

If we rename lat_d to lat, lon_d to lon, area_d to area and ncol_d to ncol in the initial condition file then it works.

So a possible solution could be to change the dimension names when we write the initial condition file ...

**Comment by jedwards4b** [comment]
It should be an easy change in the code to look first for dimension ncol_d and then for ncol.  ditto the other variables.

**Comment by gold2718** [comment]
> It should be an easy change in the code to look first for dimension ncol_d and then for ncol. ditto the other variables.

We also have to check the grid size to make sure we know what sort of data we are reading in.
