### ISSUE TITLE
Changes needed to finish 2deg DECK

### ISSUE THREAD

**Issue by fvitt** [ESCOMP/CAM#34]
Mike Mills has described the desired changes in:
https://docs.google.com/document/d/1TXfpAkVAR3hyHZpprc2LFZMg-RAk7RWVkHa5CHnSLis/edit

**Comment by nusbaume** [comment]
@fvitt Does this issue need to remain open?  It looks like a pull request for it has been merged (and the branch associated with it is now frozen), but I wanted to check with you first  before closing it.

**Comment by fvitt** [comment]
Please close
