### ISSUE TITLE
After updating to cism2_1_76 or later, change compsets involving CISM

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CAM#340]
cism2_1_76 changes the compset naming convention in preparation for supporting Antarctica. For now, it is backwards compatible with the old compset names, but we'd like to remove that backwards compatibility within the next couple of months.

So, after updating to cism2_1_76, compsets including CISM should be changed from `CISM2%NOEVOLVE` to `CISM2%GRIS-NOEVOLVE` (and similar for EVOLVE, but CAM currently doesn't define any CISM EVOLVE compsets).

**Note that, if https://github.com/ESCOMP/CAM/issues/204 is done first and results in no remaining CAM-defined compsets using CISM, then this issue can be closed with nothing to do.**

@Katetc

**Comment by fvitt** [comment]
As noted by @billsacks ,  MAM5 compsets need to to use _SGLC.
