### ISSUE TITLE
IRT_N3_PM3_Ld7_Vnuopc.f19_g17.BHIST does not build for cesm2_3_alpha02d

### ISSUE THREAD

**Issue by mvertens** [ESCOMP/CAM#356]
The following test will not build due to decomposition issues:

ERROR: Command /glade/work/mvertens/cesm.nuopc_dev.apr11.prealpha/components/cam/bld/build-namelist -ntasks 1296 -csmdata /glade/p/cesmdata/cseg/inputdata -infile /glade/scratch/mvertens/IRT_N3_PM3_Ld7_Vnuopc.f19_g17.BHIST.cheyenne_intel.allactive-defaultio.prealpha/Buildconf/camconf/namelist -start_ymd 18500101 -ignore_ic_year -use_case hist_cam6 -inputdata /glade/scratch/mvertens/IRT_N3_PM3_Ld7_Vnuopc.f19_g17.BHIST.cheyenne_intel.allactive-defaultio.prealpha/Buildconf/cam.input_data_list -namelist " &atmexp  co2_cycle_rad_passive=.true. /"  failed rc=255
out=
err=Smartmatch is experimental at /glade/work/mvertens/cesm.nuopc_dev.apr11.prealpha/components/cam/bld/perl5lib/Build/ChemNamelist.pm line 274.
CAM build-namelist - ERROR: fv_decomp_set failed to find a decomposition.
  npr_yz needs to be set by the user. at /glade/work/mvertens/cesm.nuopc_dev.apr11.prealpha/components/cam/bld/build-namelist line 4158.

**Comment by mvertens** [comment]
@gold2718 - is this still an issue?

**Comment by fischer-ncar** [comment]
I was able to get this test to pass by changing it to IRT_C3_Ld7_Vnuopc.f19_g17.BHIST.

**Comment by gold2718** [comment]
This seems like a better option anyway, can we just use that and close this issue?

**Comment by fischer-ncar** [comment]
I have no problem with changing the test.  I believe that PM3 was originally added to avoid the npr_yz error.

**Comment by gold2718** [comment]
Did you try `IRT_C3_PM3_Ld7_Vnuopc.f19_g17.BHIST`?

**Comment by fischer-ncar** [comment]
I might have tried it, but don't remember.  I'll give it a try now.
I still get the decomp error with IRT_C3_PM3.

**Comment by jedwards4b** [comment]
When you change from N3 to C3 it changes the decomposition of the individual members of the ensemble.  I think that the PM3 was a modification needed for the N3 case to decompose properly that won't be required for C3.

**Comment by gold2718** [comment]
Thanks @jedwards4b (I should have thought of that).
Given that, I'm fine with switching to `IRT_C3_Ld7_Vnuopc.f19_g17.BHIST` and closing this issue. @mvertens?

**Comment by cacraigucar** [comment]
Closing based on previous comments
