### ISSUE TITLE
error in MPAN+M reaction

### ISSUE THREAD

**Issue by lkemmons** [ESCOMP/CAM#364]
An error in the "user reaction" for MPAN+M (in ./chemistry/mozart/mo_usrrxt.F90) was introduced in CESM.2.2.0.  This affects all CAM-chem and WACCM simulations using TS1 or TSMLT1 chemical mechanisms. 
To correct this either mo_usrrxt.F90 must be updated, with a check for the reaction index for either "tag_MCO3_NO2" or "usr_MCO3_NO2" reactions, prior to the calculation of the "usr_MPAN_M" reaction. 
IMPACT: primarily at the surface in high isoprene-emitting regions, Monthly average surface ozone differences are up to ~3 ppb.
[MPAN_bugfix_CESM2.2.0.pdf](https://github.com/ESCOMP/CAM/files/6326543/MPAN_bugfix_CESM2.2.0.pdf)

**Comment by lkemmons** [comment]
Adding to above - the other option for users is to update the MCO3+NO2 reaction (and then do not need to change mo_usrrxt) from:
[usr_MCO3_NO2] MCO3 + NO2 + M  -> MPAN + M
to:
[tag_MCO3_NO2] MCO3 + NO2 + M  -> MPAN + M. ; 9.7e-29, 5.6, 9.3e-12, 1.5, 0.6

**Comment by fvitt** [comment]
@lkemmons,
Your fix to mo_usrrxt is here:
 /glade/u/home/emmons/src_cesm/mpan_corr/mo_usrrxt.F90

Is the the fix you are recommending rather than a change to chemical mechanisms?
Does this fix need to go into cems2.1 and cesm2.2 releases as well as cam_development?

**Comment by lkemmons** [comment]
I recommend the fix to mo_usrrxt so that all past mechanisms will work.
Future mechanisms will use the new MCO3+NO2 reaction (which is now in TS2 chemical mechanisms).
This fix should go in CESM2.2.0 and later - it is not needed in CESM2.1. It was only introduced when the capability for TS2 chemistry was added.

**Comment by cacraigucar** [comment]
@fvitt and @lkemmons - Has this been fixed?

**Comment by lkemmons** [comment]
Yes.
