### ISSUE TITLE
Grid matches in refcases will need to change from gland4 to gris4 if they are re-enabled

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CAM#371]
CAM has a bunch of currently-disabled refcases:

https://github.com/ESCOMP/CAM/blob/e0810cd1240fc9a165b15152554cd87390299282/cime_config/config_compsets.xml#L600-L641

If they are re-enabled, the grid match will need to change from gland4 to gris4, since that is the new name for the Greenland grid, once https://github.com/ESMCI/cime/pull/3943 comes in (tentatively scheduled for cesm2_3_alpha04b).

**Comment by cacraigucar** [comment]
These commented out lines should be removed
