### ISSUE TITLE
gas phase reaction rate in pp_trop_mam3 and mam4 is out of date

### ISSUE THREAD

**Issue by AndrewJConley** [ESCOMP/CAM#372]
The rate constant for the reaction:
H2O2 + OH -> H2O + HO2                                           
in the pp_trop_mam3 and 4 "prescribed oxidant" chemistry system is out of date.

In the current code base it is 2.9e-12* exp( -160 / T)
It should be 1.8e-12, according to a more recent JPL database search.

Someone (other than me) should identify the correct value, do some runs to see how much it affects results, and then we should update the code.

**Comment by fvitt** [comment]
It appears that these mechanisms need to be updated :

```
src/chemistry/pp_trop_mam3/chem_mech.in:               H2O2 + OH -> H2O + HO2                                           ; 2.9e-12, -160
src/chemistry/pp_trop_mam4/chem_mech.in:               H2O2 + OH -> H2O + HO2                                           ; 2.9e-12, -160
src/chemistry/pp_trop_mam7/chem_mech.in:               H2O2 + OH -> H2O + HO2                             ; 2.9e-12, -160
src/chemistry/pp_trop_mozart/chem_mech.in:          H2O2 + OH -> H2O + HO2                                         ; 2.9e-12, -160
src/chemistry/pp_waccm_sc_mam4/chem_mech.in:                  H2O2 + OH -> H2O + HO2                                           ; 2.9e-12, -160
```

Someone needs to provided updated mechanism files produced by the chemistry Cafe'.  ( @lkemmons @AndrewJConley )

**Comment by lkemmons** [comment]
None of the mechanisms that Francis has listed are currently in the cafe, except for trop_mam4 mechanism which I just created ("CAM_MAM4" in the cafe).   They are too simple to have needed the cafe, except for trop_mozart, which is only kept for historical purposes and has never been updated since publication of MOZART-4.  We need to check the impact of this update before incorporating it in current compsets.

**Comment by lkemmons** [comment]
Note again, we should not update the 'pp_trop_mozart' with this H2O2 rate -- there are many out-of-date reaction rates in that mechanism and it will just cause confusion if we update a single rate.

**Comment by fvitt** [comment]
> I did a short F2000 run with the new and old rate constants for H2O2+OH:
> https://acomstaff.acom.ucar.edu/emmons/cesm/f.e22.F2000climo.f09.cesm220.newrate.0002_2-f.e22.F2000climo.f09.cesm220.orig.0002_2/
> There are some (small) differences, so we should be clear when we update the rate for CAM compsets.

@lkemmons, Can you point me to the test case directory?  Are the results of the control and test cases archived somewhere (maybe in campaign store)?  I am gathering information for the change log.

**Comment by lkemmons** [comment]
Cases are:
reference: /glade/u/home/emmons/cesm22_cases/f.e22.F2000climo.f09.cesm220.orig
test: /glade/u/home/emmons/cesm22_cases/f.e22.F2000climo.f09.cesm220.newrate
Output archived in: /glade/campaign/acom/acom-weather/emmons/newrate_H2O2_OH
