### ISSUE TITLE
snapshot has output names with an extra pbuf_ in them

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#373]
Names in cam_snapshot files for pbuf fields have pbuf_pbuf_xxx for the names.  The extra pbuf_ needs to be removed.

**Comment by nusbaume** [comment]
This issue was fixed by PR #374, but since it was referenced and then merged via another PR the script didn't catch it (which is a missing feature in the script itself).  Thus this issue will be closed manually.
