### ISSUE TITLE
Pass surface ozone concentrations to the coupler

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CAM#381]
CTSM would like to be able to receive surface ozone concentrations from the atmosphere. There were some discussions involving @danicalombardozzi @mvertens and @fvitt in late 2016, and a plan was developed at the time, but CESM2 release priorities interfered and this never happened. We would like to restart these discussions.

My impression / recollection is that, when running with CAM-Chem, surface ozone concentrations are readily available. Things get trickier when running CAM without Chem; a note from a few years ago suggested that CAM may still have surface ozone concentrations in that case, but that they may just be monthly averages. I'm not sure what the best approach will be, but we'd like to have some discussions about this.

@danicalombardozzi and I would like to talk with the relevant people to (re)chart a path forward on this: @mvertens @fvitt and anyone else who should be included.

**Comment by fvitt** [comment]
When we run CAM without chemistry, ozone is prescribed for radiation transfer calculations.  The prescribed ozone is typically monthly averaged and are time interpolated.  It seems that we should be able to provide ozone concentrations in the bottom most layer whether the concentrations are prognosed by chemistry or prescribed.

**Comment by AndrewJConley** [comment]
I agree as well.  This is not the only surface flux that needs to be
calculated by, or passed to, the surface models.  With the transition to
NUOPC, it will be good to reevaluate where and how we do surface flux
computations.

**Comment by AndrewJConley** [comment]
Thanks for including me.  I expect Francis can cover the technical aspects
of the specific question of Ozone deposition to land for both prescribed
and prognostic chemistries.  I look forward to the discussion for
informational purposes as we design the next phase of our deposition work
for other chemicals and aerosols.

**Comment by gold2718** [comment]
Should have been closed by #404
