### ISSUE TITLE
Modify Launch Parcel Definition for ZM Deep Convection (option)

### ISSUE THREAD

**Issue by swrneale** [ESCOMP/CAM#383]
This will hopefully be a namelist variable to enable the Zhang McFarlane launch parcel properties to be defined over a vertical length scale rather than the existing formulation, where the level of maximum of moist static energy is used. The launch level will then be the next vertical level above this parcel mixing length scale. The length scale is currently 0.5*PBL height, but that could change. The modification is needed to reduced the large level sensitivities when using the planned L48+BL10 vertical grid for CAM7.

**Comment by swrneale** [comment]
@cacraigucar is it ok to assign you as I will be making pull request this week or next? It should be pretty straightforward?

**Comment by cacraigucar** [comment]
@swrneale - That is fine to assign me.  I can give you a hand opening the PR if you have difficulties.
