### ISSUE TITLE
CAM additions required to accomodate MPAS dycore using a height based vertical coordinate

### ISSUE THREAD

**Issue by jtruesdal** [ESCOMP/CAM#388]
New functionality and infrastructure will be needed to accommodate a dynamical core using a different vertical coordinate (and hence different total energy formulas).
 
- Total energy diagnostics for MPAS
- Energy consistent physics-dynamics coupling
- Introduce more thermodynamic arrays to identify liquid and ice forms of water (implemented in SE and MPAS; FV3 can be done with FV3 PR)
- Move total energy computations to physconst.F90 and generalize
- WACCM-x code in MPAS dp_coupling layer (not tested)
- make dry air mass namelist (all dycores)
- analysis initial condition for 1 degree F2000 MPAS

**Comment by gold2718** [comment]
This should have been closed when #403 was merged.
