### ISSUE TITLE
MPAS regression test failure for cam6_3_020

### ISSUE THREAD

**Issue by jtruesdal** [ESCOMP/CAM#389]
**FAIL ERC_D_Ln9.mpasa120z32_mpasa120.FKESSLER.cheyenne_intel.cam-outfrq3s_usecase COMPARE_base_rest**

CAM6_3_020 inadvertently included a regression test failure.   The comparison of the initial files produced from the base and restart run showed differences in some of the grid description fields. All other history files were BFB.
According to the cprnc.out file, 4 fields are different: edgesOnCell, edgesOnEdge, cellsOnCell, verticesOnCell.
The restart and initial files are only opened in CAM and the resulting filehandles are passed to the MPAS dycore to complete the writing of restart information.

**Comment by jtruesdal** [comment]
@cacraigucar This problem behind the MPAS regression fail is described in MPAS PR [#143](https://github.com/MPAS-Dev/MPAS-Model/pull/143). @mgduda will provide a fix for our CAM-MPAS development effort.

**Comment by mgduda** [comment]
Updating the [MPAS-A dycore external](https://github.com/ESCOMP/CAM/blob/cam_development/Externals_CAM.cfg#L57-L63) to `8fb89189` should fix the exact restart failure, though the baseline results will change. Here are the results I get after updating the MPAS-A dycore external in a local sandbox:
```
michael01: 1 test
  ERC_D_Ln9.mpasa120z32_mpasa120.FKESSLER.cheyenne_intel.cam-outfrq3s_usecase (Overall: DIFF) details:
    PASS ERC_D_Ln9.mpasa120z32_mpasa120.FKESSLER.cheyenne_intel.cam-outfrq3s_usecase CREATE_NEWCASE
    PASS ERC_D_Ln9.mpasa120z32_mpasa120.FKESSLER.cheyenne_intel.cam-outfrq3s_usecase XML
    PASS ERC_D_Ln9.mpasa120z32_mpasa120.FKESSLER.cheyenne_intel.cam-outfrq3s_usecase SETUP
    PASS ERC_D_Ln9.mpasa120z32_mpasa120.FKESSLER.cheyenne_intel.cam-outfrq3s_usecase SHAREDLIB_BUILD time=85
    PASS ERC_D_Ln9.mpasa120z32_mpasa120.FKESSLER.cheyenne_intel.cam-outfrq3s_usecase NLCOMP
    PASS ERC_D_Ln9.mpasa120z32_mpasa120.FKESSLER.cheyenne_intel.cam-outfrq3s_usecase MODEL_BUILD time=118
    PASS ERC_D_Ln9.mpasa120z32_mpasa120.FKESSLER.cheyenne_intel.cam-outfrq3s_usecase SUBMIT
    PASS ERC_D_Ln9.mpasa120z32_mpasa120.FKESSLER.cheyenne_intel.cam-outfrq3s_usecase RUN time=227
    PASS ERC_D_Ln9.mpasa120z32_mpasa120.FKESSLER.cheyenne_intel.cam-outfrq3s_usecase COMPARE_base_rest
    FAIL ERC_D_Ln9.mpasa120z32_mpasa120.FKESSLER.cheyenne_intel.cam-outfrq3s_usecase BASELINE /glade/p/cesm/amwg/cesm_baselines/cam6_3_020: DIFF
    PASS ERC_D_Ln9.mpasa120z32_mpasa120.FKESSLER.cheyenne_intel.cam-outfrq3s_usecase TPUTCOMP
    PASS ERC_D_Ln9.mpasa120z32_mpasa120.FKESSLER.cheyenne_intel.cam-outfrq3s_usecase MEMLEAK insuffiencient data for memleak test
    PASS ERC_D_Ln9.mpasa120z32_mpasa120.FKESSLER.cheyenne_intel.cam-outfrq3s_usecase SHORT_TERM_ARCHIVER
```

**Comment by cacraigucar** [comment]
@jtruesdal - Should we ask @fvitt to include this change in his upcoming PR #380?
