### ISSUE TITLE
CAM/MPAS cannot run when nsteps=1 with CESM/NUOPC

### ISSUE THREAD

**Issue by MiCurry** [ESCOMP/CAM#396]
I'm not sure if this is the right place for this error. This behavior does not occur when running the F2000climo case within CAM.

We would like to run with a small number of timesteps when running/debugging issues with the 15-3 km 6.5 million columns mesh as running longer simulations will significantly waste core hours.

**Body**
When running CAM/MPAS with CESM/NUOPC and setting the run duration less a day (i.e. `STOP_OPTION=nsteps` and `STOP_N=1`, ESMF_LogFiles return: 

```
20210701 112907.855 ERROR            PET097 src/addon/NUOPC/src/NUOPC_Base.F90:936 Invalid argument  - setClock timeStep=86400s is not a divisor of runDuration=1800s
```

Changing `NCPL_BASE_PERIOD` from `day` to `hour` circumvents this problem:

`./xmlchange NCPL_BASE_PERIOD=day`

However, dyn_comp::dyn_init then complains that the ratio of the CAM timestep (75s) to the MPAS dynamics timestep (900s) is not correct (although the CAM time step was not explicitly changed). 

Changing ATM_NCPL to be something more desirable (i.e. 2, which would make the CAM timestamp 1800, twice that of the dynamics timestep), gives an error when submitting:

`CIME.utils.CIMEError: ERROR: Active atm should match shortest model timestep atmdt=1800 mindt=450`

With `ATM_NCPL=48`, changing the dynamics timestep (`mpas_dt`), to also be 75, returns to the first error listed (`timeStep not a divisor of runDuration`).

**Steps to reproduce:**
```
git clone https://github.com/ESCOMP/CESM.git CESM-ESCOMP-cam-mpas
cd CESM-ESCOMP-cam-mpas                                                                                      
git checkout cesm2_3_beta03
```

update Externals.cfg with the following
``` 
[cam]
tag = cam6_3_023

[cime]
tag = mpas_dev/cime5.8.47
repo_url = https://github.com/jtruesdal/cime

[clm]
tag = mpas_dev/ctsm5.1.dev038
repo_url = https://github.com/jtruesdal/CTSM
```
Checkout externals:
`./manage_externals/checkout_externals`

Change the following tolerances (to `1.e-02_r8`) in `components/cam/src/cpl/nuopc/atm_comp_nuopc.F90` on lines 695 and 700:

``` Fortran
695: if (abs(lonMesh(n) - lon(n)) > 1.e-02_r8 .and. abs(lonMesh(n) - lon(n)) /= 360._r8) then
...
700: if (abs(latMesh(n) - lat(n)) > 1.e-02_r8) then
```

Create newcase and cd into directory
```
./cime/scripts/create_newcase --compset F2000climo --res mpasa120_mpasa120 --case /glade/scratch/mcurry/nuopc-timestep --run-unsupported --pecount 72x1 --driver nuopc
cd /glade/scratch/mcurry/nuopc-timestep
```

```
./xmlchange --append CAM_CONFIG_OPTS='-nlev 32'
./xmlchange STOP_OPTION=nsteps,STOP_N=1
./xmlchange JOB_WALLCLOCK_TIME=01:00:00
./case.setup
```

Add the following to user_nl_cam:
```
ncdata = '/glade/p/cesmdata/inputdata/atm/cam/inic/mpas/mpasa120.CFSR.L32.nc'
```

Then build and run:
```
qmcd -- ./case.build
./case.submit
```

**Comment by gold2718** [comment]
Your short run issue may be because for `F` cases, you need to make sure the runoff and ice sheet code get to run. To do this, make the following changes right after `./create_newcase`.
```
./xmlchange ROF_NCPL=\$ATM_NCPL
./xmlchange GLC_NCPL=\$ATM_NCPL
```

**Comment by MiCurry** [comment]
@gold2718 I'll give that a try! Thanks!
