### ISSUE TITLE
Bug fix needed for interactive fire compsets and capability

### ISSUE THREAD

**Issue by tilmes** [ESCOMP/CAM#405]
The interactive fire compsets (e.g., FCfireHIST) has a bug in the namelist. It needs to include fire emissions to num_a1 and num_a4. However, in order to do this, one needs to be able to set num_a4 twice:
fire_emis_specifier = 'bc_a4 = BC','num_a4 = 5.602969e+18*BC', 'pom_a4 = 1.4*OC', 'num_a4 = 1.33350672e+19*OC', 'SO2 = 0.975*SO2', 'so4_a1 = 0.025*SO2', 'num_a1 = 1.33350672e+19*SO2', 'DMS = DMS', 'SOAG = 0.45*BIGALK + 0.35*BIGENE + 1.725*TOLUENE + 1.4625*BENZENE + 1.9875*XYLENE + 0.34*ISOP + 4.25*C10H16'

However, doing this results in an error:
" ERROR: ADDFLD:  FireSF_num_a4 already on list"
41:cesm.exe           00000000005223FB  cam_history_mp_ad        5170  cam_history.F90
41:cesm.exe           0000000001255AE5  fire_emissions_mp         154  fire_emissions.F90

**Comment by fvitt** [comment]
One option for a workaround might be to combine the num parts in a single strings, like this: 

```
fire_emis_specifier =
 'bc_a4 = BC',
 'pom_a4 = 1.4*OC',
 'num_a4 = 5.602969e+18*BC + 1.33350672e+19*OC',
 'SO2 = 0.975*SO2',
 'so4_a1 = 0.025*SO2',
 'num_a1 = 1.33350672e+19*SO2',
 'DMS = DMS',
...
```

However, the namelist parser gets confused with the large coefficients expressed using the exponential notation including the "+" sign.   As an alternative, should we consider calculating the num portion of the aerosol modes inline rather than trying to explicitly expressing these in the namelist, only have the individual species specified in the namelist?

@tilmes, @lkemmons : Thoughts?

**Comment by fvitt** [comment]
Expressing the large coefficients without the "+" in the literal constants solves the issue with the parser.  
For example:
```
fire_emis_specifier =
 'bc_a4 = BC',
 'pom_a4 = 1.4*OC',
 'num_a4 = 5.602969e18*BC + 1.33350672e19*OC',
 'SO2 = 0.975*SO2',
 'so4_a1 = 0.025*SO2',
 'num_a1 = 1.33350672e19*SO2',
 'DMS = DMS',
...
```

However, both the driver share code and the CTSM fire emissions code assumes each fire emissions chemical compound is included in only one chemical species of the CAM-Chem mechanism.   So a bit of code refactoring will be required (in CTSM and driver share).  Units should be corrected in the CAM fire emissions diagnostics for the emissions of number densities (/m2/sec).

**Comment by lkemmons** [comment]
To avoid re-writing code, I have created a new emissions factor file that includes the number emissions:
fire_emis_factors_file = '/glade/work/emmons/fire_inputs/fire_emission_factors_78PFTs_c20210803.nc'
With this, one can use:
 fire_emis_specifier = 'bc_a4 = bc_a4', 'pom_a4 = pom_a4', 'num_a4 = num_a4_bc + num_a4_pom',
      'SO2 = SO2', 'NO = NO', 'CO = CO', ...
