### ISSUE TITLE
CIME assumes CAM component naming convention has a number modifier

### ISSUE THREAD

**Issue by adamrher** [ESCOMP/CAM#410]
CIME assumes the CAM component version names are an uppercase "CAM" followed by a number. E.g., the current versions are CAM30, CAM40, CAM50, CAM60.

@cacraigucar and I came across this issue when we attempted to introduce a new version CAMDEV, which when invoked gives an error near line 615 in cime/scripts/lib/CIME/case/case.py

```
Compset longname is 2000_CAMDEV_CLM50%SP_CICE%PRES_DOCN%DOM_MOSART_CISM2%NOEVOLVE_SWAV
Compset specification file is /home/aherring/src/cam6_3_020.tphysac/cime_config/config_compsets.xml
ERROR: Unknown model type, CAMDEV
```

@fischer-ncar looked into this and sent Cheryl and I an email:

> After doing some quick digging,  it looks like a "feature of cime."  cime is assuming the cam component will always be cam3,cam4,cam5,cam6.  Basically cam followed by a number.  cime is stripping the number to see if it's a valid model.  When it reaches camdev, it's checking to see if camdev == cam, and it fails.  This hack works for now, but I'll come up with something better on Monday.  This hack will never pass a cime code review.
```
diff --git a/scripts/lib/CIME/case/case.py b/scripts/lib/CIME/case/case.py
index d228b2003..66605b34e 100644
--- a/scripts/lib/CIME/case/case.py
+++ b/scripts/lib/CIME/case/case.py
@@ -607,6 +607,9 @@ class Case(object):
             match = Case.__mod_match_re__.match(model.lower())
             expect(match is not None, "No model match for {}".format(model))
             mod_match = match.group(1)
+            if mod_match == 'camdev':
+                logger.info("CAMDEV TRUE")
+                mod_match = "cam"
             # Check for noncomponent appends (BGC & TEST)
             if mod_match in ('bgc', 'test'):
                 noncomps.append(model)
```

I instead just changed the name from CAMDEV to CAM64 to satisfy cime. But in the future we may want to relax this assumption in cime.

**Comment by gold2718** [comment]
I think that what CIME assumes is that `CAM` _may_ be followed by digits, not that it _must_ be followed by digits.
Thus, we could specify the development options in the long name without a numeric qualifier, e.g., 
```
CAM%DEV
CAM%DEV%4xCO2
CAM%DEV%CCTS2
```
etc.

**Comment by adamrher** [comment]
I think I prefer CAM%DEV over CAM64 ... for the same reason I prefer that the new physics directory be called src/physics/camdev/ ... It allows us to re-assign the latest cam -phys flag, which is currently cam64, to the CAM%DEV component.

**Comment by gold2718** [comment]
It seems that everyone is happy with CAM%DEV and we do not see any reason why we will need to change this for now.
