### ISSUE TITLE
Transition tests to NUOPC

### ISSUE THREAD

**Issue by gold2718** [ESCOMP/CAM#423]
Since NUOPC will soon become the default CESM driver, CAM needs to transition its test suite to NUOPC. Currently, the plan is:
- Run all tests in both MCT and in NUOPC.
- Update externals to cesm2_3_alpha05b (successfully running all the NUOPC tests requires updating cime and all the NUOPC externals)
    - Comparing baselines with updated NUOPC externals is not straightforward because the test names have been changed
    - Will probably need to create new baseline directories to do straight baseline check or write a script to check the discrepancies.
- Fix existing NUOPC issues (#411, #412)
- Miscellaneous (_next tag_) fixes (e.g., #422).
- Create a minimal, `aux_cam_mct` test suite to ensure CAM/MCT is not broken
- Make NUOPC the default driver for regression tests (in test_driver.sh)

**Comment by fischer-ncar** [comment]
You can easily run nuopc tests by setting the environment variable CIME_DRIVER=nuopc.  This way you won't need to edit the test lists when running both mct and nuopc tests.

**Comment by gold2718** [comment]
@fischer-ncar: Our test framework already handles running tests in MCT or in NUOPC. However, currently, all of our baselines are MCT-only. This work is meant to transition our baselines to NUOPC and the purpose of creating a new testlist is to maintain only a few MCT tests once NUOPC becomes the default driver.

The issue with the new test names is that our current baselines do not have the `_Vmct` (or `_Vnuopc`) string.

**Comment by gold2718** [comment]
**Update: The PGI issue with running using the NUOPC driver is not going to be fixed for CESM2.3, so that release will _not_ have PGI support.**

To move forward with CAM, I propose we move our NUOPC driver aux_cam pgi tests to gnu. To  do this, I propose the following set of steps:
1. In a checkout of cam6_3_031, change the aux_cam pgi tests to gnu and create a set of MCT baselines. Creating an archived version might need to be done by hand.
2. In the branch for this issue, change the aux_cam pgi tests to gnu
3. Change the default compiler in archive_baseline.sh to gnu (and maybe update some of the instructions).
4. Run tests and compare with baselines made using tag (we still expect some answer changes and this will allow us to note them).

@fischer-ncar, do you want me to go ahead and change the prebeta pgi test to gnu as well?

There are other pgi tests (especially the gpu tests on Casper) but I do not think we have worry about those right now. One 'solution' is to turn all the leftover pgi tests (including one waccmx test @fvitt) to be explicit MCT tests.

Thoughts?

**Comment by gold2718** [comment]
> You should be able to move the pgi WACCMX test to gnu. Is there a reason to test this with MCT?

I'll let you know ;)

`<translation>`I will try with NUOPC / gnu first`</translation>`
