### ISSUE TITLE
Zhang McFarlane (ZM) Convective Parcel Modification

### ISSUE THREAD

**Issue by swrneale** [ESCOMP/CAM#428]
Include the new calculation of the convective parcel initialization properties and vertical level (in zm_conv.F90). This will form part of the prototype version of CAM7 with increased vertical resolution (L58 and L93 as of 9/3/2021).

**Comment by gold2718** [comment]
Is this a duplicate of #383?

**Comment by swrneale** [comment]
Why, yes it is, sorry. I clearly didn't search for it correctly. I'll close this one then.

**Comment by swrneale** [comment]
Duplicate of  #383 so closing.
