### ISSUE TITLE
Does new FV3 or SE dycore support CAM case BW1850_f09_g17?

### ISSUE THREAD

**Issue by Qiyu8** [ESCOMP/CAM#443]
I have successfully build a BW1850 case under CESM 2.2.0, but after changing the dycore to FV3 or SE, The build error occurs:

- Using FV3 dycore(decomposition not found)

```
ERROR: Command /Oceanfile/fang/CESM-release-cesm2.2.0/components/cam/bld/build-namelist -ntasks 128 -csmdata /Oceanfile/inputdata_BW1850_f09_g17 -infile /Oceanfile/fang/CESM-release-cesm2.2.0/cime/scripts/mycase/Buildconf/camconf/namelist -start_ymd 00010101 -ignore_ic_year -use_case waccm_tsmlt_1850_cam6 -inputdata /Oceanfile/fang/CESM-release-cesm2.2.0/cime/scripts/mycase/Buildconf/cam.input_data_list -namelist " &atmexp /"  failed rc=255
out=
err=CAM build-namelist - ERROR: fv3_decomp_set failed to find a decomposition.
```
- Using SE dycore(mesh_file not found)
```
/Oceanfile/fang/CESM-release-cesm2.2.0/components/cam/src/dynamics/se/dycore/mesh_mod.F90:         101 : No such file or directory
```

**Comment by cacraigucar** [comment]
Please follow the directions specified in the wiki on what to do when you find a bug:
https://github.com/ESCOMP/CAM/wiki/CAM-Development-Workflow-in-GitHub#how-to-notify-ncar-of-a-problem-or-bug-in-cam

The bottom line is that the CESM forum is the proper location to report suspected bugs/problems and issues.  

This issue will be closed.
