### ISSUE TITLE
Failing WACCMX test

### ISSUE THREAD

**Issue by fvitt** [ESCOMP/CAM#446]
As of tag cam6_3_031, the following WACCMX aux_cam test fails to run:
SMS_D_Ln9_Vmct.f19_f19_mg17.FXHIST.cheyenne_intel.cam-outfrq9s_amie 

The suspicion is that the updated externals in this tag has caused the job to require more memory.

**Comment by cacraigucar** [comment]
Wasn't able to auto-close due to it missing the Project assignment.  Manually closing.
