### ISSUE TITLE
Reduce clubb stdout messages 

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CAM#454]
I believe that the following call to print_clubb_config_flags_api 
https://github.com/ESCOMP/CAM/blob/cam_development/src/physics/cam/clubb_intr.F90#L1147
should be inside the if(masterproc) clause preceding it.  There is no reason to output this from every task in a production situation.

**Comment by adamrher** [comment]
seems like this should be added to my kitchen sink clubb PR https://github.com/ESCOMP/CAM/pull/352

**Comment by cacraigucar** [comment]
@adamrher - I am putting together a misc CAM tag that will probably beat your kitchen sink CLUBB tag.  Should I just go ahead and add this to it so that it makes it in sooner?  @MiCurry might also appreciate this.

**Comment by cacraigucar** [comment]
This will go into an upcoming misc CAM PR.

**Comment by MiCurry** [comment]
@cacraigucar wonderful! Thank you! :)
