### ISSUE TITLE
DP_FRAC and SH_FRAC not initialized in clubb_intr

### ISSUE THREAD

**Issue by adamrher** [ESCOMP/CAM#461]
clubb_intr.F90 is basically a merged version of macrop_driver.F90 and cloud_fraction.F90, and neither of their run-time modules are being called in CAM6 anymore. It turns out the pbuf vars ```DP_FRAC``` and  ```SH_FRAC```, which are intilized to zero in cloud_fraction.F90, are not being initialized in clubb_intr.F90. This isn't a problem so much for ```DP_FRAC``` because there is a limiter that filters out bogus small values:

         if (deepcu(i,k) <= frac_limit .or. dp_icwmr(i,k) < ic_limit) then
            deepcu(i,k) = 0._r8
         endif

But this is just serendipitous. shalcu or ```SH_FRAC``` has no such limiter so it's is being passed around the code and all sorts of unhinged behavior may be happening under our nose.

I'll point out that this reinventing of cloud_fraction in clubb_intr has already caused some issues (the namelist vars ```cldfrac_dp1``` and ```cldfrac_dp2``` became uncoupled because they were hard coded into clubb_intr ... this was fixed by Kate's PPE PR). And it is really ugly that the ```DP_FRAC``` and ```SH_FRAC``` are registered into the pbuf using the cloud_fraction.F90 register subroutine, even though we no longer use the cloud_fraction.F90 runtime subroutines.

@mikaelwitte

**Comment by swrneale** [comment]
I also think we may want to consider that CAM6 PRECL is not really large-scale cloud in the sense it has been in the past, because ShCU is now part of CLUBB. I would bet that PRECL is being compared somewhere between CAM5 and CAM6 with some head scratching. Maybe change to PREC_NODEEP or something?
