### ISSUE TITLE
update externals to cesm2_3_alpha07b +

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#476]
Update externals to match cesm2_3_alpha07b, but updating CTSM to ctsm5.1.dev064 so that PR #387 can update to dev066 without answer changes

**Comment by jedwards4b** [comment]
I notice that the file cam_pio_utils.F90 has several macros of the form #ifdef PIO2 
this macro is not defined in the cesm Makefile (but can easily be added)

**Comment by cacraigucar** [comment]
@jedwards4b - I'm seeing in cime/scripts/Tools/Makefile a section that says if PIO_VERSION is 2 add -DPIO2 to CPPDEFS.  There are more places that have #ifdef PIO2 that just cam_pio_utils.  MPAS and components/cpl7/driver/main/seq_io_mod.F90 also have it.  

I'm not seeing the problem you are describing.  Could you please give us the exact fix you propose I put into this CAM tag?

Thanks

**Comment by cacraigucar** [comment]
@jedwards4b  - All regression testing ran and I am preparing to make the CAM tag.  Is there an issue here we need to address?

**Comment by jedwards4b** [comment]
Sorry, my mistake - I was looking at an older version of the Makefile.

**Comment by cacraigucar** [comment]
Closed by #477
