### ISSUE TITLE
Initialize a couple of wet dep variables

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#482]
(1) ```dgnumwet``` was initialized to 0, and I'm proposing initializing it with a non-zero value instead. In the first time-step w/ the new re-ordering https://github.com/ESCOMP/CAM/pull/387, wet deposition is not called before radiation, and so radiation (via modal_aero_opt.F90) takes the ```log(dgnumwet)``` = NAN. This is not a problem in the current code because the initialized values of dgnumwgt are overwritten by wet deposition before the first radiation call.

(2) ```qaerwat``` was never initialized, and so I'm proposing to initialized it to zero. I don't have as a good a handle on this issue, but for some reason I exposed this problem in my debugging runs; modal_aero_opt is deriving all sorts of optical properties from the initialized value of ```qaerwat```, and it was never initialized. It looks to me like wet deposition changes some values of ```qaerwat```, but not all of them. So I think the non-initialized ```qaerwat``` values are retained for some parts of the arrays in the current code, and I think that's why it changes answers now that I am initializing it to zero.

In sum, my theory is that (1) shouldn't change answers in the current code and (2) should. And that the answer changes in (2) are really just changing some weird uninitialized small number like 2E-349 to zero. And so (2) is a bug fix in the current code. w.r.t (1) it is still open for discussion on whether this change should only be for ```cam_dev``` physics https://github.com/ESCOMP/CAM/pull/387, or for all cases.

**Comment by gold2718** [comment]
(2) is one of those situations where, once you discover it, you wonder 'how did this ever work'?

For (1), I am in favor of only setting it to a non-zero value when needed for two reasons. First, it makes it clear _why_ we are setting the value. Second, it makes it easier to adopt a different approach (e.g., if we decide to read in initial values for this field -- bets anyone?).

**Comment by adamrher** [comment]
I'll defer to you re: (1). I am working on a better way to initialize ```dgnumwet``` https://github.com/ESCOMP/CAM/pull/483#discussion_r766801806

Yes, (2) is a head scratcher. And I think this is occurring for SH_FRAC as well: https://github.com/ESCOMP/CAM/issues/461

**Comment by cacraigucar** [comment]
This issue will address (2) and (1) will be addressed in #387.

**Comment by adamrher** [comment]
closing this as I was incorrect that (2) is a bug: https://github.com/ESCOMP/CAM/pull/483#discussion_r767315331

(1) can stay as it is. I'm just going to follow the default code to call the wet dep routines before radiation, since that initializes dgnumwet with the dry mode radius for the first time-step (https://github.com/ESCOMP/CAM/pull/483#discussion_r767315331)
