### ISSUE TITLE
cam_dev is failing ERP test

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#491]
Restarts are not BFB in cam_dev (compare_base_rest failing when running on izumi w/ nag). Run phase is failing for cam_dev (on cheyenne w/ intel and debug=T). Further exploration needs to be done to identify the cause.

**Comment by swrneale** [comment]
Is this pre or post the ZM bug fixes?

**Comment by cacraigucar** [comment]
It was in the code we committed with the ZM bugs.   I was hoping the ZM bug fixes would solve it, but it did not.

**Comment by swrneale** [comment]
Still quite sure what you mean. Is it (other) code that went in 'with' the the zm bug fixes, or the zm code itself?

**Comment by cacraigucar** [comment]
The bug is there before the ZM bug fixes (in PR #387) and remains after we use them (using the upcoming PR #490).  At this point we don't know where the restart errors are originating.  There is no reason to suspect the ZM code over any other parts of the code.  @adamrher said he has some ideas on where the issue might be.  I've not heard where he is going to be looking.

**Comment by gold2718** [comment]
It seems there are at least two issue at play (looking at the PR). Can someone please write those down here (as comment or by editing the issue text)?
