### ISSUE TITLE
add value of zmconv_parcel_pbl in the namelist 

### ISSUE THREAD

**Issue by cecilehannay** [ESCOMP/CAM#498]
I am setting a run with cam6_3_041. 

By default the value of zmconv_parcel_pbl is not output in the namelist. It is possible to go in the code and figure out the value that the model will be using. But if it was in the namelist, it would be less prone to be "forgotten". 

Would it be possible to add this to the namelist?

**Comment by adamrher** [comment]
FYI, I do see ```zmconv_parcel_pbl = .true.``` in cam6_3_039. It is in atm_in, e.g.,
/glade/scratch/hannay/f.e21.FWscHIST.ne30_L48_BL10_cam6_3_039.001.hf2/run/atm_in

is there somewhere else it's supposed to be output, but is not? Or maybe this got broken in cam6_3_041?

**Comment by cacraigucar** [comment]
I believe it may not be output when it is not being set.  I will look into this

**Comment by swrneale** [comment]
When I put this in I followed the workflow @Katetc had used for some new zmconv namelist parameters in the PPE tags https://github.com/ESCOMP/CAM/pull/398/files. Maybe I missed something for the parameter writing.

**Comment by cecilehannay** [comment]
It is there because I set it in user_nl_cam.
But it would like the value of the variable to be available in namelist
even if it is not set in user_nl_cam.

**Comment by adamrher** [comment]
when you invoke -cam_dev in cam6_3_039 or later, it automatically sets ```zmconv_parcel_pbl = .true.```, so you don't need to specify it in user_nl_cam. And like I said above, it is outputting the value of this namelists in run/atm_in.

**Comment by gold2718** [comment]
@cecilehannay , do you have a case where it did _not_ show up in atm_in? It does look like there is code to add it in `build_namelist` for the combination of `cam_dev` and `deep_scheme == ZM`. Perhaps we should set it to `.false.` in other cases?

**Comment by adamrher** [comment]
I do not have a case where it doesn't show up at all in atm_in. It is either T or F in all cases I've test. Rich made it default to false automatically, and so it should show up in atm_in as false for all non cam_dev runs (and does for me). As you noted, this default is then overwritten with true when invoking cam_dev, and that is also reflected in atm_in.

**Comment by cecilehannay** [comment]
It doesn't appear when I don't invoke: -cam_dev
Maybe it is normal and it is not used without -cam_dev
But if it is used, it should be set in the namelist.

**Comment by gold2718** [comment]
> I do not have a case where it doesn't show up at all in atm_in.

Does this include non-`cam_dev` cases? I do not see a default generated for those cases in build_namelist.

**Comment by adamrher** [comment]
I now realize that I was manually forcing ```zmconv_parcel_pbl = .false.``` in user_nl_cam in my non cam_dev tests. So I retract any claims of evidence that ```zmconv_parcel_pbl``` is written into atm_in for non cam_dev cases.

**Comment by adamrher** [comment]
@swrneale I think you and I are both wrong about the proper way to add a namelist. I had thought that one just needs to add it to the relevant readnl subroutine, and then add an entry in ```namelist_defaults_cam.xml```. But I now realize that we have to both add it to ```build-namelist``` under the appropriate namelist group, and then add the value you want it to default to in ```namelist_defaults_cam.xml ```. 

As Steve said, I doesn't look like you added it to ```build-namelist ```.

**Comment by gold2718** [comment]
> As Steve said, I doesn't look like you added it to `build-namelist `.

It was added as `.true.` for the cases where the default should be `.true.`, what @cecilehannay is asking for is that it has a default of `.false` for other cases. I have submitted code to @cacraigucar to hopefully get into her upcoming externals-update PR.

**Comment by cecilehannay** [comment]
@Steve Goldhaber ***@***.***>
You described exactly what I want. (And better than I did). Thanks.
