### ISSUE TITLE
F2000dev bombs out for finite-volume dycores (FV and FV3)

### ISSUE THREAD

**Issue by adamrher** [ESCOMP/CAM#506]
CAM is bombing out for ```-phys cam_dev``` with the Lin-Rood finite volume dycores. The model doesn't exit until around 700-1100 time-steps in, and for about the final 20 time-steps or so, a bunch aerosol optical depth warnings pop up:

24: WARNING: Aerosol optical depth is unreasonably high in this layer.

After enough of these are triggered, a warning tolerance ```nerrmax_dopaer``` is exceeded in ```modal_aer_opt.F90``` and ends the run. I actually spent a good deal of time debugging this today and came to realize that this is dycore dependent. The following grid alias's evoke the error: ```f10_f10_mg37```, ```f09_f09_mg17``` and ```C96_C96_mg17```, which are the Lin-Rood (hybrid C-grid / D-grid) type finite-volume dycores. MPAS (```mpasa120_mpasa120```), CAM-SE (```ne30_ne30_mg17```) and CAM-SE-CSLAM (```ne30pg3_ne30pg3_mg17```) run a year or more w/o any issues (there are no ```dopaer``` warnings in their logs). @cecilehannay has run ```ne30pg3_ne30pg3_mg17``` w/ cam_dev for over tens years w/o any issues (no ```dopaer``` warnings in those logs either).

Looking at the evolution of a bad point in ```f10_f10_mg37```, it looks like the warnings and eventual error are due to a runaway value for the aerosol number mixing ratio (#/kg-air) for some species. This value is well behaved at nstep=0 and thereafter, so this does not appear to be due to not initializing something properly in the new ```-phys cam_dev``` physics. But in the last 20 or so time-steps before the model bombs out, the pbuf var ```NAER``` departs from its normal magnitude (for this grid point, and m=1 species) of 1E7, monotonically increasing to 1E11.

I suspect ```NAER``` is a dycore tracer, and so that is consistent with this being a dycore dependent error. However, it could also be some dycore logic in the physics package (e.g.,  dry_to_wet conversions) ... Or something entirely different (likely!). I have in the past run ```f09_f09_mg17``` for at least ten years w/ the new physics ordering ([see here for proof](https://webext.cgd.ucar.edu/F2000climo/cam6_3_015_F2000climo_f09_f09_mg17_1800pes_210421_3macmic_tphysac-radinit_Nx5yrs/atm/cam6_3_015_F2000climo_f09_f09_mg17_1800pes_210421_3macmic_tphysac-radinit_Nx5yrs.2_5-cam6_3_006_F2000climo_f09_f09_mg17_1800pes_201209_Nx5yrs.2_5/)). So that suggests there is a particular commit in https://github.com/ESCOMP/CAM/pull/387 that introduced this error. The next step is then to revert back the commits to find when this error was introduced.

I'd be curious to hear feedback on the urgency of this issue. I do not think it is a four alarm fire as there is no indication of bad behavior in the CAM-SE-CSLAM or MPAS configurations, which are the current focus of model development in AMP.

**Comment by andrewgettelman** [comment]
I don't think we can drop this issue, and we might need to elevate it. I started running cam_dev physics with SE, and we are getting some strange aerosol behavior even with SE. Below is a 3 year climatology from a series of sensitivity runs with and with out PUMAS changes: but all are using cam_dev in tags cam3_6_045 or cam3_6_052. 

![zm_PUMAS22_3yr](https://user-images.githubusercontent.com/9616874/159131125-33557ae6-de05-47ac-b61d-15815c6d3d3c.png)

Something is not right with the AOD at high latitudes even if the climate and the cloud drop number are okay: so maybe whatever is going on with FV is present here too with SE? 

Haven't had time to diagnose what is up with aerosol fields yet.

**Comment by adamrher** [comment]
uh oh. Well I thank you for looking into this in SE since I haven't a clue what is the cause of this issue. I will spend some time looking into it next week. I presume AOD shouldn't be "spiky" but to be clear, none of these runs plotted are w/o cam_dev?

I am thinking the way to get at what's going on is to compare L32 cam6 to L32 cam_dev (since cam6 isn't stable w/ L58).

**Comment by andrewgettelman** [comment]
Thanks @adamrher.  I can fire off a run with the same tag and SE w/o cam_dev if you want and re-analyze....

**Comment by andrewgettelman** [comment]
Just an update: I ran a case with cam6_3_52 and the SE core, but without cam_dev physics and it has the sam issue above with AODVIS. It also bombed out after a year, but not sure why (could have just been a communication issue). 

But the main issue is that something is up with the SE core with aerosols. I did not get time to trace this back to see what fields are affected. (E.g. mass, number, etc). Seems like that would be the first thing to look at: num_a[1-4] to see if anything is amiss. Zonal mean latitude height climatology, and look for high latitudes.

**Comment by adamrher** [comment]
@andrewgettelman this AODVIS issue that occurs polewards of about 65˚ seems to be present in all versions of the model. If you look at the AMWG diags ([here's an f09 L32 run w/ an older pre-cam_dev code base](https://webext.cgd.ucar.edu/FSCAM/AMIP_REPORTCARD/cam6_3_006.dev_FHIST_f09_f09_mg17_L32_1800pes_211105_6macmic_25nup_1a05b3alph_Nx2yrs/atm/cam6_3_006.dev_FHIST_f09_f09_mg17_L32_1800pes_211105_6macmic_25nup_1a05b3alph_Nx2yrs.1999_2017-cam6_3_006.dev_FHIST_f09_f09_mg17_L32_1800pes_211105_6macmic_cam6_Nx2yrs.1999_2017/)) the AODVIS variables seems to be set to missing values above that critical latitude. In fact, your values of order 1E34 suggests you're plotting missing values.

We need to ping someone about why AODVIS is so strange at high-latitudes. And whether we need to worry about it.

**Comment by adamrher** [comment]
From Julio:

> I am trying to run an F-case with grid f09_f09_g17 with 58 levels and -phys cam_dev using cam6_3_055

> My run dies immediately. Not even through the first time step.  I am initializing with a minimal cam.i file, U,V,T,Q,PS ...nothing else

**Comment by cacraigucar** [comment]
@jtruesdal - Would this bug fix be a candidate for your upcoming misc PR?

**Comment by jtruesdal** [comment]
@cacraigucar this sounds like an important bug fix and is a good candidate for the upcomming misc PR.  I am working through one last error in the regression tests and will add this fix and resubmit.

**Comment by adamrher** [comment]
@jtruesdal thanks. To be specific, the block bracketed in my initials ARH is what/where needs to be added:

```
    !-------------- Energy budget checks vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
    ! Save total energy for global fixer in next timestep
    call pbuf_set_field(pbuf, teout_idx, state%te_cur(:,dyn_te_idx), (/1,itim_old/),(/pcols,1/))
    !
    ! FV: convert dry-type mixing ratios to moist here because physics_dme_adjust
    !     assumes moist. This is done in p_d_coupling for other dynamics. Bundy, Feb 2004.
    moist_mixing_ratio_dycore = dycore_is('LR').or. dycore_is('FV3')
!+++ARH
    !
    ! FV: convert dry-type mixing ratios to moist here because physics_dme_adjust
    !     assumes moist. This is done in p_d_coupling for other dynamics. Bundy, Feb 2004.
    if (moist_mixing_ratio_dycore) call set_dry_to_wet(state)    ! Physics had dry, dynamics wants moist
!---ARH

    ! Scale dry mass and energy (does nothing if dycore is EUL or SLD)
    tmp_q     (:ncol,:pver) = state%q(:ncol,:pver,ixq)
    tmp_cldliq(:ncol,:pver) = state%q(:ncol,:pver,ixcldliq)
    tmp_cldice(:ncol,:pver) = state%q(:ncol,:pver,ixcldice)
```
