### ISSUE TITLE
CIME update needed for running the pumas codes on GPU and introduce a GPU regression test suite

### ISSUE THREAD

**Issue by sjsprecious** [ESCOMP/CAM#512]
In the PR #409 , the pumas codes with tag `v1.22` will be brought in and it includes the file name changes from `micro_mg3_0.F90` to `micro_pumas_v1.F90` (https://github.com/ESCOMP/PUMAS/commit/9c562418de23fbbf3ac6aa507a30b9b187deb60b).

Thus the CIME codes (or https://github.com/ESMCI/ccs_config_cesm for CIME tag later than `cime6.0.13`) need to be updated so that they applies the GPU flags to the correct source codes.

In addition, the CICE5/CICE6/ccs_config modules need to be updated correspondingly before we could introduce a GPU regression test suite

**Comment by cacraigucar** [comment]
@sjsprecious - It sounds like changes need to be made in cime and/or ccs_config_cesm?  If so, those changes need to be made and tested in CESM and tagged.  Once a CESM alpha tag has been made with these changes, please open a PR that contains these updated externals.  If this update requires code changes in CAM as well, then we'll need to coordinate the changes.  Right now the latest cime tag I see is cime6.0.13 and the ccs_config tag is ccs_config_cem0.0.4.

**Comment by sjsprecious** [comment]
Thanks @cacraigucar and yes, changes are needed in cime and ccs_config_cesm. I will do what you suggested on the cime side first and bring in those tags in my CAM PR later.

**Comment by cacraigucar** [comment]
@sjsprecious I just wanted to let you know that #513 has been tagged.  This brings in cime6.0.13 and introduces the ccs_config external ccs_config_cesm0.0.4 .  I believe you indicated you will need mods beyond these which is why I left this issue open.

**Comment by sjsprecious** [comment]
@cacraigucar , thanks a lot for your help. I have addressed this issue in this PR (https://github.com/ESMCI/ccs_config_cesm/pull/8) but there is a runtime error of using NUOPC driver with the NVHPC compiler and OpenMPI lib. Jim and I are working on this issue right now and I will update it here once the issue is resolved.

On the other hand, this tag (https://github.com/ESMCI/ccs_config_cesm/tree/ccs_config_cesm0.0.6) works fine with MCT driver and nvhpc/openmpi on Casper.

**Comment by sjsprecious** [comment]
Hi @cacraigucar , the NVHPC and ESMF lib version have been updated to resolve a runtime error in CAM with NUOPC driver. The PR is accepted (https://github.com/ESMCI/ccs_config_cesm/pull/22) and tagged (ccs_config_cesm0.0.22). Could you please help brought this tag into CAM? I expect this change is BFB on Cheyenne since there is no change related to it. Thanks!

**Comment by cacraigucar** [comment]
@sjsprecious  - Is there an immediate need for this?  We typically update our externals to match CESM externals when a new CESM beta tag is made.  The next CESM beta tag may be a while.

**Comment by sjsprecious** [comment]
@cacraigucar , thanks for your reply. I do not have an immediate need for this, but just want to give you an update since this issue has been here for a while. It is fine for me to wait for the next CESM beta tag. How long will it usually take?

**Comment by gold2718** [comment]
We need a new ccs_config_cesm tag much sooner anyway to resolve issues with the port to NUOPC testing and CICE6 so I think this update will happen sooner (in the next week or two).

**Comment by sjsprecious** [comment]
Thanks @gold2718, that will be great!
