### ISSUE TITLE
Change CAM physics to variable latent heats (related to enthalpy flux) #521

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [ESCOMP/CAM#521]
For consistent coupling with MOM6, CAM physics needs to use variable latent heats. If not, then enthalpy flux from CAM will use dry heat capacities and MOM6 will use the heat capacities appropriate for different forms of water (that are a factor of 2 and 4 larger!).

This will involve changing %s to a more accurate (temperature dependent latent hearting) formula. There will be possible changes to parameterizations or interfaces to parameterization if constant latent heating is hardcoded in them (CLUBB, ZM, PUMAS). The energy formula must be updated along with this change.

For details see

Reconciling and improving formulations for thermodynamics and conservation principles in Earth
System Models (ESMs)

https://www.overleaf.com/read/fgxczmxqfkzg

**Comment by adamrher** [comment]
@PeterHjortLauritzen for clarity, this issue is **not** preventing us from coupling to MOM? The plan as I understood it was to implement a global fixer in the near-term, since resolving this correctly (as this issue is intended to do) will take ... a while. Do I have this right?
