### ISSUE TITLE
Change 'micro_mg_precip_fall_corr' to true for cam_dev

### ISSUE THREAD

**Issue by andrewgettelman** [ESCOMP/CAM#524]
The default for `micro_mg_precip_fall_corr` in the microphysics namelist should be true. Not sure whether this is best set in namelist_defaults.xml or namelist_definitions.xml or both. Should be on for all cam_dev physics cases until we decide to change it.  This is also relevant for the pack/unpack removal and could come in in that PR (issue #254 ).

**Comment by gold2718** [comment]
This was fixed in cam6_3_063 (#597)
