### ISSUE TITLE
Modifications to test_driver.sh will need to be made when updating cime

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#528]
When the changes mentioned in https://github.com/ESMCI/cime/issues/3979 are introduced into cime, test_driver.sh will need to be modified.  The string "--xml-driver" will be replaced with "--driver"

**Comment by gold2718** [comment]
We should decide if we want to fix this or just remove it since we now have the driver in all our test names.

**Comment by cacraigucar** [comment]
No longer an issue
