### ISSUE TITLE
bug: sponge layer extends to surface in low top (z=~10km) setup #530

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [ESCOMP/CAM#530]
Issue: This formula (taken from FV) 

press = (hvcoord%hyam(k)+hvcoord%hybm(k))*hvcoord%ps0
nu_scale_top(k) = 8.0_r8*(1.0_r8+tanh(1.0_r8*log(ptop/press(1)))) ! tau will be maximum 8 at model top

extends sponge to surface in low top setup. Sponge should just be active in top 3 layers for low top applications.

**Comment by PeterHjortLauritzen** [comment]
proposed fix. In dyncomp.F90 replace

       ptop  = hvcoord%hyai(1)*hvcoord%ps0

       do k=1,nlev
         press = (hvcoord%hyam(k)+hvcoord%hybm(k))*hvcoord%ps0
         nu_scale_top(k) = 8.0_r8*(1.0_r8+tanh(1.0_r8*log(ptop/press(1)))) ! tau will be maximum 8 at model top
         if (nu_scale_top(k).ge.0.15_r8) then
           ksponge_end = k
         else
           nu_scale_top(k) = 0.0_r8
         end if
       end do
     

with

    ptop  = hvcoord%hyai(1)*hvcoord%ps0
     if (ptop>300.0_r8) then
       !
       ! for low tops the formulae below makes the sponge excessively deep
       !
       nu_scale_top(1) = 4.0_r8
       nu_scale_top(2) = 2.0_r8
       nu_scale_top(3) = 1.0_r8
       ksponge_end     = 3
     else
       do k=1,nlev
         press = (hvcoord%hyam(k)+hvcoord%hybm(k))*hvcoord%ps0
         nu_scale_top(k) = 8.0_r8*(1.0_r8+tanh(1.0_r8*log(ptop/press(1)))) ! tau will be maximum 8 at model top
         if (nu_scale_top(k).ge.0.15_r8) then
           ksponge_end = k
         else
           nu_scale_top(k) = 0.0_r8
         end if
       end do
     end if

**Comment by swrneale** [comment]
@PeterHjortLauritzen  Errr. Has this always been in there, and does it matter?! Or is it new?

**Comment by PeterHjortLauritzen** [comment]
Not new but not impacting any of our "standard" applications (CAM, WACCM, etc.) since the model top is much higher than ~10km ...

**Comment by JulioTBacmeister** [comment]
When is the model top near ~10km?

**Comment by PeterHjortLauritzen** [comment]
In idealized user modified setups
