### ISSUE TITLE
SCAM does not work on Izumi with NUOPC driver

### ISSUE THREAD

**Issue by gold2718** [ESCOMP/CAM#532]
There is a bug in CIME which is causing SCAM runs to produce a misinterpreted pathname on Izumi. This will be fixed in CIME and brought into CAM.

^^This has been done, but there is still a lingering issue with aquaplanet/SCAM with the nuopc driver.

This is related to: https://github.com/ESCOMP/CDEPS/issues/150

**Comment by swrneale** [comment]
Oh good this was the confusing errors I was getting!

**Comment by swrneale** [comment]
@gold2718 any status update on this? Is it fixed in 6_3_055 at all?

**Comment by peverwhee** [comment]
@swrneale Yes, partially. With the exception of aquaplanet SCAM cases, this will be fixed in cam6_3_055

**Comment by gold2718** [comment]
@swrneale, yes, you will have to use `--driver mct` to run an aquaplanet SCAM.
FSCAM should work with this PR although it will give you slightly different answers than the global run. The fix for that will be coming soon.
