### ISSUE TITLE
Transition PGI tests to GNU

### ISSUE THREAD

**Issue by peverwhee** [ESCOMP/CAM#539]
In the process of implementing #423, we (re-)discovered that the nuopc driver does not work with the PGI compiler on izumi. This is a good opportunity to transition the CAM PGI tests to GNU. Plan is:

- update testlist_cam.xml to change all aux_cam pgi tests to gnu (plus additional tests, as desired)
- make a soft link from a new cam6_3_xxx_gnu directory to cam6_3_xxx_pgi
- run aux_cam tests
- spot check RMS differences (and dive deeper if necessary)

**Comment by peverwhee** [comment]
@fvitt You currently have a waccmx test (QPC4X) that is running with PGI on izumi. Once we transition this test to nuopc, it will no longer work. Would you like us to move it to GNU?

**Comment by peverwhee** [comment]
@jtruesdal You currently have a fv3_cam test (FKESSLER) that is running with PGI on izumi. Once we transition this test to nuopc, it will no longer work. Would you like us to move it to GNU?

**Comment by fvitt** [comment]
> @fvitt You currently have a waccmx test (QPC4X) that is running with PGI on izumi. Once we transition this test to nuopc, it will no longer work. Would you like us to move it to GNU?

Yes, move it to GNU.  Thanks.

**Comment by jtruesdal** [comment]
Yes.  Thank you!

jt

**Comment by cacraigucar** [comment]
@peverwhee - The one (and only) PGI test_spcam test may be removed completely (it already is being tested in aux_cam and with nag).

**Comment by gold2718** [comment]
Since this is a pgi/gnu-only test, I think that gnu is the only test list (aux_cam) we need to run.
Once that is merged, make new baselines for gnu and create softlinks for nag and intel (Cheyenne).

**Comment by peverwhee** [comment]
@fischer-ncar there is a cheyenne/pgi prebeta test (F2000climo) that will no longer work once we transition the tests to nuopc. We're transitioning our aux_cam pgi tests to gnu for this reason. Would you like us to move the prebeta test to gnu as well?

**Comment by fischer-ncar** [comment]
You can move the prebeta test to gnu.  Further down the road we might want to move this test to nvhpc.
