### ISSUE TITLE
Convective gustiness impacts added to ocean surface flux #540

### ISSUE THREAD

**Issue by megandevlan** [ESCOMP/CAM#540]
Related to[ CMEPS issue #267](https://github.com/ESCOMP/CMEPS/issues/267), we're exploring how to add the effects of convective gustiness into the calculation of surface fluxes over oceans. The code mods so far are all contained within CMEPS (`esmFldsExchange_cesm_mod.F90`, `med_phases_aofluxes_mod.F90`, and `shr_flux_mod.F90`) but the impacts of the addition also influence the atmosphere and might require some tuning. 

We've tested this with 32L (ten year F2010 runs, diagnostics here: [gust_32L_diag](https://webext.cgd.ucar.edu/AMWG/gust_mods/F2010climo.f09_f09_mg17.TestGustGlobal.001-F2010climo.f09_f09_mg17.TestGustGlobal_Control.001/)), and over a shorter period with 58L [(gust_58L_diag).](https://webext.cgd.ucar.edu/AMWG/gust_mods/F2010climo.f09_f09_mg17.TestGustGlobal_58L.001-F2010climo.f09_f09_mg17.TestGustGlobal_Control_58L.001/)  For reference, there are also comparisons to observations in the [parent directory](https://webext.cgd.ucar.edu/AMWG/gust_mods/).

**Comment by adamrher** [comment]
It looks to me like a slight increase in ITCZ precip rates; more significant in the L32 run and barely discernible in L58. Does the L58 run use ZM2? @swrneale have you looked at impacts on MJO?

**Comment by megandevlan** [comment]
@adamrher Yep, good eye! we'll need to dive into this more, the 58L diagnostics are hot off the press and definitely deserve more focused attention. I think a few more years might be helpful - the JJA signal in precip rate for the 32L for example looks nice and consistent, the 58L with fewer years is still a little noisy in the West Pacific.
I was under the impression that ZM2 is used... I branched from cam_development in mid-January but didn't make any changes, are those incorporated yet? (Sorry for my lack of familiarity with this)

**Comment by megandevlan** [comment]
That's what I've been looking for, thanks Adam!! cam6_3_045

**Comment by adamrher** [comment]
That's a great tag! To invoke ZM2, you just need to ```./xmlchange CAM_CONFIG_OPTS='-phys cam_dev' --append```. This will also reorder the physics ... the reordered physics + ZM2 should be used when running L58. Apologies if you already know this; just want to be explicit about this as you continue to explore this gustiness param.

**Comment by megandevlan** [comment]
Just as a quick update - we now have diagnostics for a 58L SE run with the cam_dev physics [here](https://webext.cgd.ucar.edu/AMWG/gust_mods/F2010climo.ne30pg3_ne30pg3_mg17.TestGustGlobal_58L.002-F2010climo.ne30pg3_ne30pg3_mg17.TestGustGlobal_Control_58L.002/) (and each vs obs in the parent directory as before). A lot more analysis still needed to understand this fully but the patterns of change are somewhat more similar to the 32L case now, as Rich has suggested - somewhat of an increase in JJA precip over the West Pacific, and fairly consistent LHFLX changes globally in that season as well.

**Comment by megandevlan** [comment]
It's been a long time since opening this, but the gust mods are finally ready to be added to cam-dev; I'm opening a PR request now.

**Comment by megandevlan** [comment]
Yep, hadn't thought about that one! Not entirely clear how to do that, so will definitely need SE help.

**Comment by cacraigucar** [comment]
I have just added the CoupledEval3 tag to this since it sounds like it is wanted for the release.  

Yes, we SEs can help with the namelists.  We will need to know how to set the defaults.  It sounds like it will only be needed for cam_dev/CAM7.  Should it be on by default or not for cam_dev/CAM7?  If it will be on by default, I assume it changes answers and it will need some science runs to validate answers so that Peter (and Adam maybe) can say that it is okay to go into current cam_development.  If it will be off by default, then not so critical to have science runs, but still very helpful to document what it is doing.

**Comment by PeterHjortLauritzen** [comment]
Yes we want this on by default in cam_dev/CAM7

**Comment by megandevlan** [comment]
Exciting update! https://github.com/ESCOMP/CMEPS/pull/422 is in CMEPS with a flag to check that this can only be activated when using cam_dev physics right now thanks to @jedwards4b. So the CAM side should be pretty straightforward from here (fingers crossed)

**Comment by adamrher** [comment]
Thanks! Not clear to me tho if this is just a check (y"ou can only run gust's w/ CAM%DEV, else error out"), or if it's setting gust=T if CAM%DEV is invoked. We don't need a conflict check, we need it to set gusts=T if CAM%DEV is invoked.

**Comment by jedwards4b** [comment]
What is there is only a conflict check.  If you want it on when camdev is invoked then you need another change.

**Comment by jedwards4b** [comment]
https://github.com/ESCOMP/CMEPS/pull/424
