### ISSUE TITLE
CAM DEV is crashing....

### ISSUE THREAD

**Issue by andrewgettelman** [ESCOMP/CAM#544]
Greetings,

What testing or simulations have been done with -phys cam_dev?  I have been working on updating and tuning the new microphysics and yesterday when I tried to run the cam_dev physics, I started getting crashes, about 18 days (~840 timesteps) into a F2000climo simulation.  I backed down to cam3_6_039 when cam_dev was introduced and before microphysics changes, and I am getting an error:

```WARNING: Aerosol optical depth is unreasonably high in this layer.```

And then it dies. 

Script: /glade/u/home/andrew/cesm_ch/pumas/camdev2_cam6339.csh
Run directory with logs: /glade/scratch/andrew/camdev2_cam6339/run
Case Directory: /glade/work/andrew/cam_dev/cases/camdev2_cam6339

I have been running cam6_3_050 with cam_dev for a few weeks, with no errors. 

A few questions:

1. @adamrher : have you seen this error in any of your testing for the physics re-ordering
2. @adamrher and @cecilehannay : what simulations have been run with cam_dev physics? Did I do something I should not in my cases?

**Comment by gold2718** [comment]
Our current regression tests only have a short restart test for F2000dev. Given that this is the second cam_dev bug reported in the last 24 hours, we might want to replace some older tests with more `CAM%DEV` tests.

**Comment by adamrher** [comment]
@andrewgettelman this is a known bug. FV isn't stable with cam_dev: https://github.com/ESCOMP/CAM/issues/506. Switch to ne30pg3_ne30pg3_mg17.

**Comment by adamrher** [comment]
this is a duplicate issue https://github.com/ESCOMP/CAM/issues/506.
