### ISSUE TITLE
Chemistry updates

### ISSUE THREAD

**Issue by tilmes** [ESCOMP/CAM#558]
Two changes in chemistry are required based on recent studies:
1. Modifying the denitrification in the stratosphere by changing the number of particles per cc of NAT (nat_part_dens). A smaller # increases denitrification. More denitrification increases the ozone depletion. The NAT particle density is currently set to 1e-02. I would suggest we set the nat_part_dens to 5e-04. This is a compromise, in that, one gets too much ozone depletion in the SH, however, more/better ozone depletion in the NH (based on Wilka et al,. 2020)
To make this change, modify mo_sad.F90.
nat_part_dens    = 5.0e-4_r8, &

Ref: Wilka, C., Solomon, S., Kinnison, D., and Tarasick, D.: An Arctic ozone hole in 2020 if not for the Montreal Protocol, Atmos. Chem. Phys., 21, 15771–15781, https://doi.org/10.5194/acp-21-15771-2021, 2021.

2. Modify heterogeneous chemistry reaction: 
[usr_HO2_aer]          HO2  -> H2O (H2O instead of H2O2)
and in components/cam/src/chemistry/mozart/mo_usrrxt.F90
real(r8), parameter :: gamma_ho2  = 0.1_r8          ! 
based on Gaubert et al. (2020) 10.5194/acp-20-14617-2020

Ref: Gaubert, B., Emmons, L. K., Raeder, K., Tilmes, S., Miyazaki, K., Arellano Jr., A. F., Elguindi, N., Granier, C., Tang, W., Barré, J., Worden, H. M., Buchholz, R. R., Edwards, D. P., Franke, P., Anderson, J. L., Saunois, M., Schroeder, J., Woo, J.-H., Simpson, I. J., Blake, D. R., Meinardi, S., Wennberg, P. O., Crounse, J., Teng, A., Kim, M., Dickerson, R. R., He, H., Ren, X., Pusede, S. E., and Diskin, G. S.: Correcting model biases of CO in East Asia: impact on oxidant distributions during KORUS-AQ, Atmos. Chem. Phys., 20, 14617–14647, https://doi.org/10.5194/acp-20-14617-2020, 2020.

**Comment by tilmes** [comment]
@cacraigucar could you assign Francis to this?

**Comment by fvitt** [comment]
@lkemmons @tilmes 
Do we need new mechanism files from the Chemistry Cafe HO2 -> H2O reaction change?

**Comment by lkemmons** [comment]
Actually, as Simone suggested offline, we should do all of these changes together.  So, this will include:
1. update mo_sad.F90 (nat_part_dens = 5.0e-4_r8)
2. update mo_usrrxt.F90 (gamma_ho2=0.1, DMS_OH usr reaction update to JPL10)
3. chemical mechanism updates and corrections (HO2+aer-> H2O; ISOPOOH+hv correction; several reactions update to JPL19).  See attached list. 
4. update photolysis lookup table (Doug Kinnison is working on this; estimates completing in 2 weeks.)
[Mechanism_TS1.2_updates.pdf](https://github.com/ESCOMP/CAM/files/8430278/Mechanism_TS1.2_updates.pdf)

**Comment by lkemmons** [comment]
1. Doug is still evaluating mo_sad update.
2-4: tested in case: /glade/u/home/emmons/cases_ts1.2/f.e22.FCnudged.f09.cam6_3_064.ts12_01
Diagnostics at:
https://acomstaff.acom.ucar.edu/emmons/cesm/f.e22.FCnudged.f09.cam6_3_064.ts12_01.2011_2011-f.e22.FCnudged.f09.cam6_3_064.ts11.2011_2011/

**Comment by lkemmons** [comment]
All 4 changes are in case: /glade/u/home/emmons/cases_ts1.2/f.e22.FCnudged.f09.cam6_3_064.ts12_02

1)  /glade/u/home/emmons/cases_ts1.2/f.e22.FCnudged.f09.cam6_3_064.ts12_02/SourceMods/src.cam/mo_sad.F90
2)  /glade/u/home/emmons/cases_ts1.2/f.e22.FCnudged.f09.cam6_3_064.ts12_02/SourceMods/src.cam/mo_usrrxt.F90
3)  /glade/u/home/emmons/mechanisms/MZ305_TS1.2_20220407.in
4)  
&chem_inparm
 xs_long_file = '/glade/work/emmons/cesm_inputs/lut/temp_prs_GT200nm_c220622mm.nc'
 xs_short_file = '/glade/work/emmons/cesm_inputs/lut/xs_short_c220622mm.nc'
/

**Comment by lkemmons** [comment]
For WACCM, the TSMLT mechanism has also been updated:
/glade/u/home/emmons/mechanisms/MZ308_TSMLT1.2_simpleVBS_20220712.in
and tested (/glade/u/home/emmons/cases_ts1.2/f.e22.FWSD.f09.cam6_3_064.tsmlt12). This is an update for "waccm_tsmlt_mam4". 

The mechanism file /glade/u/home/emmons/mechanisms/MZ305_TS1.2_20220407.in is for updating "trop_strat_mam4_vbs". 

I will have to make additional mechanism files for the other trop_strat, tsmlt and ma mechanisms, to be consistent.

**Comment by lkemmons** [comment]
Just realized the CO+OH reaction should be updated.  Will be creating all new mechanisms including that: TS, TSMLT, MA, MAD.  This does not affect CAM or WACCM-SC.

**Comment by lkemmons** [comment]
Now have finalized code and mechanisms for chemistry update TS1.2 (to JPL19 reaction rates):
Source code changes:
/glade/u/home/emmons/cases_ts1.2/f.e22.FCnudged.f09.cam6_3_087.ts12/
SourceMods/src.cam/
mo_sad.F90
mo_usrrxt.F90
 
Namelist changes (new photolysis lookup tables):
&chem_inparm
xs_long_file = '/glade/work/emmons/cesm_inputs/lut/temp_prs_GT200nm_c220622mm.nc'
xs_short_file = '/glade/work/emmons/cesm_inputs/lut/xs_short_c220622mm.nc'
/

New mechanism files
trop_strat_mam4_vbs:
/glade/u/home/emmons/mechanisms/MZ316_TS1.2_20221220.in
waccm_tsmlt_mam4:
/glade/u/home/emmons/mechanisms/MZ317_TSMLT1.2_simpleVBS_20221220.in

waccm_ma_mam4: 
/glade/u/home/emmons/mechanisms/MZ319_MA_MAM4_20221220.in

waccm_mad_mam4: 
/glade/u/home/emmons/mechanisms/MZ322_MAD_MAM4_20221220.in

trop_strat_mam4_ts2: 
/glade/u/home/emmons/mechanisms/MZ321_TS2.2_20221220.in

Additional mechanisms to be updated:
trop_strat_mam4_vbsext
mam5 mechanisms

**Comment by tilmes** [comment]
@lkemmons Moving over to MAM5 I think, we will also require all these to become mam5 mechanisms.
I think, we only have to add num_a5 and so4_a5 for the chemistry.

**Comment by lkemmons** [comment]
Yes - I will make MAM5 versions.  It is a little more involved in the Cafe,
but shouldn't take long.

**Comment by fvitt** [comment]
@tilmes @lkemmons ,
Should we remove the trop_mam5 mechanism?

**Comment by tilmes** [comment]
Yes, we don't need a trop_mam5 or WACCM SC mam5 (if that exists)

**Comment by lkemmons** [comment]
I am just adding MAM5 to the other mechanisms - shouldn't there be Ext
Forcing emissions of num_a5 to go along with so4_a5?

**Comment by tilmes** [comment]
The so4_a5 mode is sulfate that is produced from volcanic SO2 injection in the stratosphere. I suppose one may want to at one point inject directly into the so4_a5 mode, so I guess it would not hurt to add that in the mechanism as external forcing.

**Comment by lkemmons** [comment]
Thanks for clarifying.  I'll leave it out for now.

**Comment by fvitt** [comment]
@lkemmons ,

This reaction was added to the TS2 mechanism:
```
[AOA_NH]               AOA_NH  -> AOA_NH                                        ; 1 
```

Is this intended?  It seem to not do anything.

**Comment by lkemmons** [comment]
> 

Sorry - that's a mistake. I have corrected:
/glade/u/home/emmons/mechanisms/version_2022dec/MZ321_TS2.2_20221220.in

**Comment by lkemmons** [comment]
MAM5 mechanisms:
trop_strat_mam5_vbs:
/glade/u/home/emmons/mechanisms/version_2022dec/MZ316a_TS1.2_MAM5_20221220.in

waccm_tsmlt_mam5:
/glade/u/home/emmons/mechanisms/version_2022dec/MZ317a_TSMLT1.2_MAM5_simpleVBS_20221220.in

trop_strat_mam5_ts2: 
/glade/u/home/emmons/mechanisms/version_2022dec/MZ321_TS2.2_20221220.in

waccm_ma_mam5:
/glade/u/home/emmons/mechanisms/version_2022dec/MZ319a_MA_MAM5_20221220.in

waccm_mad_mam5:
/glade/u/home/emmons/mechanisms/version_2022dec/MZ322a_MAD_MAM5_20221220.in

**Comment by lkemmons** [comment]
CAM diagnostics comparing MOZART-TS1.2 to TS1.1 are at:
https://acomstaff.acom.ucar.edu/emmons/cesm/f.e22.FCnudged.f09.cam6_3_087.ts12.2010_2010-f.e22.FCnudged.f09.cam6_3_087.ts11.2010_2010/

Updated photolysis lookup tables (xs_long_file, xs_short_file)

Updated reactions include:
ISOPOOH + hv [bug correction]
DMS + OH [JPL15 update]
HO2 aerosol uptake [product change to H2O, gamma change from 0.2 to 0.1]
N2O5 aerosol uptake [gamma from 0.1 to 0.02, JPL19]
NO2 aerosol uptake [gamma from 1.e-4 to 8.e-6]
NO3 aerosol uptake [gamma from 1e-3 to 2e-3 [JPL19]
CO + OH [replaces 2 reactions, new usrrxt, JPL19]

In mo_sad: nat_part_dens from 1e-01 to 5.0e-4 [Wilka et al., ACP, 2021]

**Comment by fvitt** [comment]
Are we replacing the MAM4 chemistry compsets with MAM5 in this PR?  Should that be a separate issue/pull request?

**Comment by lkemmons** [comment]
2 more mechanisms (not previously in compsets):

/glade/u/home/emmons/mechanisms/version_2022dec/MZ325_TSMLT1_fullVBS_20221223.in
/glade/u/home/emmons/mechanisms/version_2022dec/MZ325a_TSMLT1_MAM5_fullVBS_20221223.in

We can discuss whether these should be compsets, or just made available for interested users.

I think the compsets should just be updated to the MAM5 versions (for example, FCHIST would use MZ316a_TS1.2_MAM5_20221220.in).  I don't see a need for additional compsets for MAM4.

**Comment by lkemmons** [comment]
@fvitt One more update for the FCnudged compset - we would like the defaults in &nudging_nl to be:

 model_times_per_day = 48
 nudge_times_per_day = 8
 nudge_tprof = 1
 nudge_tcoef = 0.25
 nudge_uprof = 1
 nudge_ucoef = 0.25
 nudge_vprof = 1
 nudge_vcoef = 0.25
