### ISSUE TITLE
genf90 moving in cime

### ISSUE THREAD

**Issue by fischer-ncar** [ESCOMP/CAM#559]
This is a heads up that PR https://github.com/ESMCI/cime/pull/4162 moves the location
of genf90.  There will need to be a change in bld/Makefile.in

```
--- a/bld/Makefile.in
+++ b/bld/Makefile.in
@@ -208,7 +208,7 @@ endif
        $(AS) -m  $<
 
 %.F90: %.F90.in
-        $(ROOTDIR)/cime/src/externals/genf90/genf90.pl $< > $@
+        $(ROOTDIR)/cime/CIME/non_py/externals/genf90/genf90.pl $< > $@
```

This change will be in cime6.0.17, which hasn't been made yet.  This will be needed for cesm2_3_alpha09b.
Also, a new external will need to be added to Externals.cfg.

```
[genf90]
protocol = git
repo_url = https://github.com/PARALLELIO/genf90
branch = master
local_path = cime/CIME/non_py/externals/genf90
required = True
```

**Comment by gold2718** [comment]
@peverwhee, is this an issue for your upcoming alpha09a+ tag?

**Comment by peverwhee** [comment]
@gold2718 hm. It seems like it should be (but I'm not seeing any problems that seems related to this).  But it sounds like I should bring in this change.

**Comment by peverwhee** [comment]
Since the genf90 external is in the CIME externals, it doesn't need to be added to CAM's.

**Comment by fischer-ncar** [comment]
The behavior of cime and genf90 has changed since I made this issue.  But it's was a good idea to fix the Makefile.
genf90 is no longer an external, so it's not needed in any external files, I think.
