### ISSUE TITLE
WACCMX time interpolation fix for multiple day AMIE input file #562

### ISSUE THREAD

**Issue by npedatella** [ESCOMP/CAM#562]
The current AMIE code has an error in the time interpolation if a file with multiple days is used. Specifically:

denoma = amie_sh_ut(iset1) - amie_sh_ut(iset)

should be changed to:

denoma = (day(iset1) - day(iset))*24._r8 + amie_sh_ut(iset1)-amie_sh_ut(iset)

See /glade/u/home/nickp/waccmx_src/cesm2_2_0/components/cam/src/ionosphere/waccmx/amie.F90 for the code fix.

**Comment by fvitt** [comment]
@npedatella 
Can you point me to an AMIE input file that has multiple day?

**Comment by npedatella** [comment]
A multiple day file is here: /glade/p/hao/itmodel/chihting/amgeo_temp/amgeo_all_days/mar15-19_2013_sh_amgeo_ori.nc

**Comment by fvitt** [comment]
@npedatella 

Your change needs to be applied to northern hemisphere inputs as well.

I don't believe the calculation of the f2 time interpolation factor is quite right.  I propose we make this change:
```
        f1 = (amie_sh_ut(iset1) - (model_ut+(iday- &
             day(iset1))*24._r8))/denoma
-       f2 = (model_ut+(iday-day(iset1))*24._r8 - &
+       f2 = (model_ut+(iday-day(iset))*24._r8 - &
             amie_sh_ut(iset))/denoma
```

I am afraid to ask what happens when the AMIE input files span a month boundary.

**Comment by npedatella** [comment]
@fvitt 

You are correct that the calculation of f2 also needs to be changed. These also need to be made for the NH. 

Would it make sense to rewrite the AMIE subroutines to do the time interpolation using fractional days? This would avoid the issue of crossing month boundaries. I believe that this is what is done for the MERRA time interpolation.

**Comment by fvitt** [comment]
> 
> Would it make sense to rewrite the AMIE subroutines to do the time interpolation using fractional days? This would avoid the issue of crossing month boundaries. I believe that this is what is done for the MERRA time interpolation.

Yes.  If the AMIE input files could include a "time" coordinate variable, like solar irradiance and solar params input files do, we could make use of the same time_coordinate code.

**Comment by fvitt** [comment]
> @fvitt - Could the AMIE inputs (yr, month, day, hour, minute, second) be converted to date and datesec on input so that the existing code could be used?

Sure, we can do that as well.
