### ISSUE TITLE
Interpolation issue for SE dycore output? 

### ISSUE THREAD

**Issue by andrewgettelman** [ESCOMP/CAM#564]
I'm running an F-case with the se core on the cam_dev branch (res = ne30pg3_ne30pg3_mg17), tag is cam6_3_052 (but cam6_3_045 has the same problem)

When I set:
 interpolate_output = .true.
 interpolate_nlat = 192
 interpolate_nlon = 288

I get strange behavior in some of the output files. For some fields (AODVIS, TOT_CLD_VISTAU) but not others (SWCF) I get anomalies at high latitudes, even in a 3 year average:

![download](https://user-images.githubusercontent.com/9616874/162837476-07e76efa-ffef-48e7-b032-f3e65450a4f8.png)

Is this a known interpolation issue with the internal interpolation for CAM? It certainly looks like some imprinting at high latitudes.

Should I NOT use the interpolate function? Or just not use f09 style resolution> (I could do 180 x 360 for example).

Files are in: /glade/scratch/andrew/archive/pumasNewAcc_cam6352/atm/hist/*.h0.000[1-3]*

Thanks for any help/advice

**Comment by adamrher** [comment]
Just putting this relevant info here regarding the apparent missing values at high-latitudes for these variables, from https://github.com/ESCOMP/CAM/issues/506

> @andrewgettelman this AODVIS issue that occurs polewards of about 65˚ seems to be present in all versions of the model. If you look at the AMWG diags ([here's an f09 L32 run w/ an older pre-cam_dev code base](https://webext.cgd.ucar.edu/FSCAM/AMIP_REPORTCARD/cam6_3_006.dev_FHIST_f09_f09_mg17_L32_1800pes_211105_6macmic_25nup_1a05b3alph_Nx2yrs/atm/cam6_3_006.dev_FHIST_f09_f09_mg17_L32_1800pes_211105_6macmic_25nup_1a05b3alph_Nx2yrs.1999_2017-cam6_3_006.dev_FHIST_f09_f09_mg17_L32_1800pes_211105_6macmic_cam6_Nx2yrs.1999_2017/)) the AODVIS variables seems to be set to missing values above that critical latitude. In fact, your values of order 1E34 suggests you're plotting missing values.
>
>We need to ping someone about why AODVIS is so strange at high-latitudes. And whether we need to worry about it.

**Comment by andrewgettelman** [comment]
So maybe this is just a masking problem for missing data when there is no sunlight (AODVIS and TOT_CLD_VISTAU would have it). There is a different variable for AODVIS (AODVISDN= Day Night, calculated at all times). 

I thought most of the previous interpolation routines could handle this with the FV core. It's probably that the 'fill value' is something like 1e.34 and the internal interpolation might mix values so that we are getting slightly higher and lower values.  that are not picked up as missing.... I can mask for now, but I think this might be a bit of an interpolation issue. from SE --> Lat lon when done internally.

**Comment by adamrher** [comment]
when I do ncview to a AODVIS for a month w/o any sunlight over the N.Pole (December), I get:

<img width="578" alt="Screen Shot 2022-04-12 at 9 29 24 AM" src="https://user-images.githubusercontent.com/29961476/162998699-bb5dd435-4e82-435d-bee6-675f8e63f152.png">

And this is a ne30pg2 interpolated output h0 file. It's telling me everything above a certain latitude is missing values. Is there a way to scan arrays in python to search for all types of NaN's / Missing Value, which may be different than python's specific definition of a missing value? NCL has a routine like this here: https://www.ncl.ucar.edu/Document/Functions/Built-in/replace_ieeenan.shtml

**Comment by andrewgettelman** [comment]
You can search in python for nans (isnan) and then replace them, and/or use a threshold. I can see what works. It's just previous code with FV seemed to work. 

I think the problem is that the interpolation produces values right around the terminator which are not equal to the missing value. Below is an FV december monthly mean plotted with ncview

![Screen Shot 2022-04-12 at 9 42 46 AM](https://user-images.githubusercontent.com/9616874/163001366-76529b91-fa27-4d14-9e2e-e2b179f4e8d7.png)

Here all the missing values = 1.e36 and the software can filter it. 

So the issue is a minor annoyance in the interpolation. Can work around it in the workflow (either not plotting it, or 'correcting' to specify as missing). Let me play with the python and I'll post a solution and close it.

Not sure if we need to deal with changing the interpolation algorithm for output or not at this point. Probably not work spending time on. 

Thanks again Adam for commenting.

**Comment by adamrher** [comment]
I think I agree there is a problem, but like you said probably low priority considering all that's going on. ncview w/ f09 seems to treat this variable the ideal way, whereas the interpolated ne30 output has some *intermediate* real/missing values anear the terminator, and computes an enormous contour range such that you can't see the structure in the good regions (i.e., all blue in the interior compared to the f09 plot).

**Comment by andrewgettelman** [comment]
Okay, one line fix solves it in python: 
`corr=ms1.AODVIS.where(ms1.AODVIS < 1000.) `

This sets all large values to missing (the conditional is true, everything else is missing), and then you can average/slice and dice and it behaves, e.g., then you can get the plot below...(all SE h0 output with interpolation):

![download](https://user-images.githubusercontent.com/9616874/163008776-3ea1fd77-dd42-4f1f-b373-3e96dec93d26.png)


I'll close this issue for now. It's not a bug in the model, it's a workflow issue with interpolation (diagnostic).

**Comment by adamrher** [comment]
this issue was never resolved.

**Comment by andrewgettelman** [comment]
May be related to #644. Added @nusbaume to the issue. He is working on #644. Test any solution for that looking at AOD....

**Comment by nusbaume** [comment]
@andrewgettelman @adamrher Have either of you run into this problem when not running with CSLAM?  I have been able to replicate it, but only when using CSLAM at `ne30` resolution or higher.  So if you possibly have an example at either a lower resolution or without CSLAM it would great if you could share it with me.  Thanks!

**Comment by andrewgettelman** [comment]
Yes. I have run into it without CSLAM. Part of the issue is interpolation between values which are 'missing' and those that are real numbers. When the interpolation ends up with a value slightly different than missing, it can look like a real value. That is what I have seen, even without CSLAM. There may be other issues. I saw it at ne120 resolution without CSLAM.

**Comment by nusbaume** [comment]
Hello again,

So after investigating this issue some more, I believe I have found a fix for monthly average (`h0`) data.  If you want to try it out for one of your own runs you can find the SourceMods on Cheyenne here:

```
/glade/scratch/nusbaume/model_runs/cam6_ne30pg3_F2000_aodvis/SourceMods/src.cam/*.F90
```

Sadly it looks like to fix this problem at all output time-scales (daily, six-hourly, every time step, etc.) it will potentially require a significant modification of the code even down into the "guts" of the SE dycore itself.  However, arguably the interpolation code should be re-factored anyways in order to work with all dycores with un-structured grids, as opposed to just the SE dycore.  Thus if the above fix works for you I might get it into the model ASAP, but then try to fix the more general issue later once I re-factor the interpolation routine.

Does this plan sound reasonable to you @andrewgettelman @adamrher ?  If not, or if the fix above doesn't work for you, just let me know.  Thanks!

**Comment by andrewgettelman** [comment]
Hi @nusbaume , I think fixing it for h0 files is fine for now. It's going to just be a diagnostic issue, and for some higher frequency output (e.g. instantaneous) we are likely not interpolating to lat-lon anyway. I think not investing a lot of resources in it now as you suggest is fine, as long as we try to let everyone know.

**Comment by cacraigucar** [comment]
Mostly solved - will reopen if it becomes an issue in the future
