### ISSUE TITLE
Bug fix for Q925 in cam_diagnostics.

### ISSUE THREAD

**Issue by brian-eaton** [ESCOMP/CAM#57]
Bug was reported on bulletin board.  The fix is in cam_diagnostics.F90 at line 1413.

    if (hist_fld_active('THE9251000')) then

should be

    if (hist_fld_active('THE9251000') .or. &
        hist_fld_active('Q925')) then

**Comment by cacraigucar** [comment]
@gold2718 - this will be going into my upcoming misc PR which I will be making most likely without review (minor changes which are non-answer changing).  Could you give your approval for this change when you get a chance?

**Comment by gold2718** [comment]
This change looks okay but I think a quick review cycle should still be conducted. Just make sure everyone knows that this is a high priority.
