### ISSUE TITLE
moving CLUBB pdf closure to after advancing the CLUBB equations #582

### ISSUE THREAD

**Issue by adamrher** [ESCOMP/CAM#582]
In https://github.com/ESCOMP/CAM/pull/545, UWM wanted to move the pdf closure to the post position (i.e., call pdf closure after advancing the prognostic moments). I believe the motivation is because the pdf closure is CAM's saturation adjustment, which is usually the last process to be called because it provides an instantaneous adjustment. We decided against moving the pdf closure in https://github.com/ESCOMP/CAM/pull/545, and I instead have opened this issue to discuss what I perceive as the obstacles needed to be addressed before moving the pdf closure.

The pdf closure provides variables that are used to advance the prognostic equations, and we currently call the pdf closure at the top of CLUBB, so that all routines in CLUBB are able to use to those variables. By moving the pdf closure to the post position, the necessary variables will need to be saved from time-step to time-step, and fed in to CLUBB to be used to advance the CLUBB equations. UWM proposed saving these variables time-step to time-step by expanding their scope in the PBUF to 'global':

```
    call pbuf_add_field('WP2THVP',    'global', dtype_r8, (/pcols,pverp/), wp2thvp_idx)
    call pbuf_add_field('RTPTHVP',    'global', dtype_r8, (/pcols,pverp/), rtpthvp_idx)
    call pbuf_add_field('THLPTHVP',   'global', dtype_r8, (/pcols,pverp/), thlpthvp_idx)
    call pbuf_add_field('CLOUD_FRAC', 'global', dtype_r8, (/pcols,pverp/), cloud_frac_idx)
    call pbuf_add_field('ISS_FRAC',   'global',  dtype_r8, (/pcols,pverp/), ice_supersat_idx)
    call pbuf_add_field('RCM',        'global', dtype_r8, (/pcols,pverp/), rcm_idx)
```

The first three variables are probably fine to keep in the PBUF, but they are incorrect if we turn on advecting the moments via ```clubb_do_adv```. Looking through ```advance_clubb_core``` I don't believe CLOUD_FRAC is used anywhere prior to the post position of the pdf closure (I only see one place where CLOUD_FRAC might be used before the pdf closure, and that's for adjusting the C2 coefficient using cloud_frac (l_C2_cloud_frac), which as far as I can tell is defaulting to false).

RCM is my major concern. It is used in many places in CLUBB before the post pdf closure position (primarily for computing virtual potential temperature or just plain temperature, from RCM). Cloud liquid is supposed to be advected by the dycore, and so using the PBUF to access the cloud field from time-step to time-step is not appropriate. Two possible solutions:

1. Make RCM a proper dycore tracer in state%q
2. Set RCM to CLDLIQ to be fed into CLUBB (this would be for all macmic cycles to be consistent)

The nice thing about (2) is that then thl and rtm are consistent with RCM, since they are defined using CLDLIQ. However, this will introduce a change to the definition of cloud liquid compared to the current code base where we compute the pdf closure at the top of CLUBB. That is because CLUBB lives in an all liquid world, and the cloud liquid created by the pdf closure is always going to be larger than the CLDLIQ field after MG2 has had chance to repartition some of it to CLDICE. Setting RCM to CLDLIQ will always reflect this MG2 re-partition. So by initializing RCM to CLDLIQ we are changing the definition of the cloud used to calculate various things such virtual potential temperature. 

I actually think that the balance of trade-offs points towards using (2). This is because it creates consistency between thl, rtm and RCM throughout a larger portion of the CLUBB code, where it is important to maintain these consistencies because their definitions are used to convert back and forth from moist conserved to non conserved variables (e.g., thl and T). However, once we exit CLUBB we will use the pdf closure cloud to convert from CLUBB's thl / rtm back to CAM's T, q, CLDLIQ. 

This all make me wonder whether an (3) option is possible; initializing RCM to CLDLIQ+CLDICE, rtm=qv+RCM, and thl = thli = f(CLDLIQ,CLDICE), and using the pdf closure cloud liquid to convert back to CAM's variables.

@Katetc
@vlarson
@bstephens82
@JulioTBacmeister

**Comment by vlarson** [comment]
> RCM is my major concern. It is used in many places in CLUBB before the post pdf closure position (primarily for computing virtual potential temperature or just plain temperature, from RCM). Cloud liquid is supposed to be advected by the dycore, and so using the PBUF to access the cloud field from time-step to time-step is not appropriate. 

I wonder how much advection of liquid by the dycore matters if it is just re-diagnosed by CLUBB every time step.  (Other moments that are needed for diagnosing rcm, such as rtp2, are not horizontally advected.)

> 1. Make RCM a proper dycore tracer in state%q
> 2. Set RCM to CLDLIQ to be fed into CLUBB (this would be for all macmic cycles to be consistent)
> 
> The nice thing about (2) is that then thl and rtm are consistent with RCM, since they are defined using CLDLIQ. However, this will introduce a change to the definition of cloud liquid compared to the current code base where we compute the pdf closure at the top of CLUBB. That is because CLUBB lives in an all liquid world, and the cloud liquid created by the pdf closure is always going to be larger than the CLDLIQ field after MG2 has had chance to repartition some of it to CLDICE. Setting RCM to CLDLIQ will always reflect this MG2 re-partition. So by initializing RCM to CLDLIQ we are changing the definition of the cloud used to calculate various things such virtual potential temperature.

I don't see usage of a re-partitioned liquid variable as a problem, in principle.  If we're lucky, use of CLDLIQ and RCM won't make much difference, because RCM is re-diagnosed in CLUBB each substep (hopefully in a way consistent with MG2!).

> I actually think that the balance of trade-offs points towards using (2). This is because it creates consistency between thl, rtm and RCM throughout a larger portion of the CLUBB code, where it is important to maintain these consistencies because their definitions are used to convert back and forth from moist conserved to non conserved variables (e.g., thl and T). However, once we exit CLUBB we will use the pdf closure cloud to convert from CLUBB's thl / rtm back to CAM's T, q, CLDLIQ.

To me, option (2) sounds like it is worth trying.  It might require re-tuning.

> This all make me wonder whether an (3) option is possible; initializing RCM to CLDLIQ+CLDICE, rtm=qv+RCM, and thl = thli = f(CLDLIQ,CLDICE), and using the pdf closure cloud liquid to convert back to CAM's variables.

UWM has discussed this in the past, but we've always rejected it because once liquid and ice are combined, it is hard to separate them again.  We'd need to rely on, e.g., a temperature-dependent partition between liquid and ice, which seems undesirable.

**Comment by bstephens82** [comment]
Would option (2) be as simple as the following replacement in clubb_intr.F90?
~~~
!        rcm_inout(i,k)  = rcm(i,pverp-k+1)
        rcm_inout(i,k)  = state1%q(i,pver-k+1,ixcldliq)
~~~

**Comment by adamrher** [comment]
> Would option (2) be as simple as the following replacement in clubb_intr.F90 (neglecting retuning)?
> 
> ```
> !        rcm_inout(i,k)  = rcm(i,pverp-k+1)
>         rcm_inout(i,k)  = state1%q(i,pver-k+1,ixcldliq)
> ```

It's a little sloppier b/c the loop you cite is over pverp, and cldliq is only of size pver. So something like this:

```
  if (k.gt.1) then
    rcm_inout(i,k)  = state1%q(i,pverp-k+1,ixcldliq)
  end if
```

Note I'm indexing the state array with pverp. Then after exiting the pverp loop, set the subsurface ghost point:
```
rcm_inout(i,1) = rcm_inout(i,2)
```

You thinking of giving (2) a try? I'd vote for that ...

**Comment by bstephens82** [comment]
> You thinking of giving (2) a try? I'd vote for that ...

Yeah I was thinking about doing a test.  I tried a test with SCAM, but I'm not sure how enlightening that is considering we are talking about things being advected by the dycore.  But I could run a short FHIST test or something.

Also thanks for pointing out the pver vs pverp distinction, that was a mistake in my proposed new line.  I would've written pverp if I'd noticed that.

**Comment by bstephens82** [comment]
Here are a couple of SWCF plots from two runs I did.  They are both FHIST, camdev, L58 runs with SE core on Kate's PR code from a few days ago.  (I'm realizing now I neglected to set `rcm_inout(i,1) = rcm_inout(i,2)`, but I guess I'll post these results anyway.) The first makes no changes to the code and uses the default parameters and flags:
![set5_ANN_SWCF_CERES-EBAF_obsc](https://user-images.githubusercontent.com/59519056/166510876-2c7d1837-ee7a-42a5-aaf3-9494a1737b9d.png)

The second makes one change to the code and that is the replacement
~~~
!        rcm_inout(i,k)  = rcm(i,pverp-k+1)
        if (k.gt.1) then
          rcm_inout(i,k) = state1%q(i,pverp-k+1,ixcldliq)
        end if
~~~
![set5_ANN_SWCF_CERES-EBAF_obsc](https://user-images.githubusercontent.com/59519056/166511102-26333ba5-4518-4ccc-a0a8-1c1db3bb5376.png)

**Comment by bstephens82** [comment]
> > Here are a couple of SWCF plots from two runs I did. They are both FHIST, camdev, L58 runs with SE core on Kate's PR code from a few days ago.
> 
> Do these runs have the pdf closure in the post position or the pre position?

Post.  `ipdf_call_placement = 2`.

**Comment by adamrher** [comment]
suggests to me we should just do (2). My only remaining concern is whether there is any impact on clubb's energy fixer between these two simulations. What do you think about adding this ELEAK_CLUBB diagnostic to clubb_intr [here](https://github.com/adamrher/CAM/blob/df5b52edd22f350f592e38b375b3b1bd68405d32/src/physics/cam/clubb_intr.F90#L3539)?

**Comment by bstephens82** [comment]
> suggests to me we should just do (2). My only remaining concern is whether there is any impact on clubb's energy fixer between these two simulations. What do you think about adding this ELEAK_CLUBB diagnostic to clubb_intr [here](https://github.com/adamrher/CAM/blob/df5b52edd22f350f592e38b375b3b1bd68405d32/src/physics/cam/clubb_intr.F90#L3539)?

Are you asking if I can add this diagnostic to my code and then run the experiment?  Happy to do that, just wasn't sure if I understood.

**Comment by adamrher** [comment]
yes, that's what I'm asking. To add ELEAK_CLUBB to fincl1 and see if the monthly mean or annual mean are significantly different.

**Comment by adamrher** [comment]
Attached are the year 1979 + 2 months mean ELEAK_CLUBB, for two runs in the post pdf position, but the right panel with rcm_inout initialized with cldliq. I see no discernible difference between the two simulations

![temp_ELEAK_CLUBB](https://user-images.githubusercontent.com/29961476/166809364-3cb170b8-2214-4c71-8116-c8e1e5aeeafe.png)

So I think if we want to move the pdf closure position, we can do that. @vlarson what is UWM's reasoning for moving the pdf closure to the post position?

**Comment by adamrher** [comment]
From @bstephens82 

> so vince is confirming that the reason for moving the pdf call is to have the saturation adjustment come right beore microphysics

OK. So I wanted to look a little bit closer at the sensitivity to moving this pdf closure to the post position. I've looked at the sensitivity to this over a year ago, and came to the conclusion it doesn't change the climate one bit. But with the new simulations ben did, here are the [amwg diagnostics](https://webext.cgd.ucar.edu/FHIST/fhist_se_l58_camdev_katePR_rcmEqCldliq/atm/fhist_se_l58_camdev_katePR_rcmEqCldliq.1979_1979-fhist_se_l58_camdev_katePR_dflt.1979_1979/). This is only for one year. My takeaway is the climate is pretty much the same, or within the bound of differences from comparing two 1 year simulations.

Please feel free to look over the diagnostics. If no one can spot any important distinctions, I will plan on moving the pdf closure to the post position (and initialize rcm to CLDLIQ) in PR https://github.com/ESCOMP/CAM/pull/598.

**Comment by bstephens82** [comment]
> If no one can spot any important distinctions, I will plan on moving the pdf closure to the post position (and initialize rcm to CLDLIQ) in PR #598.

Would it be important to deal with rcm being used in subcol_SILHS.F90 for [setup_pdf_parameters](https://github.com/ESCOMP/CAM/blob/034f04c935947cc6e8bd79535dac7ef5483bcb16/src/physics/cam/subcol_SILHS.F90#L1142) and [generate_silhs_sample](https://github.com/ESCOMP/CAM/blob/034f04c935947cc6e8bd79535dac7ef5483bcb16/src/physics/cam/subcol_SILHS.F90#L1230) in this same PR?  This would require updating the external.  I've written this code for CLUBB external and I'm going to merge it today, but I don't know how critical it would be for your PR.

**Comment by adamrher** [comment]
Since these subroutines are called from the ```subcol_gen_SILHS``` subroutine, and I believe this is called after CLUBB is called. Which means (I think) that ```subcol_gen_SILHS``` is pulling rcm from the pbuf, which has already been set to rcm produced by the pdf closure in the CLUBB call. This rcm SILHS uses should not be equal to CLDLIQ, it should be that predicted by the pdf closure.

**Comment by bstephens82** [comment]
Ok sounds good.  When the external is updated again, rcm will not even need to be passed into setup_pdf_parameters or generate_silhs_sample, since those subroutines already have the information they need (ie `pdf_params`) to construct rcm internally.

**Comment by adamrher** [comment]
Oh I think I misunderstood your comment. You're saying that you coded up the externals to not pull rcm from the pbuf, but to grab it from ```pdf_params```? Is that the UWM repo or the actual CLUBB externals pointed to in Externals_CAM.cfg?

**Comment by bstephens82** [comment]
I merged those changes into the UWM repo.

**Comment by adamrher** [comment]
I am looking to close this issue with PR https://github.com/ESCOMP/CAM/pull/598, and so I'm dotting my i's and crossing my t's.

The following are pbuf variables in which the original PR https://github.com/ESCOMP/CAM/pull/545 wanted to change to global scope, in order to move the pdf closure to the post position. That is, these are variables that the pdf closure determines, and so moving the pdf closure to the post position means we may need to retain these pdf closure variables from time-step to time-step in order to advance the prognostic moments. I will annotate below where these variables are used, before the call to the pdf closure in the post position.

WP2THVP - intent(in) to advance_wp2_wp3
RTPTHVP - intent(in) to advance_xm_wpxp
THLPTHVP - intent(in) to advance_xm_wpxp

The three moments containing thv are needed to advance the xm, wp2 and wp3. I think that storing these in the pbuf in global scope is a practical solution. They should be transported by the dycore, but I don't know that this is justification to add 3 tracers to the dycore.

CLOUD_FRAC
- intent(in) to #ifdef GFDL, advance_sclrm_Nd_diffusion_OG
- intent(in) for update_xp2_mc, which is only invoked if l_morr_xp2_mc = .true.
- intent(in) used to adjust C2 is l_C2_cloud_frac=T

It's not clear that either of these three are invoked in the current default CAM. If they are, then we will need to initialize it with a pbuf variable. The question is whether to initialize it w/ ALST (CAM's stratiform cloud fraction) or CLOUD_FRAC (CLUBB's cloud fraction). They may be identical.

ISS_FRAC
- intent(in) to diagnose_Lscale_from_tau
- intent(in) to calc_stability_correction
- intent(in) to compute_Cx_Fnc_Richardson
- intent(in) to advance_xm_wpxp

I really don't know much about this variable. I will defer to others, but my instinct is to just set this to global scope and initialize it to the pbuf value.

RCM
- intent(in) to calculate_thvm (from thlm)
- intent(in) to diagnose_Lscale_from_tau
- intent(in) to stat_update_var  - this looks fine though as long as rcm is initialized to CLDLIQ
- intent(in) to calc_stability_correction
- intent(in) to compute_Cx_Fnc_Richardson
- intent(in) to advance_xm_wpxp
- intent(inout) to clip_rcm

We've already discussed/tested initializing RCM with CLDLIQ, instead of initializing RCM to it's value from the prior time-step. I think it makes more sense to do this, because then RCM is consistent with our definition of RTM (=Q+CLDLIQ). This is necessary for calculate_thvm to give the correct thv.

@bstephens82 @vlarson @huebleruwm

**Comment by vlarson** [comment]
With the exception of rcm, my vote is to store all the variables below in pbuf (I think with a global scope, I'm not sure what the implications of that is).  I think that letting the dycore transport CLUBB's higher-order moments is not worth the expense.

> WP2THVP - intent(in) to advance_wp2_wp3 RTPTHVP - intent(in) to advance_xm_wpxp THLPTHVP - intent(in) to 
advance_xm_wpxp
> 
> The three moments containing thv are needed to advance the xm, xpwp, wp2 and wp3. I think that storing these in the pbuf in global scope is a practical solution. They should be transported by the dycore, but my feeling is that this is not justification to add 3 tracers to the dycore (unless shown this is necessary).

Sounds good.
 
> CLOUD_FRAC
> 
> * intent(in) to #ifdef GFDL, advance_sclrm_Nd_diffusion_OG
> * intent(in) for update_xp2_mc, which is only invoked if l_morr_xp2_mc = .true.
> * intent(in) used to adjust C2 is l_C2_cloud_frac=T
> 
> It's not clear that any of these three are invoked in the current default CAM. 

I doubt they are turned on by default, but the update_xp2_mc subroutine is worth maintaining as an option.  In the past, it helped improve the diurnal cycle of precipitation.

> If they are, then we will need to initialize it with a pbuf variable. The question is whether to initialize it w/ ALST (CAM's stratiform cloud fraction) or CLOUD_FRAC (CLUBB's cloud fraction). They may be identical (they are at the clubb_intr level; is ALST overwritten in mg2?)

I would use cloud_frac.  I don't know whether ALST includes ice, but if it does, it would be inconsistent with CLUBB's liquid-only PDF.

> ISS_FRAC
> 
> * intent(in) to diagnose_Lscale_from_tau
> * intent(in) to calc_stability_correction
> * intent(in) to compute_Cx_Fnc_Richardson
> * intent(in) to advance_xm_wpxp
> 
> I really don't know much about this variable. I will defer to others, but my instinct is to just set this to global scope and initialize it to the pbuf value.

Sounds good.  Nota bene: ice_supersat_frac is like cloud_frac, but with respect to ice saturation rather than liquid saturation.  CLUBB uses it to estimate the effects of static stability on turbulent fluxes.

> RCM
> 
> * intent(in) to calculate_thvm (from thlm)
> * intent(in) to diagnose_Lscale_from_tau
> * intent(in) to stat_update_var  - this looks fine though as long as rcm is initialized to CLDLIQ
> * intent(in) to calc_stability_correction
> * intent(in) to compute_Cx_Fnc_Richardson
> * intent(in) to advance_xm_wpxp
> * intent(inout) to clip_rcm
> 
> We've already discussed/tested initializing RCM with CLDLIQ, instead of initializing RCM to it's value from the prior time-step. I think it makes more sense to do this, because then RCM is consistent with our definition of RTM (=Q+CLDLIQ). This is necessary for calculate_thvm to give the correct thv.

rcm is exceptional because, unlike the variables above, liquid is advected by the dycore.

**Comment by adamrher** [comment]
PR https://github.com/ESCOMP/CAM/pull/598#event-6955605619 closed this issue.
