### ISSUE TITLE
Fix path for buildlib/buildnml

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#608]
### What happened?

Accroding to Erik Kluzek:

Change path for components buildlib/buildnml from cime/scripts/Tools to cime/CIME/Tools. We had some discussion over email. The previous path no longer exists, so it's at least confusing to set a path that no longer exists. But, it also might break in the future if it's not corrected. And having the right path also allows you to run these scripts outside on their own, which is sometimes useful.

### What are the steps to reproduce the bug?

N/A

### What CAM tag were you using?

cam6_3_060

### What machine were you running CAM on?

Other (please explain below)

### What compiler were you using?

Other (please specify below)

### Will you be addressing this bug yourself?

No

**Comment by nusbaume** [comment]
It looks like the only change still needed in the `cam_development` branch is in the `cime_config/buildnml` script, where line 13:

`_LIBDIR = os.path.join(_CIMEROOT, "scripts", "Tools")`

Should be replaced with:

`_LIBDIR = os.path.join(_CIMEROOT, "CIME", "Tools")`
