### ISSUE TITLE
SE grid updates and sponge-layer bug fix

### ISSUE THREAD

**Issue by adamrher** [ESCOMP/CAM#62]
This issue is to be associated with a PR for grid updates in CAM-SE from my vr-arctic branch off of tag cam6_2_010 (cc @brian-eaton). Two additional grids w/ refinement over the arctic have been implemented. The arctic grids (pdf's of grids attached) are eventually to become part of a cesm2 release of CAM-SE, along with CONUS, and are also a part of the planned [SIMAv0 Polar release](https://wiki.ucar.edu/display/SIMA/System+for+Integrated+Modeling+of+the+Atmosphere). The arctic grids were developed for the CESM community (cross-WG) project "Development of a CESM Arctic Prediction System (CAPS)." These new grids will require a CIME PR, which @fischer-ncar is in the process of doing.

1. Added two new variable resolution grids w/ refinement in the ARCTIC.
- Only needed to modify bld/namelist_files/namelist_defaults.xml
- bld/config_files/horiz_grids.xml did not have to be modified since I branch off the latest tag( [cam6_2_010 tag](https://github.com/ESCOMP/CAM/pull/59)).
  
2. Updated bnd_topo, ncdata files and dycore time stepping for the CONUS grid.
- new topo file using vr topo software recently updated by @PeterHjortLauritzen and I.
- set dycore time-stepping to be consistent with the corresponding CIME PR, in which the physics time-step  is reduced to 225 s (i.e., ATM_NCPL=384), after consulting w/ @PeterHjortLauritzen.

3. Added missing drydep_srf_files for ne30pg2 and ne120pg2 grids.
- These files were created to parallel the CIME PR, which is not only to implement the arctic grids, but also to allow for ne30pg2 and ne120pg2 to be ran in an F compset. These grids are being considered as part of AMPs dycore intercomparison to determine the next default dycore in CAM.

4. Fixed bug in time-stepping for sponge-layer hyperviscosity
- big fix from @PeterHjortLauritzen

All four of these changes have been tested in an F2000climo compset, described in the ChangeLog. This is my first PR, so please let me know if I am overlooking something here.

[squadgen-lowerconn-arctic-2x-13043-grid.pdf](https://github.com/ESCOMP/CAM/files/4074175/squadgen-lowerconn-arctic-2x-13043-grid.pdf)
[squadgen-lowerconn-arctic-3x-16931-grid.pdf](https://github.com/ESCOMP/CAM/files/4074176/squadgen-lowerconn-arctic-3x-16931-grid.pdf)

**Comment by adamrher** [comment]
the corresponding CIME issue is here https://github.com/ESMCI/cime/issues/3385

**Comment by adamrher** [comment]
@eaton, we had a mtg on friday about what is required by CTSM to support new grids ([short summary here](https://github.com/ESCOMP/CTSM/wiki/Meeting-Notes-2020-Software)). It became clear to me that CAM/CTSM will eventually need to update their input datasets for all grids used in cesm (e.g., if there are update's to the TopoCESM2 software and/or updates to the pft definitions in fsurdat). But since the tools to generate these datasets require the SCRIP grid file, whomever is tasked with updating the input datasets for the new grids will not be able to find the SCRIP grid file b/c it is not in the cesm-inputdata repo. @ekluzek and I agree that they should reside in the cesm-inputdata repo, and after looking through: /glade/p/cesmdata/cseg/inputdata/atm/cam/coords , it appears that many SCRIP files (not all) are up to date with the grids supported in CAM up until this point (I don't see ne120np4 or ne120pg3 grids). Should I have included pushing the scrip files for the new grids into this coords directory in https://github.com/ESCOMP/CAM/issues/62?

Erik said he is perfectly fine with fetching the scrip files from this atm/cam/coords directly, when the time comes. He also maintains a repo for clm here: /glade/p/cesmdata/cseg/inputdata/lnd/clm2/mappingdata/grids. It appears up to date with all grids officially supported in CTSM at this point.

Regardless of what we decide to do, I could consolidate them into a folder and then point them to  you @brian-eaton if you'd like? This would include ARCTIC, ARCTICGRIS grids ... ne30pg2 and ne120pg2 grids. Note that the two (2) pg2 grids are not going to be supported in CTSM for the cesm2.2 release.

I think when we fully transition to nuopc, the ESMF mesh file will be used directly in config_grids.xml ... and so the tools-for-making-the-datasets could just point to that file instead of the SCRIP grid file.

**Comment by gold2718** [comment]
@adamrher, I agree with your statements but want to add a couple of fine points.

1. While config_grids.xml will be around for a while, it is the intention to provide an alternative path  for specifying new grids (but, when the land model is involved, this obviously involves a bunch of new infrastructure).
2. The ESMF mesh files are already in use via the new ionosphere interface which will be coming soon to cam_development. It is used to create an ESMF mesh for the physics decomposition which I hope can also be useful for other experiments where we may want to break the column-only nature of our physics suites.

**Comment by adamrher** [comment]
Brian has copied the new scrip files into /glade/p/cesmdata/cseg/inputdata/atm/cam/coords/

The PR https://github.com/ESCOMP/CAM/pull/63 has been completed, so I'm closing this issue.
