### ISSUE TITLE
part of cam_cesm2_2_rel_04: Bug in spectral-element advection

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [ESCOMP/CAM#633]
### Issue Type

Other (please describe below)

### Issue Description

Bug in spectral-element advection. See details here 

https://github.com/NCAR/amwg_dev/issues/151

Source code modifications to fix bug:

In src/dynamics/se/dycore/prim_advance_mod.F90. replace

               elem(ie)%derived%dpdiss_ave(i,j,k)=elem(ie)%derived%dpdiss_ave(i,j,k)+&
                     rhypervis_subcycle*eta_ave_w*(elem(ie)%state%dp3d(i,j,k,nt)

with

                elem(ie)%derived%dpdiss_ave(i,j,k)=elem(ie)%derived%dpdiss_ave(i,j,k)+&
                     rhypervis_subcycle*eta_ave_w*(elem(ie)%state%dp3d(i,j,k,nt)-elem(ie)%derived%dp_ref(i,j,k))

Source code modification here:

/glade/u/home/pel/src/for-cecille/qdp_ref_bufix/prim_advance_mod.F90

### Will this change answers?

All SE tests  with topography should show significant differences  (round-off or no differences for non-topo  tests such as FKESSLER and QPC). Tests with all other dynamical cores should not show differences.

### Will you be implementing this yourself?

Yes

**Comment by nusbaume** [comment]
@jiang-zhu just pinging you in case you want to try the bug fix above in one of the water isotope simulations.

**Comment by gold2718** [comment]
Managed to fool the auto-close script (added CESM2.2 after cam_development was merged but did not make a new cam_development tag).
