### ISSUE TITLE
CAM Thermo answer-changing bug fixes and code clean-up

### ISSUE THREAD

**Issue by nusbaume** [ESCOMP/CAM#635]
### What happened?

There were two change requests made for the CAM Thermo PR (#615) that would fix a bug and help clean-up the code, but which would likely result in answer changes.  Thus it would be great to apply these changes into a PR that is already known to be answer-changing.  The two requested changes are:

1.  In the subroutine `get_Richardson_number` in `physconst.F90`, the loop:

     `do k=nlev-1,2,-1`

      Should be replaced with:

      `do k=nlev,2,-1`

      Otherwise the Richardson number will be undefined at nlev.

2.  In the subroutine `get_molecular_diff_coef` in `physconst.F90`, there are multiple locations where variables are being multiplied by `1.e-7_r8` and `1.e-5_r8`, which are actually part of the variable values themselves.  Thus it would be better if these values were multiplied during the original initialization of these variables during model initialization, as opposed to every time step like is being done here.  Note that this will likely involve modification both of `thermodynamic_active_species_kv` and `thermodynamic_active_species_kc`, as well as of the `kv#` and `kc#` parameters.
 

### What are the steps to reproduce the bug?

Not sure, but if you just look at the source code you can hopefully spot it.

### What CAM tag were you using?

cam6_3_071

### What machine were you running CAM on?

Other (please explain below)

### What compiler were you using?

Other (please specify below)

### Will you be addressing this bug yourself?

No

### Extra info

I didn't actually run the model to examine these bugs, I just found them during  code review.

**Comment by cacraigucar** [comment]
@nusbaume   - I will make the following changes and want to confirm this is the sum total of the changes:

real(r8), parameter :: &
   kv1 = 4.03_r8 * 1.e-7_r8, &
   kv2 = 3.42_r8 * 1.e-7_r8, &
   kv3 = 3.9_r8 * 1.e-7_r8,  &
   kv4 = 0.69_r8 * 1.e-7_r8, &
   kc1 = 56._r8 * 1.e-5_r8,  &
   kc2 = 56._r8 * 1.e-5_r8,  &
   kc3 = 75.9_r8 * 1.e-5_r8, &
   kc4 = 0.69_r8 * 1.e-5_r8

I will also change the two lines to be:
         thermodynamic_active_species_kv(icnst)  = 3.42_r8 *1.e-7_r8
          thermodynamic_active_species_kc(icnst)  = 56._r8 *1.e-5_r8

**Comment by nusbaume** [comment]
@cacraigucar I think you'll also want to update `thermodynamic_active_species_XX` for the `O` and `O2` cases as well, but otherwise that looks good to me!

**Comment by cacraigucar** [comment]
@nusbaume - Thanks.  I missed those and have now added them.

**Comment by nusbaume** [comment]
@cacraigucar Also, after looking through the code and manuscript again it appears that `kv4` and `kc4` should NOT have the `1.e-7_r8` and `1.e-5_r8` additions, as they are used as exponents as opposed to multiplication factors.  Apologies for the confusion!
