### ISSUE TITLE
part of cam6_2_014: Remove unused "use" statement

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#64]
After testing of cam_snapshot was completed, an unused use statement was discovered and it should be removed.

src/physics/cam/physics_types.F90:  "use cam_history,  only: outfld'  is not used and should be removed.

**Comment by fvitt** [comment]
There are several things that should be cleaned up in physics_types:

Warning: /home/fvitt/camdev/waccm_efield/src/physics/cam/physics_types.F90, line 199: Unused dummy variable PSETCOLS
Warning: /home/fvitt/camdev/waccm_efield/src/physics/cam/physics_types.F90, line 199: Unused local variable STATE
Warning: /home/fvitt/camdev/waccm_efield/src/physics/cam/physics_types.F90, line 199: Unused local variable TEND
Warning: /home/fvitt/camdev/waccm_efield/src/physics/cam/physics_types.F90, line 481: BEGCHUNK explicitly imported into PHYSICS_UPDATE but not used
Warning: /home/fvitt/camdev/waccm_efield/src/physics/cam/physics_types.F90, line 481: CNST_MW explicitly imported into PHYSICS_UPDATE but not used
Warning: /home/fvitt/camdev/waccm_efield/src/physics/cam/physics_types.F90, line 481: ENDCHUNK explicitly imported into PHYSICS_UPDATE but not used
Warning: /home/fvitt/camdev/waccm_efield/src/physics/cam/physics_types.F90, line 481: Unused local variable I
Warning: /home/fvitt/camdev/waccm_efield/src/physics/cam/physics_types.F90, line 481: OUTFLD explicitly imported into PHYSICS_UPDATE but not used
Warning: /home/fvitt/camdev/waccm_efield/src/physics/cam/physics_types.F90, line 671: PI explicitly imported into PHYSICS_STATE_CHECK but not used
Warning: /home/fvitt/camdev/waccm_efield/src/physics/cam/physics_types.F90, line 671: SHR_ASSERT explicitly imported into PHYSICS_STATE_CHECK but not used
Warning: /home/fvitt/camdev/waccm_efield/src/physics/cam/physics_types.F90, line 671: SHR_INFNAN_INF_TYPE explicitly imported into PHYSICS_STATE_CHECK but not used
Warning: /home/fvitt/camdev/waccm_efield/src/physics/cam/physics_types.F90, line 975: Unused local variable M
Warning: /home/fvitt/camdev/waccm_efield/src/physics/cam/physics_types.F90, line 1271: BEGCHUNK explicitly imported into PHYSICS_DME_ADJUST but not used
Warning: /home/fvitt/camdev/waccm_efield/src/physics/cam/physics_types.F90, line 1271: CNST_GET_TYPE_BYIND explicitly imported into PHYSICS_DME_ADJUST but not used
Warning: /home/fvitt/camdev/waccm_efield/src/physics/cam/physics_types.F90, line 1271: ENDCHUNK explicitly imported into PHYSICS_DME_ADJUST but not used
Warning: /home/fvitt/camdev/waccm_efield/src/physics/cam/physics_types.F90, line 1271: Unused local variable I
Warning: /home/fvitt/camdev/waccm_efield/src/physics/cam/physics_types.F90, line 1437: Unused local variable I
Warning: /home/fvitt/camdev/waccm_efield/src/physics/cam/physics_types.F90, line 1437: PLEV explicitly imported into SET_STATE_PDRY but not used
Warning: /home/fvitt/camdev/waccm_efield/src/physics/cam/physics_types.F90, line 1437: PLEVP explicitly imported into SET_STATE_PDRY but not used
Warning: /home/fvitt/camdev/waccm_efield/src/physics/cam/physics_types.F90, line 1645: Unused local variable I
Warning: /home/fvitt/camdev/waccm_efield/src/physics/cam/physics_types.F90, line 1832: Unused local variable PSETCOLS
Warning: /home/fvitt/camdev/waccm_efield/src/physics/cam/physics_types.F90, line 1943: PSUBCOLS explicitly imported into PHYSICS_TYPES but not used

**Comment by cacraigucar** [comment]
We will address all of these in a future tag
