### ISSUE TITLE
Bug - use_hetfrz_classnuc off not working

### ISSUE THREAD

**Issue by cmcclus** [ESCOMP/CAM#641]
### What happened?

F200climo run  with cam_dev failed (error below) when 

> use_hetfrz_classnuc = .false.

(added to user_nl_cam)

Error from /glade/scratch/cmcclus/cam6_3063_F2000climo_1deg_CNToff/run/cesm.log.*
> 342: ERROR: Invalid value produced in physics_state by package clubb.
> 342:*** longjmp causes uninitialized stack frame ***: /glade/scratch/cmcclus/cam6_3063_F2000climo_1deg_CNToff/bld/cesm.exe terminated
> 238: ERROR: shr_assert_in_domain: state%t has invalid value   -889.837813858155     
> 238:  at location:           10          20
> 238: Expected value to be greater than   0.000000000000000E+000
> 238: ERROR: Invalid value produced in physics_state by package clubb.

### What are the steps to reproduce the bug?

1. ./create_newcase --case /CASEDIR/ -res f09_f09_mg17 --compset f2000climo --project PXXXXXX
2. cd /CASEDIR/
3. edit user_nl_cam: add "use_hetfrz_classnuc = .false."
4. ./case.setup
5. ./xmlchange CAM_CONFIG_OPTS = '-phys cam_dev -nlev 32'
6. ./case.build
7. ./case.submit

### What CAM tag were you using?

cam6_3_063

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

/glade/work/cmcclus/cam_dev/cases/cam6_3063_F2000climo_1deg_CNToff

### Will you be addressing this bug yourself?

No

### Extra info

first issue I'm submitting - feedback welcome!

**Comment by cmcclus** [comment]
@nusbaume

**Comment by nusbaume** [comment]
Just adding a note here that this particular bug is apparently holding up @cmcclus's work related to CAM7 development, and so is fairly high priority.

**Comment by cmcclus** [comment]
Thanks, @nusbaume. Yes, I need to be able to run without hetfrz_classnuc in order to test the other ice nucleation schemes I am testing with @andrewgettelman and also using in my research.

**Comment by adamrher** [comment]
can we verify whether this is unique to cam_dev, or does it persist with -phys cam6?

also, I know there's a cam interface level hetfrz, and then an option to turn on hetfrz in the pumas externals. I'm assuming we are trying to invoke the cam interface level one, in ice_nucleate_cam?

**Comment by cmcclus** [comment]
Thanks @adamrher - great idea. This issue/bug is unique to cam_dev. I just submitted the same case -phys cam6, hetfrz_classnuc .false. and it's running fine. 

Not sure regarding your second question. You are correct that hetfrz false should turn on Meyers 92 and Bigg 53, so perhaps the issue is on the cam interface level, like you suggest.

**Comment by adamrher** [comment]
ok. here's another test. Go into nucleate_ice_cam.F90, and comment out all of the logic that gets invoked by:
```
   if (cam_physpkg_is("cam_dev")) then
```

Such that, as far as that module concerned, cam_dev if off. To explain, invoking cam_dev does two things. It triggers if statements in nucleate_ice_cam.F90. The if statements will turn off ```add_prexisting_ice```, but it may do more. Invoking cam_dev also points to the pumas directory, instead of the pumas-frozen directory. It's possible that these if statements are inconsistent with setting hetfrz to false.

**Comment by andrewgettelman** [comment]
A few notes:

1. hetfrz_classnuc is used in nucleate_ice to turn off meyers (false will leave it on). 

3. Still trying to sort out how this works with immersion freezing: it's split now between having immersion freezing in the aerosol activation for CNT and present in the CAM code.... I think my intent with PUMAS is that hetfrz_classnuc = true but we don't use the immersion freezing part from CNT. If it is false, then there is some zero values set for nnuccc. 

Not sure why it would cause the code to fail on cam_dev. 

Haven't had time to dive all the way into these 2 code threads between ice nucleation and PUMAS to sort it out.

**Comment by andrewgettelman** [comment]
FYI: SCAM works with an ARM97 case, cam_dev and use_hetfrz_classnuc = .false.

So this is not an issue everywhere. Is it first timestep stuff or into the run?

**Comment by cmcclus** [comment]
> FYI: SCAM works with an ARM97 case, cam_dev and use_hetfrz_classnuc = .false.
> 
> So this is not an issue everywhere. Is it first timestep stuff or into the run?

Yes, fails on the first timestep. The SCAM run is with tag cam6_3_063?

**Comment by andrewgettelman** [comment]
No. It was cam6_3_057. I can update it. Might be logic that came in with the immersion freezing change. Let me check it out. I did not see it.

**Comment by andrewgettelman** [comment]
Okay, confirming this in SCAM. 

cam6_3_072 is failing with use_hetfrz_classnuc = false and cam_dev. It does not fail without cam_dev and hetfrz_classnuc = false, and it does not fail with cam_dev and hetfrz_classnuc = True. 

Not sure why. I'm also not sure what Cheryl did: I think changes did not get propagated to cam_dev. Will have to see if I can sort it out.

**Comment by adamrher** [comment]
not sure if you missed my suggestion above, but I think incrementally reverting nucleate_ice_cam back to non-cam_dev is a useful exercise.

Also since this is happening at nstep=0, then maybe try running w/ DEBUG=T for my info?

**Comment by cacraigucar** [comment]
> Okay, confirming this in SCAM.
> 
> cam6_3_072 is failing with use_hetfrz_classnuc = false and cam_dev. It does not fail without cam_dev and hetfrz_classnuc = false, and it does not fail with cam_dev and hetfrz_classnuc = True.
> 
> Not sure why. I'm also not sure what Cheryl did: I think changes did not get propagated to cam_dev. Will have to see if I can sort it out.

@andrewgettelman  - What tag are we talking about that I might have made an error in?

**Comment by andrewgettelman** [comment]
Sorry, should not have mentioned you Cheryl. It's probably a bug I put in there. Christina is identifying this as cam6_3_063 and that's when some PUMAS mods came in. I'm diving into the code now. Found one issue, will see if that solves it. Then I will take up Adam's suggestion and lookin nucleate_ice_cam. Not sure it's a simple reversion: but the changes are not that large....

**Comment by adamrher** [comment]
in nucleate_ice_cam, just comment out these code blocks, so it always goes to the "else" case.
```
if (cam_physpkg_is("cam_dev")) then
```

**Comment by andrewgettelman** [comment]
Okay. Think I found the issue. In micro_pumas_v1.F90 if use_hetfrz_classnuc = false then nnudep and mnudep are never set but they are applied to the process rates. I tried initializing them to zero at the top of the routine (where everything else is set) and that ran through to completion in SCAM. So maybe you can try that Christina. The modified code is on izumi: 

/project/amp/andrew/scam_pumas/mods/hetfrz_fix/micro_pumas_v1.F90

It's a 2 line change adding the initialization of these variables...

Likely my mistake.

**Comment by adamrher** [comment]
Andrew, this is besides the point but for my sanity. The only thing that use_hetfrz_classnuc does in nucleate_ice is:

```
   if (use_hetfrz_classnuc) nimey = 0._r8

   nuci=ni + nimey
```

where nimey is the meyer contribution to "deposition nucleation." You also pass the use_hetfrz_classnuc namelist into PUMAS as an argument. I just want to make sure there's not double-counting when this flag is turned on, since it seems the meyers ice nucleation is not performed in PUMAS, but in nucleate_ice. Can you clarify this for me?

**Comment by andrewgettelman** [comment]
Good question Adam, not simple.

The Classical Nucleation Theory (CNT: use_hetfrz_classnuc = True) calculates immersion, deposition and contact nucleation , which occur in the 'mixed phase' regime ( -40 > T > -5 ˚C). Before (CAM5), immersion freezing for cloud water and rain was done inside of PUMAS, as was contact freezing (on dust). Deposition was covered under the Meyers 1992 empirical formula. For historical reasons, it ended up being coded by Xiaohong Liu with 'nucleate_ice' which mostly just does homogeneous and heterogeneous freezing of pure ice ( T < -40 ˚C or so). 

If you look in PUMAS, there is no deposition nucleation without CNT (use_hetfrz_classnuc = False). That was I think the problem here. When it was modified to go back to using immersion freezing from Bigg and Meyers, deposition freezing was never initialized. I think that might be the error (which I found last night, and in SCAM that seemed to solve my crash). 

Hope that clarifies. May not, it's pretty murky down there.

**Comment by andrewgettelman** [comment]
@cmcclus, can you implement these changes in your experiment with use_hetfrz_classnuc = false and let me (us, github) know if that solves the problem?

diff /project/amp/andrew/tags/cam6_3_072/src/physics/pumas/micro_pumas_v1.F90 /project/amp/andrew/scam_pumas/mods/hetfrz_fix/micro_pumas_v1.F90

Thanks!

**Comment by gold2718** [comment]
> which occur in the 'mixed phase' regime ( -40 > T > -5 ˚C).

Is this supposed to be `-40 < T < -5 ˚C`?

**Comment by andrewgettelman** [comment]
Yes, Sorry. You know what I meant.....

**Comment by cmcclus** [comment]
Success! That fixed it, or at least it's running now. Thanks for the help!

**Comment by adamrher** [comment]
> If you look in PUMAS, there is no deposition nucleation without CNT (use_hetfrz_classnuc = False)

Right, but in nucleate_ice, there is nimey, and I think you're saying this is just for homogenous T < -40 C. So what you mean is there is no deposition nucleation without CNT in the heterogenous regime -40 < T < -5 C?

**Comment by andrewgettelman** [comment]
Comment from @adamrher which I don't see here:

> > If you look in PUMAS, there is no deposition nucleation without CNT (use_hetfrz_classnuc = False)
> 
> Right, but in nucleate_ice, there is nimey, and I think you're saying this is just for homogenous T < -40 C. So what you mean is there is no deposition nucleation without CNT in the heterogenous regime -40 < T < -5 C?
> 

Sorry, nimey is for the mixed phase regime -40 < T < -5 C. The homo and het in that routine is for the pure ice phase.

**Comment by andrewgettelman** [comment]
It looks like my solution works, so I'll try to get time to do a PUMAS PR and get this checked in. Then we can close this issue.

**Comment by andrewgettelman** [comment]
The fix is within PUMAS, it will be fixed there and reported when it is done and ready to pull into CAM.
