### ISSUE TITLE
The interpolate_output namelist flag results in bad output values

### ISSUE THREAD

**Issue by nusbaume** [ESCOMP/CAM#644]
### What happened?

As reported by @brianpm , a recent CAM simulation with the `ne30pg3_ne30pg3_mg17` and `ne30_g17` grids and the `interpolate_output` namelist flag(s) set to `.true.` resulted in history files with bad/missing values (history variables had O(10^-38) values).  

It should be noted that the non-interpolated history output was fine, so this is likely an issue with the interpolation itself.

### What are the steps to reproduce the bug?

Not entirely sure yet, but based on the example case below it appears that running an F2000climo compset for two days with one of the grids above and the following `user_nl_cam` settings:

```
nhtfrq = 0,-1,-1
mfilt = 1,24,24
ndens = 2,2,2
empty_htapes=.false.
interpolate_output=.true.,.true.,.true.
interpolate_nlat=192,192,192
interpolate_nlon=288,288,288

FINCL2 = 'U','V','T','Q','SOLIN','FSNT','FLUT','PRECC','PRECT'
FINCL3 = 'U','V','T','Q','SOLIN','FSNT','FLUT','PRECC','PRECT'

iradsw = -1
iradlw = -1
use_rad_dt_cosz = .false.
spectralflux = .false.
```

results in the bad history file output.  I will add a comment to this issue if I can find an even simpler setup which produces the same error.

### What CAM tag were you using?

Not sure, but will try with the latest tag and report the results here.

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

/glade/work/brianpm/my_cases/test_cases/vanilla.f2000climo.ne30pg3.testinterp02

### Will you be addressing this bug yourself?

Yes

**Comment by fvitt** [comment]
I also am experiencing this issue with the ne5pg3 grid in tag cam6_3_074.

**Comment by nusbaume** [comment]
@fvitt can you point me to your failing case?  I have tried both a  ne30 F2000climo run and a ne5pg3 aquaplanet run with cam6_3_074 and both had the output interpolation work correctly.

**Comment by fvitt** [comment]
> @fvitt can you point me to your failing case? I have tried both a ne30 F2000climo run and a ne5pg3 aquaplanet run with cam6_3_074 and both had the output interpolation work correctly.

It was on an ACOM cluster using gnu compiler.  I have not be able reproduce the problem on cheyenne.

**Comment by nusbaume** [comment]
Thanks @fvitt!  I was able to reproduce the error on Izumi with GNU, so at least I now have a test case to work with.

**Comment by andrewgettelman** [comment]
May also be related to #564 errors in AODVIS output with SE. So check any solutions with AODVIS please, and then this could also close that issue.

**Comment by nusbaume** [comment]
I have now been able to reproduce the issue on Cheyenne by switching the `PIO_TYPENAME` from `pnetcdf` to `netcdf`.  For some reason the RRTMGP CAM branch was defaulting to `netcdf` (which is how I found the issue).  It also might explain why Izumi fails as well, because it also defaults to `netcdf`.

The next step will be to see why the PIO type matters for this particular interpolation calculation.

@brianpm  if you are still having trouble getting `interpolate_output` to work on your branch, then can you try the following before you submit a run:

```
./xmlchange PIO_TYPENAME=pnetcdf
```

and see if it fixes the issue for you?  If so then it can at least be a temporary solution while I try and trace down the root cause.  Thanks!

**Comment by brianpm** [comment]
Thanks, Jesse! I haven't been able to follow up yet, but I will try to get back to this next week and let you know. I'm actually rather heartened that it might be a real issue and not just me breaking things!

**Comment by andrewgettelman** [comment]
I have been using pnetcdf and that doesn't totally fix it. What I see now in my current simulations (e.g.: /glade/scratch/andrew/archive/cntlSE_cam6345_mg3/atm/hist) is that the north pole (Lat ~90) has one or two of the first latitudes with bad values for some fields, mostly fields that are NANs (i.e., related to SW radiation code in the winter hemisphere): AODVIS, (all the AOD* fields), and the *VISTAU optical depths. Strangely BURDENSO4 is also an issue. 

So now to me (cam6345) this looks like just an interpolation at the pole issue with interpolate_output in these simulations.  Hope that helps.

**Comment by gold2718** [comment]
> I have now been able to reproduce the issue on Cheyenne by switching the `PIO_TYPENAME` from `pnetcdf` to `netcdf`

and

> I have been using pnetcdf and that doesn't totally fix it.

We need to separate out issues with outputting to disk (possible netcdf issue) from possible SE interpolation issues (e.g., problems Andrew is seeing). This might require some sanity checks on interpolated data just before writing to disk.

**Comment by brianpm** [comment]
@nusbaume -- Looks like when I change to pnetcdf, the interpolated files have reasonable values:

```
./xmlchange PIO_TYPENAME=pnetcdf
```

This is with the same RRTMGP branch that I was using before, so no other changes were involved.

**Comment by nusbaume** [comment]
Thanks @brianpm!  As an FYI, it looks like you can also set `ndens` to one and it will work properly as well (which is how this error slipped through our regression tests).

**Comment by gold2718** [comment]
> set `ndens` to one

Aha! This is almost certainly the problem. The `write_interpolated` calls in cam_history.F90 (lines 4785 and 4797) have a hard-coded `PIO_DOUBLE` whereas the variable is defined depending on the value of `tape(t)%hlist(f)%hwrt_prec`.
This needs to be fixed to use `PIO_DOUBLE` when `tape(t)%hlist(f)%hwrt_prec == 8` and `PIO_REAL` otherwise. You can copy the code block in `h_define`:
```
      if ((tape(t)%hlist(f)%hwrt_prec == 8) .or. restart) then
        ncreal = pio_double
      else
        ncreal = pio_real
      end if
```
where `ncreal` is an integer and use `ncreal` instead of `PIO_DOUBLE`.

This is another example of code that worked as expected with PIO1 but not in PIO2.

**Comment by nusbaume** [comment]
Thanks for the fix @gold2718!  It looks like that bug fix plus converting the field to a four byte real (if PIO is set to `pio_real`)   before sending it to PIO fixes the problem.  Sadly it doesn't look it fixes the AODVIS issue, so I'll continue to debug that and add any updates on its own page (just FYI for anyone who has been following this).
