### ISSUE TITLE
Crash from CLM 4-5 mos into FHIST SE cam_dev test w/ debug=T

### ISSUE THREAD

**Issue by bstephens82** [ESCOMP/CAM#646]
### What happened?

When running an FHIST SE case with cam_dev and with the debugger on, I find that with no other modications to the model, I get a crash about 4-5 months into the run. It comes from the land model at
~~~
CAM/components/clm/src/biogeophys/PhotosynthesisMod.F90:5151
~~~

### What are the steps to reproduce the bug?

Run FHIST SE with cam_dev with DEBUG=TRUE with no other modifications (I put interpolation into user_nl_cam) for 5 months.

### What CAM tag were you using?

067 and then 074 (latest)

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

/glade/u/home/stepheba/CAM/cime/scripts/debug_test074

### Will you be addressing this bug yourself?

No

### Extra info

Run directory is /glade/scratch/stepheba/debug_test074/run.

**Comment by adamrher** [comment]
@bstephens82 Are you running debug for 4-5 months straight? That'd take all day, no? Or did you restart close to the break point with debug=T? Have you confirmed this error is reproducible?

**Comment by swrneale** [comment]
Is this debugger sensitive? i.e., if you turn debugger off then does it make it past 5 months?

**Comment by bstephens82** [comment]
@adamrher yes I ran it through with the debugger for something Julio and I were working on. It took maybe 6-8 hours to make it to the crash. 

@swrneale if you run it without the debugger it will continue without showing this error.

**Comment by swrneale** [comment]
Unless we have a test that is this long (@cacraigucar do we have any cam-dev tests that are +5mon long?) then all our simulations might croak after 5 months with debugger on, no?

**Comment by cacraigucar** [comment]
As a first step, I ran the only test which we routinely run for longer than a month, an F2000climo compset with the f10_f10_mg37 grid which is run for 13 months (but with debug=false).  I turned on debug, and it successfully ran for the full 13 months.  As a next step, I will convert this test from an F2000climo to an F2000dev compset, but keep the f10_f10_mg37 grid and see what happens.

**Comment by adamrher** [comment]
I see you're way down the clm rabbit hole ... you gotta do what you gotta do!

**Comment by bstephens82** [comment]
I investigated a bit further based on advice from some land model experts.  Here is what Daniel Kennedy told me:
"x(root)" in this case is root water potential, which is in units of pressure (mmH2O)

>We're trying to find the correct x(root), such that the flow from soil->roots is equivalent to the plant's transpiration (T). 
from a simplified perspective:
T is proportional to ( smp - x(root) ) 
where smp is the soil water potential

>T is meant to be positive
smp is meant to be negative
such that x(root) ought to also be negative

>So there are at least three ways that x(root) could become positive:
>1) transpiration is negative (you can inspect qflx_sun, qflx_sha)
>2) numerical issue, newton's method solver for x is jumping across 0 (calcstress routine)
>3) the soil potential is positive

As far as I can tell, the qflx variables are always either zero or positive, and I did not find that the soil potential `smp` was ever positive in the timesteps leading up to the crash.  So this may indicate a numerical issue.  Daniel had some suggestions to look into this possibility: 

>The newton solver is within the calcstress routine
https://github.com/ESCOMP/CTSM/blob/97f34c975fdaed5e840a1184742efb06b3b3c29a/src/biogeophys/PhotosynthesisMod.F90#L4589

>To learn more you could print qflx_sun, qflx_sha, x, and dx after that if-block, printing when x(root) is positive.

>To soften up the numerics, you could edit the plc and d1plc functions
https://github.com/ESCOMP/CTSM/blob/97f34c975fdaed5e840a1184742efb06b3b3c29a/src/biogeophys/PhotosynthesisMod.F90#L5151
https://github.com/ESCOMP/CTSM/blob/97f34c975fdaed5e840a1184742efb06b3b3c29a/src/biogeophys/PhotosynthesisMod.F90#L5183

>you could add
if ( x > 0._r8) x = 0._r8
before the calculation of plc 

>for d1plc you would want:
if ( x >= 0._r8) then
  d1plc = 0._r8
else
  d1plc = ...
endif

>This is reasonable, because if we extended those two functions into the positive domain, we would expect plc=1 and d1plc=0.
The hope would be that the solver will find its way back to negative values of x.

I tried printing out these variables after the `if` block in question:
~~~
771: after if block x =   -339.542825819600       -338.535397132883
771:  -338.535397132883        161.464423196482
771: after if block dx =   0.000000000000000E+000  -51.8462930160458
771:  -50.8388643293292        439.160956000036
771: after if block qflx_sun =   1.003969036540721E-009
771: after if block qflx_sha =   1.986439153963049E-011
771: params_inst%psi50 =   -390000.000000000
771: params_inst%ck =    3.95000000000000
771: x =   -339.542825819600
771: params_inst%psi50 =   -390000.000000000
771: params_inst%ck =    3.95000000000000
771: x =   -338.535397132883
771: params_inst%psi50 =   -390000.000000000
771: params_inst%ck =    3.95000000000000
771: x =   -338.535397132883
771: params_inst%psi50 =   -390000.000000000
771: params_inst%ck =    3.95000000000000
771: x =    161.464423196482
771:MPT ERROR: Rank 771(g:771) received signal SIGFPE(8).
~~~

It's easy to see the positive value of `x` ~161, although it's not clear to me why it is occurring, nor is it clear to me if this has any connection to CAM or is purely a land model issue.  At this point @JulioTBacmeister and I are thinking it would be more efficient for a land model person to look into it.

**Comment by adamrher** [comment]
What would be required to confirm that CAM is not responsible for this error that you traced back to ```x```? I just want to be sure that the atmosphere didn't blow-up. Could you do one last check ... check that all the input variables to the ```subroutine calcstress``` are not out to lunch? It would good to confirm, e.g., that ```temperature_inst``` isn't bad.

**Comment by nusbaume** [comment]
After checking with @bstephens82 it seems like this is no longer a problem, so will close as a "won't fix".  If this bug re-appears as a problem then this issue can be re-opened then.
