### ISSUE TITLE
Need to add zonal mean grid to history for fields on arbitrary grids

### ISSUE THREAD

**Issue by fvitt** [ESCOMP/CAM#652]
### What is the feature/what would you like to discuss?

The ability to output zonal mean physics fields to history.  The physics fields would be on general physics grid, structured or unstructured.   The zonal means would Use the Zonal_Mean code proposed in PR #629 which computes zonal mean values for arbitrary grids based on m=0 spherical harmonics.

### Is there anyone in particular you want to be part of this conversation?

@gold2718 @patcal 

### Will this change (regression test) answers?

No

### Will you be implementing this enhancement yourself?

Yes, but I will need some help

**Comment by gold2718** [comment]
@fvitt, #368 mentions the need for zonal mean history output. How is this different?
