### ISSUE TITLE
Update CAM externals to match cesm2_3_alpha10b

### ISSUE THREAD

**Issue by peverwhee** [ESCOMP/CAM#661]
### Issue Type

Externals Update

### Issue Description

When cesm2_3_alpha10b gets through testing, update CAM externals to match

This will address https://github.com/ESCOMP/CAM/issues/639

### Will this change answers?

Yes

### Will you be implementing this yourself?

Yes

**Comment by cacraigucar** [comment]
It would be good to see if we can bring in https://github.com/ESCOMP/CDEPS/pull/194 as well with this tag as it solves #673

**Comment by peverwhee** [comment]
Agreed 100%. I will include the [cdeps0.12.67](https://github.com/ESCOMP/CDEPS/releases/tag/cdeps0.12.67) tag in this PR (which will hopefully fix my failing tests!)
