### ISSUE TITLE
CONUS FHIST compset does not run out of the box

### ISSUE THREAD

**Issue by adamrher** [ESCOMP/CAM#662]
### What happened?

The CONUS grid alias does not run with FHIST. This is because unlike the other var-res grids (arctic and greenland) CONUS points to emissions files defined on the CONUS grid, and the dates do not extend before Jan 2000. FHIST runs w/ Jan 1979 start date out of the box and so we get the error that the emissions files can't find the right dates:

```
 FIND_TIMES: ALL data times are after   0.000000000000000E+000
 FIND_TIMES: file:
 /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/CAMS_Anthro_ne0CONUSne30x8/C
 AMS-GLOB-ANT_Glb_ne0CONUSne30x8_SO2_anthro-ag-ship-res_surface_v3.1_c20191103.n
 c
 FIND_TIMES: time:   0.000000000000000E+000
 ERROR:
 find_times: all(all_data_times(:) > time) /glade/p/cesmdata/cseg/inputdata/atm/
 cam/chem/emis/CAMS_Anthro_ne0CONUSne30x8/CAMS-GLOB-ANT_Glb_ne0CONUSne30x8_SO2_a
 nthro-ag-ship-res_surface_v3.1_c20191103.nc

```

I think that all three var-res grids should be able to run with the FHIST compset out of the box, of which CONUS is currently the only one failing. 

### What are the steps to reproduce the bug?

create_newcase with the ```FHIST``` compset and ```ne0CONUSne30x8_ne0CONUSne30x8_mt12``` grid alias

However, this won't run w/o the var-res bug fix https://github.com/ESCOMP/CAM/issues/631 not yet made into a tag. Therefore you will have to add those mods to reproduce this error.

### What CAM tag were you using?

cam6_3_067

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

/glade/scratch/aherring/cam6_3_067.newpio_FHISTdev_ne0CONUSne30x8_ne0CONUSne30x8_mt12_L32_nuopc_600pes_220927_aerotest0

### Will you be addressing this bug yourself?

No

**Comment by fvitt** [comment]
Changing the start date to correspond to the emissions should solve this issue.  Might also want to customized PE layout for this configuration.

**Comment by adamrher** [comment]
> Changing the start date to correspond to the emissions should solve this issue

That may well be all we want to do at this point. But I don't know that we should let that close the issue until CONUS can run w/ 1979 FHIST out of the box. I would like all three of our var-res grids to be able to run the historical FHIST compsets beginning at year 1979, as I feel that this serves the needs of our user base (happy to hear opposing views).

**Comment by fvitt** [comment]
Would we be okay with letting the model bi-linearly interpolate the emissions to physics grid for the FHIST compset in these cases when the emissions are not available on the corresponding grid?

**Comment by adamrher** [comment]
> Would we be okay with letting the model bi-linearly interpolate the emissions to physics grid for the FHIST compset in these cases when the emissions are not available on the corresponding grid?

I am ok with this b/c usually people running FHIST aren't all that concerned with high-resolution chemistry and emissions, more of the low-top crowd. This is what we do with arctic and greenland grids and some great science has already come of them. It would be nice if we had all the emissions defined on their native grids from 1979 onwards for all three var-res grids ... but this is a separate issue. @tilmes @lkemmons thoughts on opening an issue to put all emissions on native grids, priority TBD?
