### ISSUE TITLE
Create MAM5 chemistry compsets FCHIST (58L and 93L)  

### ISSUE THREAD

**Issue by tilmes** [ESCOMP/CAM#663]
### What is the feature/what would you like to discuss?

We need to add the new MAM5 modal model version into the workhorse model in order to test this for upcoming model runs.
MAM5 adds a stratospheric sulfate mode that improves the representation of volcanic eruptions and aerosol injection studies on high clouds, through separating the stratospheric sulfate model from the mixed coarse mode in MAM4. MAM5 does also revert the widths of the log normal standard deviation for the modes back to CAM5 sizes. This change is desired for improved representations of sea-salt and dust. MAM5 has been implemented and tested in WACCM previously by Xiaohong Liu's group.

### Is there anyone in particular you want to be part of this conversation?

@fvitt @lkemmons @mmills

### Will this change (regression test) answers?

Yes

### Will you be implementing this enhancement yourself?

No

**Comment by fvitt** [comment]
@tilmes  Do we need a 93-layer camchem+mam5 configuration that runs out of the box?

**Comment by tilmes** [comment]
Yes, that would be best. Please note, this will change answers, and is likely to need dust and  possibly sea-salt tuning after implemented.

**Comment by fvitt** [comment]
@tilmes Do you have a working cam-chem 93-layer case?  Do have an IC file?  How should we specify upper boundary conditions in this configuration?

**Comment by fvitt** [comment]
@tilmes 
Should the MAM5 CAM-Chem compsets be configured with `cam_dev` physics?  The 58-layer test case you pointed me to uses `cam_dev` physics.

**Comment by tilmes** [comment]
Hi Francis,
I think, we discussed to add MAM5 to all the cam version, so both cam_dev and cam. I think, it should be configured with just cam physics, and people can change it to cam_dev if they would want to. Or does this not make sense?

**Comment by fvitt** [comment]
So, out-of-the-box the MAM5 CAM-Chem compsets be configured with cam6 physics.  The users can switch to cam_dev physics desired.

**Comment by tilmes** [comment]
sounds good to me

**Comment by adamrher** [comment]
> So, out-of-the-box the MAM5 CAM-Chem compsets be configured with cam6 physics. The users can switch to cam_dev physics desired.

Im going to dissent. For two reasons, (1) we are talking about the next cam physics package, which will officially be called cam7 but for now we are invoking it through -phys cam_dev. The MAM5 options we discussed at the Friday meeting should be a part of cam7, not cam6. Ill note @andrewgettelman made a similar comment on Friday that these MAM5 mods should be key'ed off of cam_dev physics.

(2) cam_dev was developed specifically to deal with the increased boundary layer resolution in L58/L93 and cam6 should not be run w/ these new grids. To the extent that MAM5 is tied to these grids, I'd rather not have MAM5 pointing to the older cam6 physics.

**Comment by tilmes** [comment]
@adamrher I seem to remember that we agreed that it was easier to implement MAM4 (with the sigma change) to both cam and cam_dev for CAM without chemistry. However, that is really up to the CAM group to decide. However, for CAMchem (this pull request), the implementation from MAM5 will result in a different new compset (in addition to the MAM4 compset, if I am not mistaken) that I think can be added to cam6. For cam7 we may not want to continue MAM4 for CAMchem anymore. This is useful since I may actually want to compare the cam6 MAM4 and MAM5; having both compsets available in cam6 seems to be useful to me.

**Comment by tilmes** [comment]
@andrewgettelman Again, for CAM (no chemistry) there will be no MAM5, not in cam6 or in cam7. The question is, where do we change the mode details, in cam6 or cam6_dev. It seems like you prefer doing that in cam6_dev, which is fine with me.
For CAMchem, MAM5 is a different compset, this can be added in both cam6 and cam6_dev (eventually cam7).

**Comment by tilmes** [comment]
@andrewgettelman @adamrher do we need a small meeting to clarify this difference?

**Comment by tilmes** [comment]
@andrewgettelman This pull request is for CAMchem with Chemistry, I am not sure why we should not have a MAM5 version in cam6 and going forward, given that we may want to test it in parallel to the MAM4 compset?

**Comment by andrewgettelman** [comment]
I'm suggesting it not be a compset. You just make the changes manually to switch. It's not hard is it? I'm suggesting to limit the extraneous compsets we are only using for development. Yes you want to run both MAM4 and MAM5 for testing, but we don't necessarily need a compset for everything (in my opinion).

**Comment by tilmes** [comment]
@andrewgettelman for chemistry, there are many more changes, including code changes..

**Comment by fvitt** [comment]
@tilmes, I think @andrewgettelman is saying is that the user can simply replace `-chem trop_strat_mam4_vbs` with `-chem trop_strat_mam5_vbs` in a case that is created with an existing MAM4 CAM-Chem compset.  We just need to include the changes to implement the `trop_strat_mam5_vbs` chemistry option.

**Comment by tilmes** [comment]
@fvitt So for example the FCnudged compset would then used MAM5 instead of MAM4?
well, that would be fine for  CAM7 going forward, what if I want to test MAM4 vs MAM5 without having to get all the other changes that are in cam_dev?
