### ISSUE TITLE
More restart non-bit-for-bit occurrences

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#667]
### What happened?

From Keith Lindsay via email:

I have confirmed that my clone of one of Cecile's fully coupled experiments is not restarting exactly, when attempting to restart on particular dates.

The experiment restarts exactly early in the run, such as 0001-01-02 and 0001-01-03.
It also restarts exactly on 0001-12-01.
However, it does not restart exactly on 0001-12-31 or 0002-01-01.

In my tests of exact restartability, I've enabled cpl hist files (approximately) every timestep. (I need to move where history writing in the nuopc run sequence occurs to get this to happen.) So I'm getting a record of fields getting passed to and from the coupler. The first divergence of fields after a restart is in some fields sent from CAM to the coupler. Here's the RMS lines from cprnc comparing the cpl hist files:
 RMS atmImp_Faxa_rainc                7.1978E-15            NORMALIZED  4.7962E-10
 RMS atmImp_Faxa_snowc                1.5895E-16            NORMALIZED  3.5183E-09
 RMS atmImp_Sa_dens                   1.8034E-13            NORMALIZED  1.5064E-13
 RMS atmImp_Sa_pbot                   1.0914E-08            NORMALIZED  1.1155E-13
 RMS atmImp_Sa_ptem                   1.8113E-11            NORMALIZED  6.3387E-14
 RMS atmImp_Sa_shum                   1.2418E-14            NORMALIZED  1.3697E-12
 RMS atmImp_Sa_tbot                   1.8035E-11            NORMALIZED  6.3250E-14
 RMS atmImp_Sa_u                      7.9879E-13            NORMALIZED  1.5167E-13
 RMS atmImp_Sa_v                      4.5647E-12            NORMALIZED  9.7223E-13
 RMS atmImp_Sa_z                      9.1689E-12            NORMALIZED  1.4462E-13

So the differences are pretty small. But they grow.

This experiment has a number of CAM forcings with type CYCLICAL. Given that the problem occurs at the end of the year, but not only on Jan 1, my initial hypothesis is that there is a roundoff difference after restart in one of these forcing fields. That is, how the interpolation weights in time across the year boundary are computed.

I don't have high frequency CAM output enabled, yet, so I'm currently only able to diagnose differences in the fields the CAM sends to the coupler.

Given what I'm seeing, I'm guessing that this is reproducible in an F compset, and probably at lower resolution.

Do you have a preference on how I, or we, might proceed on further investigating this?

### What are the steps to reproduce the bug?

See above description

### What CAM tag were you using?

branch which Cecile is using

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Will you be addressing this bug yourself?

No

### Extra info

This issue will be evolving and becoming more specific as we gain more information

**Comment by klindsay28** [comment]
Here is a recipe for reproducing the problem in an F1850 compset:

1. ./create_test --no-setup ERS_Vnuopc.f10_f10_mg37.F1850.cheyenne_intel.cam-outfrq1d
2. cd CASEROOT
3. ./xmlchange CAM_CONFIG_OPTS="-phys cam_dev -microphys mg2 -chem waccm_sc_mam4 -nlev 32"
4. ./xmlchange RUN_STARTDATE=0001-12-12
5. add the following to user_nl_cam
```
empty_htapes = .true.

fincl1 = 'ACTNI', 'ACTNL', 'ACTREI', 'ACTREL', 'AODDUST', 'AODVIS', 'BURDENBC', 'BURDENDUST', 'BURDENPOM', 'BURDENSEASALT',
'BURDENSO4', 'BURDENSOA', 'CAPE', 'CCN3', 'CDNUMC',  'CLDHGH', 'CLDICE', 'CLDLIQ', 'CLDLOW', 'CLDMED', 'CLDTOT', 'CLOUD', 'CMFMC_DP',
'CT_H2O', 'DCQ', 'DQCORE', 'DTCOND', 'DTCORE', 'DTV', 'EVAPPREC', 'EVAPSNOW', 'FCTI', 'FCTL', 'FICE', 'FLDS', 'FLNS', 'FLNSC', 'FLNT', 'FLNTC', 'FLUT',
'FREQZM', 'FSDS', 'FSDSC', 'FSNS', 'FSNSC', 'FSNT', 'FSNTC', 'FSNTOA', 'ICEFRAC', 'LANDFRAC', 'LHFLX', 'LWCF', 'MPDICE', 'MPDLIQ', 'MPDQ', 'MPDT',
'OCNFRAC', 'OMEGA', 'OMEGA500', 'PBLH', 'PHIS', 'PINT', 'PMID', 'PRECC', 'PRECL', 'PRECSC', 'PRECSL', 'PRECT', 'PS', 'PSL', 'PTEQ', 'PTTEND', 'Q',
'QFLX', 'QRL', 'QRS', 'QTGW', 'RCMTEND_CLUBB', 'RELHUM', 'RVMTEND_CLUBB', 'SHFLX', 'SOLIN', 'SST', 'STEND_CLUBB', 'SWCF',
'T', 'TAUX', 'TAUY', 'TFIX', 'TGCLDIWP', 'TGCLDLWP', 'TMQ', 'TREFHT', 'TS', 'TTGW', 'U', 'U10', 'UBOT', 'UTGWORO', 'UTGW_TOTAL',
'V', 'VBOT', 'VTGWORO', 'VTGW_TOTAL', 'WPRTP_CLUBB', 'WPTHLP_CLUBB', 'Z3', 'ZMDQ', 'ZMDT', 'CH4', 'N2O'

fincl2 = 'OMEGA', 'PMID', 'PS', 'Q', 'QRL', 'QRS', 'T', 'TROP_P', 'TROP_T', 'U', 'V', 'Z3'

fincl4 =  'PRECC','PRECL'

tracer_cnst_specifier          = 'O3','OH','NO3','HO2','HALONS'
```
6. ./case.setup
7. qcmd -- ./case.build
8. ./case.submit

I ran this from Cecile's sandbox at
/glade/work/hannay/cesm_tags/cesm3_cam6_3_058_MOM_e
and also included a fix for #655 in SourceMods/src.cam. This SourceMod would not be necessary if the test were done with a sandbox that includes a fix for #655.

The RUN_STARTDATE is chosen to ensure that the run starts before 0001-12-16 and the continuation is after 0001-12-16. I suspect that this is an important ingredient in triggering the problem.

The CAM_CONFIG_OPTS and user_nl_cam settings are from Cecile's case. It's possible that the problem can be triggered with a subset of these changes.

I have an example of this failure on CISL machines at
/glade/scratch/klindsay/ERS_Vnuopc.f10_f10_mg37.F1850.cheyenne_intel.cam-outfrq1d.20221003_214436_1gw65a

Most CAM fields in the COMPARE_base_rest phase of the test fail.


To investigate further, it would be useful to compare instantaneous hist output immediately after the continuation to the same output in the continuous run, to see which fields first diverge. But I'm not sure how to get such a comparison with the CIME testing infrastructure.

**Comment by klindsay28** [comment]
I've come up with a pared down recipe for reproducing this issue. It also generates, within the CIME testing infrastructure, instantaneous CAM hist output, which enables identification of the fields that first diverge after the continuation. Here's the recipe:

1. ./create_test --no-setup ERS_Ld3_Vnuopc.f10_f10_mg37.F1850.cheyenne_intel.cam-outfrq1d
2. cd caseroot
3. ./xmlchange RUN_STARTDATE=0001-12-14
4. ./xmlchange CAM_CONFIG_OPTS="-phys cam_dev -microphys mg2 -chem waccm_sc_mam4 -nlev 32"
5. Ensure fix for #655 is in place (with SourceMods/src.cam or use sandbox with fix)
6. Replace user_nl_cam with
```
mfilt = 150
ndens = 1
nhtfrq = 1

empty_htapes = .true.

fincl1 = 'U', 'UTEND_TOT', 'UTGWORO', 'UTGW_TOTAL',
'V', 'VTEND_TOT', 'VTGWORO', 'VTGW_TOTAL', 'KVM',
'OMEGA', 'Z3', 'PS',
'T', 'TTEND', 'PTTEND', 'QRL', 'QRLC', 'QRS', 'QRSC',
'TTGW', 'TTGWORO', 'DTCOND', 'DTCORE', 'DTV', 'KVH', 'PBLH',
'Q', 'CT_H2O', 'PTEQ', 'QFLX', 'PRECT', 'QTGW', 'DCQ', 'DQCORE',
'CLOUD', 'CLDLIQ', 'CLDICE', 'CLDLIQTGW', 'CLDICETGW',
'PRECL', 'PRECC', 'PRECSL', 'PRECSC',
'TAUX', 'TAUY', 'TS', 'SST', 'OCNFRAC', 'ICEFRAC', 'SHFLX', 'LHFLX',
'FLDS', 'FLNS', 'FSDS', 'FSNS',
'ASDIR', 'ASDIF', 'ALDIR', 'ALDIF',
'CH4', 'CT_CH4', 'N2O', 'CT_N2O', 'O3'

tracer_cnst_specifier = 'O3','OH','NO3','HO2','HALONS'
```
7.  ./case.setup ; qcmd -- ./case.build ; ./case.submit

Using ERS_Ld3 with RUN_STARTDATE=0001-12-14 ensures that the continuation occurs on 0001-12-16.
Setting nhtfrq=1 and mfilt=150 generates output every timestep and places all 3-days worth in one file.
Then the cprnc.out file for cam.h0 can be inspected to see which fields first diverge.
When I run the command
cat $cprnc.out | grep -E 'nsteph|RMS' | grep -B1 RMS | less
I see the following initial divergences (from the fields that I've included in fincl1):
```
 nsteph   (time)  t_index =     98    98
 RMS CH4                              5.3779E-13            NORMALIZED  6.8117E-07
 RMS CLDICETGW                        1.6362E-26            NORMALIZED  1.2525E-12
 RMS CLDLIQTGW                        5.3596E-25            NORMALIZED  8.2379E-13
 RMS CT_CH4                           1.6545E-16            NORMALIZED  1.0658E-01
 RMS CT_H2O                           3.7162E-16            NORMALIZED  1.5814E-01
 RMS DTV                              2.6646E-19            NORMALIZED  7.5163E-12
 RMS PTEQ                             3.7151E-16            NORMALIZED  1.3032E-07
 RMS PTTEND                           2.5712E-18            NORMALIZED  1.7169E-13
 RMS QTGW                             3.6208E-21            NORMALIZED  3.5878E-10
 RMS TTGW                             2.5573E-18            NORMALIZED  9.2814E-11
 RMS TTGWORO                          2.4566E-18            NORMALIZED  9.3671E-11
 RMS UTEND_TOT                        9.4568E-20            NORMALIZED  1.4774E-15
 RMS UTGWORO                          3.8530E-20            NORMALIZED  1.1886E-13
 RMS UTGW_TOTAL                       3.8531E-20            NORMALIZED  8.7862E-14
 RMS VTEND_TOT                        3.7953E-20            NORMALIZED  5.2834E-16
 RMS VTGWORO                          2.3935E-20            NORMALIZED  8.5635E-14
 RMS VTGW_TOTAL                       2.3935E-20            NORMALIZED  7.5191E-14
```

Hopefully this is enough info for CAM developers to take over further investigation.

**Comment by cacraigucar** [comment]
My plan is to duplicate the test with the current CAM tag.  If it fails there, then I will see if it fails with CAM6 and/or aquaplanet.  Results will be posted here.

**Comment by cacraigucar** [comment]
@klindsay28 - Using the steps you outlined in cam6_3_078, I get the following error:

 ERROR: ubc_init: MSIS is not allowed in this configuration

Any ideas?

**Comment by fvitt** [comment]
What is the need for using `waccm_sc_mam4` chemistry in this low top configuration?

**Comment by fvitt** [comment]
> @klindsay28 - Using the steps you outlined in cam6_3_078, I get the following error:
> 
> ERROR: ubc_init: MSIS is not allowed in this configuration
> 
> Any ideas?

Try this namelist setting:
 `ubc_specifier = ' '`

**Comment by klindsay28** [comment]
@cacraigucar, this error message comes from `chemistry/mozart/upper_bc.F90`.
The error message was introduced in 8f7a4b9b8 on 2022-07-08 by @fvitt. I defer to his advice.
It looks like this file has received multiples updates this year, including this commit, that are not in Cecile's sandbox.

@fvitt, the configuration of CAM in this fully coupled run has been designed by folks in AMWG and/or CGD/AMP.
I defer to them for the rationale for the setup.

**Comment by cacraigucar** [comment]
I have been able to duplicate Keith's results  of non-bit-for-bit runs when I remove -nlev 32 from his configuration.

I can now move forward with CAM6/aquaplanet tests to see where the problem may be occurring

**Comment by fvitt** [comment]
> @fvitt - Using the above blank ubc_specifier, I now get the error message: ERROR: ubc_readnl: ubc_specifier "" must include "->"

try this:
 ` ubc_specifier = 'NOTSET'`

**Comment by cacraigucar** [comment]
Executive summary:  - I believe the bit-for-bit problem is coming from chemistry.  It does not appear to be a cam_dev issue

When I run using:
`./xmlchange RUN_STARTDATE=0001-12-14; ./xmlchange CAM_CONFIG_OPTS="-phys cam6 -microphys mg2 -chem waccm_sc_mam4 "`
The TestStatus has FAIL for "COMPARE base_rest"

`./xmlchange RUN_STARTDATE=0001-12-14; ./xmlchange CAM_CONFIG_OPTS="-phys cam6 -microphys mg2 "`
The TestStatus has PASS for "COMPARE base_rest"

To configure these tests:
```
./create_test --no-setup ERS_Ld3_Vnuopc.f10_f10_mg37.F1850.cheyenne_intel.cam-outfrq1d
cd caseroot
Use above xmlchange command
```

user_nl_cam:

mfilt = 150
ndens = 1
nhtfrq = 1

empty_htapes = .true.

fincl1 = 'U', 'UTEND_TOT', 'UTGWORO', 'UTGW_TOTAL',
'V', 'VTEND_TOT', 'VTGWORO', 'VTGW_TOTAL', 'KVM',
'OMEGA', 'Z3', 'PS',
'T', 'TTEND', 'PTTEND', 'QRL', 'QRLC', 'QRS', 'QRSC',
'TTGW', 'TTGWORO', 'DTCOND', 'DTCORE', 'DTV', 'KVH', 'PBLH',
'Q', 'CT_H2O', 'PTEQ', 'QFLX', 'PRECT', 'QTGW', 'DCQ', 'DQCORE',
'CLOUD', 'CLDLIQ', 'CLDICE', 'CLDLIQTGW', 'CLDICETGW',
'PRECL', 'PRECC', 'PRECSL', 'PRECSC',
'TAUX', 'TAUY', 'TS', 'SST', 'OCNFRAC', 'ICEFRAC', 'SHFLX', 'LHFLX',
'FLDS', 'FLNS', 'FSDS', 'FSNS',
'ASDIR', 'ASDIF', 'ALDIR', 'ALDIF',
'CH4', 'CT_CH4', 'N2O', 'CT_N2O', 'O3'

tracer_cnst_specifier = 'O3','OH','NO3','HO2','HALONS'

[For run w/o chemistry, removed 'CH4', 'CT_CH4', 'N2O', 'CT_N2O' from fincl1 list, and tracer_cnst_specifier = 'O3','OH','NO3','HO2','HALONS']

@fvitt - Do you agree that this problem seems to fall under Chemistry and should I assign it to you?

**Comment by fvitt** [comment]
I would like to understand the rationale for using wacm-sc chemistry in a low top configuration before I spend any time on this.

**Comment by gold2718** [comment]
> I would like to understand the rationale for using wacm-sc chemistry in a low top configuration before I spend any time on this.

In particular, is this even a valid configuration of CAM?

**Comment by adamrher** [comment]
waccm-sc chemistry is what @cecilehannay has been running, right? I don't recall the origins story ...

**Comment by gold2718** [comment]
> waccm-sc chemistry is what @cecilehannay has been running, right?

Has she been running it on a low-top CAM configuration? These details matter.

**Comment by adamrher** [comment]
yes, all our runs targeting CAM7 have been low-top waccm-sc. I don't know why this configuration was chosen.

**Comment by cacraigucar** [comment]
@fvitt  - I should point out that my conclusion is based on NOT having the low-top being set in the runs I reported .  You can see that I specifically did not use nlev=32 in my runs (they do not appear in my xmlchange list).  These none BFB runs were made simply by starting mid-December from the out-of-the box configuration.

**Comment by JulioTBacmeister** [comment]
@fvitt We are using use WACCM-SC in the present low-top runs because we expect the low-top model to actually resolve some stratospheric dynamical processes. It just seems a better strategy to use the WACCM_SC approach rather than the CAM approach of single global numbers for things like CO2, N2O etc..    In the addition for the final CAM6.5/7 model I think it will be better to have the option for both the low-top and high-top to use the _**same**_ simplified chemistry for tuning.  I will let @dan800 chime-in on this topic also.

**Comment by dan800** [comment]
@JulioTBacmeister I agree we want to unify the chemistry approach between the high and low top versions of CAM. The differences in cost are minor and out-weighed by the potential pitfalls of having to switch chemistries when switching the lid. The term WACCM_SC is a bit of a misnomer - much of what was implemented in SC is not being used (specification of heating rates above ~65 km and calling of non-LTE cooling). This is much closer to the standard prescribed constituents in CAM than WACCM-SC, but we simply move CO2 and N2O over to the prognostic / advected category along with the many aerosol and water tracers. What I would like to explore is the choice of upper boundary conditions - zero flux vs prescribed from a climatology. I think we agreed that we want to use a climatology for H2O UBC in low top and zero flux for the UBC in the high top. In no case should we be using the MSIS upper boundary.

**Comment by klindsay28** [comment]
I think the following diff fixes this problem:
```
--- /glade/work/hannay/cesm_tags/cesm3_cam6_3_058_MOM_e/components/cam/src/physics/cam/boundarydata.F90	2022-07-21 16:09:13.380738156 -0600
+++ SourceMods/src.cam/boundarydata.F90	2022-10-08 20:27:16.037378437 -0600
@@ -597,6 +597,7 @@ subroutine boundarydata_read(phys_state,
                   map=bndydata%map),_FILE,__LINE__)
           else
              bndydata%count(bndydata%thistimedim,1)=1
+             bndydata%start(bndydata%thistimedim,1)=bndydata%nm
              call handle_ncerr( nf90_get_var(bndydata%ncid, bndydata%dataid(i), &
                   datain(:,:,:,1:1,i), bndydata%start(:,1), bndydata%count(:,1), &
                   map=bndydata%map), _FILE,__LINE__)
```
During init, `boundarydata_read` sets up the model for time interpolation of various monthly forcings. It reads into a variable `datain` the time slices bounding the current model date/time. If the current model date/time is >= Dec 16 or < Jan 16, it reads the Dec values into the 1:1 time index of `datain` and the Jan values into the 2:2 time index of `datain`. It does this inside an `i` loop over the `fieldcnt` forcing fields being read in. However, I think there's a bug in the implementation. For `i>1`, the Jan value (`bndydata%start(...)=bndydata%np`) is read into both the 1:1 and 2:2 time indices of `datain`. The start argument to `nf90_get_var` needs to be set to the Dec value for each iteration of the `i` loop. It is set outside the `i` loop, so is only correct for the first fields read.

This diff fixes the exact restart problem in the high top F1850 waccm_sc_mam4 test problem described by @cacraigucar. (I haven't tested it yet in the fully coupled experiment.)

@fvitt, please chime in on if you think my analysis and diff are correct.

If I'm correct, then runs using `boundarydata_read` with 2 or more fields, and having a start and/or continuation date >= Dec 16 or < Jan 16 are using the incorrect forcing from model initialization through Jan 16. This includes restarts on Jan 1, a common occurance.

An ERS test with STARTDATE prior to Dec 16 and the continuation date >= Dec 16 and < Jan 16 will catch this, because the continuous run is correct and the continuation run is incorrect. However, an ERS test with  both STARTDATE and the continuation date >= Dec 16 and < Jan 16 won't catch this, because the continuous and continuation run are both incorrect in the same way.
