### ISSUE TITLE
Secondary bug in spectral-element advection

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [ESCOMP/CAM#678]
### What happened?

The bug fix for spectral-element advection discussed in https://github.com/ESCOMP/CAM/issues/633 introduced a secondary bug identified by @jzhan166 (ACOM, NCAR). The problem can be seen in N2O (level 90hPa) as well as the uniform test tracer TT_UN (level 682hPa) (day 5 instantaneous values) when running with chemistry (CAM_CONFIG_OPTS="-phys cam_dev -microphys mg2 -age_of_air_trcs -chem trop_strat_mam4_vbs -nlev 58 -nadv 207 -nadv_tt 5"):

![Screen Shot 2022-10-25 at 9 09 06 AM](https://user-images.githubusercontent.com/8782989/197811734-48fc5ee5-70a0-48cf-989a-1e36276d0ecd.png)
![Screen Shot 2022-10-25 at 9 17 09 AM](https://user-images.githubusercontent.com/8782989/197813642-63d095e7-b35c-4ee1-99c3-eadf180f9068.png)

![Screen Shot 2022-10-25 at 9 18 40 AM](https://user-images.githubusercontent.com/8782989/197814038-acdca30e-a7c0-4796-8504-9443a3772307.png)

The problem is that when subtracting a reference profile in the hyper viscosity for spectral-element tracer advection the background reference value should be zero. This can be fixed with adding the following modifications to code in dynamics/se/dycore/prim_driver.F90 where the reference profiles are computed (the fix is subtracting dp0 from dp_ref so that the background value is zero when PHIS=0):

     do ie=nets,nete
       do k=1,nlev
         pmid_ref =hvcoord%hyam(k)*hvcoord%ps0 + hvcoord%hybm(k)*ps_ref(:,:,ie)
         dp0 = ( hvcoord%hyai(k+1) - hvcoord%hyai(k) )*hvcoord%ps0 + &
               ( hvcoord%hybi(k+1) - hvcoord%hybi(k) )*hvcoord%ps0    
         if (hvcoord%hybm(k)>0) then
           elem(ie)%derived%T_ref(:,:,k)    = T0+T1*(pmid_ref/hvcoord%ps0)**cappa
           !
           ! pel@ucar.edu: resolved noise issue over Antartica - bug not fixed in CESM2.2 release branch
           !
           elem(ie)%derived%dp_ref(:,:,k)   = elem(ie)%derived%dp_ref(:,:,k)-dp0
         else
           elem(ie)%derived%T_ref(:,:,k)    = 0.0_r8
           elem(ie)%derived%dp_ref(:,:,k)   = 0.0_r8
         end if
       end do
     end do

Here is N2O and TT_UN (same as above) but when using the bug fix:

![Screen Shot 2022-10-25 at 9 12 29 AM](https://user-images.githubusercontent.com/8782989/197812524-7cff4406-e132-42fd-9016-8f751f976b8a.png)
![Screen Shot 2022-10-25 at 9 15 33 AM](https://user-images.githubusercontent.com/8782989/197813231-776ac650-9e5a-444e-9fb8-ed5ea690e428.png)

### What are the steps to reproduce the bug?

Here is a run script to reproduce the problem:

/glade/u/home/pel/git-scripts/run-cam/collection/ACOM.sh

(it is a setup provided by Simone Tilmes, ACOM)

### What CAM tag were you using?

cam6_3_077

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Will you be addressing this bug yourself?

Yes

**Comment by adamrher** [comment]
@PeterHjortLauritzen do we want this on the 2.2 release branch as well? If so, I'd really like this issue on the 2.2 release as it's a serious oversight: https://github.com/ESCOMP/CAM/issues/662.

**Comment by PeterHjortLauritzen** [comment]
That would be my preference ...

**Comment by PeterHjortLauritzen** [comment]
A couple of science comments:

First of all, @mt5555 agrees with the code fix. Second, we evaluated if this problem could have been detected in a simpler setup. We ran the moist Held-Suarez with topography test introduced in Appendix A3 of [Herrington et al. (2022)](https://agupubs.onlinelibrary.wiley.com/doi/pdf/10.1029/2022MS003192); basically Held-Suarez forcing except that the temperature relaxation is turned off in the lower atmosphere (sigma>0.7), has moisture and real-work topography.

Below is 11 months average of a uniform tracer (TT_UN) at 273hPa without code fix (left) and with code fix (right), respectively:

<img width="1146" alt="Screen Shot 2022-10-31 at 1 39 41 PM" src="https://user-images.githubusercontent.com/8782989/199095745-d328ca2b-8ce7-4a20-98b9-357924df4c7d.png">

So indeed this problem can be reproduced in a simpler setup!

Also, since the reference profile for pressure is changed with the code fix we assess how it impacts OMEGA500 which was used to diagnose spurious topographically induced noise in [Herrington et al. (2022)](https://agupubs.onlinelibrary.wiley.com/doi/pdf/10.1029/2022MS003192). Left is 11 months average of OMEGA500 using code with fix, middle is cam_development code and right is the difference between code fix run and cam_development:

<img width="1706" alt="Screen Shot 2022-10-31 at 1 27 11 PM" src="https://user-images.githubusercontent.com/8782989/199095398-3c668bb6-966c-4421-8258-0278c3184eca.png">

We observe that there is no new noise introduced by code fix and that the up and downdrafts are about 10% stronger with the code fix.

**Comment by mt5555** [comment]
Thanks for finding this and fixing!  We will port to E3SM HOMME also:  
https://github.com/E3SM-Project/E3SM/issues/5144

**Comment by peverwhee** [comment]
Proposed code change for the cesm2_2_rel branch (changes are in prim_advance_mod.F90)
```
do ie=nets,nete
     do k=1,nlev
        dp3d_ref(:,:,k,ie) = ((hvcoord%hyai(k+1)-hvcoord%hyai(k))*hvcoord%ps0 + &
                              (hvcoord%hybi(k+1)-hvcoord%hybi(k))*ps_ref(:,:,ie))
+      dp0                = ( hvcoord%hyai(k+1) - hvcoord%hyai(k) )*hvcoord%ps0 + &
+                            ( hvcoord%hybi(k+1) - hvcoord%hybi(k) )*hvcoord%ps0
+       !
+       ! pel@ucar.edu: resolved noise issue over Antarctica
+       !
+      dp3d_ref(:,:,k,ie)    = dp3d_ref(:,:,k,ie) - dp0
        tmp                = hvcoord%hyam(k)*hvcoord%ps0+hvcoord%hybm(k)*ps_ref(:,:,ie)
        tmp2               = (tmp/hvcoord%ps0)**cappa
        T_ref(:,:,k,ie)    = (T0+T1*tmp2)
     end do
end do
```

**Comment by PeterHjortLauritzen** [comment]
Looks good. Thanks!

**Comment by peverwhee** [comment]
closing because #687 has been merged
