### ISSUE TITLE
indexing bug for optional argument PS for get_dp subroutine of cam_thermo.F90

### ISSUE THREAD

**Issue by jtruesdal** [ESCOMP/CAM#679]
### What happened?

The optional output argument PS is passed into get_dp as an (i,j) array but used within the procedures as (i,k).  An out of bounds reference on the array causes the model to halt when run under DEBUG with NAG.
PS should be passed in as (:,j) and worked with inside the get_dp routines as a single rank variable dimensioned by (i)

A diff of cam_thermo without/with fix:

```
diff ../../collections/cam6_3_078.FCSCAM/src/utils/  ../../collections/cam6_3_080_ebudget_dev_update.102022/src/utils/cam_thermo.F90
_600c600
<      real(r8), optional,intent(out) :: ps(:, :)                  ! surface pressure (if ps present then ptop'
---
>      real(r8), optional,intent(out) :: ps(:)                     ! surface pressure (if ps present then ptop
635c635
<              ps(idx, kdx) = ps(idx, kdx) + dp(idx, kdx)
---
>              ps(idx) = ps(idx) + dp(idx, kdx)
658,659c658,664
<        call get_dp(tracer(:, jdx, :, :), mixing_ratio, active_species_idx,  &
<                dp_dry(:, jdx, :), dp(:, jdx, :), ps=ps, ptop=ptop)
---
>        if (present(ps).and.present(ptop)) then
>           call get_dp(tracer(:, jdx, :, :), mixing_ratio, active_species_idx,  &
>                dp_dry(:, jdx, :), dp(:, jdx, :), ps=ps(:,jdx), ptop=ptop)
>        else
>           call get_dp(tracer(:, jdx, :, :), mixing_ratio, active_species_idx,  &
>                dp_dry(:, jdx, :), dp(:, jdx, :))
>        end if
```

### What are the steps to reproduce the bug?

We are calling get_dp in some new budgeting code running with DEBUG under NAG.  Any call to get_dp where the optional argument PS is specified should reproduce the error using DEBUG under NAG.

### What CAM tag were you using?

cam6_3_080

### What machine were you running CAM on?

CGD machine (e.g. izumi)

### What compiler were you using?

NAG

### Will you be addressing this bug yourself?

No

**Comment by peverwhee** [comment]
closing this issue - was addressed in #680
