### ISSUE TITLE
part of cam6_3_083:  Bad ozone (Sa_o3) values in first coupling time step

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CAM#693]
### What happened?

In @fischer-ncar 's testing for CESM2_3_alpha10c, he noticed failures in B compsets run at f19_g17 resolution:

```
    FAIL ERS_Ld7.f19_g17.B1850.cheyenne_intel.allactive-defaultio RUN time=1817
    FAIL IRT_C3_Ld7.f19_g17.BHIST.cheyenne_intel.allactive-defaultio RUN time=799
    FAIL MCC.f19_g17.B1850.cheyenne_intel.allactive-defaultiomi RUN time=479
    FAIL MCC_Ld5.f19_g17.B1850G.cheyenne_intel.allactive-cism-test_coupling RUN time=486
    FAIL SMS_Ld5.f19_g17.B1850G.cheyenne_intel.allactive-cism-test_coupling RUN time=1819
```

These all fail in the same way (note that there is a mistake in the text of the error message: "output from CLM" should really be "input to CLM" here):

```
120: # of NaNs =            1
120: Which are NaNs =  F F F F F F F F F F F F F F F F F F F F T F F F F F F F F F F
120: F F F F F F F F F
120: NaN found in field Sa_o3 at gridcell index           21
120: ERROR:  ERROR: One or more of the output from CLM to the coupler are NaN
120:Image              PC                Routine            Line        Source            
120:cesm.exe           00000000042381C6  Unknown               Unknown  Unknown
120:cesm.exe           0000000003DB3657  shr_abort_mod_mp_         114  shr_abort_mod.F90
120:cesm.exe           0000000002929B4C  lnd_import_export         164  lnd_import_export_utils.F90
120:cesm.exe           0000000002924D82  lnd_import_export        1083  lnd_import_export.F90
120:cesm.exe           0000000002921C72  lnd_import_export         539  lnd_import_export.F90
120:cesm.exe           0000000002916D2B  lnd_comp_nuopc_mp         810  lnd_comp_nuopc.F90
```

The relevant change in this alpha tag is the inclusion of an updated CTSM: starting with `ctsm5.1.dev108`, CTSM imports the Sa_o3 field from the atmosphere. All CTSM coupling fields (input and output) are checked for NaN values in each time step, so now CTSM is aborting due to detecting a NaN value.

By removing the abort, I have verified that there is only a single grid cell with a NaN value, and only in the first coupling time step. However, by writing out cpl hist values at each time step (see steps to reproduce below) I see that the Sa_o3 values seem bad everywhere in the first coupling time step: they are 0 over most grid cells, but NaN over 3 grid cells. These are the values received from CAM's initialization. **So it seems that CAM is not properly setting the ozone coupling field in initialization, at least in this case that (I think) uses a prescribed ozone field rather than prognostic chemistry** (in contrast to other coupling fields, which seem to get valid values in model initialization).

The ideal solution would be for CAM to send the actual, correct ozone field in model initialization. If that is too difficult, can it at least send something like a reasonable, globally-constant value in initialization so that CTSM has something reasonable to work with in its first time step?

### What are the steps to reproduce the bug?

1. Checkout the latest CESM master: ESCOMP/CESM@bf1bf7f

2. Create, build and run a short test case with compset `B1850` and res `f19_g17` (e.g., one of the above tests or via create_newcase). Observe the failure.

3. To see more information, do the following:

Introduce this diff in components/clm to allow the model to continue past the initial abort:

```diff
diff --git a/src/cpl/nuopc/lnd_import_export.F90 b/src/cpl/nuopc/lnd_import_export.F90
index 0e7a5e2ee..8dccf3ddc 100644
--- a/src/cpl/nuopc/lnd_import_export.F90
+++ b/src/cpl/nuopc/lnd_import_export.F90
@@ -510,6 +510,8 @@ contains
     call NUOPC_ModelGet(gcomp, importState=importState, rc=rc)
     if (ChkErr(rc,__LINE__,u_FILE_u)) return
 
+    write(iulog,*) 'WJS: lnd_import: nstep = ', get_nstep()
+
     ! Set bounds
     begg = bounds%begg; endg=bounds%endg
 
diff --git a/src/cpl/utils/lnd_import_export_utils.F90 b/src/cpl/utils/lnd_import_export_utils.F90
index 032cb19b6..495fcd8b9 100644
--- a/src/cpl/utils/lnd_import_export_utils.F90
+++ b/src/cpl/utils/lnd_import_export_utils.F90
@@ -161,7 +161,7 @@ contains
              write(iulog,*) "NaN found in field ", trim(fname), ' at gridcell index ',begg+i-1
           end if
        end do
-       call shr_sys_abort(' ERROR: One or more of the output from CLM to the coupler are NaN ' )
+       ! call shr_sys_abort(' ERROR: One or more of the output from CLM to the coupler are NaN ' )
     end if
   end subroutine check_for_nans
 ```

Change cplhist frequency to every time step with:

```
./xmlchange HIST_OPTION=nsteps,HIST_N=1
```

Also, change where the cpl hist files are written so that they are written with the field values before the LND run. This way, the first cpl hist file written will contain the atm -> mediator fields from CAM initialization. Do this by copying `run/nuopc.runseq` to your case directory, then moving the line `MED med_phases_history_write` from near the bottom of the file to just before the `LND` line (after the `ICE` line).

Then rerun the case.

4. Look at the `atmImp_Sa_o3` field in the first cpl hist file to see values of this field in the first LND coupling, from CAM initialization.

A case set up this way is here: `/glade/scratch/sacks/b1850_o3test_1110a`. See `/glade/scratch/sacks/archive/b1850_o3test_1110a/cpl/hist/b1850_o3test_1110a.cpl.hi.0001-01-01-01800.nc` or the file `b1850_o3test_1110a.cpl.hi.0001-01-01-01800_o3.txt` which contains the dump of atmImp_Sa_o3 (showing the 3 NaN values).

### What CAM tag were you using?

cam6_3_082

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

/glade/scratch/sacks/b1850_o3test_1110a

### Will you be addressing this bug yourself?

No

**Comment by fvitt** [comment]
@cacraigucar I think we are expecting changes to configurations that use cam_dev physics.  The test you point to uses cam_dev physics.

**Comment by cacraigucar** [comment]
@fvitt - Thanks for that.  I was depending on the longname for identifying the cam_dev tests, but do see that the use case is setting this to be cam_dev.  I agree that cam_dev is answer changing (and I identified it for the other tests with answer changes).  I missed that this test was actually cam_dev as well.  Thanks for your input.
