### ISSUE TITLE
interpolation error on initialization in cam_dev

### ISSUE THREAD

**Issue by bstephens82** [ESCOMP/CAM#701]
### What happened?

When running cam_dev with L93, the model crashes on startup with an interpolation error originating from rrtmg/cloud_rad_props.F90.  Details are [here](https://github.com/NCAR/amwg_dev/issues/201#issuecomment-1320246549).

### What are the steps to reproduce the bug?

From @cecilehannay:

## 
cd /glade/work/hannay/cesm_tags/cesm3_cam6_3_058_MOM_e/cime/scripts
./create_newcase --compset   FWscHIST  --res ne30pg3_ne30pg3_mg17 --case /glade/p/cesmdata/cseg/runs/cesm2_0/f.cesm3_cam058_mom_e.FWscHIST.ne30_L93.26c_non-orogw_on.001 --run-unsupported  --pecount 2160 --project 93300722 

## set up
cd /glade/p/cesmdata/cseg/runs/cesm2_0/f.cesm3_cam058_mom_e.FWscHIST.ne30_L93.26c_non-orogw_on.001  
./xmlchange CAM_CONFIG_OPTS="-phys cam_dev -microphys mg2 -chem waccm_sc_mam4 -nlev 93"
./case.setup

./xmlchange RUN_STARTDATE=1979-01-01
./xmlchange STOP_N=2
./xmlchange STOP_OPTION=nyears
./xmlchange RESUBMIT=5
./xmlchange RUN_TYPE=hybrid
./xmlchange RUN_REFCASE=f.e21.FWscHIST_BGC.ne30_ne30_mg17_L48_revert-J.001
./xmlchange RUN_REFDATE=1989-01-01
./xmlchange GET_REFCASE=TRUE
./xmlchange RUN_REFDIR=cesm2_init

Use the same user_nl_* and SourceMods as in: 
/glade/p/cesmdata/cseg/runs/cesm2_0/f.cesm3_cam058_mom_e.FWscHIST.ne30_L93.26c_non-orogw_on.001

### What CAM tag were you using?

cam6_3_058

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

Cecile's above, or mine: /glade/scratch/stepheba/l93058test

### Will you be addressing this bug yourself?

Yes, but I will need some help

### Extra info

The problem was that the variable `dei` was not initialized appropriately when running with cam_dev.  The fix is just to use a call to `pbuf_set_field` in order to initialize this field to zero.  This involves a one-line change to rrtmg/radiation.F90 and a few changes to rrtmg/cloud_rad_props.F90.

**Comment by bstephens82** [comment]
I ran into the interpolation error again unexpectedly, this time with respect to the variable `pgam` in cloud_rad_props.F90, also known as `mu` in other places in the code and indexed by `i_mu` in cloud_rad_props.F90.  This one also needs to be initialized properly for cam_dev.  Other variables that we might as well go ahead and initialize are LAMBDAC and ICGRAUWP.  It is probably best to initialize these variables in micro_pumas_cam.F90 since that is where the variables are originally added to the pbuf.

**Comment by nusbaume** [comment]
This should have been closed by PR #632.  Closing now.
