### ISSUE TITLE
nvhpc compiler issue 

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CAM#705]
### Issue Type

Other (please describe below)

### Issue Description

UCAR service ticket opened:  HELP-8142 nvhpc 22.7 compiler issue
   I have a self contained bug report on gust in directory
   /glade/u/home/jedwards/sandboxes/nvhpcbug

   the script bld can be run to compile the file odf_init.c
   The nvhpc compiler in all three versions available ( nvhpc/21.3    nvhpc/22.2    nvhpc/22.7)
   hangs when trying to compile this file.   This file is critical to the cam atmospheric model,
   please report this issue to nvidia as soon as possible.

### Will this change answers?

No

### Will you be implementing this yourself?

No

**Comment by jedwards4b** [comment]
#706 avoids compiling the ali-arms code except in the waccm cases where it is needed.

**Comment by nusbaume** [comment]
This should have been closed by PR #632.  Closing now.
