### ISSUE TITLE
create_newcase using updated cime does not start jobs on izumi

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#711]
### What happened?

Get this error when run ./case.submit:

Submitting job script qsub -q medium  -l walltime=08:00:00  -A  -v ARGS_FOR_SCRIPT='--resubmit' .case.run
ERROR: Command: 'qsub -q medium  -l walltime=08:00:00  -A  -v ARGS_FOR_SCRIPT='--resubmit' .case.run' failed with error 'qsub: script file 'ARGS_FOR_SCRIPT=--resubmit' cannot be loaded - No such file or directory' from dir '/home/cacraig/cam6_fix_snapshot/cime/scripts/test_try01'

According to Chris Fischer, believes updating the cime tag to a cime later than cime6.0.64 should fix the problem

### What are the steps to reproduce the bug?

Any create_newcase, case.setup, case.build, case.submit on izumi currently duplicates this problem

### What CAM tag were you using?

cam6_3_085

### What machine were you running CAM on?

CGD machine (e.g. izumi)

### What compiler were you using?

Other (please specify below)

### Will you be addressing this bug yourself?

Yes

**Comment by nusbaume** [comment]
This should have been closed by PR #632.  Closing now.
