### ISSUE TITLE
Remove bndtvs from cam

### ISSUE THREAD

**Issue by mvertens** [ESCOMP/CAM#713]
### Issue Type

Code Clean-up

### Issue Description

bndtvs specifies an SST dataset. CAM should no longer use this - since only the DOCN component would need this. This should be removed from all use cases, namelist_defaults and namelist_definitions.

### Will this change answers?

No

### Will you be implementing this yourself?

Yes

**Comment by brian-eaton** [comment]
Resolved by PR#764 (cam6_3_098).
