### ISSUE TITLE
cam6_3_088: update externals to match cesm2_3_beta10 with newer cime to fix restarts

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#730]
### Issue Type

Infrastructure Update

### Issue Description

Update the CAM externals to match those in cesm2_3_beta10

Update the cime tag to the latest one to bring in the changes needed for fixing restart problems

### Will this change answers?

I Don't Know

### Will you be implementing this yourself?

No

**Comment by cacraigucar** [comment]
@nusbaume - If the cime update can include this https://github.com/ESMCI/cime/pull/4348 if it is available, that would be great.  It gives a much better error message when the coupling intervals have a mismatch

**Comment by nusbaume** [comment]
Sure! Hopefully they'll both get merged either today or Monday, at which point I'll go ahead and get the CAM externals updated.
