### ISSUE TITLE
In cam_cesm2_1_rel: SSP126 ozone forcing file is NetCDF4 format

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CAM#732]
### Issue Type

Infrastructure Update

### Issue Description

As a user pointed out in the forums (https://bb.cgd.ucar.edu/cesm/threads/bssp126-fails-because-netcdf-file-is-actually-an-hdf5.7910/), the SSP126 ozone forcing file in the cam_cesm2_1_rel branch (in CESM2.1.3) is a NetCDF4-formatted file (ozone_strataero_WACCM_L70_zm5day_2015-2100_SSP126_c190221.nc), which causes problems on some machines. It looks like @nanr created a NetCDF3-formatted file, which I have just added to the inputdata repository (ozone_strataero_WACCM_L70_zm5day_2015-2100_SSP126_c190221_netcdf3.nc). I have confirmed (with cprnc) that these two files are identical except for their file format.

I'm not sure if it's worth making a new CAM release tag with this change (for an eventual CESM2.1.4 if we ever have one), but I wanted to at least make note of this in an issue for anyone else running into this problem.

### Will this change answers?

No

### Will you be implementing this yourself?

No

**Comment by cacraigucar** [comment]
@billsacks - Thanks for letting us know.  After discussing this within the AMP group, we concluded that making a note of this of this is all that we will do and that we will not be making any changes.
