### ISSUE TITLE
Replace "Invert_Matrix" subroutine in "zonal_mean_mod.F90" with LAPACK version

### ISSUE THREAD

**Issue by nusbaume** [ESCOMP/CAM#736]
### Issue Type

Code Clean-up

### Issue Description

PR #677 will bring in a new "zonal_mean_mod.F90" that has its own matrix inversion subroutine (`Invert_Matrix`).  However, given that CAM already uses LAPACK, and that LAPACK has optimized routines to do matrix inversion, it would make sense to replace this `Invert_Matrix` subroutine with one from LAPACK.

### Will this change answers?

I Don't Know

### Will you be implementing this yourself?

Any CAM SE can do this

closes #745

**Comment by peverwhee** [comment]
The PR for this issue can close https://github.com/ESCOMP/CAM/issues/745 as well
