### ISSUE TITLE
CLUBB energy fixer broken in cam6_3_066

### ISSUE THREAD

**Issue by adamrher** [ESCOMP/CAM#739]
### What happened?

In testing Kate's CLUBB PR coming in, I noticed CLUBB is no longer conserving energy and so it's energy fixer is broken. I tracked this down to my CLUBB PR https://github.com/ESCOMP/CAM/pull/598 and therefore tag cam6_3_066.

I'm testing the energy fixer by setting ```print_energy_errors = .true.``` and keeping my eye on the size of the atm.log. Here's what I've tested so far:

cam6_3_065: 59537 Jan 10 11:30 atm.log.8060421.chadmin1.ib0.cheyenne.ucar.edu.230110-112854.gz
cam6_3_067: 6989535 Jan 10 10:42 atm.log.8059691.chadmin1.ib0.cheyenne.ucar.edu.230110-103113
cam6_3_067*: 1417479 Jan 10 10:59 atm.log.8059869.chadmin1.ib0.cheyenne.ucar.edu.230110-104818.gz

The correct size of the log file with the print energy error on is 59KB (this is a QPC6, ne30pg3, 1 day run). Tag cam6_3_067 is ~7MB. The cam6_3_067* is modified by removing the scaling of the sensible heat fluxes by inverse exner introduced in cam6_3_066, which reduces the log file down to 1.4MB (I didn't test cam6_3_066 because I had cam6_3_067 laying around).

@PeterHjortLauritzen @bstephens82 I think we need to diff clubb_intr in cam6_3_065 and cam6_3_066, make some mods, and then run some experiments tracking the clubb energy leak variables EFIX_CLUBB, to resolve this issue.

### What are the steps to reproduce the bug?

set print energy errors to true in any tag after cam6_3_065

### What CAM tag were you using?

cam6_3_067

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

/glade/scratch/aherring/cam6_3_067_QPC6_ne30pg3_ne30pg3_mg17_L32_nuopc_600pes_230110_testenergy/run/

### Will you be addressing this bug yourself?

Yes, but I will need some help

**Comment by adamrher** [comment]
I have fixed this issue on my branch of cam6_3_092. Peter is going to add some mods next week to my branch that addresses a different issue (thermo refactor enhancement). @PeterHjortLauritzen maybe we should open an issue for the thermo refactor work?

**Comment by adamrher** [comment]
Providing the record of the changes needed to fix this issue. The issue is that I changed the density used by clubb to a dry density, and that broke the ability to enforce CAM's energy on the new CLUBB state. The issue was that by changing rho to dry, I needed to change everything to dry. A list of the changes to fix this:

- convert state array to dry mixing ratios, instead of moist mixing ratios
- use dpdry to compute dry rho ```(1._r8/gravit)*(state1%pdeldry(i,pver-k+1)/dz_g(i,pver-k+1))```
- convert qrl_clubb to dry mixing ratios (only used for ```do_cldcool```, which is not used by default)
- use dry rho to back out kinematic surface fluxes from the host model surface fluxes
- integrate before and after water mass used to enforce CAMs energy with dpdry, instead of dp
- convert detrainment tendencies (e.g., dlf) to dry mixing ratios
- convert accumulated tendencies ptend_all back to moist mixing ratios

These changes are required to enforce CAMs energy on the clubb state, which is now based on dry mixing ratios.

**Comment by PeterHjortLauritzen** [comment]
I will do the "thermo refactor" in a different PR that I am currently working on ... so please proceed with getting this on cam_development ...

**Comment by adamrher** [comment]
providing the energy less that we then correct for, here:

![temp_ELEAK_CLUBB](https://user-images.githubusercontent.com/29961476/217356182-ac629c31-2da1-4542-8321-e75edce3217c.png)

where the second row is my PR branch fix. The correction is reduced at low latitudes, to the global value of -1/4 W/m2, which is the same value in the JAMES energy paper.

Peter - can u clarify for me. If the "corrector" as I'm calling it in clubb_intr, is incorrectly formulated, would the global energy fixer make up for that inconsistency? Or does the global energy corrector assume the physics tendencies are correct and just ensure that after integrating with the dycore, the energy change is the same as implied by the physics tendencies?

**Comment by PeterHjortLauritzen** [comment]
No (you would only get errors from "check_energy_chng" if enabled). The energy fixer only fixes global energy errors introduced between in the state right before "physics_dme_adjust" is called and the state entering physics one time-step later (hence only fixing dme_adjust energy imbalance, adiabatic dynamical core errors, physics-dynamics coupling errors).

Hence the CLUBB energy fixer is a little dangerous in the sense that if CLUBB does something crazy (energy-wise) then the fixer will just fix it ...

**Comment by PeterHjortLauritzen** [comment]
(and thanks for providing the diagnostics - looks consistent with our energy paper: Figure 11 https://agupubs.onlinelibrary.wiley.com/doi/epdf/10.1029/2022MS003117)

**Comment by nusbaume** [comment]
This issue was fixed by PR #750, so closing now.

**Comment by adamrher** [comment]
why didn't this automatically close? I wrote "Fixes " and then added then paster url to this issue in the PR. What's the right recipe here?

**Comment by nusbaume** [comment]
@adamrher You need to just use the number, not the full URL.

In other words you should type `Fixes #739` not `Fixes https://github.com/ESCOMP/CAM/issues/739`.

Hope that helps!

**Comment by adamrher** [comment]
Ah, OK. Will try to do this going forward.
