### ISSUE TITLE
Unhelpful error message when running SCAM and IOP file is too short

### ISSUE THREAD

**Issue by peverwhee** [ESCOMP/CAM#742]
### What happened?

When running SCAM with the cgils configuration for longer than the IOP file, the user used to get this error:

> ERROR - setiopupdate.c:Reached the end of the time varient dataset

Since **cam6_3_085**, the run now crashes in ice_import_export.F90 instead (which is very unhelpful in debugging).

I have not determined which external in the externals update PR for cam6_3_085 is the culprit.

### What are the steps to reproduce the bug?

Run a SCAM configuration for longer than the IOP file.

### What CAM tag were you using?

cam6_3_085

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

/glade/scratch/courtneyp/isaac-repro

### Will you be addressing this bug yourself?

Any CAM SE can do this

**Comment by jtruesdal** [comment]
This error is due to a bug in the nuopc code in cice.  I've started the process of getting this fixed via the cice consortium.  Once the fix is in and approved we can close this issue.
