### ISSUE TITLE
Bug in zonal mean "Invert_Matrix" subroutine

### ISSUE THREAD

**Issue by nusbaume** [ESCOMP/CAM#745]
### What happened?

As reported by @patcal, line 1432 in the `Invert_Matrix` subroutine in `zonal_mean_mod.F90`, which is:

`do ii=11,Nbas`

Should instead be:

 `do ii=1,Nbas`

Otherwise some elements will be missed during the inversion.

### What are the steps to reproduce the bug?

@patcal Found the bug when expanding the spherical harmonics routines to manage quantities that aren't just purely zonal.

### What CAM tag were you using?

cam6_3_092

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Will you be addressing this bug yourself?

Any CAM SE can do this

### Extra info

The SEs need to decide if we will fix this bug directly, or if we'll instead try and resolve issue #736 instead.

**Comment by fvitt** [comment]
I'm in favor of replacing the Invert_Matrix routine with corresponding lapack routines (issue #736)
