### ISSUE TITLE
aerosol mass imbalance due to pbuf and state aerosol variables not in sync in macmic

### ISSUE THREAD

**Issue by cmcclus** [ESCOMP/CAM#751]
### What happened?

Chuck Bardeen discovered a mass imbalance between interstitial and cloud-borne sulfate aerosol, where the tendency of creating cloud borne sulfate aerosol was exactly a factor of 3 times more than interstitial sulfate aerosol. This error is "fixed" when number_of_stubsteps = 1. The issues is related to the state and pbuf variables being out of sync in the macmic loop (physpkg.F90). This issue will likely influence all aerosol types and possible other variables in pbuf. 

Interstitial aerosol variables are in state, advected, and are modified with ptend in the macmic loop. When interstitial aerosol activate into cloudborne aerosol, they are no longer advected and switch over from state to pbuf. Different dtimes are used within the micmac loop to apply ptend to state and pbuf variables, which is causing a mass imbalance. It is unclear what is exactly needed as dtime in the various routines and what is needed for variables in pbuf (e.g., diagnostics that require an accumulated value versus cloud-borne aerosol that should be treated the same as their counterparts in state). 

time variables: 
ztodt ! physics timestep
cld_macmic_num_steps ! Number of macro/micro substeps
cld_macmic_ztodt ! ztodt/cld_macmic_num_steps

call physics_ptend_scale(ptend, 1._r8/cld_macmic_num_steps, ncol)
call physics_update(state, ptend, ztodt, tend)

Above, ptend is being scaled by 1/cld_macmic_num_steps before physics_update(), which reduces the tendency of state variables but not pbuf (where cloud-borne aerosol live). 

Note: this is a comment in physpkg.F90 (L2495) 
>             ! Unfortunately, physics_update does not know what time period
>              ! "tend" is supposed to cover, and therefore can't update it
>              ! with substeps correctly. For now, work around this by scaling
>              ! ptend down by the number of substeps, then applying it for
>              ! the full time (ztodt).

### What are the steps to reproduce the bug?

n/a

### What CAM tag were you using?

cam6_3_045 is what Chuck used, but issue is present in any tag.

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Will you be addressing this bug yourself?

No

**Comment by adamrher** [comment]
@andrewgettelman @PeterHjortLauritzen @cbardeen

**Comment by adamrher** [comment]
I really don't think that there are problems at the physpkg level related to this issue. At first I was confused on how the tendencies are being applied to the state in the macmic loop in physpkg, but the statement in physpkg referred to at the top of this thread actually does make sense:
```
        ! Unfortunately, physics_update does not know what time period
        ! "tend" is supposed to cover
```
Note it says "tend" not "ptend". tend accumulates the physics tendencies from all processes, as an intent(inout) argument in all calls to physics_update. **tend assumes that all the tendencies accumulated are integrated over ztodt**. So to get around this, they divide ptend by cld_macmic_num_steps, and then integrate it over a dtime that is a factor cld_macmic_num_steps larger, i.e., ztodt. This renormalization is necessary to properly update "tend".

I think this suggests that the issue is internal to the microp/aero subroutines, not physpkg.

**Comment by cbardeen** [comment]
I haven't looked into this in detail beyond getting a work around. But could a workflow like this work:

1) Copy State
2) Iterate
    a) CLUBB(copy_state, ptend_inner, sub_dt)
    b) accumulate(ptend_outer, ptend_inner)
    c) physics_update(copy_state, ptend_inner, sub_dt)
    d) MG(copy_state, ptend_inner, sub_dt)
    e) accumulate(ptend_outer, ptend_inner)
    f) physics_update(copy_state, ptend_inner, sub_dt)
3) physics_update(state, ptend_outer, dt)

I think then state and pbuf would be in sync the whole time using the sub_dt time scale. #3 is the only one that updates the real state with the total tendency and could be the one to update tend using the dt timescale that it apparently needs/assumes.

**Comment by adamrher** [comment]
I don't think that would work as you would still need to scale ptend_outer by 1/cld_macmic_num_steps (you could interpret that to be like taking the average tendecy over the sub-steps).

I think you have a better idea of the issue then I do. Whatever is happening to the pbuf variables is happening internal to the microp/aero subroutines, right? How would changing how we scale ptend at the physpkg level matter in that case? It is scaled appropriately and the state array we feed into the subroutines is correct.

**Comment by adamrher** [comment]
Thankfully, this was a false alarm. Turned out the problem was how we were trying to diagnose the sulfate budget, which if you aren't careful about how the tendencies get rescaled in the macmic loop (i.e., see our discussion above), can easily trip you up.
