### ISSUE TITLE
redundant O3 specifiers in out-of-the-box F-cases

### ISSUE THREAD

**Issue by adamrher** [ESCOMP/CAM#756]
### Issue Type

Code Clean-up

### Issue Description

Looking through an atm_in file of the 26 series runs, there are two separate ozone namelist streams:

```
&prescribed_ozone_nl
 prescribed_ozone_datapath              = '/glade/p/cesmdata/cseg/inputdata/atm/cam/ozone_strataero'
 prescribed_ozone_file          = 'ozone_strataero_WACCM_L70_zm5day_18500101-20150103_CMIP6ensAvg_c180923.nc'
 prescribed_ozone_name          = 'O3'
 prescribed_ozone_type          = 'SERIAL'
/
&prescribed_strataero_nl
 prescribed_strataero_datapath          = '/glade/p/cesmdata/cseg/inputdata/atm/cam/ozone_strataero'
 prescribed_strataero_file              = 'ozone_strataero_WACCM_L70_zm5day_18500101-20150103_CMIP6ensAvg_c180923.nc'
 prescribed_strataero_type              = 'SERIAL'
 prescribed_strataero_use_chemtrop              =    .true.
/
```

At first I thought that the first stream is the prescribed ozone in the troposphere and the second stream for use above the chemical tropopause. Note they point to the same file -- a zonal-height climatology at 5 day intervals. But then there's a 3D monthly ozone stream in the "tracer_cnst" group:

```
 tracer_cnst_datapath           = '/glade/p/cesmdata/cseg/inputdata/atm/cam/tracer_cnst'
 tracer_cnst_file               = 'tracer_cnst_halons_3D_L70_1849-2015_CMIP6ensAvg_c180927.nc'
 tracer_cnst_filelist           = ''
 tracer_cnst_specifier          = 'O3','OH','NO3','HO2','HALONS'
 tracer_cnst_type               = 'INTERP_MISSING_MONTHS'
 xs_long_file           = '/glade/p/cesmdata/cseg/inputdata/atm/waccm/phot/temp_prs_GT200nm_JPL10_c140624.nc'
/
```

Is anyone able to interpret what files the model is actually using? In the troposphere? Above the tropopause? Do we need to clean up this redundancy? @dan800 tells me that the 3D lower frequency (monthly) stream in tracer_cnst should be used in the troposphere, and the zonal-height high-frequency (5 day) stream should be used above the tropopause.

@dan800 @tilmes @fvitt @JulioTBacmeister @cecilehannay @renerwijn

### Will this change answers?

I Don't Know

### Will you be implementing this yourself?

No

**Comment by tilmes** [comment]
@adamrher 
The prescribed ozone and prescribed strataero settings are used to prescribe ozone and aerosols in the stratosphere, so above the troposphere. We are using 5-day zm fields to represent the movements of the polar vortex / stratosphere more reasonable than what monthly means can do. Both use the same file, because the file contains information for both ozone and aerosol.

The tracer_cnst file is for the tropospheric oxidants for the troposphere. Here, we need a 3D fields of monthly mean data because of more regional differences. There is nothing to clean up and no redundancies in my view.

**Comment by adamrher** [comment]
thanks @tilmes ! That clear it up for me. I agree that there is no issue --- other then my inability to parse namelists (prescribed_strataero is not for ozone, it just happens to use the same file as is used for ozone).

I'll close this false alarm in a bit. But I'm curious how the two solutions gets pasted together across the tropopause? Is there any blending of the two datasets, or is there a step function like change in concentration's across the tropopause?

**Comment by adamrher** [comment]
false alarm. closing issue.
