### ISSUE TITLE
TEM diags not implemented in cam_dev physics

### ISSUE THREAD

**Issue by fvitt** [ESCOMP/CAM#769]
### What happened?

The calls to `phys_grid_ctem` are not in `src/physics/cam_dev/physpkg.F90`, only in `src/physics/cam/physpkg.F90`.  

### What are the steps to reproduce the bug?

Use configure option `-phys cam_dev`

and add namelist settings to turn on TEM diags, such as:
```
  phys_grid_ctem_nfreq=-6
  phys_grid_ctem_zm_nbas=120 
  phys_grid_ctem_za_nlat=90
  fincl3 = 'VTHzaphys','WTHzaphys','UVzaphys','UWzaphys'
```

### What CAM tag were you using?

cam6_3_100

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Will you be addressing this bug yourself?

Yes

**Comment by islasimpson** [comment]
I may have left this following comment in the wrong place.  Putting it here instead...

@fvitt  just to clarify, I think the other pieces that are needed are Uzm, Vzm, THzm and Wzm (or whatever we want to call them now). I see they are there in the code as the part that is subtracted to calculate the zonal deviations, before the fluxes are calculated (uzm, vzm, wzm, thzm). Thanks.--
