### ISSUE TITLE
Add PBUF fields to make cosp compatible with cam_dev

### ISSUE THREAD

**Issue by bstephens82** [ESCOMP/CAM#776]
### What happened?

I tried to run cam_dev with cosp and the model crashed right away.  The error was
~~~
874: ERROR: Attempt to find undefined name in pbuf SH_CLDLIQ
~~~
I looked into it and it looks like this variable, and three others, are added to the pbuf in cam/convect_shallow.F90, which I believe is no longer used in cam_dev.  Rather the file that is used is cam_dev/convect_diagnostics.F90, which is a simpler version of convect_shallow.F90 according to @adamrher.  So I think if we add the relevant four pbuf_add_field statements to the cam_dev file, we should be good.  I am currently testing this.

### What are the steps to reproduce the bug?

Create a new case with CAM_CONFIG_OPTS="-phys cam_dev -cosp", compile, and run it.

### What CAM tag were you using?

cam6_3_099

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

/glade/u/home/stepheba/cam99/cime/scripts/dflt099

### Will you be addressing this bug yourself?

Yes

**Comment by adamrher** [comment]
I presume you knew to do this, but those missing vars will also need to be initialized to zero somewhere in cam_dev/convect_diagnostics.F90. I see it being done at run time in convect_shallow.F90, but I think using a pbuf_set_field call in _init is more efficient than setting to zero every time-step.

**Comment by bstephens82** [comment]
Thanks I hadn't thought about that actually.
