### ISSUE TITLE
fix baseline directory for CESM tests in CAM regression testing

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#80]
When the baseline directory was moved to CAM, the test_driver script remained pointing to the old location.   Remove "basename for the testargs in the CESM work directory.

**Comment by fischer-ncar** [comment]
Another problem is BL_TESTDIR is used by cam stand-alone and CESM testing.  But the baselines are being storied in separate directories, cam_baselines and cesm_baselines.  We need to combine all of the baselines into one directory, or introduce a new environment variable.  I think it would be best to go with one directory for the baselines.

**Comment by cacraigucar** [comment]
As long as your testing completes successfully, I am okay with you combining CAM and CESM tests into the same directory (specified by BL_TESTDIR).
