### ISSUE TITLE
Can't checkout all of CAM_CESM2.1

### ISSUE THREAD

**Issue by gold2718** [ESCOMP/CAM#800]
### What happened?

Many machines can no longer get to the NCAR subversion server (which doesn't always seem to be up anyway). As a result, checkouts fail:
```
...Checking out externals: cam, cice, cime, cism, clm, mosart, pop, rtm, ww3, 
Processing externals description file : Externals_CAM.cfg
Checking out externals: chem_proc, 

Command 'svn checkout --quiet https://svn-ccsm-models.cgd.ucar.edu/tools/proc_atm/chem_proc/release_tags/chem_proc5_0_03_rel /cluster/home/goldy/Projects/CESM/components/cam/chem_proc'
from directory /cluster/home/goldy/Projects/CESM
has taken 300 seconds. It may be hanging.
...


### What are the steps to reproduce the bug?

Try checking out CESM 2.1 and running manage_externals from the wrong place or at the wrong time.

### What CAM tag were you using?

cam_cesm2_1_rel_41 (from release-cesm2.1.3)

### What machine were you running CAM on?

Other (please explain below)

### What compiler were you using?

Other (please specify below)

### Path to a case directory, if applicable

_No response_

### Will you be addressing this bug yourself?

Any CAM SE can do this

### Extra info

I was trying this from different machines in Norway but have seen the issue elsewhere.
I do not think machine or compiler are particularly important here.

**Comment by fvitt** [comment]
@gold2718 ,
 Do you really need the chemistry preprocessor?  If it is not needed, a workaround is to set `required = False` for `chem_proc` in `Externals_CAM.cfg`.  You may have the same issue with `carma`.

**Comment by gold2718** [comment]
> @gold2718 , Do you really need the chemistry preprocessor? If it is not needed, a workaround is to set `required = False` for `chem_proc` in `Externals_CAM.cfg`. You may have the same issue with `carma`.

Sure, I know how to turn it off (or just remove it), however, I am hearing from users in Europe who just try to checkout CESM and are getting stuck. 

I just found this workaround on the CESM forum (thanks @fischer-ncar) which does not involved explaining how to edit Externals files (or even removing the chemistry preprocessor).
https://bb.cgd.ucar.edu/cesm/threads/manage_externals-checkout_externals-error.7951/#post-47695

I will close this issue now that it has a workaround in the discussion.
