### ISSUE TITLE
new external forcings for both LT and MT GHGchem models

### ISSUE THREAD

**Issue by fvitt** [ESCOMP/CAM#825]
### What is the feature/what would you like to discuss?

add the following aircraft emissions to all the LT and MT compsets with GHG chemistry

```
 ext_frc_specifier = 'num_a1 -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/historical_ne30pg3/[emissions-cmip6_num_so4_a1_anthro-ene_vertical_mol_175001-201412_ne30pg3_c20200103.nc](http://emissions-cmip6_num_so4_a1_anthro-ene_vertical_mol_175001-201412_ne30pg3_c20200103.nc/)',
         'num_a1 -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/historical_ne30pg3/[emissions-cmip6_num_a1_so4_contvolcano_vertical_850-5000_ne30pg3_c20200125.nc](http://emissions-cmip6_num_a1_so4_contvolcano_vertical_850-5000_ne30pg3_c20200125.nc/)',
         'num_a2 -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/historical_ne30pg3/[emissions-cmip6_num_a2_so4_contvolcano_vertical_850-5000_ne30pg3_c20200125.nc](http://emissions-cmip6_num_a2_so4_contvolcano_vertical_850-5000_ne30pg3_c20200125.nc/)',
         'SO2 -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/historical_ne30pg3/emissions-cmip6_SO2_contvolcano_vertical_850-5000_ne30pg3_c20200125.nc',
         'so4_a1 -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/historical_ne30pg3/[emissions-cmip6_so4_a1_anthro-ene_vertical_mol_175001-201412_ne30pg3_c20200103.nc](http://emissions-cmip6_so4_a1_anthro-ene_vertical_mol_175001-201412_ne30pg3_c20200103.nc/)',
         'so4_a1 -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/historical_ne30pg3/[emissions-cmip6_so4_a1_contvolcano_vertical_850-5000_ne30pg3_c20200125.nc](http://emissions-cmip6_so4_a1_contvolcano_vertical_850-5000_ne30pg3_c20200125.nc/)',
         'so4_a2 -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/historical_ne30pg3/[emissions-cmip6_so4_a2_contvolcano_vertical_850-5000_ne30pg3_c20200125.nc](http://emissions-cmip6_so4_a2_contvolcano_vertical_850-5000_ne30pg3_c20200125.nc/)'
'bc_a4 -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/historical_ne30pg3/[emissions-cmip6_bc_a4_air_vertical_175001-201412_ne30pg3_c20200521.nc](http://emissions-cmip6_bc_a4_air_vertical_175001-201412_ne30pg3_c20200521.nc/)'
'num_a4 -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/historical_ne30pg3/[emissions-cmip6_num_bc_a4_air_vertical_175001-201412_ne30pg3_c20200521.nc](http://emissions-cmip6_num_bc_a4_air_vertical_175001-201412_ne30pg3_c20200521.nc/)'
'SO2 -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/historical_ne30pg3/emissions-cmip6_SO2_air_vertical_175001-201412_ne30pg3_c20200522.nc'
```

### Is there anyone in particular you want to be part of this conversation?

@tilmes

### Will this change (regression test) answers?

Yes

### Will you be implementing this enhancement yourself?

Any CAM SE can do this

**Comment by tilmes** [comment]
@fvitt it turns out that the ne30pg3 emissions must have a problem. For now we can use these emissions that work: 
ext_frc_specifier              = 'num_a1 -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/historical_ne30pg3/emissions-cmip6_num_so4_a1_anthro-ene_vertical_mol_175001-201412_ne30pg3_c20200103.nc',
         'num_a1 -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/historical_ne30pg3/emissions-cmip6_num_a1_so4_contvolcano_vertical_850-5000_ne30pg3_c20200125.nc',
         'num_a2 -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/historical_ne30pg3/emissions-cmip6_num_a2_so4_contvolcano_vertical_850-5000_ne30pg3_c20200125.nc',
         'SO2 -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/historical_ne30pg3/emissions-cmip6_SO2_contvolcano_vertical_850-5000_ne30pg3_c20200125.nc',
         'so4_a1 -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/historical_ne30pg3/emissions-cmip6_so4_a1_anthro-ene_vertical_mol_175001-201412_ne30pg3_c20200103.nc',
         'so4_a1 -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/historical_ne30pg3/emissions-cmip6_so4_a1_contvolcano_vertical_850-5000_ne30pg3_c20200125.nc',
         'so4_a2 -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/historical_ne30pg3/emissions-cmip6_so4_a2_contvolcano_vertical_850-5000_ne30pg3_c20200125.nc',
         'bc_a4 -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/CMIP6_emissions_1750_2015/emissions-cmip6_bc_a4_aircraft_vertical_1750-2015_0.9x1.25_c20170608.nc',
         'num_a4 -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/CMIP6_emissions_1750_2015/emissions-cmip6_num_bc_a4_aircraft_vertical_1750-2015_0.9x1.25_c20170608.nc',
         'SO2 -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/CMIP6_emissions_1750_2015/emissions-cmip6_SO2_aircraft_vertical_1750-2015_0.9x1.25_c20170608.nc'

**Comment by tilmes** [comment]
@fvitt I am going to see if I can get new emissions that work

**Comment by fvitt** [comment]
> @fvitt I am going to see if I can get new emissions that work

@tilmes Have you finalized the emissions settings?

**Comment by tilmes** [comment]
@fvitt still not yet finalized, but I hope I can work on this this week.

**Comment by tilmes** [comment]
@fvitt I finally finished the new aircraft emissions and the new namelist addition should be:
'bc_a4 -> /glade/campaign/acom/acom-climate/cmip6inputs/historical_ne30pg3/emissions-cmip6_bc_a4_aircraft_vertical_1750-2015_ne30pg3_c20231112.nc',
         'num_a4 ->/glade/campaign/acom/acom-climate/cmip6inputs/historical_ne30pg3/emissions-cmip6_num_bc_a4_aircraft_vertical_1750-2015_ne30pg3_c20231112.nc',
         'NO2 -> /glade/campaign/acom/acom-climate/cmip6inputs/historical_ne30pg3/emissions-cmip6_NO2_aircraft_vertical_1750-2015_ne30pg3_c20231112.nc',
         'SO2 ->/glade/campaign/acom/acom-climate/cmip6inputs/historical_ne30pg3/emissions-cmip6_SO2_aircraft_vertical_1750-2015_ne30pg3_c20231112.nc',

and without NO2 for no chemistry runs.
