### ISSUE TITLE
Input file missing from svn repo

### ISSUE THREAD

**Issue by gold2718** [ESCOMP/CAM#826]
### What happened?

`svn export failed with output:  and errput svn: E170000: URL 'https://svn-ccsm-inputdata.cgd.ucar.edu/trunk/inputdata/atm/cam/chem/ubc/b.e21.BWHIST.f09_g17.CMIP6-historical-WACCM.ensAvg123.cam.h0zm.H2O.185001-201412_c230509cdf5.nc' doesn't exist`

This file is requested in bld/namelist_files/use_cases/1850_cam_lt.xml which was brought in by the cam6_3_111 tag.

### What are the steps to reproduce the bug?

Try running a case with the `FCLTHIST` compset.

### What CAM tag were you using?

cam6_3_112

### What machine were you running CAM on?

Other (please explain below)

### What compiler were you using?

Intel

### Will you be addressing this bug yourself?

No

### Extra info

This was on Betzy (Norwegian HPC resource) but I do not think the problem is machine specific.

**Comment by cacraigucar** [comment]
@fvitt - This file needs the mandatory metadata before it can be put in the svn inputdata repo. 
 It looks like you were the author of the original file.

https://www2.cesm.ucar.edu/working_groups/Atmosphere/amwg_datasets.html.

**Comment by fvitt** [comment]
> @fvitt - This file needs the mandatory metadata before it can be put in the svn inputdata repo. It looks like you were the author of the original file.
> 
> https://www2.cesm.ucar.edu/working_groups/Atmosphere/amwg_datasets.html.

I have added the metadata.

**Comment by fvitt** [comment]
@gold2718 The input file has been imported to the svn repo.

**Comment by gold2718** [comment]
That seemed to be the only missing file, thanks for the quick solution!
