### ISSUE TITLE
Remove setting of CTSM fsurdat file and LND_DOMAIN_FILE in mpas testmods

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CAM#837]
### What is the feature/what would you like to discuss?

The mpasa testmods set the CTSM fsurdat file in user_nl_clm, which no longer needs to be done, so this should be removed. As of ctsm5.1.dev124 this no longer needs to be done so can be removed. It'll be important to get this in before CTSM5.2 become the standard as the tests will fail at that point.

Also LND_DOMAIN_FILE is set and that can be removed from the shell_commands file. This was only needed for MCT and only in the past before updated ccs_config.

The testmods that need to change are:
outfrq1d_physgrid_tem_mpasa120_wcmsc
outfrq9s_mpasa120
outfrq9s_mpasa480

This will change answers because the surface datasets are different.

### Is there anyone in particular you want to be part of this conversation?

@jtruesdal 
@cacraigucar 
@fischer-ncar 

### Will this change (regression test) answers?

Yes

### Will you be implementing this enhancement yourself?

No

**Comment by adamrher** [comment]
I have a related concern as I was looking at the mpas tests the other day. Why are we setting ```LND_DOMAIN_FILE``` in shell_commands? We shouldn't need to do this for nuopc, and I think it should be removed. No? 

See e.g., https://github.com/ESCOMP/CAM/blob/cam_development/cime_config/testdefs/testmods_dirs/cam/outfrq9s_mpasa480/shell_commands

**Comment by ekluzek** [comment]
Yes, that was probably required in the past, but shouldn't with latest versions of ccs_config. So yes that should be removed as well.

**Comment by ekluzek** [comment]
Actually LND_DOMAIN_FILE would've only been required for MCT, so doesn't matter now.
