### ISSUE TITLE
Make frontal gravity wave spectrum half-width a namelist variable

### ISSUE THREAD

**Issue by nadavis-ncar** [ESCOMP/CAM#839]
### What is the feature/what would you like to discuss?

The frontal gravity wave spectrum half-width, front_gaussian_width, in gw_drag.F90 should be a namelist variable. It is currently hard-coded. 

This variable is useful for tuning the mesopause region independently from the polar vortex, unlike adjusting taubgnd or frontgfc which have a stronger projection onto the whole column. 

Backwards compatibility/regression testing would require the default namelist value to remain 30 m/s, but at least for WACCM compsets we will want to adjust it to something like ~24 m/s.

### Is there anyone in particular you want to be part of this conversation?

@fvitt @JulioTBacmeister  

### Will this change (regression test) answers?

No

### Will you be implementing this enhancement yourself?

Any CAM SE can do this

**Comment by fvitt** [comment]
@nadavis-ncar Do you have source mods for this?  If not then I can implement this myself.  Thanks.
