### ISSUE TITLE
WACCMX ionosphere to CAM physics coupling

### ISSUE THREAD

**Issue by fvitt** [ESCOMP/CAM#84]
Refactor how WACCMX ionosphere couples to CAM physics to be independent of dynamical core.  The existing code is dependent on the FV dycore.  To be  independent of choice of dycore, ESMF regridding methods will be used to regrid state variables between CAM physics state, a magnetic grid used in electrodynamo module, and a regular latitude longitude grid used in ion transport.

**Comment by gold2718** [comment]
@fvitt, does this mean a PR is impending?

**Comment by fvitt** [comment]
yes
