### ISSUE TITLE
some SCAM IOP's are broken

### ISSUE THREAD

**Issue by adamrher** [ESCOMP/CAM#853]
### What happened?

Running FSCAM in debug mode, I am getting error's for IOP cases dycomsRF01, gateIII and bomex:

```
 shr_file_mod.F90         912
 This routine is depricated - use shr_log_setLogUnit instead        -139
forrtl: severe (408): fort: (8): Attempt to fetch from allocatable variable MED2MOD_AREACOR when it is not allocated

Image              PC                Routine            Line        Source
cesm.exe           000000000A4F637F  Unknown               Unknown  Unknown
cesm.exe           000000000532CA83  ice_import_export         712  ice_import_export.F90
cesm.exe           0000000004D43B53  ice_comp_nuopc_mp        1098  ice_comp_nuopc.F90
libesmf.so         00002B67186A12D6  _ZNK5ESMCI13Metho         377  ESMCI_MethodTable.C
libesmf.so         00002B67186A273A  _ZN5ESMCI11Method         563  ESMCI_MethodTable.C
libesmf.so         00002B67186A0C9B  c_esmc_methodtabl         317  ESMCI_MethodTable.C
libesmf.so         00002B6718AC97AF  esmf_attachmethod        1287  ESMF_AttachMethods.F90
libesmf.so         00002B671A472A94  Unknown               Unknown  Unknown

```

arm97 and twp06 both run fine. So it's not all IOP's, just some.

### What are the steps to reproduce the bug?

set compset to FSCAM and --user-mods-dir to the IOP directory you want to run. Set DEBUG=T.

### What CAM tag were you using?

cam6_3_115

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

/glade/scratch/aherring/cam6_3_115_FSCAM_twp06_T42_T42_L58dev_1pes_230712_run94_debug

### Will you be addressing this bug yourself?

Any CAM SE can do this

**Comment by swrneale** [comment]
@jtruesdal do you know when this came in? And I am looking to run togaII and arm95 also, if they are unaffected no problem. But togaII is an ocean IOP of course. Thanks!

**Comment by adamrher** [comment]
@jtruesdal any idea if the cice group has implemented this SCAM fix yet?

**Comment by swrneale** [comment]
I think now that we can only use a more recent cam_development tag on derecho, that precludes us from using SCAM then right? Either way this is pretty important for development and it should be a high priority. We stress this is a high priority to the cice group.

**Comment by jtruesdal** [comment]
I've started working with Dave Bailey to get a fix to the cice core code through the consortium.  The bug was in the NUOPC driver code for CICE and popped up when we switched from MCT to NUOPC.  It affects all runs over ocean.
