### ISSUE TITLE
Variable resolution grid fails when using more than 6272 tasks

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CAM#857]
### What happened?

I am running case  /glade/u/home/emmons/derecho/cesm_src/cam6_3_018_mosaic01_20230622/cime/scripts/create_newcase --case /glade/u/home/emmons/derecho/cases_asd/f.e22_cam6_3_018mosaic.FCnudged.TS1mosaic.NAEUAS01_ne30x8.01 --re
s ne0np4.NAEUAS01.ne30x8_mt12 --compset FCnudged --run-unsupported --project AACD0004 --user-mods-dir /glade/work/emmons/VRM_Files/ne0np4.NAEUAS01.ne30x8

and find that at mpi task counts > 6272 errors occur on startup.  This is an ASD project and @lkemmons would like to be able to use more tasks.  Is there a variable resolution developer who can take a look at the problem?   My case is in 
/glade/derecho/scratch/jedwards/f.e22_cam6_3_018mosaic.FCnudged.TS1mosaic.NAEUAS01_ne30x8.01

### What are the steps to reproduce the bug?

Attempt to run the case on 6400 tasks. 
My attempt can be found in file
/glade/derecho/scratch/jedwards/f.e22_cam6_3_018mosaic.FCnudged.TS1mosaic.NAEUAS01_ne30x8.01/cesm.log.1241865.desched1.230717-094119

### What CAM tag were you using?

cam6_3_018_mosaic01_20230622

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

 /glade/derecho/scratch/jedwards/f.e22_cam6_3_018mosaic.FCnudged.TS1mosaic.NAEUAS01_ne30x8.01

### Will you be addressing this bug yourself?

No

**Comment by lkemmons** [comment]
Thanks for any help! If I cannot get faster throughput on Derecho I will have to significantly revise my ASD plans.

**Comment by adamrher** [comment]
This doesn't really look like a problem with large core count, but just a bug in general of some sort. Anyone think otherwise? It's flagging a sigseg in the aerosols in the ice nucleation scheme:

cesm.log.1241865.desched1.230717-094119:
```
dec2212.hsn.de.hpc.ucar.edu 643: cesm.exe           000000000178B7CB  ndrop_mp_dropmixn         942  ndrop.F90
```

cesm.log.1241890.desched1.230717-101059 :
```
dec2275.hsn.de.hpc.ucar.edu 4736: cesm.exe           000000000178B918  ndrop_mp_dropmixn         949  ndrop.F90
``` 
If this last one refers to the ndrop in SourceMods (@jedwards4b can you confirm?) then it refers to the last line of this block:

```
      dtmix   = 0.9_r8*dtmin
      nsubmix = dtmicro/dtmix + 1
      print *,__FILE__,__LINE__,dtmin,dtmix, dtmicro
      if (nsubmix > 100) then
         nsubmix_bnd = 100
      else
         nsubmix_bnd = nsubmix
      end if
      count_submix(nsubmix_bnd) = count_submix(nsubmix_bnd) + 1
      dtmix = dtmicro/nsubmix
```
I'm not on derecho. It would be good to see some print statements here.

**Comment by jedwards4b** [comment]
I added a print statement and couldn't see anything that had gone to 0.
You should already have access to the derecho login nodes (or you can see it from casper) the case is in:  /glade/derecho/scratch/jedwards/f.e22_cam6_3_018mosaic.FCnudged.TS1mosaic.NAEUAS01_ne30x8.01

**Comment by adamrher** [comment]
Ah, I see that print statement you added. Yeah, the values look fine. Maybe the sigseg is downstream of the actual issue. 

The first error in the cesm.log.1241890.desched1.230717-101059 run looks different ... not sure what to make of it:
```
dec2227.hsn.de.hpc.ucar.edu 2560: MPICH ERROR [Rank 2560] [job id 2d8b1d44-97b0-4142-ac6d-1195dd1e68d9] [Mon Jul 17 10:14:16 2023] [dec2227] - Abort(69804047) (rank 2560 in comm 0): Fatal error in PMPI_Bcast: Other MPI error, error stack:
```

**Comment by lkemmons** [comment]
Maybe this is something in the custom MOSAIC code I am running.  I will try
my new grid in standard CESM2.2.0.

**Comment by lkemmons** [comment]
Or maybe it is the grid, because I can run (for 2 days at least) the standard CONUS ne30x8 grid with the custom MOSAIC code, and with NTASKS=17280.  Case dir:
/glade/u/home/emmons/derecho/cases_asd/f.e22_cam6_3_018mosaic.FCnudged.TS1mosaic.CONUSne30x8.01

**Comment by lkemmons** [comment]
I can successfully run (at least for an hour) standard CESM2.2.0 code, with default MOZART-TS1 chemistry (CAM-chem, FCnudged compset), with my ne0np4.NAEUAS01.ne30x8 grid (ncol = 458111) using NTASKS=15360.
I will do a longer run to get a better estimate of timing.
Case:
/glade/u/home/emmons/derecho/cases_asd/f.e22_cesm220.FCnudged.NAEUAS01_ne30x8.01/

**Comment by lkemmons** [comment]
I will give up (at least for now) using the MOSAIC aerosol code, and just use standard CESM2.2 (MAM4) for these simulations.  It seems there is an issue with the combination of my 3-region grid, MOSAIC and a large number of tasks, but don't think it is worth figuring that out.  I'll provide updates here after doing some longer runs.

**Comment by cacraigucar** [comment]
@lkemmons - Can this issue be closed now?

**Comment by lkemmons** [comment]
yes.
But I still cannot run this grid with sufficient throughput to perform the simulations I had in mind, so have created a new grid with 173k columns, instead of 458k.

**Comment by cacraigucar** [comment]
Closing as @lkemmons directed
