### ISSUE TITLE
Incorrect error message

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CAM#863]
### What happened?

FLDLST: Uzm in fincl(1, 5) only available with FV dycore
 FLDLST: Vzm in fincl(2, 5) only available with FV dycore
 FLDLST: Wzm in fincl(3, 5) only available with FV dycore
 FLDLST: THzm in fincl(4, 5) only available with FV dycore
 FLDLST: VTHzm in fincl(5, 5) only available with FV dycore
 FLDLST: WTHzm in fincl(6, 5) only available with FV dycore
 FLDLST: UVzm in fincl(7, 5) only available with FV dycore
 FLDLST: UWzm in fincl(8, 5) only available with FV dycore

### What are the steps to reproduce the bug?

These variables are available with the SE dycore when -cosp is added to CAM_CONFIG_OPTS
so the error message must be incorrect.

### What CAM tag were you using?

cam6_3_119

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Will you be addressing this bug yourself?

No

**Comment by jedwards4b** [comment]
I see that the warnings are still present but the model doesn't error out.   Should these be removed from user_nl_cam?

**Comment by fvitt** [comment]
Those messages are erroneous.  The *zm fields are now available independent of dycore choice when TEM diagnostics are turned on.

**Comment by cecilehannay** [comment]
Yes the warning are also present and it should be removed. These variables are for the TEM diags. 
Thanks a bunch.
