### ISSUE TITLE
Unusable namelist default?

### ISSUE THREAD

**Issue by gold2718** [ESCOMP/CAM#867]
### What happened?

Found this in namelist_defaults_cam.xml:
`<ncdata dyn="se" hgrid="10x15"   nlev="32" chem="trop_strat_mam5_vbs">atm/cam/inic/fv/FC2000mam5_f10_0002-01-01_c221214.nc</ncdata>`

Did not expect to see that.

### What are the steps to reproduce the bug?

Look on line 126 of bld/namelist_files/namelist_defaults_cam.xml

### What CAM tag were you using?

cam6_3_120

### What machine were you running CAM on?

Other (please explain below)

### What compiler were you using?

Other (please specify below)

### Will you be addressing this bug yourself?

No

### Extra info

Am I missing something?

**Comment by adamrher** [comment]
whoopsy. good catch. there's sooo many ncdata entries. can't help but wonder if it's necessary.
