### ISSUE TITLE
Add derecho regression tests

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#875]
### Issue Type

Infrastructure Update

### Issue Description

Cheyenne tests will be duplicated to create identical derecho regression tests.   For the short-term, we will run both cheyenne and derecho tests for every CAM tag, since scientists will be running on both machines.

### Will this change answers?

No

### Will you be implementing this yourself?

Yes, but I will need some help

**Comment by fischer-ncar** [comment]
@cacraigucar do you plan on creating a new test list for derecho, or just reuse the cheyenne test list on derecho.  You can run the cheyenne test on derecho by doing "--mach derecho --xml-machine cheyenne".  Which is how I'm doing the prealpha tests.  I can set this up in test_driver if you want.  I do have a version of test_driver working on derecho now.

**Comment by fischer-ncar** [comment]
Then I propose we use --mach derecho --xml-machine cheyenne until we feel confident with derecho.  Then it's a simple search and replace in the testlist_cam.xml when we're ready to move on from cheyenne.  Also, there's a one line edit in test_driver.sh.

**Comment by cacraigucar** [comment]
@fischer-ncar - that sounds good to me

**Comment by nusbaume** [comment]
This was fixed in PR #948, but wasn't referenced in that PR.  Closing it now.
