### ISSUE TITLE
Update cam_development to match current tuning runs

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#895]
### What is the feature/what would you like to discuss?

@cecilehannay has been making an number of changes to tune the model.  Some of these changes are ready to be incorporated into cam_development.  

### Is there anyone in particular you want to be part of this conversation?

@PeterHjortLauritzen 

### Will this change (regression test) answers?

Yes

### Will you be implementing this enhancement yourself?

Yes, but I will need some help

Discussion for this issue also occurred at:   https://github.com/NCAR/amwg_dev/discussions/412

**Comment by adamrher** [comment]
Hi @PeterHjortLauritzen @cacraigucar @cecilehannay @JulioTBacmeister. I coded up a cldfrc_iceopt=7 namelist option. It is here:

/glade/u/home/aherring/src/cam6_3_128/usr_src/cldfrc2m.F90

I verified it builds and runs. We will need to add this to the PR that resolves this issue. I have my initials ARH surrounding all the changes so if you could look it over and make sure it's implemented appropriately, that'd be great. In particular, I introduced a wonky parameter qist_min7 b/c I didn't want to change qist_min for all the iceopts. Although maybe we should just change qist_min for all iceopts?

**Comment by PeterHjortLauritzen** [comment]
Tagging @tto061 

Thank you Adam. I can't speak to changing qist_min for all options. (maybe it would be best not to change it so we don't change answers for CAM6, CAM5, etc.?)

Just a couple of minor things not related to the scientific validity of the code (that we could also deal with at the code review phase):

1. line 68: need to add comment explaining option 7 (seems like iceopt 6 is not explained either)
2. we need to modify namelist_definition with explanation of iceopt 7 :

```
<entry id="cldfrc_iceopt" type="integer" category="conv"
       group="cldfrc_nl" valid_values="" >                                                                                                                                             
Scheme for ice cloud fraction: 1=wang &amp; sassen, 2=schiller (iciwc),                                                                                                                
3=wood &amp; field, 4=Wilson (based on smith), 5=modified slingo (ssat &amp; empyt cloud)                                                                                              
Default: set by build-namelist                                                                                                                                                         
</entry>
```
3. I guess ```valid_values=""``` in the namelist definition should be modified to ```valid_values="1,2,3,4,5,6,7"```

**Comment by adamrher** [comment]
Ah, right. We need to add this option to namelist_defintion. Maybe use the following def's:
```
6=Heymsfield, 7=Toniazzo
```

Elsewhere for the credit @tto061, I put the following in the cldfrc2m module:
```
     ! iceopt=6 is identical to iceopt=5, but for small ice concentrations
     ! take the geometric mean of the iceopt=4 and iceopt=5 values.
     ! Mods developed by Thomas Toniazzo from NorESM.
```
Let me know if you approve of this attribution statement for your code mods.

> I can't speak to changing qist_min for all options. (maybe it would be best not to change it so we don't change answers for CAM6, CAM5, etc.?)

I think we'd probably have to fire off a new run with default qist_min. The larger value used by Thomas I think helps to increase ice cloud fraction, since we invoke the new mods for ```icimr < qist_min```. So it increases the impact of these mods.

**Comment by cacraigucar** [comment]
Email from Adam:

I spoke with Julio about how to handle wmixmin in the new tuning PR. We agreed on a plan; it's two steps:

(1) turn the "wmixmin" parameter in ndrop.F90 into a namelist. Set it to 0.0 m/s for "cam_dev" and 0.1 m/s otherwise (the current hard coded value). This would ensure backwards compatibility.

(2) remove the new namelist_default for wsub_min for cam_dev:

<microp_aero_wsub_min                  >  0.2D0    </microp_aero_wsub_min>
<microp_aero_wsub_min phys="cam_dev"   >  0.D0    </microp_aero_wsub_min>

Would you be willing to implement this in your PR branch?

Followup email from him:
I realized that it would be better to retain (2), but rather set it to 0.1 for "cam_dev" instead of 0.0. Along with (1), that will replicate our coupled runs (#42, #51) exactly, but using this more explicit workflow.

**Comment by tto061** [comment]
Adam, thanks for tagging me, attribution looks good as proposed, PR also OK.
