### ISSUE TITLE
Preparing for new CAM tag based on coupled run 51 

### ISSUE THREAD

**Issue by cecilehannay** [ESCOMP/CAM#899]
### Issue Type

Other (please describe below)

### Issue Description

As discussed at the last cam7 meeting, we would like to create a new cam tag to bring the head of cam closer to the simulations we are doing at the moment. 

We started a discussion about the setting at:
https://github.com/NCAR/amwg_dev/discussions/412

@cacraigucar

### Will this change answers?

Yes

### Will you be implementing this yourself?

Any CAM SE can do this

**Comment by cecilehannay** [comment]
closing this as it is redundant with #895

**Comment by cacraigucar** [comment]
Duplicate
