### ISSUE TITLE
Problem with waccmx writing restart files on derecho in CESM2.2

### ISSUE THREAD

**Issue by fvitt** [ESCOMP/CAM#901]
### What happened?

To enable running waccmx on derecho in cesm2.2 cime tag cime5.8.32.2 was used.  
See sandbox:
```
 /glade/work/fvitt/cesm/cesm2.2.1_derecho
```
An error occurred with the following traceback:
```
[dec0251.hsn.de.hpc.ucar.edu](http://dec0251.hsn.de.hpc.ucar.edu/) 15: libmpi_intel.so.1  000015403AAD8953  MPI_Bcast             Unknown  Unknown
[dec0251.hsn.de.hpc.ucar.edu](http://dec0251.hsn.de.hpc.ucar.edu/) 15: libpioc.so         0000154049314607  PIOc_closefile        Unknown  Unknown
[dec0251.hsn.de.hpc.ucar.edu](http://dec0251.hsn.de.hpc.ucar.edu/) 15: libpiof.so         00001540495634FD  piolib_mod_mp_clo     Unknown  Unknown
[dec0251.hsn.de.hpc.ucar.edu](http://dec0251.hsn.de.hpc.ucar.edu/) 15: cesm.exe           000000000051F7AE  cam_history_mp_ws        5106  cam_history.F90
[dec0251.hsn.de.hpc.ucar.edu](http://dec0251.hsn.de.hpc.ucar.edu/) 15: cesm.exe           000000000051AB80  cam_history_mp_wr        1395  cam_history.F90
[dec0251.hsn.de.hpc.ucar.edu](http://dec0251.hsn.de.hpc.ucar.edu/) 15: cesm.exe           0000000000562E5D  cam_restart_mp_ca         140  cam_restart.F90
[dec0251.hsn.de.hpc.ucar.edu](http://dec0251.hsn.de.hpc.ucar.edu/) 15: cesm.exe           000000000050BCC6  cam_comp_mp_cam_r         401  cam_comp.F90
[dec0251.hsn.de.hpc.ucar.edu](http://dec0251.hsn.de.hpc.ucar.edu/) 15: cesm.exe           00000000004FB477  atm_comp_mct_mp_a         508  atm_comp_mct.F90
[dec0251.hsn.de.hpc.ucar.edu](http://dec0251.hsn.de.hpc.ucar.edu/) 15: cesm.exe           000000000043AECE  component_mod_mp_         737  component_mod.F90
[dec0251.hsn.de.hpc.ucar.edu](http://dec0251.hsn.de.hpc.ucar.edu/) 15: cesm.exe           000000000041BB6E  cime_comp_mod_mp_        3052  cime_comp_mod.F90
[dec0251.hsn.de.hpc.ucar.edu](http://dec0251.hsn.de.hpc.ucar.edu/) 15: cesm.exe           000000000043AB62  MAIN__                    153  cime_driver.F90

```

### What are the steps to reproduce the bug?

clone case
 /glade/derecho/scratch/fvitt/FXSD_f19_cesm2_2_test01

### What CAM tag were you using?

cam_cesm2_2_rel_07

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

/glade/derecho/scratch/fvitt/FXSD_f19_cesm2_2_test01

### Will you be addressing this bug yourself?

No

**Comment by jedwards4b** [comment]
Abort with message Input/Output data amount mismatch in file /glade/derecho/scratch/csgteam/temp/spack/derecho/23.06/builds/spack-stage-parallel\
io-2.6.2-qn7u7p6crdjeal37y5uw3g4j6vllytgb/spack-src/src/clib/pio_darray_int.c at line 677

**Comment by jedwards4b** [comment]
I've traced the problem to writing zonal mean values.  eg UVzm

**Comment by jedwards4b** [comment]
The file size of the array: 96*146=14016
but cam is trying to write 280170 elements - 20x what the file is expecting.

**Comment by jedwards4b** [comment]
I have confirmed that the same error occurs on cheyenne so this is not a derecho porting issue.  Do you have evidence that writing zonal variables from the se dycore works from this cam tag?

**Comment by jedwards4b** [comment]
Support for zonal means in the se dycore was introduced in https://github.com/ESCOMP/CAM/pull/629. cam6_3_092 and, as far as I can tell, is not available in cesm2.2

**Comment by fvitt** [comment]
@jedwards4b 
I don't understand why this is closed.  There is a problem with the cesm2.2 on derecho.  

The zm fields have existed in cam for long before tag cam6_3_092.  Prior to cam6_3_092 the zm fields were available only when the finite volume dycore is used -- zonal means were calculated on the FV dynamics grid.

Tag cam6_3_092 provided the capability to compute zonal mean independent of dycore choice.

**Comment by jedwards4b** [comment]
I had it in my head that this was on a se grid - sorry.

**Comment by fvitt** [comment]
It seems that the changes to `src/dynamics/fv/dyn_grid.F90` in cam tag cam6_3_008 fixes this issue.
See issue https://github.com/ESCOMP/CAM/issues/282

The changes are:
 ```
diff --git a/src/dynamics/fv/dyn_grid.F90 b/src/dynamics/fv/dyn_grid.F90
index 722fd8e6..610df458 100644
--- a/src/dynamics/fv/dyn_grid.F90
+++ b/src/dynamics/fv/dyn_grid.F90
@@ -1108,18 +1108,23 @@ subroutine define_cam_grids()
   ! Zonal mean grid
   ! Make a map
   allocate(grid_map(4, (endlatxy - beglatxy + 1)))
   ind = 0
   do i = beglatxy, endlatxy
     ind = ind + 1
     grid_map(1, ind) = 1
     grid_map(2, ind) = i
-    grid_map(3, ind) = 1
-    grid_map(4, ind) = i
+    if (beglonxy == 1) then
+      grid_map(3, ind) = 1
+      grid_map(4, ind) = i
+    else
+      grid_map(3, ind) = 0
+      grid_map(4, ind) = 0
+    end if
   end do
```
The fixes are applied to sandbox `/glade/work/fvitt/cesm/cesm2.2.1_derecho`

**Comment by fvitt** [comment]
@npedatella Please try waccmx with the latest I have in sandbox `/glade/work/fvitt/cesm/cesm2.2.1_derecho`

**Comment by jedwards4b** [comment]
Awesome - thank you @fvitt

**Comment by npedatella** [comment]
@fvitt I was able to run this successfully for one day at 2 degree resolution. Thanks for fixing this.

**Comment by npedatella** [comment]
@fvitt I have encountered a new problem with this version, specifically related to running with multiple instances/drivers, which is needed to run ensembles and for DART. I receive an error:

>>> create_geo_grid: error return from ESMF_GridGetCoord for longitude coords

The case is in /glade/derecho/scratch/nickp/tmp/test_wx_multi.002/ and run directory is /glade/derecho/scratch/nickp/test_wx_multi.002/run/

**Comment by jedwards4b** [comment]
@npedatella does this work on cheyenne?   If it does then we can try building the older esmf library used on cheyenne for use on derecho.

**Comment by npedatella** [comment]
I am unable to build this version on cheyenne using the default settings. I get an error building pio: /glade/scratch/nickp/test_wx_multi.ch/bld/pio.bldlog.231019-115332

**Comment by fvitt** [comment]
@npedatella Correct me if I am mistaken, but I don't believe WACCMX in CESM2.2 is able to run in multi-instance mode.  We did not have this capability until after the refactor of how the ionosphere is coupled to CAM, i.e., the implementation of the new ESMF regridding scheme in WACCMX.

**Comment by npedatella** [comment]
@fvitt You are right. This was my mistake. I forgot that I had to use source mods to run with multiple instances. It works when I use the modifications. Sorry for the confusion.

**Comment by fvitt** [comment]
Should have been closed by https://github.com/ESCOMP/CAM/pull/915
