### ISSUE TITLE
Fix failing derecho WACCM regression test

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#917]
### What happened?

  ERP_Ln9_Vnuopc.ne30pg3_ne30pg3_mg17.FW2000climo.derecho_intel.cam-outfrq9s_wcm_ne30 (Overall: PEND) details:
    PEND ERP_Ln9_Vnuopc.ne30pg3_ne30pg3_mg17.FW2000climo.derecho_intel.cam-outfrq9s_wcm_ne30 RUN
    PEND ERP_Ln9_Vnuopc.ne30pg3_ne30pg3_mg17.FW2000climo.derecho_intel.cam-outfrq9s_wcm_ne30 COMPARE_base_rest

This appears to fail after the run is complete and is reproducible

### What are the steps to reproduce the bug?

Run appropriate CAM regression test

### What CAM tag were you using?

cam6_3_136

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

/glade/derecho/scratch/cacraig/aux_cam_20231117145442/ERP_Ln9_Vnuopc.ne30pg3_ne30pg3_mg17.FW2000climo.derecho_intel.cam-outfrq9s_wcm_ne30.GC.aux_cam_20231117145442

### Will you be addressing this bug yourself?

No

**Comment by fvitt** [comment]
Seems to be a memory issue on the restart run.  The test passes for me if I use 8 derecho nodes.
