### ISSUE TITLE
Bad outfld calls in cam_development?

### ISSUE THREAD

**Issue by gold2718** [ESCOMP/CAM#931]
### What happened?

Reviewing `outfld` calls, I see these in src/physics/waccm/mo_aurora.F90
```
      call outfld( 'ALONM', r2d*alonm(:ncol,lchnk), pcols, lchnk )
      call outfld( 'ALATM', r2d*alatm(:ncol,lchnk), pcols, lchnk )
```
and this call on line 2056 of src/physics/spcam/spcam_drivers.F90
```
call outfld('SWCF    ',rad_avgdata%fsntoa_m(:ncol)-rad_avgdata%fsntoac_m(:ncol)  ,pcols,lchnk)
```
and this call on line 236 of src/physics/rrtmg/rrtmg_state.F90
```
    call outfld('O3colAbove', chi_eff(:ncol), pcols, lchnk)
```
and these calls starting on line 1111 and on 1475 of src/physics/cam/vertical_diffusion.F90
```
     call outfld( 'qv_pre_PBL   ', state%q(:ncol,:,1),        pcols, lchnk )
     call outfld( 'ql_pre_PBL   ', state%q(:ncol,:,ixcldliq), pcols, lchnk )
     call outfld( 'qi_pre_PBL   ', state%q(:ncol,:,ixcldice), pcols, lchnk )
```
```
     call outfld( 'uten_PBL'     , ptend%u(:ncol,:),          pcols, lchnk )
     call outfld( 'vten_PBL'     , ptend%v(:ncol,:),          pcols, lchnk )
     call outfld( 'qvten_PBL'    , ptend%q(:ncol,:,1),        pcols, lchnk )
     call outfld( 'qlten_PBL'    , ptend%q(:ncol,:,ixcldliq), pcols, lchnk )
     call outfld( 'qiten_PBL'    , ptend%q(:ncol,:,ixcldice), pcols, lchnk )
```
and this call on line 1410 of src/physics/cam/cam_diagnostics.F90
```
    call outfld ('ATMEINT   ',ftem(:ncol,1)  ,pcols   ,lchnk     )
```
I believe these are incorrect as the perceived size of the first dimension inside of `outfld` does not match the size that is passed. I think that these will output incorrect values for any non-full chunk.
Note, I did not find these in a full survey of cam_development. Rather, when I found them in a local codebase, I confirmed their presence in cam_development before including them.

### What are the steps to reproduce the bug?

Look at code.

### What CAM tag were you using?

cam_development

### What machine were you running CAM on?

Other (please explain below)

### What compiler were you using?

Other (please specify below)

### Will you be addressing this bug yourself?

No

### Extra info

Code inspection so no machine / compiler information. I will be doing some testing here to see how (if?) answers change.

**Comment by brian-eaton** [comment]
Hi @gold2718.  Thanks for pointing out the bad `outfld` calls.  I grep'ed the current cam_development source and didn't find any additional occurences of this problem.  Fortunately the output of single level fields is still OK, so just the multi-level field outputs would be garbled.  Apparently no one is looking at those vertical diffusion diagnostics.  I will add the fixes to a miscellaneous PR that I'm working on.
