### ISSUE TITLE
Increase computational throughput of SE-CSLAM dycore

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [ESCOMP/CAM#949]
### What is the feature/what would you like to discuss?

Increase computational throughput of SE-CSLAM dycore:

- no double advection of thermodynamic active species
- in FMT and FLT: no increased del4 sponge damping
- decrease nsplit to 2 in FMT

### Will this change (regression test) answers?

Yes

### Will you be implementing this enhancement yourself?

Yes

**Comment by cacraigucar** [comment]
Done in previous CAM tag
