### ISSUE TITLE
Update to new CLUBB External

### ISSUE THREAD

**Issue by Katetc** [ESCOMP/CAM#956]
### Issue Type

Other (please describe below)

### Issue Description

UWM has a new CLUBB version to bring in for CAM7 that includes some new namelist parameters and some taus code modifications. 
This is related to Issue #953 but it's own issue to address the specific task of updating the CLUBB external.

### Will this change answers?

Yes

### Will you be implementing this yourself?

Yes

**Comment by bstephens82** [comment]
@Katetc Just as a reminder I have been using the new CLUBB external, and have a working version of clubb_intr.F90.  I'm sure it's not up to normal coding standards, but it may make things go quicker for you!  Can you see this [link](https://github.com/bstephens82/CAM/blob/my.cam6_3_134.newclubb/src/physics/cam/clubb_intr.F90)?
