### ISSUE TITLE
Bug fixes in COSP MODIS simulator

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#97]
From @dustinswales 

We recently uncovered a few bugs in the COSP/CAM interface that impact the MODIS simulator retrievals. 
The MODIS simulator cloud diagnostics are not in close agreement with the cloud fields produced by other COSP simulators, such as ISCCP. Attached are images provided by Yuying Zhang illustrating the change in the MODIS and ISCCP cloud-fractions from COSP1.4 to COSP2.
[COSP2_modis_CESM2.pdf](https://github.com/ESCOMP/CAM/files/4344675/COSP2_modis_CESM2.pdf)

Issue 1:
From COSP1.4 to COSP2 there was a change in the LUTs used by the particle-size retrieval within the MODIS simulator, but this change was not accounted for on the CAM side. This mismatch in LUTs resulted in the retrieval failing more often, hence the reduction in MODIS total cloud fraction.
Solution 1:
Use the new LUTs in the COSP/CAM interface (cosp2/optics/cosp_optics.F90).

Additionally there is a bug-fix in the MODIS optics in COSP2 that should be propagated into CAM. The implementation of COSP2 in CAM occurred around the same time when this fix was implemented in COSP2 (and as a patch to COSP1.4) and I forgot to include it in CAM.

Issue 2: The combining of the MODIS optical fields, single-scattering albedo and asymmetry parameter, are incorrect.
Solution 2: Propagate changes in the computation of optical properties into CAM.

**Comment by gold2718** [comment]
@dustinswales, can you edit the description above or add move detail so that someone could know if your bug fixes solve their problem? Something more in line of reporting a bug would be helpful here.
