### ISSUE TITLE
convert CLUBB lat/lon crash report from radians to degrees

### ISSUE THREAD

**Issue by bstephens82** [ESCOMP/CAM#971]
### What is the feature/what would you like to discuss?

Currently if CLUBB crashes with a [fatal error in the CLUBB library](https://github.com/ESCOMP/CAM/blob/74018ee9e1bb113134239402b9e000ab26cfa15a/src/physics/cam/clubb_intr.F90#L3361C1-L3366C13), it outputs the lat/lon of the error, but it is output in radians.  It would be nice if this were output in degrees.  And ideally, it would also be nice if the longitude was output from -180 to +180 instead of from 0 to 360. 

I spoke with @Katetc and she indicated this would probably be easy enough to implement as part of her [current PR for the new CLUBB external](https://github.com/ESCOMP/CAM/pull/960).

### Is there anyone in particular you want to be part of this conversation?

@Katetc 

### Will this change (regression test) answers?

No

### Will you be implementing this enhancement yourself?

No

**Comment by adamrher** [comment]
I recall that when the new externals came in, allowing passing pcol arrays to clubb, that the errors message only spits out the range of lat/lon points given by the pcol array, rather than the actual pcol index and lat/lon point of the error. Am I mistaken?

**Comment by bstephens82** [comment]
If I understand your question yes it still gives a range.  But I think the range is in radians.
