### ISSUE TITLE
Need to convert RRTMGP externals to submodules with depth=1

### ISSUE THREAD

**Issue by nusbaume** [ESCOMP/CAM#975]
### Issue Type

Externals Update

### Issue Description

Once PR #909 has been merged, and PR #946 is out-of-draft, then it would be great to make sure that the two RRTMGP externals (`rte-rrtmgp` and `rrtmgp-data`) are brought in as shallow submodules with a depth of one.  This will allow CAM to significantly reduce the size of a checkout while still acquiring all of the necessary files needed for radiation.

Pinging @cacraigucar @jedwards4b @brian-eaton as a heads-up.

### Will this change answers?

No

### Will you be implementing this yourself?

Any CAM SE can do this

**Comment by jedwards4b** [comment]
My plan will be to bring in all of the submodules using this method in PR #946.

**Comment by nusbaume** [comment]
Great, thanks @jedwards4b!  I'll leave this issue open for now just so us CAM SEs will remember that git-fleximod will fix our current repo size issue.

**Comment by cacraigucar** [comment]
Done with git-fleximod
