### ISSUE TITLE
Bring in namelist settings which Cecile is using for current testing

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#976]
### Issue Type

Other (please describe below)

### Issue Description

The list of namelist settings which @cecilehannay is currently using and need to be changed are:

! dust tuning
dust_emis_fact = 1.3
! clubb diffusion on
clubb_l_do_expldiff_rtm_thlm = .true.
! tuning
microp_aero_wsub_scale  = 1.0
clubb_C8=4.25
! revert NorESMs mods
cldfrc2m_do_avg_aist_algs = .false.
cldfrc2m_qist_min = 1.e-7
bnd_topo = "/glade/campaign/cgd/amp/pel/topo/files/se/ne30pg3_gmted2010_modis_bedmachine_nc3000_Laplace0100_noleak_20240117.nc"
se_hypervis_subcycle = 2

@adamrher, @PeterHjortLauritzen - Should these changes all be tied to` -phys cam_dev` or made default for all CAM runs?

### Will this change answers?

Yes

### Will you be implementing this yourself?

Yes

**Comment by adamrher** [comment]
I think we should tie it all to cam_dev, except bnd_topo (we don't want to support two versions of topo).

microp_aero_wsub_scale, cldfrc2m_do_avg_aist_algs, cldfrc2m_qist_min are just reverting to the defaults so no need for conditionals.

It would be convenient to bring this in with the new externals for the gust param, but not sure how far that work is.

Not sure about se_hypervis_subcycle, I defer to @PeterHjortLauritzen.

**Comment by PeterHjortLauritzen** [comment]
Regarding se_hypervis_subcycle=2: se_hypervis_subcycle will be set in namelist_defaults with PR https://github.com/ESCOMP/CAM/pull/968
