### ISSUE TITLE
README_EXTERNALS file talks about using svn

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#982]
### What happened?

When we updated to git, we didn't remember that we have this README_EXTERNALS file in our home directory.  It talks about svn in it.  Either this file needs to be removed completely or updated with git commands.

### What are the steps to reproduce the bug?

Do any checkout of CAM

### What CAM tag were you using?

cam6_3_146

### What machine were you running CAM on?

Other (please explain below)

### What compiler were you using?

Other (please specify below)

### Will you be addressing this bug yourself?

Any CAM SE can do this

**Comment by gold2718** [comment]
See also #954

**Comment by cacraigucar** [comment]
Duplicate -- closed
